In [3]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from datetime import datetime, timedelta

def parse_interfax_date(url):
    """Парсит новости за конкретную дату"""
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        news_block = soup.find('div', class_='an')
        
        if not news_block:
            return []
        
        full_text = news_block.get_text()
        time_pattern = r'\d{2}:\d{2}'
        all_times = re.findall(time_pattern, full_text)
        links = news_block.find_all('a', href=True)
        
        # Извлекаем дату из URL
        date_match = re.search(r'/(\d{4})/(\d{2})/(\d{2})', url)
        if date_match:
            year, month, day = date_match.groups()
            base_date = f"{year}-{month}-{day}"
        else:
            return []
        
        data = []
        time_index = 0
        
        for link in links:
            text = link.get_text(strip=True)
            
            if text and len(text) > 10:
                time_str = all_times[time_index] if time_index < len(all_times) else "00:00"
                time_index += 1
                
                datetime_str = f"{base_date} {time_str}:00"
                
                data.append({
                    'datetime': datetime_str,
                    'text': text
                })
        
        return data
        
    except Exception as e:
        print(f"Ошибка при парсинге {url}: {e}")
        return []

def parse_interfax_period(start_year = 2022, end_year = 2025):
    """Парсит новости за период с start_year по end_year"""
    all_news = []
    
    # Генерируем даты с 2022-01-01 по 2025-12-31
    start_date = datetime(start_year, 1, 1)
    end_date = datetime(end_year, 10, 19)
    
    current_date = start_date
    total_days = (end_date - start_date).days + 1
    
    print(f"Начинаем парсинг с {start_date.date()} по {end_date.date()}")
    print(f"Всего дней: {total_days}")
    
    for day_num in range(total_days):
        date_str = current_date.strftime("%Y/%m/%d")
        url = f"https://www.interfax.ru/business/news/{date_str}"
        
        # Парсим новости за день
        daily_news = parse_interfax_date(url)
        all_news.extend(daily_news)
        
        if daily_news:
            print(f"{current_date.date()}: {len(daily_news)} новостей")
        else:
            print(f"{current_date.date()}: 0 новостей")
        
        # Переходим к следующему дню
        current_date += timedelta(days=1)
        
        # Пауза между запросами
        import time
        time.sleep(1)
    
    # Создаем итоговый DataFrame
    df = pd.DataFrame(all_news)
    
    if not df.empty:
        df = df.sort_values('datetime').reset_index(drop=True)
    
    return df

# Запускаем парсинг за весь период
print("=== ПАРСИНГ INTERFAX ЗА 2022-2025 ===")
final_df = parse_interfax_period(2022, 2025)

print(f"\n=== РЕЗУЛЬТАТ ===")
print(f"Итоговый размер датафрейма: {len(final_df)} новостей")

if not final_df.empty:
    print("\nПервые 5 записей:")
    print(final_df.head())
    print(f"\nДиапазон дат: {final_df['datetime'].min()} - {final_df['datetime'].max()}")
else:
    print("Не удалось спарсить ни одной новости!")

=== ПАРСИНГ INTERFAX ЗА 2022-2025 ===
Начинаем парсинг с 2022-01-01 по 2025-10-19
Всего дней: 1388
2022-01-01: 0 новостей
2022-01-02: 6 новостей
2022-01-03: 18 новостей
2022-01-04: 18 новостей
2022-01-05: 9 новостей
2022-01-06: 18 новостей
2022-01-07: 7 новостей
2022-01-08: 0 новостей
2022-01-09: 1 новостей
2022-01-10: 38 новостей
2022-01-11: 46 новостей
2022-01-12: 41 новостей
2022-01-13: 39 новостей
2022-01-14: 56 новостей
2022-01-15: 2 новостей
2022-01-16: 0 новостей
2022-01-17: 35 новостей
2022-01-18: 49 новостей
2022-01-19: 47 новостей
2022-01-20: 56 новостей
2022-01-21: 42 новостей
2022-01-22: 1 новостей
2022-01-23: 1 новостей
2022-01-24: 48 новостей
2022-01-25: 52 новостей
2022-01-26: 52 новостей
2022-01-27: 55 новостей
2022-01-28: 42 новостей
2022-01-29: 1 новостей
2022-01-30: 2 новостей
2022-01-31: 46 новостей
2022-02-01: 41 новостей
2022-02-02: 63 новостей
2022-02-03: 53 новостей
2022-02-04: 50 новостей
2022-02-05: 2 новостей
2022-02-06: 1 новостей
2022-02-07: 52 новостей
2022-02-08: 51 новостей
2022-02-09: 51 новостей
2022-02-10: 49 новостей
2022-02-11: 87 новостей
2022-02-12: 1 новостей
2022-02-13: 1 новостей
2022-02-14: 35 новостей
2022-02-15: 58 новостей
2022-02-16: 56 новостей
2022-02-17: 63 новостей
2022-02-18: 43 новостей
2022-02-19: 0 новостей
2022-02-20: 1 новостей
2022-02-21: 63 новостей
2022-02-22: 65 новостей
2022-02-23: 20 новостей
2022-02-24: 109 новостей
2022-02-25: 97 новостей
2022-02-26: 17 новостей
2022-02-27: 37 новостей
2022-02-28: 115 новостей
2022-03-01: 106 новостей
2022-03-02: 119 новостей
2022-03-03: 112 новостей
2022-03-04: 119 новостей
2022-03-05: 75 новостей
2022-03-06: 21 новостей
2022-03-07: 40 новостей
2022-03-08: 23 новостей
2022-03-09: 141 новостей
2022-03-10: 124 новостей
2022-03-11: 96 новостей
2022-03-12: 20 новостей
2022-03-13: 7 новостей
2022-03-14: 92 новостей
2022-03-15: 83 новостей
2022-03-16: 93 новостей
2022-03-17: 103 новостей
2022-03-18: 79 новостей
2022-03-19: 10 новостей
2022-03-20: 4 новостей
2022-03-21: 105 новостей
2022-03-22: 72 новостей
2022-03-23: 105 новостей
2022-03-24: 86 новостей
2022-03-25: 93 новостей
2022-03-26: 5 новостей
2022-03-27: 6 новостей
2022-03-28: 98 новостей
2022-03-29: 82 новостей
2022-03-30: 97 новостей
2022-03-31: 102 новостей
2022-04-01: 88 новостей
2022-04-02: 8 новостей
2022-04-03: 3 новостей
2022-04-04: 73 новостей
2022-04-05: 91 новостей
2022-04-06: 70 новостей
2022-04-07: 83 новостей
2022-04-08: 91 новостей
2022-04-09: 7 новостей
2022-04-10: 6 новостей
2022-04-11: 75 новостей
2022-04-12: 74 новостей
2022-04-13: 81 новостей
2022-04-14: 92 новостей
2022-04-15: 67 новостей
2022-04-16: 1 новостей
2022-04-17: 5 новостей
2022-04-18: 68 новостей
2022-04-19: 83 новостей
2022-04-20: 75 новостей
2022-04-21: 79 новостей
2022-04-22: 68 новостей
2022-04-23: 5 новостей
2022-04-24: 3 новостей
2022-04-25: 61 новостей
2022-04-26: 60 новостей
2022-04-27: 80 новостей
2022-04-28: 87 новостей
2022-04-29: 117 новостей
2022-04-30: 5 новостей
2022-05-01: 8 новостей
2022-05-02: 13 новостей
2022-05-03: 8 новостей
2022-05-04: 80 новостей
2022-05-05: 65 новостей
2022-05-06: 56 новостей
2022-05-07: 5 новостей
2022-05-08: 4 новостей
2022-05-09: 3 новостей
2022-05-10: 4 новостей
2022-05-11: 83 новостей
2022-05-12: 84 новостей
2022-05-13: 76 новостей
2022-05-14: 3 новостей
2022-05-15: 2 новостей
2022-05-16: 79 новостей
2022-05-17: 82 новостей
2022-05-18: 73 новостей
2022-05-19: 86 новостей
2022-05-20: 74 новостей
2022-05-21: 6 новостей
2022-05-22: 6 новостей
2022-05-23: 67 новостей
2022-05-24: 82 новостей
2022-05-25: 85 новостей
2022-05-26: 83 новостей
2022-05-27: 87 новостей
2022-05-28: 4 новостей
2022-05-29: 8 новостей
2022-05-30: 77 новостей
2022-05-31: 73 новостей
2022-06-01: 91 новостей
2022-06-02: 79 новостей
2022-06-03: 65 новостей
2022-06-04: 5 новостей
2022-06-05: 1 новостей
2022-06-06: 48 новостей
2022-06-07: 81 новостей
2022-06-08: 88 новостей
2022-06-09: 70 новостей
2022-06-10: 98 новостей
2022-06-11: 5 новостей
2022-06-12: 4 новостей
2022-06-13: 4 новостей
2022-06-14: 62 новостей
2022-06-15: 62 новостей
2022-06-16: 117 новостей
2022-06-17: 108 новостей
2022-06-18: 22 новостей
2022-06-19: 7 новостей
2022-06-20: 41 новостей
2022-06-21: 40 новостей
2022-06-22: 48 новостей
2022-06-23: 36 новостей
2022-06-24: 34 новостей
2022-06-25: 3 новостей
2022-06-26: 7 новостей
2022-06-27: 81 новостей
2022-06-28: 74 новостей
2022-06-29: 86 новостей
2022-06-30: 103 новостей
2022-07-01: 94 новостей
2022-07-02: 3 новостей
2022-07-03: 1 новостей
2022-07-04: 74 новостей
2022-07-05: 92 новостей
2022-07-06: 59 новостей
2022-07-07: 65 новостей
2022-07-08: 44 новостей
2022-07-09: 3 новостей
2022-07-10: 4 новостей
2022-07-11: 62 новостей
2022-07-12: 77 новостей
2022-07-13: 89 новостей
2022-07-14: 69 новостей
2022-07-15: 80 новостей
2022-07-16: 7 новостей
2022-07-17: 4 новостей
2022-07-18: 61 новостей
2022-07-19: 63 новостей
2022-07-20: 58 новостей
2022-07-21: 64 новостей
2022-07-22: 84 новостей
2022-07-23: 0 новостей
2022-07-24: 2 новостей
2022-07-25: 66 новостей
2022-07-26: 69 новостей
2022-07-27: 91 новостей
2022-07-28: 85 новостей
2022-07-29: 80 новостей
2022-07-30: 5 новостей
2022-07-31: 2 новостей
2022-08-01: 84 новостей
2022-08-02: 61 новостей
2022-08-03: 76 новостей
2022-08-04: 78 новостей
2022-08-05: 68 новостей
2022-08-06: 0 новостей
2022-08-07: 1 новостей
2022-08-08: 59 новостей
2022-08-09: 63 новостей
2022-08-10: 73 новостей
2022-08-11: 65 новостей
2022-08-12: 80 новостей
2022-08-13: 5 новостей
2022-08-14: 2 новостей
2022-08-15: 75 новостей
2022-08-16: 70 новостей
2022-08-17: 52 новостей
2022-08-18: 57 новостей
2022-08-19: 73 новостей
2022-08-20: 0 новостей
2022-08-21: 0 новостей
2022-08-22: 60 новостей
2022-08-23: 64 новостей
2022-08-24: 61 новостей
2022-08-25: 61 новостей
2022-08-26: 95 новостей
2022-08-27: 1 новостей
2022-08-28: 2 новостей
2022-08-29: 62 новостей
2022-08-30: 69 новостей
2022-08-31: 77 новостей
2022-09-01: 63 новостей
2022-09-02: 72 новостей
2022-09-03: 4 новостей
2022-09-04: 2 новостей
2022-09-05: 34 новостей
2022-09-06: 55 новостей
2022-09-07: 48 новостей
2022-09-08: 47 новостей
2022-09-09: 40 новостей
2022-09-10: 1 новостей
2022-09-11: 4 новостей
2022-09-12: 62 новостей
2022-09-13: 69 новостей
2022-09-14: 75 новостей
2022-09-15: 80 новостей
2022-09-16: 82 новостей
2022-09-17: 4 новостей
2022-09-18: 2 новостей
2022-09-19: 80 новостей
2022-09-20: 75 новостей
2022-09-21: 64 новостей
2022-09-22: 97 новостей
2022-09-23: 76 новостей
2022-09-24: 3 новостей
2022-09-25: 2 новостей
2022-09-26: 54 новостей
2022-09-27: 61 новостей
2022-09-28: 99 новостей
2022-09-29: 71 новостей
2022-09-30: 70 новостей
2022-10-01: 8 новостей
2022-10-02: 6 новостей
2022-10-03: 89 новостей
2022-10-04: 60 новостей
2022-10-05: 88 новостей
2022-10-06: 73 новостей
2022-10-07: 74 новостей
2022-10-08: 1 новостей
2022-10-09: 3 новостей
2022-10-10: 64 новостей
2022-10-11: 62 новостей
2022-10-12: 86 новостей
2022-10-13: 89 новостей
2022-10-14: 86 новостей
2022-10-15: 4 новостей
2022-10-16: 3 новостей
2022-10-17: 72 новостей
2022-10-18: 84 новостей
2022-10-19: 72 новостей
2022-10-20: 86 новостей
2022-10-21: 67 новостей
2022-10-22: 1 новостей
2022-10-23: 0 новостей
2022-10-24: 73 новостей
2022-10-25: 78 новостей
2022-10-26: 84 новостей
2022-10-27: 103 новостей
2022-10-28: 113 новостей
2022-10-29: 0 новостей
2022-10-30: 3 новостей
2022-10-31: 68 новостей
2022-11-01: 84 новостей
2022-11-02: 86 новостей
2022-11-03: 106 новостей
2022-11-04: 7 новостей
2022-11-05: 2 новостей
2022-11-06: 1 новостей
2022-11-07: 73 новостей
2022-11-08: 76 новостей
2022-11-09: 72 новостей
2022-11-10: 94 новостей
2022-11-11: 83 новостей
2022-11-12: 2 новостей
2022-11-13: 2 новостей
2022-11-14: 79 новостей
2022-11-15: 72 новостей
2022-11-16: 80 новостей
2022-11-17: 72 новостей
2022-11-18: 69 новостей
2022-11-19: 2 новостей
2022-11-20: 0 новостей
2022-11-21: 75 новостей
2022-11-22: 74 новостей
2022-11-23: 80 новостей
2022-11-24: 73 новостей
2022-11-25: 67 новостей
2022-11-26: 4 новостей
2022-11-27: 0 новостей
2022-11-28: 39 новостей
2022-11-29: 54 новостей
2022-11-30: 55 новостей
2022-12-01: 51 новостей
2022-12-02: 43 новостей
2022-12-03: 3 новостей
2022-12-04: 14 новостей
2022-12-05: 71 новостей
2022-12-06: 61 новостей
2022-12-07: 73 новостей

2022-12-08: 68 новостей
2022-12-09: 73 новостей
2022-12-10: 3 новостей
2022-12-11: 3 новостей
2022-12-12: 68 новостей
2022-12-13: 63 новостей
2022-12-14: 72 новостей
2022-12-15: 75 новостей
2022-12-16: 89 новостей
2022-12-17: 3 новостей
2022-12-18: 0 новостей
2022-12-19: 58 новостей
2022-12-20: 67 новостей
2022-12-21: 72 новостей
2022-12-22: 76 новостей
2022-12-23: 64 новостей
2022-12-24: 3 новостей
2022-12-25: 2 новостей
2022-12-26: 52 новостей
2022-12-27: 80 новостей
2022-12-28: 70 новостей
2022-12-29: 60 новостей
2022-12-30: 47 новостей
2022-12-31: 5 новостей
2023-01-01: 9 новостей
2023-01-02: 2 новостей
2023-01-03: 20 новостей
2023-01-04: 18 новостей
2023-01-05: 17 новостей
2023-01-06: 18 новостей
2023-01-07: 2 новостей
2023-01-08: 2 новостей
2023-01-09: 50 новостей
2023-01-10: 62 новостей
2023-01-11: 60 новостей
2023-01-12: 60 новостей
2023-01-13: 76 новостей
2023-01-14: 4 новостей
2023-01-15: 4 новостей
2023-01-16: 60 новостей
2023-01-17: 64 новостей
2023-01-18: 72 новостей
2023-01-19: 77 новостей
2023-01-20: 63 новостей
2023-01-21: 3 новостей
2023-01-22: 1 новостей
2023-01-23: 57 новостей
2023-01-24: 56 новостей
2023-01-25: 63 новостей
2023-01-26: 68 новостей
2023-01-27: 78 новостей
2023-01-28: 3 новостей
2023-01-29: 0 новостей
2023-01-30: 62 новостей
2023-01-31: 91 новостей
2023-02-01: 84 новостей
2023-02-02: 75 новостей
2023-02-03: 72 новостей
2023-02-04: 7 новостей
2023-02-05: 0 новостей
2023-02-06: 84 новостей
2023-02-07: 68 новостей
2023-02-08: 99 новостей
2023-02-09: 74 новостей
2023-02-10: 104 новостей
2023-02-11: 1 новостей
2023-02-12: 4 новостей
2023-02-13: 61 новостей
2023-02-14: 75 новостей
2023-02-15: 93 новостей
2023-02-16: 84 новостей
2023-02-17: 73 новостей
2023-02-18: 0 новостей
2023-02-19: 2 новостей
2023-02-20: 62 новостей
2023-02-21: 67 новостей
2023-02-22: 78 новостей
2023-02-23: 3 новостей
2023-02-24: 22 новостей
2023-02-25: 7 новостей
2023-02-26: 2 новостей
2023-02-27: 65 новостей
2023-02-28: 87 новостей
2023-03-01: 68 новостей
2023-03-02: 86 новостей
2023-03-03: 62 новостей
2023-03-04: 2 новостей
2023-03-05: 2 новостей
2023-03-06: 70 новостей
2023-03-07: 62 новостей
2023-03-08: 3 новостей
2023-03-09: 78 новостей
2023-03-10: 68 новостей
2023-03-11: 4 новостей
2023-03-12: 0 новостей
2023-03-13: 63 новостей
2023-03-14: 62 новостей
2023-03-15: 77 новостей
2023-03-16: 85 новостей
2023-03-17: 107 новостей
2023-03-18: 0 новостей
2023-03-19: 2 новостей
2023-03-20: 78 новостей
2023-03-21: 69 новостей
2023-03-22: 66 новостей
2023-03-23: 63 новостей
2023-03-24: 67 новостей
2023-03-25: 1 новостей
2023-03-26: 2 новостей
2023-03-27: 75 новостей
2023-03-28: 68 новостей
2023-03-29: 74 новостей
2023-03-30: 70 новостей
2023-03-31: 57 новостей
2023-04-01: 4 новостей
2023-04-02: 4 новостей
2023-04-03: 72 новостей
2023-04-04: 60 новостей
2023-04-05: 82 новостей
2023-04-06: 76 новостей
2023-04-07: 74 новостей
2023-04-08: 2 новостей
2023-04-09: 2 новостей
2023-04-10: 57 новостей
2023-04-11: 70 новостей
2023-04-12: 63 новостей
2023-04-13: 77 новостей
2023-04-14: 89 новостей
2023-04-15: 2 новостей
2023-04-16: 3 новостей
2023-04-17: 57 новостей
2023-04-18: 71 новостей
2023-04-19: 76 новостей
2023-04-20: 92 новостей
2023-04-21: 99 новостей
2023-04-22: 3 новостей
2023-04-23: 1 новостей
2023-04-24: 72 новостей
2023-04-25: 75 новостей
2023-04-26: 72 новостей
2023-04-27: 84 новостей
2023-04-28: 117 новостей
2023-04-29: 0 новостей
2023-04-30: 0 новостей
2023-05-01: 4 новостей
2023-05-02: 91 новостей
2023-05-03: 83 новостей
2023-05-04: 88 новостей
2023-05-05: 69 новостей
2023-05-06: 3 новостей
2023-05-07: 1 новостей
2023-05-08: 18 новостей
2023-05-09: 6 новостей
2023-05-10: 83 новостей
2023-05-11: 91 новостей
2023-05-12: 72 новостей
2023-05-13: 1 новостей
2023-05-14: 1 новостей
2023-05-15: 58 новостей
2023-05-16: 63 новостей
2023-05-17: 76 новостей
2023-05-18: 86 новостей
2023-05-19: 73 новостей
2023-05-20: 1 новостей
2023-05-21: 1 новостей
2023-05-22: 61 новостей
2023-05-23: 65 новостей
2023-05-24: 83 новостей
2023-05-25: 81 новостей
2023-05-26: 74 новостей
2023-05-27: 1 новостей
2023-05-28: 0 новостей
2023-05-29: 58 новостей
2023-05-30: 62 новостей
2023-05-31: 101 новостей
2023-06-01: 74 новостей
2023-06-02: 68 новостей
2023-06-03: 6 новостей
2023-06-04: 7 новостей
2023-06-05: 66 новостей
2023-06-06: 52 новостей
2023-06-07: 77 новостей
2023-06-08: 57 новостей
2023-06-09: 89 новостей
2023-06-10: 2 новостей
2023-06-11: 2 новостей
2023-06-12: 4 новостей
2023-06-13: 70 новостей
2023-06-14: 71 новостей
2023-06-15: 126 новостей
2023-06-16: 127 новостей
2023-06-17: 16 новостей
2023-06-18: 0 новостей
2023-06-19: 28 новостей
2023-06-20: 35 новостей
2023-06-21: 41 новостей
2023-06-22: 43 новостей
2023-06-23: 38 новостей
2023-06-24: 1 новостей
2023-06-25: 3 новостей
2023-06-26: 36 новостей
2023-06-27: 45 новостей
2023-06-28: 47 новостей
2023-06-29: 39 новостей
2023-06-30: 57 новостей
2023-07-01: 3 новостей
2023-07-02: 1 новостей
2023-07-03: 90 новостей
2023-07-04: 52 новостей
2023-07-05: 69 новостей
2023-07-06: 88 новостей
2023-07-07: 81 новостей
2023-07-08: 3 новостей
2023-07-09: 1 новостей
2023-07-10: 66 новостей
2023-07-11: 66 новостей
2023-07-12: 71 новостей
2023-07-13: 58 новостей
2023-07-14: 55 новостей
2023-07-15: 1 новостей
2023-07-16: 2 новостей
2023-07-17: 58 новостей
2023-07-18: 71 новостей
2023-07-19: 75 новостей
2023-07-20: 96 новостей
2023-07-21: 78 новостей
2023-07-22: 1 новостей
2023-07-23: 1 новостей
2023-07-24: 60 новостей
2023-07-25: 83 новостей
2023-07-26: 96 новостей
2023-07-27: 87 новостей
2023-07-28: 82 новостей
2023-07-29: 2 новостей
2023-07-30: 2 новостей
2023-07-31: 63 новостей
2023-08-01: 64 новостей
2023-08-02: 83 новостей
2023-08-03: 89 новостей
2023-08-04: 62 новостей
2023-08-05: 0 новостей
2023-08-06: 2 новостей
2023-08-07: 71 новостей
2023-08-08: 68 новостей
2023-08-09: 58 новостей
2023-08-10: 57 новостей
2023-08-11: 69 новостей
2023-08-12: 1 новостей
2023-08-13: 1 новостей
2023-08-14: 60 новостей
2023-08-15: 56 новостей
2023-08-16: 63 новостей
2023-08-17: 52 новостей
2023-08-18: 50 новостей
2023-08-19: 1 новостей
2023-08-20: 3 новостей
2023-08-21: 64 новостей
2023-08-22: 66 новостей
2023-08-23: 63 новостей
2023-08-24: 50 новостей
2023-08-25: 76 новостей
2023-08-26: 4 новостей
2023-08-27: 0 новостей
2023-08-28: 70 новостей
2023-08-29: 96 новостей
2023-08-30: 82 новостей
2023-08-31: 57 новостей
2023-09-01: 79 новостей
2023-09-02: 1 новостей
2023-09-03: 0 новостей
2023-09-04: 40 новостей
2023-09-05: 47 новостей
2023-09-06: 55 новостей
2023-09-07: 43 новостей
2023-09-08: 34 новостей
2023-09-09: 1 новостей
2023-09-10: 3 новостей
2023-09-11: 89 новостей
2023-09-12: 100 новостей
2023-09-13: 69 новостей
2023-09-14: 64 новостей
2023-09-15: 82 новостей
2023-09-16: 3 новостей
2023-09-17: 0 новостей
2023-09-18: 72 новостей
2023-09-19: 64 новостей
2023-09-20: 91 новостей
2023-09-21: 78 новостей
2023-09-22: 113 новостей
2023-09-23: 3 новостей
2023-09-24: 8 новостей
2023-09-25: 96 новостей
2023-09-26: 61 новостей
2023-09-27: 103 новостей
2023-09-28: 97 новостей
2023-09-29: 108 новостей
2023-09-30: 2 новостей
2023-10-01: 3 новостей
2023-10-02: 69 новостей
2023-10-03: 79 новостей
2023-10-04: 80 новостей
2023-10-05: 78 новостей
2023-10-06: 78 новостей
2023-10-07: 5 новостей
2023-10-08: 1 новостей
2023-10-09: 70 новостей
2023-10-10: 65 новостей
2023-10-11: 71 новостей
2023-10-12: 100 новостей
2023-10-13: 74 новостей
2023-10-14: 3 новостей
2023-10-15: 0 новостей
2023-10-16: 66 новостей
2023-10-17: 72 новостей
2023-10-18: 78 новостей
2023-10-19: 79 новостей
2023-10-20: 73 новостей
2023-10-21: 5 новостей
2023-10-22: 5 новостей
2023-10-23: 68 новостей
2023-10-24: 58 новостей
2023-10-25: 92 новостей
2023-10-26: 84 новостей
2023-10-27: 97 новостей
2023-10-28: 1 новостей
2023-10-29: 1 новостей
2023-10-30: 65 новостей
2023-10-31: 76 новостей
2023-11-01: 86 новостей
2023-11-02: 87 новостей
2023-11-03: 76 новостей
2023-11-04: 7 новостей
2023-11-05: 2 новостей
2023-11-06: 16 новостей
2023-11-07: 79 новостей
2023-11-08: 87 новостей
2023-11-09: 89 новостей
2023-11-10: 87 новостей
2023-11-11: 1 новостей
2023-11-12: 0 новостей
2023-11-13: 67 новостей
2023-11-14: 72 новостей
2023-11-15: 90 новостей
2023-11-16: 66 новостей
2023-11-17: 70 новостей
2023-11-18: 1 новостей

2023-11-19: 0 новостей
2023-11-20: 61 новостей
2023-11-21: 58 новостей
2023-11-22: 68 новостей
2023-11-23: 71 новостей
2023-11-24: 68 новостей
2023-11-25: 6 новостей
2023-11-26: 1 новостей
2023-11-27: 59 новостей
2023-11-28: 63 новостей
2023-11-29: 100 новостей
2023-11-30: 114 новостей
2023-12-01: 69 новостей
2023-12-02: 1 новостей
2023-12-03: 0 новостей
2023-12-04: 74 новостей
2023-12-05: 82 новостей
2023-12-06: 92 новостей
2023-12-07: 102 новостей
2023-12-08: 83 новостей
2023-12-09: 1 новостей
2023-12-10: 5 новостей
2023-12-11: 60 новостей
2023-12-12: 73 новостей
2023-12-13: 70 новостей
2023-12-14: 76 новостей
2023-12-15: 82 новостей
2023-12-16: 0 новостей
2023-12-17: 8 новостей
2023-12-18: 89 новостей
2023-12-19: 67 новостей
2023-12-20: 100 новостей
2023-12-21: 67 новостей
2023-12-22: 64 новостей
2023-12-23: 4 новостей
2023-12-24: 2 новостей
2023-12-25: 58 новостей
2023-12-26: 58 новостей
2023-12-27: 86 новостей
2023-12-28: 78 новостей
2023-12-29: 62 новостей
2023-12-30: 3 новостей
2023-12-31: 1 новостей
2024-01-01: 12 новостей
2024-01-02: 0 новостей
2024-01-03: 29 новостей
2024-01-04: 15 новостей
2024-01-05: 19 новостей
2024-01-06: 1 новостей
2024-01-07: 2 новостей
2024-01-08: 17 новостей
2024-01-09: 69 новостей
2024-01-10: 65 новостей
2024-01-11: 66 новостей
2024-01-12: 83 новостей
2024-01-13: 1 новостей
2024-01-14: 0 новостей
2024-01-15: 76 новостей
2024-01-16: 62 новостей
2024-01-17: 84 новостей
2024-01-18: 70 новостей
2024-01-19: 70 новостей
2024-01-20: 1 новостей
2024-01-21: 3 новостей
2024-01-22: 58 новостей
2024-01-23: 60 новостей
2024-01-24: 80 новостей
2024-01-25: 87 новостей
2024-01-26: 84 новостей
2024-01-27: 15 новостей
2024-01-28: 2 новостей
2024-01-29: 75 новостей
2024-01-30: 90 новостей
2024-01-31: 97 новостей
2024-02-01: 85 новостей
2024-02-02: 86 новостей
2024-02-03: 1 новостей
2024-02-04: 2 новостей
2024-02-05: 95 новостей
2024-02-06: 78 новостей
2024-02-07: 87 новостей
2024-02-08: 81 новостей
2024-02-09: 83 новостей
2024-02-10: 0 новостей
2024-02-11: 0 новостей
2024-02-12: 67 новостей
2024-02-13: 65 новостей
2024-02-14: 96 новостей
2024-02-15: 88 новостей
2024-02-16: 78 новостей
2024-02-17: 1 новостей
2024-02-18: 2 новостей
2024-02-19: 83 новостей
2024-02-20: 80 новостей
2024-02-21: 86 новостей
2024-02-22: 94 новостей
2024-02-23: 14 новостей
2024-02-24: 3 новостей
2024-02-25: 0 новостей
2024-02-26: 73 новостей
2024-02-27: 78 новостей
2024-02-28: 105 новостей
2024-02-29: 93 новостей
2024-03-01: 81 новостей
2024-03-02: 3 новостей
2024-03-03: 7 новостей
2024-03-04: 63 новостей
2024-03-05: 68 новостей
2024-03-06: 75 новостей
2024-03-07: 57 новостей
2024-03-08: 1 новостей
2024-03-09: 2 новостей
2024-03-10: 1 новостей
2024-03-11: 68 новостей
2024-03-12: 64 новостей
2024-03-13: 86 новостей
2024-03-14: 65 новостей
2024-03-15: 65 новостей
2024-03-16: 0 новостей
2024-03-17: 1 новостей
2024-03-18: 48 новостей
2024-03-19: 60 новостей
2024-03-20: 67 новостей
2024-03-21: 80 новостей
2024-03-22: 91 новостей
2024-03-23: 5 новостей
2024-03-24: 0 новостей
Ошибка при парсинге https://www.interfax.ru/business/news/2024/03/25: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/news/2024/03/25 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A7CDE962D0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
2024-03-25: 0 новостей
2024-03-26: 56 новостей
2024-03-27: 89 новостей
2024-03-28: 75 новостей
2024-03-29: 83 новостей
2024-03-30: 1 новостей
2024-03-31: 0 новостей
2024-04-01: 63 новостей
2024-04-02: 71 новостей
2024-04-03: 76 новостей
2024-04-04: 73 новостей
2024-04-05: 90 новостей
2024-04-06: 0 новостей
2024-04-07: 1 новостей
2024-04-08: 78 новостей
2024-04-09: 61 новостей
2024-04-10: 74 новостей
2024-04-11: 76 новостей
2024-04-12: 66 новостей
2024-04-13: 6 новостей
2024-04-14: 2 новостей
2024-04-15: 63 новостей
2024-04-16: 87 новостей
2024-04-17: 76 новостей
2024-04-18: 81 новостей
2024-04-19: 73 новостей
2024-04-20: 1 новостей
2024-04-21: 0 новостей
2024-04-22: 71 новостей
2024-04-23: 94 новостей
2024-04-24: 78 новостей
2024-04-25: 95 новостей
2024-04-26: 133 новостей
2024-04-27: 66 новостей
2024-04-28: 3 новостей
2024-04-29: 21 новостей
2024-04-30: 20 новостей
2024-05-01: 7 новостей
2024-05-02: 103 новостей
2024-05-03: 60 новостей
2024-05-04: 3 новостей
2024-05-05: 0 новостей
2024-05-06: 60 новостей
2024-05-07: 63 новостей
2024-05-08: 81 новостей
2024-05-09: 3 новостей
2024-05-10: 19 новостей
2024-05-11: 2 новостей
2024-05-12: 4 новостей
2024-05-13: 59 новостей
2024-05-14: 82 новостей
2024-05-15: 112 новостей
2024-05-16: 112 новостей
2024-05-17: 85 новостей
2024-05-18: 4 новостей
2024-05-19: 0 новостей
2024-05-20: 80 новостей
2024-05-21: 76 новостей
2024-05-22: 81 новостей
2024-05-23: 84 новостей
2024-05-24: 75 новостей
2024-05-25: 5 новостей
2024-05-26: 0 новостей
2024-05-27: 82 новостей
2024-05-28: 63 новостей
2024-05-29: 106 новостей
2024-05-30: 67 новостей
2024-05-31: 84 новостей
2024-06-01: 3 новостей
2024-06-02: 8 новостей
2024-06-03: 69 новостей
2024-06-04: 65 новостей
2024-06-05: 109 новостей
2024-06-06: 137 новостей
2024-06-07: 145 новостей
2024-06-08: 17 новостей
2024-06-09: 0 новостей
2024-06-10: 80 новостей
2024-06-11: 68 новостей
2024-06-12: 17 новостей
2024-06-13: 79 новостей
2024-06-14: 69 новостей
2024-06-15: 5 новостей
2024-06-16: 0 новостей
2024-06-17: 35 новостей
2024-06-18: 38 новостей
2024-06-19: 53 новостей
2024-06-20: 43 новостей
2024-06-21: 40 новостей
2024-06-22: 5 новостей
2024-06-23: 0 новостей
2024-06-24: 37 новостей
2024-06-25: 35 новостей
2024-06-26: 50 новостей
2024-06-27: 33 новостей
2024-06-28: 52 новостей
2024-06-29: 1 новостей
2024-06-30: 0 новостей
2024-07-01: 86 новостей
2024-07-02: 65 новостей
2024-07-03: 89 новостей
2024-07-04: 79 новостей
2024-07-05: 73 новостей
2024-07-06: 4 новостей
2024-07-07: 0 новостей
2024-07-08: 78 новостей
2024-07-09: 86 новостей
2024-07-10: 79 новостей
2024-07-11: 60 новостей
2024-07-12: 74 новостей
2024-07-13: 1 новостей
2024-07-14: 1 новостей
2024-07-15: 73 новостей
2024-07-16: 54 новостей
2024-07-17: 61 новостей
2024-07-18: 59 новостей
2024-07-19: 55 новостей
2024-07-20: 5 новостей
2024-07-21: 2 новостей
2024-07-22: 66 новостей
2024-07-23: 64 новостей
2024-07-24: 76 новостей
2024-07-25: 83 новостей
2024-07-26: 78 новостей
2024-07-27: 0 новостей
2024-07-28: 0 новостей
2024-07-29: 53 новостей
2024-07-30: 72 новостей
2024-07-31: 82 новостей
2024-08-01: 85 новостей
2024-08-02: 65 новостей
2024-08-03: 1 новостей
2024-08-04: 0 новостей
2024-08-05: 69 новостей
2024-08-06: 68 новостей
2024-08-07: 77 новостей
2024-08-08: 67 новостей
2024-08-09: 74 новостей
2024-08-10: 1 новостей
2024-08-11: 1 новостей
2024-08-12: 53 новостей
2024-08-13: 58 новостей
2024-08-14: 69 новостей
2024-08-15: 64 новостей
2024-08-16: 59 новостей
2024-08-17: 2 новостей
2024-08-18: 1 новостей
2024-08-19: 52 новостей
2024-08-20: 63 новостей
2024-08-21: 69 новостей
2024-08-22: 68 новостей
2024-08-23: 67 новостей
2024-08-24: 2 новостей
2024-08-25: 2 новостей
2024-08-26: 55 новостей
2024-08-27: 61 новостей
2024-08-28: 90 новостей
2024-08-29: 103 новостей
2024-08-30: 84 новостей
2024-08-31: 0 новостей
2024-09-01: 4 новостей
2024-09-02: 35 новостей
2024-09-03: 45 новостей
2024-09-04: 74 новостей
2024-09-05: 71 новостей
2024-09-06: 46 новостей
2024-09-07: 0 новостей
2024-09-08: 1 новостей
2024-09-09: 58 новостей
2024-09-10: 55 новостей
2024-09-11: 62 новостей
2024-09-12: 60 новостей
2024-09-13: 82 новостей
2024-09-14: 0 новостей
2024-09-15: 1 новостей
2024-09-16: 55 новостей
2024-09-17: 52 новостей
2024-09-18: 80 новостей
2024-09-19: 67 новостей
2024-09-20: 63 новостей
2024-09-21: 1 новостей
2024-09-22: 0 новостей
2024-09-23: 67 новостей
2024-09-24: 74 новостей
2024-09-25: 85 новостей
2024-09-26: 90 новостей
2024-09-27: 69 новостей
2024-09-28: 0 новостей
2024-09-29: 0 новостей
2024-09-30: 106 новостей
2024-10-01: 78 новостей
2024-10-02: 87 новостей
2024-10-03: 75 новостей
2024-10-04: 58 новостей
2024-10-05: 1 новостей
2024-10-06: 0 новостей
2024-10-07: 69 новостей
2024-10-08: 78 новостей
2024-10-09: 74 новостей
2024-10-10: 85 новостей
2024-10-11: 78 новостей
2024-10-12: 1 новостей
2024-10-13: 1 новостей
2024-10-14: 73 новостей

2024-10-15: 74 новостей
2024-10-16: 86 новостей
2024-10-17: 95 новостей
2024-10-18: 73 новостей
2024-10-19: 2 новостей
2024-10-20: 6 новостей
2024-10-21: 57 новостей
2024-10-22: 93 новостей
2024-10-23: 85 новостей
2024-10-24: 69 новостей
2024-10-25: 82 новостей
2024-10-26: 3 новостей
2024-10-27: 0 новостей
2024-10-28: 58 новостей
2024-10-29: 70 новостей
2024-10-30: 100 новостей
2024-10-31: 97 новостей
2024-11-01: 60 новостей
2024-11-02: 45 новостей
2024-11-03: 5 новостей
2024-11-04: 4 новостей
2024-11-05: 65 новостей
2024-11-06: 66 новостей
2024-11-07: 69 новостей
2024-11-08: 79 новостей
2024-11-09: 3 новостей
2024-11-10: 1 новостей
2024-11-11: 65 новостей
2024-11-12: 64 новостей
2024-11-13: 83 новостей
2024-11-14: 79 новостей
2024-11-15: 80 новостей
2024-11-16: 1 новостей
2024-11-17: 0 новостей
2024-11-18: 54 новостей
2024-11-19: 89 новостей
2024-11-20: 79 новостей
2024-11-21: 73 новостей
2024-11-22: 73 новостей
2024-11-23: 2 новостей
2024-11-24: 1 новостей
2024-11-25: 67 новостей
2024-11-26: 73 новостей
2024-11-27: 97 новостей
2024-11-28: 83 новостей
2024-11-29: 100 новостей
2024-11-30: 6 новостей
2024-12-01: 1 новостей
2024-12-02: 78 новостей
2024-12-03: 62 новостей
2024-12-04: 91 новостей
2024-12-05: 111 новостей
2024-12-06: 88 новостей
2024-12-07: 1 новостей
2024-12-08: 1 новостей
2024-12-09: 79 новостей
2024-12-10: 83 новостей
2024-12-11: 79 новостей
2024-12-12: 74 новостей
2024-12-13: 76 новостей
2024-12-14: 7 новостей
2024-12-15: 1 новостей
2024-12-16: 73 новостей
2024-12-17: 62 новостей
2024-12-18: 95 новостей
2024-12-19: 75 новостей
2024-12-20: 103 новостей
2024-12-21: 3 новостей
2024-12-22: 2 новостей
2024-12-23: 78 новостей
2024-12-24: 69 новостей
2024-12-25: 73 новостей
2024-12-26: 68 новостей
2024-12-27: 61 новостей
2024-12-28: 36 новостей
2024-12-29: 1 новостей
2024-12-30: 22 новостей
2024-12-31: 3 новостей
2025-01-01: 24 новостей
2025-01-02: 2 новостей
2025-01-03: 19 новостей
2025-01-04: 2 новостей
2025-01-05: 1 новостей
2025-01-06: 27 новостей
2025-01-07: 0 новостей
2025-01-08: 11 новостей
2025-01-09: 68 новостей
2025-01-10: 78 новостей
2025-01-11: 2 новостей
2025-01-12: 1 новостей
2025-01-13: 69 новостей
2025-01-14: 67 новостей
2025-01-15: 100 новостей
2025-01-16: 64 новостей
2025-01-17: 77 новостей
2025-01-18: 0 новостей
2025-01-19: 1 новостей
2025-01-20: 61 новостей
2025-01-21: 67 новостей
2025-01-22: 74 новостей
2025-01-23: 69 новостей
2025-01-24: 85 новостей
2025-01-25: 2 новостей
2025-01-26: 0 новостей
2025-01-27: 62 новостей
2025-01-28: 84 новостей
2025-01-29: 89 новостей
2025-01-30: 97 новостей
2025-01-31: 72 новостей
2025-02-01: 5 новостей
2025-02-02: 1 новостей
2025-02-03: 86 новостей
2025-02-04: 85 новостей
2025-02-05: 117 новостей
2025-02-06: 76 новостей
2025-02-07: 74 новостей
2025-02-08: 1 новостей
2025-02-09: 0 новостей
2025-02-10: 58 новостей
2025-02-11: 77 новостей
2025-02-12: 84 новостей
2025-02-13: 83 новостей
2025-02-14: 102 новостей
2025-02-15: 2 новостей
2025-02-16: 0 новостей
2025-02-17: 60 новостей
2025-02-18: 71 новостей
2025-02-19: 85 новостей
2025-02-20: 94 новостей
2025-02-21: 57 новостей
2025-02-22: 1 новостей
2025-02-23: 3 новостей
2025-02-24: 88 новостей
2025-02-25: 70 новостей
2025-02-26: 81 новостей
2025-02-27: 105 новостей
2025-02-28: 86 новостей
2025-03-01: 7 новостей
2025-03-02: 1 новостей
2025-03-03: 73 новостей
2025-03-04: 74 новостей
2025-03-05: 92 новостей
2025-03-06: 78 новостей
2025-03-07: 99 новостей
2025-03-08: 0 новостей
2025-03-09: 1 новостей
2025-03-10: 63 новостей
2025-03-11: 66 новостей
2025-03-12: 76 новостей
2025-03-13: 88 новостей
2025-03-14: 73 новостей
2025-03-15: 1 новостей
2025-03-16: 4 новостей
2025-03-17: 76 новостей
2025-03-18: 87 новостей
2025-03-19: 85 новостей
2025-03-20: 93 новостей
2025-03-21: 87 новостей
2025-03-22: 0 новостей
2025-03-23: 1 новостей
2025-03-24: 63 новостей
2025-03-25: 84 новостей
2025-03-26: 92 новостей
2025-03-27: 94 новостей
2025-03-28: 81 новостей
2025-03-29: 1 новостей
2025-03-30: 0 новостей
2025-03-31: 84 новостей
2025-04-01: 92 новостей
2025-04-02: 97 новостей
2025-04-03: 92 новостей
2025-04-04: 65 новостей
2025-04-05: 4 новостей
2025-04-06: 2 новостей
2025-04-07: 77 новостей
2025-04-08: 92 новостей
2025-04-09: 100 новостей
2025-04-10: 82 новостей
2025-04-11: 74 новостей
2025-04-12: 1 новостей
2025-04-13: 0 новостей
2025-04-14: 73 новостей
2025-04-15: 104 новостей
2025-04-16: 79 новостей
2025-04-17: 83 новостей
2025-04-18: 57 новостей
2025-04-19: 1 новостей
2025-04-20: 1 новостей
2025-04-21: 56 новостей
2025-04-22: 74 новостей
2025-04-23: 86 новостей
2025-04-24: 98 новостей
2025-04-25: 97 новостей
2025-04-26: 2 новостей
2025-04-27: 0 новостей
2025-04-28: 73 новостей
2025-04-29: 91 новостей
2025-04-30: 130 новостей
2025-05-01: 2 новостей
2025-05-02: 28 новостей
2025-05-03: 5 новостей
2025-05-04: 1 новостей
2025-05-05: 72 новостей
2025-05-06: 73 новостей
2025-05-07: 66 новостей
2025-05-08: 24 новостей
2025-05-09: 6 новостей
2025-05-10: 7 новостей
2025-05-11: 1 новостей
2025-05-12: 93 новостей
2025-05-13: 70 новостей
2025-05-14: 118 новостей
2025-05-15: 82 новостей
2025-05-16: 92 новостей
2025-05-17: 1 новостей
2025-05-18: 1 новостей
2025-05-19: 75 новостей
2025-05-20: 114 новостей
2025-05-21: 92 новостей
2025-05-22: 86 новостей
2025-05-23: 79 новостей
2025-05-24: 1 новостей
2025-05-25: 0 новостей
2025-05-26: 75 новостей
2025-05-27: 99 новостей
2025-05-28: 101 новостей
2025-05-29: 76 новостей
2025-05-30: 90 новостей
2025-05-31: 5 новостей
2025-06-01: 0 новостей
2025-06-02: 63 новостей
2025-06-03: 58 новостей
2025-06-04: 96 новостей
2025-06-05: 88 новостей
2025-06-06: 103 новостей
2025-06-07: 3 новостей
2025-06-08: 0 новостей
2025-06-09: 55 новостей
2025-06-10: 88 новостей
2025-06-11: 81 новостей
2025-06-12: 7 новостей
2025-06-13: 20 новостей
2025-06-14: 4 новостей
2025-06-15: 0 новостей
2025-06-16: 38 новостей
2025-06-17: 57 новостей
2025-06-18: 65 новостей
2025-06-19: 83 новостей
2025-06-20: 102 новостей
2025-06-21: 22 новостей
2025-06-22: 2 новостей
2025-06-23: 26 новостей
2025-06-24: 29 новостей
2025-06-25: 41 новостей
2025-06-26: 29 новостей
2025-06-27: 66 новостей
2025-06-28: 4 новостей
2025-06-29: 0 новостей
2025-06-30: 70 новостей
2025-07-01: 83 новостей
2025-07-02: 101 новостей
2025-07-03: 100 новостей
2025-07-04: 74 новостей
2025-07-05: 7 новостей
2025-07-06: 4 новостей
2025-07-07: 66 новостей
2025-07-08: 73 новостей
2025-07-09: 79 новостей
2025-07-10: 80 новостей
2025-07-11: 83 новостей
2025-07-12: 5 новостей
2025-07-13: 0 новостей
2025-07-14: 49 новостей
2025-07-15: 58 новостей
2025-07-16: 58 новостей
2025-07-17: 62 новостей
2025-07-18: 82 новостей
2025-07-19: 11 новостей
2025-07-20: 3 новостей
2025-07-21: 51 новостей
2025-07-22: 53 новостей
2025-07-23: 48 новостей
2025-07-24: 55 новостей
2025-07-25: 76 новостей
2025-07-26: 1 новостей
2025-07-27: 1 новостей
2025-07-28: 42 новостей
2025-07-29: 70 новостей
2025-07-30: 89 новостей
2025-07-31: 94 новостей
2025-08-01: 65 новостей
2025-08-02: 2 новостей
2025-08-03: 5 новостей
2025-08-04: 55 новостей
2025-08-05: 65 новостей
2025-08-06: 70 новостей
2025-08-07: 80 новостей
2025-08-08: 69 новостей
2025-08-09: 2 новостей
2025-08-10: 0 новостей
2025-08-11: 52 новостей
2025-08-12: 76 новостей
2025-08-13: 64 новостей
2025-08-14: 68 новостей
2025-08-15: 74 новостей
2025-08-16: 1 новостей
2025-08-17: 1 новостей
2025-08-18: 49 новостей
2025-08-19: 51 новостей
2025-08-20: 82 новостей
2025-08-21: 63 новостей
2025-08-22: 66 новостей
2025-08-23: 2 новостей
2025-08-24: 0 новостей
2025-08-25: 65 новостей
2025-08-26: 67 новостей
2025-08-27: 91 новостей
2025-08-28: 79 новостей
2025-08-29: 112 новостей
2025-08-30: 5 новостей
2025-08-31: 1 новостей
2025-09-01: 51 новостей
2025-09-02: 56 новостей
2025-09-03: 48 новостей
2025-09-04: 60 новостей
2025-09-05: 66 новостей
2025-09-06: 0 новостей
2025-09-07: 7 новостей
2025-09-08: 85 новостей
2025-09-09: 77 новостей
2025-09-10: 59 новостей
2025-09-11: 71 новостей
2025-09-12: 98 новостей
2025-09-13: 2 новостей
2025-09-14: 2 новостей
2025-09-15: 64 новостей
2025-09-16: 58 новостей
2025-09-17: 84 новостей
2025-09-18: 84 новостей
2025-09-19: 66 новостей
2025-09-20: 3 новостей
2025-09-21: 3 новостей
2025-09-22: 64 новостей
2025-09-23: 70 новостей
2025-09-24: 122 новостей

2025-09-25: 89 новостей
2025-09-26: 78 новостей
2025-09-27: 1 новостей
2025-09-28: 1 новостей
2025-09-29: 68 новостей
2025-09-30: 92 новостей
2025-10-01: 97 новостей
2025-10-02: 75 новостей
2025-10-03: 68 новостей
2025-10-04: 0 новостей
2025-10-05: 3 новостей
2025-10-06: 83 новостей
2025-10-07: 82 новостей
2025-10-08: 97 новостей
2025-10-09: 100 новостей
2025-10-10: 73 новостей
2025-10-11: 0 новостей
2025-10-12: 5 новостей
2025-10-13: 62 новостей
2025-10-14: 83 новостей
2025-10-15: 107 новостей
2025-10-16: 80 новостей
2025-10-17: 64 новостей
2025-10-18: 3 новостей
2025-10-19: 0 новостей

=== РЕЗУЛЬТАТ ===
Итоговый размер датафрейма: 71117 новостей

Первые 5 записей:
              datetime                                               text
0  2022-01-02 09:37:00  Экспорт нефти из РФ в дальнее зарубежье в 2021...
1  2022-01-02 09:42:00  Добыча нефти в РФ в 2021 году повысилась до 52...
2  2022-01-02 09:46:00    Добыча газа в России в 2021 году выросла на 10%
3  2022-01-02 15:18:00  Миллер заявил, что в "Газпроме" ждут за 2021 г...
4  2022-01-02 15:21:00  "Газпром" в 2021 году добыл 514,8 млрд куб. м ...

Диапазон дат: 2022-01-02 09:37:00 - 2025-10-18 17:24:00

In [6]:
final_df.to_csv('interfax_news_2022_2025.csv', index = False, encoding = 'utf-8')

In [7]:
df_2 = pd.read_csv('data/news_interfax.csv')
df_2.head()

              datetime                                                                                  text
0  2022-01-02 09:37:00                  Экспорт нефти из РФ в дальнее зарубежье в 2021 году снизился на 2,2%
1  2022-01-02 09:42:00                           Добыча нефти в РФ в 2021 году повысилась до 524,05 млн тонн
2  2022-01-02 09:46:00                                       Добыча газа в России в 2021 году выросла на 10%
3  2022-01-02 15:18:00  Миллер заявил, что в "Газпроме" ждут за 2021 год максимальную за его историю прибыль
4  2022-01-02 15:21:00                                    "Газпром" в 2021 году добыл 514,8 млрд куб. м газа

In [45]:
final_df.shape

(71117, 4)

In [10]:
df_2[df_2['datetime'] >= '2022-04-01']['text']

4427              Фондовые индексы США закрылись снижением, показав максимальное квартальное падение за 2 года
4428                              Цены на нефть продолжили падать после заявления Байдена по нефтяным резервам
4429                                  Европейские покупатели сохраняют высокие заявки на отбор газа "Газпрома"
4430                                            ЦБ смягчит ограничения на переводы средств за рубеж для физлиц
4431                                       Индекс PMI обрабатывающих отраслей РФ в марте рухнул до 44,1 пункта
                                                         ...
71112                                       Индекс Мосбиржи превысил 2720 пунктов на геополитическом оптимизме
71113                         Рубль в пятницу сильно упал в паре с юанем, растеряв весь рост предыдущих сессий
71114                                                  "Газпром" подал к Linde иск в суд РФ о возмещении вреда
71115                     "ВСМПО-Ависма" с 1 декабря планирует перевести административный персонал на 4-дневку
71116    Повышение утильсбора не затронет всех импортеров, приобретших машины до вступления в силу новой нормы
Name: text, Length: 66690, dtype: object

In [11]:
df.head()

              datetime                                                                                         title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               full_text                                      url
0  2022-04-01 08:36:00  Фондовые индексы США закрылись снижением, показав максимальное квартальное падение за 2 года                                                                                                                                                                                                Фондовые индексы США закрылись снижением, показав максимальное квартальное падение за 2 года\nМосква. 1 апреля. INTERFAX.RU - Американские фондовые индексы завершили снижением вторые торги подряд в четверг, закрывшись на сессионных минимумах.\nПри этом все три индикатора продемонстрировали самый существенный квартальный спад за два года,\nпишет\nMarketWatch. В то же время по итогам марта индексы выросли.\n"Худший квартал за два года не так плох, поскольку индекс S&P 500 находится примерно в 5% от рекордных максимумов", - отметил старший рыночный аналитик Oanda Эдвард Мойя.\nТрейдеры оценивали новую порцию статистических данных и следили за новостями, касающимися ситуации на Украине.\nКоличество американцев, впервые обратившихся за пособием по безработице, на прошлой неделе увеличилось на 14 тыс. - до 202 тыс. человек, сообщается в отчете министерства труда США.\nСогласно уточненным данным, неделей ранее число обращений составило 188 тыс., а не 187 тыс., как сообщалось ранее.\nОпрошенные Bloomberg аналитики в среднем ожидали повышения числа заявок до 196 тыс. с ранее объявленного уровня. Респонденты Trading Economics прогнозировали 197 тыс.\nТем временем расходы населения США в феврале выросли на 0,2% по сравнению с предыдущим месяцем, свидетельствуют данные министерства торговли страны.\nДоходы американцев увеличились на 0,5%.\nЭксперты, опрошенные агентством Bloomberg, прогнозировали подъем обоих показателей на 0,5%.\nАкции ряда технологических компаний подешевели по итогам торгов в четверг. Так, бумаги Advanced Micro Devices Inc. потеряли 8,3% после того, как аналитики Barclays ухудшили рекомендацию по акциям компании.\nЦена бумаг HP Inc. уменьшилась на 6,54%, Dell Technologies Inc. - на 7,6% на фоне ухудшения рекомендаций аналитиками Morgan Stanley.\nАкции Wendy's Co. подешевели на 2,44%. Третья по величине сеть ресторанов быстрого питания в США откроет первый виртуальный ресторан в метавселенной, разрабатываемой компанией Meta Platforms Inc. (признана в РФ экстремистской организацией и запрещена).\nБумаги Intel Corp. потеряли в цене 3,64%. Компания покупает израильского разработчика и поставщика программного обеспечения для оптимизации Granulate Cloud Solutions Ltd., при этом сумма сделки не раскрывается.     https://www.interfax.ru/world/832542
1  2022-04-01 09:07:00                  Цены на нефть продолжили падать после заявления Байдена по нефтяным резервам                                                                                                                                                                                                                                                                                                                   Цены на нефть продолжили падать после заявления Байдена по нефтяным резервам\nМосква. 1 апреля. INTERFAX.RU - Цены на нефть продолжают снижаться в пятницу после падения накануне на заявлении президента США Джо Байдена о намерении направлять на рынок в среднем по 1 млн баррелей нефти в сутки\nиз стратегического резерва\n(SPR) на протяжении следующих шести месяцев.\nБайден, выступая в Белом доме, призвал американские компании наращивать добычу, чтобы добиться снижения цен на нефть. Это, среди прочего, позволит снизить роль экспорта энергоносителей из РФ, заявил он.\nКроме того, Байден предложил рассмотреть в Конгрессе меры, которые подтолкнули бы компании в США к более активной добыче нефти.\nСтоимость июньских фьючерсов на нефть Brent на лондонской бирже ICE Futures к 8:10 по московскому времени в пятницу составила $104,35 за баррель, что на $0,36 (0,34%) ниже цены на закрытие предыдущей сессии. По итогам торгов в четверг эти контракты подешевели на $6,73 (6%), до $104,71 за баррель.\nЦена фьючерсов на нефть WTI на май на электронных торгах Нью-йоркской товарной биржи (NYMEX) составили к этому времени $99,66 за баррель, что на $0,62 (0,62%) ниже итогового значения предыдущей сессии. В четверг стоимость этих контрактов упала на $7,54 (7%), до $100,28 за баррель.\nВ марте Brent подорожала на 6,9%, WTI - на 4,8%, за первый квартал цены выросли соответственно на 39% и 33%.\n"В принципе, это временная мера, призванная минимизировать весенний подъем цен на нефть, - заявил аналитик S&P Global Commodity Insights Маршалл Стивз, комментируя решение Байдена о высвобождении нефти из SPR. - Она позволит немного увеличить поставки на рынок и соответствующим образом ограничит цены".\n"Однако война на Украине оказывает решающее влияние на рынок, и основным фактором остается возможная потеря российской нефти", - приводит слова эксперта Market Watch.\nАналитики Goldman Sachs понизили прогноз стоимости Brent на второе полугодие 2022 года на $10 за баррель, до $125 за баррель вслед за появлением информации о планах Байдена. По мнению экспертов, действия США не решат проблему "структурного дефицита на нефтяном рынке".  https://www.interfax.ru/business/832550
2  2022-04-01 09:13:00                      Европейские покупатели сохраняют высокие заявки на отбор газа "Газпрома"                                                                                                                                                                                                                                                                                                                                 Европейские покупатели сохраняют высокие заявки на отбор газа "Газпрома"\nМосква. 1 апреля. INTERFAX.RU - Цена поставок газа по экспортным контрактам\n"Газпрома"\nс начала апреля должна заметно вырасти.\nБольшинство контрактов используют биржевой индекс "на месяц вперед": в марте его значение было около $930 за тысячу кубометров, в апреле он увеличился до примерно $1400 (это, кстати, почти совпадает со значением спотового контракта "на день вперед" на хабе TTF на пятницу).\nТакже с 1 апреля действует введенный президентским указом новый порядок оплаты поставок российского газа - с обязательной конвертацией валюты контрактов в рубли. Несмотря на растерянные или враждебные комментарии европейских политиков на это нововведение, а также на рост цены, - европейские покупатели сохраняют практически прежние заявки на отбор российского газа.\nЗагрузка украинского газотранспортного коридора в пятницу сохраняется на прежнем, максимальном уровне долгосрочного контракта (40 млрд куб. м в год, или 109 млн куб. м в сутки). Как свидетельствуют данные "Оператора ГТС Украины", номинация на 1 апреля составляет 107,6 млн куб. м, заявка на 31 марта была 109,5 млн куб. м.\nФизический поток газа по газопроводу "Ямал-Европа", который транспортирует газ через Белоруссию и Польшу в Германию, на входе в ГТС ФРГ половину дня среды и весть четверг качал газ в прямом направлении. Сумма заявок на 1 апреля (в прямом и обратном направлении) складывается в пользу реверсного направления (из Германии в Польшу).\nНа этой неделе в Европу пришло сильное похолодание. Средняя температура воздуха на 7 градусов ниже, чем на неделе с 14 по 20 марта; со значительными минусовыми температурами по ночам, что оказывает новую поддержку ценам на газ. На будущей неделе также предсказываются новые вторжения холодных воздушных масс.\nВ Европе улучшилась ситуация с выработкой электроэнергии за счет ветровой электрогенерации. Если за первые три дня текущей недели (с 28 по 30 марта) ветроэлектростанции обеспечили лишь 10% выработки электроэнергии по ЕС, то четверг их доля подскочила до 20,5%, свидетельствуют данные ассоциации WindEurope.  https://www.interfax.ru/business/832553
3  2022-04-01 09:15:00                                ЦБ смягчит ограничения на переводы средств за рубеж для физлиц                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ЦБ смягчит ограничения на переводы средств за рубеж для физлиц\nМосква. 1 апреля. INTERFAX.RU - Банк России решил смягчить ограничения на переводы денег за рубеж для физлиц.\nНа ближайшие шесть месяцев установлены новые ограничения по суммам, которые граждане могут перевести со своего счета,\nследует из пресс-релиза\nрегулятора.\nВ течение календарного месяца физические лица имеют право перевести за пределы Российской Федерации со своего счета в российском банке на свой счет или другому физическому лицу за рубежом не более $10 тысяч или эквивалент этой суммы по другой валюте. Через компании, оказывающие услуги по переводу денежных средств без открытия счета, можно перевести в месяц не более $5 тысяч (или в эквиваленте в другой валюте).\nЭти нормы касаются резидентов России и нерезидентов - из стран, не поддерживающих санкции. Такую же возможность получили нерезиденты из всех других государств, работающих в России по трудовым или гражданско-правовым договорам.\nГражданам стран, поддерживающих санкции, которые не работают в России, а также юрлицам из этих государств переводы делать запрещено в течение шести месяцев.\nНа этот же срок приостановлены переводы за рубеж средств физических и юридических лиц — нерезидентов из стран, поддерживающих санкции, со счетов российских брокеров.\nСуммы переводов рассчитываются по официальному курсу иностранных валют к рублю, установленному Банком России на дату поручения на осуществление перевода.\nРанее ЦБ ограничил переводы средств физлиц за рубеж суммой в $5 тысяч в месяц, приостановил трансграничные переводы для нерезидентов (физлиц и юрлиц) из стран, поддерживающих санкции. При этом физлица не могли перевести деньги на свои счета за границей, но могли перевести другому человеку в месяц не более $5 тысяч (или эквивалент этой суммы в любой другой валюте). При этом граждане могли оплачивать учебу, медицинские услуги и проводить коммунальные платежи за рубежом.  https://www.interfax.ru/business/832554
4  2022-04-01 09:16:00                           Индекс PMI обрабатывающих отраслей РФ в марте рухнул до 44,1 пункта  Индекс PMI обрабатывающих отраслей РФ в марте рухнул до 44,1 пункта\nМосква. 1 апреля. INTERFAX.RU - Индекс PMI обрабатывающих отраслей РФ в марте 2022 года составил 44,1 пункта, резко снизившись с февральского значения 48,6 пункта, согласно исследованию IHS Markit.\nЗначение показателя выше 50 пунктов указывает на рост деловой активности, а ниже этого уровня - на ее снижение.\n"Последние данные указали на самое резкое ухудшение операционных условий по всему сектору за последние два года", - отмечается в пресс-релизе.\nВ ходе исследования было отмечено второе подряд месячное падение объемов производства, темпы которого заметно ускорились и оказались самыми стремительными с мая 2020 года. Компании связывали снижение выпуска со слабым клиентским спросом и уменьшением числа новых заказов.\nЧисло новых продаж заметно снизилось в марте на фоне ухудшения спроса. Некоторые участники опроса заявляли, что покупательная способность клиентов оказалась под ударом резкого роста цен. Снижение новых заказов было самым быстрым за почти два года.\nСпрос со стороны иностранных клиентов также снизился в конце первого квартала. Темпы падения экспортных заказов стали одними из самых резких за историю наблюдений.\nИнфляционное давление заметно усилилось в марте. Стоимость сырья росла самыми быстрыми темпами за историю наблюдений в свете повышения цен у поставщиков и неблагоприятного обменного курса. Компании перекладывали свои издержки на покупателей, рост отпускных цен стал самым заметным с января 2003 года (момента запуска исследований).\nЗначительно ухудшились и показатели поставщиков - увеличились сроки поставок, так как острая нехватка материалов мешала их своевременной доставке.\nСнижение притока новых заказов и существенные задержек со стороны поставщиков привело к самому быстрому падению закупок сырья с мая 2020 года. Снижение закупок усугубило проблемы пополнения складских запасов на фоне их серьезного истощения (наиболее резкого по скорости при сравнении с январем 2009 года и августом 1999 года).\nУменьшение нагрузки на мощности повлекло за собой самое быстрое сокращение невыполненных работ в 2022 году. На этом фоне компании сокращали наем и численность работников темпами, скорейшими почти за два года.\nОжидания участников опроса относительно перспектив производства на грядущий год оставались оптимистичными в марте. Тем не менее, уровень оптимизма упал до самого низкого значения в текущей 22-месячной серии.  https://www.interfax.ru/business/832557

In [1]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from datetime import datetime, timedelta
import time

def parse_news_article_safe(url):
    """Парсит полный текст новости, используя те же настройки, что и для заголовков"""
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Ищем текст новости в разных возможных контейнерах
        article_elem = (soup.find('article') or 
                       soup.find('div', {'itemprop': 'articleBody'}) or 
                       soup.find('div', class_='text') or
                       soup.find('div', class_='at'))
        
        if article_elem:
            # Очищаем текст от ненужных элементов
            for elem in article_elem.find_all(['script', 'style', 'iframe', 'div', 'span']):
                elem.decompose()
            
            full_text = article_elem.get_text('\n', strip=True)
            return full_text if full_text else ""
        else:
            return ""
            
    except Exception as e:
        print(f"    Ошибка при парсинге статьи: {e}")
        return ""

def parse_interfax_date(url):
    """Парсит новости за конкретную дату"""
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        news_block = soup.find('div', class_='an')
        
        if not news_block:
            return []
        
        full_text = news_block.get_text()
        time_pattern = r'\d{2}:\d{2}'
        all_times = re.findall(time_pattern, full_text)
        links = news_block.find_all('a', href=True)
        
        # Извлекаем дату из URL
        date_match = re.search(r'/(\d{4})/(\d{2})/(\d{2})', url)
        if date_match:
            year, month, day = date_match.groups()
            base_date = f"{year}-{month}-{day}"
        else:
            return []
        
        data = []
        time_index = 0
        
        for i, link in enumerate(links):
            text = link.get_text(strip=True)
            href = link.get('href')
            
            if text and len(text) > 10:
                time_str = all_times[time_index] if time_index < len(all_times) else "00:00"
                time_index += 1
                
                datetime_str = f"{base_date} {time_str}:00"
                full_url = f"https://www.interfax.ru{href}" if href.startswith('/') else href
                
                # Парсим полный текст новости
                if i < 3:  # Показываем прогресс для первых 3 новостей
                    print(f"    Парсим новость {i+1}: {text[:50]}...")
                
                article_text = parse_news_article_safe(full_url)
                
                data.append({
                    'datetime': datetime_str,
                    'title': text,  # заголовок
                    'full_text': article_text,  # полный текст
                    'url': full_url
                })
                
                # Короткая пауза между запросами
                time.sleep(0.01)
        
        return data
        
    except Exception as e:
        print(f"Ошибка при парсинге {url}: {e}")
        return []

def parse_interfax_period(start_year=2022, end_year=2025):
    """Парсит новости за период с start_year по end_year"""
    all_news = []
    
    # Генерируем даты с 2022-01-01 по 2025-12-31
    start_date = datetime(start_year, 4, 1)
    end_date = datetime(end_year, 10, 19)
    
    current_date = start_date
    total_days = (end_date - start_date).days + 1
    
    print(f"Начинаем парсинг с {start_date.date()} по {end_date.date()}")
    print(f"Всего дней: {total_days}")
    print(f"Ориентировочное время: ~{total_days * 2} минут")
    print("=" * 50)
    
    for day_num in range(total_days):
        date_str = current_date.strftime("%Y/%m/%d")
        url = f"https://www.interfax.ru/business/news/{date_str}"
        
        print(f"[{day_num+1}/{total_days}] {current_date.date()}: ", end="", flush=True)
        
        # Парсим новости за день
        daily_news = parse_interfax_date(url)
        
        if daily_news:
            all_news.extend(daily_news)
            print(f"{len(daily_news)} новостей (всего: {len(all_news)})")
        else:
            print("0 новостей")
        
        # Переходим к следующему дню
        current_date += timedelta(days=1)
        
        # Пауза между днями
        time.sleep(0.5)
        
        # Промежуточное сохранение каждые 30 дней
        if (day_num + 1) % 30 == 0 and all_news:
            temp_df = pd.DataFrame(all_news)
            temp_df.to_csv(f'interfax_temp_{day_num+1}.csv', index=False, encoding='utf-8')
            print(f"  -> Сохранено во временный файл")
    
    # Создаем итоговый DataFrame
    df = pd.DataFrame(all_news)
    
    if not df.empty:
        df = df.sort_values('datetime').reset_index(drop=True)
    
    return df

# Запускаем парсинг за весь период
print("=== ПАРСИНГ INTERFAX ЗА 2022-2025 ===")
final_df = parse_interfax_period(2022, 2025)

print(f"\n=== РЕЗУЛЬТАТ ===")
print(f"Итоговый размер датафрейма: {len(final_df)} новостей")

if not final_df.empty:
    print("\nПервые 3 записи:")
    for i, row in final_df.head(3).iterrows():
        print(f"\n{i+1}. {row['datetime']}")
        print(f"   Заголовок: {row['title']}")
        print(f"   Текст: {row['full_text'][:100]}...")
        print(f"   URL: {row['url']}")
    
    print(f"\nДиапазон дат: {final_df['datetime'].min()} - {final_df['datetime'].max()}")
    
    # Сохраняем результат
    final_df.to_csv('interfax_complete_2022_2025.csv', index=False, encoding='utf-8')
    print(f"\nСохранено в interfax_complete_2022_2025.csv")
    
else:
    print("Не удалось спарсить ни одной новости!")

=== ПАРСИНГ INTERFAX ЗА 2022-2025 ===
Начинаем парсинг с 2022-04-01 по 2025-10-19
Всего дней: 1298
Ориентировочное время: ~2596 минут
==================================================
[1/1298] 2022-04-01:     Парсим новость 1: Shell может столкнуться с проблемами при оплате "Г...
    Парсим новость 2: Эксперт счел, что Британия не сможет ограничить де...
    Парсим новость 3: Сахарные заводы "Продимекса" начали переработку им...
88 новостей (всего: 88)
[2/1298] 2022-04-02:     Парсим новость 1: Власти Нидерландов призвали жителей уменьшить отоп...
    Парсим новость 2: Природный газ из России перестал поступать в стран...
    Парсим новость 3: Поставки газа из Азербайджана в Италию в 2022 году...
8 новостей (всего: 96)
[3/1298] 2022-04-03:     Парсим новость 1: Заявка "Газпрома" на транзит через Украину осталас...
    Парсим новость 2: Глава "Росатома" заявил, что госкорпорация не план...
    Парсим новость 3: Белоруссия и Россия создали Совет промышленников...
3 новостей (всего: 99)
[4/1298] 2022-04-04:     Парсим новость 1: Правительство РФ выделило 14 млрд руб. на гранты д...
    Парсим новость 2: ЦБ РФ с 6 апреля вернется к стандартным недельным ...
    Парсим новость 3: Нефть дорожает на фоне обсуждения новых антироссий...
73 новостей (всего: 172)
[5/1298] 2022-04-05:     Парсим новость 1: США заявили, что хотят заставить РФ выбрать дефолт...
    Парсим новость 2: Лукашенко заявил, что Минск не будет рассчитыватьс...
    Парсим новость 3: Датская Vestas планирует покинуть Россию...
91 новостей (всего: 263)
[6/1298] 2022-04-06:     Парсим новость 1: Байден счел, что санкции США "сведут на нет 15 лет...
    Парсим новость 2: Рубль закрыл торги среды уверенным ростом к бивалю...
    Парсим новость 3: GlaxoSmithKline прекратит ввоз в Россию витаминов ...
70 новостей (всего: 333)
[7/1298] 2022-04-07:     Парсим новость 1: Совет ЕС обсудил продовольственную безопасность на...
    Парсим новость 2: ЕС закроет доступ судам РФ в свои порты и заморози...
    Парсим новость 3: "Сургутнефтегаз" продает танкерные партии нефти Li...
83 новостей (всего: 416)
[8/1298] 2022-04-08:     Парсим новость 1: Евросоюз ввел квоты на импорт калийных и сложных у...
    Парсим новость 2: ЦБ подтвердил, что отменил комиссию в 12% на покуп...
    Парсим новость 3: Совет директоров "Аэрофлота" утвердил  Александров...
91 новостей (всего: 507)
[9/1298] 2022-04-09:     Парсим новость 1: S&P понизило рейтинги РФ в иностранной валюте до "...
    Парсим новость 2: Правительство РФ одобрило законопроект о сотруднич...
    Парсим новость 3: Белорусских грузоперевозчиков обязали покинуть тер...
7 новостей (всего: 514)
[10/1298] 2022-04-10:     Парсим новость 1: Всемирный банк дал прогноз по падению ВВП РФ на 11...
    Парсим новость 2: В Белоруссии выразили опасение, что санкции уничто...
    Парсим новость 3: Правительство РФ увеличит свой резервный фонд на 2...
6 новостей (всего: 520)
[11/1298] 2022-04-11:     Парсим новость 1: Байден призвал Моди не увеличивать импорт российск...
    Парсим новость 2: Отток капитала из РФ в феврале-марте мог превысить...
    Парсим новость 3: Рубль закрыл торги падением к доллару и евро на фо...
75 новостей (всего: 595)
[12/1298] 2022-04-12:     Парсим новость 1: Контейнерооборот на северо-западе РФ в мае может р...
    Парсим новость 2: Капитализация рынка акций РФ во вторник снизилась ...
    Парсим новость 3: Минпромторг опасается дефицита литиевого сырья в Р...
74 новостей (всего: 669)
[13/1298] 2022-04-13:     Парсим новость 1: Внешнее управление "брошенными" в РФ активами на п...
    Парсим новость 2: Минпромторг привел список металлотрейдеров, ограни...
    Парсим новость 3: Правительство думает о смягчении проекта о запрете...
81 новостей (всего: 750)
[14/1298] 2022-04-14:     Парсим новость 1: Минторг США запретил обслуживание еще 10 самолетов...
    Парсим новость 2: "Тинькофф фонд" хочет оказать помощь украинским бе...
    Парсим новость 3: Moody's заявило, что выплаты РФ по евробондам в ру...
92 новостей (всего: 842)
[15/1298] 2022-04-15:     Парсим новость 1: Сбербанк и VK договорились с УК People&People о пр...
    Парсим новость 2: Росавиация получит 1,5 млрд рублей на поддержку аэ...
    Парсим новость 3: Германия выделит Киеву на военную помощь свыше 1 м...
67 новостей (всего: 909)
[16/1298] 2022-04-16:     Парсим новость 1: Заявка на транзит российского газа через Украину в...
1 новостей (всего: 910)
[17/1298] 2022-04-17:     Парсим новость 1: Бельгия закрыла свои порты для судов под российски...
    Парсим новость 2: Канцлер Австрии назвал возможным не зависеть от га...
    Парсим новость 3: Казахстан вводит ограничение на экспорт пшеницы и ...
5 новостей (всего: 915)
[18/1298] 2022-04-18:     Парсим новость 1: Немецкие профсоюзы выступили против бойкота россий...
    Парсим новость 2: Компании РФ смогут до 5 мая ходатайствовать о сохр...
    Парсим новость 3: Рубль на закрытии торгов растерял часть роста к до...
68 новостей (всего: 983)
[19/1298] 2022-04-19:     Парсим новость 1: Iridium Communications ожидает снижения годовой вы...
    Парсим новость 2: General Motors пока не намерен возобновлять работу...
    Парсим новость 3: Минпромторг подтвердил, что к автомобилям могут сн...
83 новостей (всего: 1066)
[20/1298] 2022-04-20:     Парсим новость 1: Комитет по CDS признал 4 апреля датой "потенциальн...
    Парсим новость 2: Под новые санкции США попали Михаил Задорнов и Ксе...
    Парсим новость 3: Крыму пообещали 64 дополнительных вагона для перев...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/835973 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A47B320>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
75 новостей (всего: 1141)
[21/1298] 2022-04-21:     Парсим новость 1: Право голоса по акциям подсанкционных владельцев к...
    Парсим новость 2: Аналитики ЦБ предсказали рост годовой инфляции из-...
    Парсим новость 3: "Газпром" утвердил график ремонта экспортных газоп...
79 новостей (всего: 1220)
[22/1298] 2022-04-22:     Парсим новость 1: РФ предоставила Белоруссии отсрочку по кредитам на...
    Парсим новость 2: Минпромторг РФ подготовил перечень товаров для пар...
    Парсим новость 3: Замглавы Минфина Окладникова может войти в совет д...
68 новостей (всего: 1288)
[23/1298] 2022-04-23:     Парсим новость 1: В Белоруссии сообщили о работе над подключением к ...
    Парсим новость 2: В Белоруссии назвали логичным переход на российски...
    Парсим новость 3: Российских нефтяников обязали увеличить процент то...
5 новостей (всего: 1293)
[24/1298] 2022-04-24:     Парсим новость 1: Альфа-банк предложил клиентам перевести иностранны...
    Парсим новость 2: КТК возобновил прокачку нефти после месяца ремонтн...
    Парсим новость 3: В бельгийском порту из-за санкций застряли 8 тыс. ...
3 новостей (всего: 1296)
[25/1298] 2022-04-25:     Парсим новость 1: Илон Маск покупает Twitter за $44 млрд...
    Парсим новость 2: СД банка "Зенит" рекомендовал оказаться от дивиден...
    Парсим новость 3: Количественный состав совета директоров АФК "Систе...
61 новостей (всего: 1357)
[26/1298] 2022-04-26:     Парсим новость 1: Renault передаст 68% доли в "АвтоВАЗе" в пользу НА...
    Парсим новость 2: Болгария отказалась платить "Газпрому" по новой сх...
    Парсим новость 3: РЖД отправили первый контейнерный поезд в Китай из...
60 новостей (всего: 1417)
[27/1298] 2022-04-27:     Парсим новость 1: Правительство сможет снижать "исторический ценз" д...
    Парсим новость 2: Рост ВВП России в марте замедлился до 1,6%...
    Парсим новость 3: Turkish Airlines отменила часть рейсов из РФ на ку...
80 новостей (всего: 1497)
[28/1298] 2022-04-28:     Парсим новость 1: Правительство РФ утвердило правила предоставления ...
    Парсим новость 2: Инвестор для "уставших банкиров". Обобщение...
    Парсим новость 3: Миноритарный пакет "Мосбиржи" вернулся к ВЭБу от "...
87 новостей (всего: 1584)
[29/1298] 2022-04-29:     Парсим новость 1: Минфин США одобрит выплату по евробондам РФ в долл...
    Парсим новость 2: "НОВАТЭК" обеспечил поставку газа в Польшу через г...
    Парсим новость 3: Заявление Банка России: широко шагая навстречу нео...

    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/838813 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A052420>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
117 новостей (всего: 1701)
[30/1298] 2022-04-30:     Парсим новость 1: В МИД РФ заявили, что санкции стимулируют переход ...
    Парсим новость 2: Правительство РФ смягчило ограничения на вывоз мин...
    Парсим новость 3: Европа увеличивает заявки на поставку российского ...
5 новостей (всего: 1706)
  -> Сохранено во временный файл
[31/1298] 2022-05-01:     Парсим новость 1: Вступил в силу закон, ограничивающий банки РФ в пе...
    Парсим новость 2: "Газпром" за январь-апрель нарастил поставки в Кит...
    Парсим новость 3: Приставы РФ принудительно взыщут с Google свыше 7,...
8 новостей (всего: 1714)
[32/1298] 2022-05-02:     Парсим новость 1: "Интеррос" купил процессинговую компанию United Ca...
    Парсим новость 2: Эстония предложила разместить в каждой стране Балт...
    Парсим новость 3: Минфин США разрешил транзакции с Gazprom Germania ...
13 новостей (всего: 1727)
[33/1298] 2022-05-03:     Парсим новость 1: Финский VR Group до конца года полностью прекратит...
    Парсим новость 2: Регулятор Казахстана одобрил покупку банком ЦентрК...
    Парсим новость 3: Тиньков заявил о намерении вывести из России бренд...
8 новостей (всего: 1735)
[34/1298] 2022-05-04:     Парсим новость 1: Долгосрочные контракты Shell по закупке российской...
    Парсим новость 2: ФРС ожидаемо повысила ставку на 50 бп и начнет сок...
    Парсим новость 3: "Квадра" в I квартале сократила чистую прибыль по ...
80 новостей (всего: 1815)
[35/1298] 2022-05-05:     Парсим новость 1: Компания TeamViewer решила полностью прекратить де...
    Парсим новость 2: АФК "Система" решила не проводить годовое собрание...
    Парсим новость 3: Рубль вечером в четверг перешел к снижению в паре ...
65 новостей (всего: 1880)
[36/1298] 2022-05-06:     Парсим новость 1: Белоруссия и Россия формализуют новые договореннос...
    Парсим новость 2: Минпромторг разрешил параллельный импорт газовых т...
    Парсим новость 3: Vale подписала долгосрочное соглашение с Tesla о п...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/839599 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A313E60>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
56 новостей (всего: 1936)
[37/1298] 2022-05-07:     Парсим новость 1: "Газпром" восстановил поврежденный участок газопро...
    Парсим новость 2: Тайвань ограничил экспорт высокотехнологичных това...
    Парсим новость 3: "Роскосмос" временно поменял свой логотип на красн...
5 новостей (всего: 1941)
[38/1298] 2022-05-08:     Парсим новость 1: Минск заявил, что цену на газ из РФ для Белоруссии...
    Парсим новость 2: США ввели блокирующие санкции против МИнБа, руково...
    Парсим новость 3: США ввели санкции против "Первого канала", НТВ, "Р...
4 новостей (всего: 1945)
[39/1298] 2022-05-09:     Парсим новость 1: Польская "дочка" "НОВАТЭКа" объявила форс-мажор из...
    Парсим новость 2: Нефтедобыча в РФ в начале мая выросла по сравнению...
    Парсим новость 3: Премьер-министр Японии заявил, что Токио будет поэ...
3 новостей (всего: 1948)
[40/1298] 2022-05-10:     Парсим новость 1: "Газпром" отверг основания для объявления Киевом ф...
    Парсим новость 2: Минэнерго США понизило прогноз потребления нефти в...
    Парсим новость 3: Украина объявила форс-мажор на прием газа по одном...
4 новостей (всего: 1952)
[41/1298] 2022-05-11:     Парсим новость 1: ЦБ отметил, что перенос недавнего ослабления рубля...
    Парсим новость 2: Банк России связал укрепление рубля с падением имп...
    Парсим новость 3: ЦБ РФ повысил прогноз структурного профицита ликви...
83 новостей (всего: 2035)
[42/1298] 2022-05-12:     Парсим новость 1: ЦБ готов не применять меры к банкам из-за СБП на ф...
    Парсим новость 2: Rivian впервые отзовет свои электромобили из-за об...
    Парсим новость 3: Минсельхоз США спрогнозировал для РФ экспорт 39 мл...
84 новостей (всего: 2119)
[43/1298] 2022-05-13:     Парсим новость 1: Минтранс предложил помочь бизнесу перестроить логи...
    Парсим новость 2: В России перенесли на шесть лет сроки строительств...
    Парсим новость 3: Грузооборот морских портов России в апреле сократи...
76 новостей (всего: 2195)
[44/1298] 2022-05-14:     Парсим новость 1: В SOCAR призвали не попадаться на уловки мошеннико...
    Парсим новость 2: Транзитная заявка через Украину в субботу выросла ...
    Парсим новость 3: Индия запретила экспорт пшеницы...
3 новостей (всего: 2198)
[45/1298] 2022-05-15:     Парсим новость 1: Транзитная заявка через Украину в воскресенье чуть...
    Парсим новость 2: Япония и США запланировали усилить сотрудничество ...
2 новостей (всего: 2200)
[46/1298] 2022-05-16:     Парсим новость 1: Renault не сможет выкупить обратно свой бывший зав...
    Парсим новость 2: На переданном Renault мэрии Москвы заводе будут вы...
    Парсим новость 3: Минцифры проведет эксперимент по повышению уровня ...
79 новостей (всего: 2279)
[47/1298] 2022-05-17:     Парсим новость 1: Венесуэла подтвердила снятие ограничений на работу...
    Парсим новость 2: Сбербанк уведомил Лондонскую фондовую биржу о прек...
    Парсим новость 3: Bloomberg сообщил, что США не позволят РФ обслужив...
82 новостей (всего: 2361)
[48/1298] 2022-05-18:     Парсим новость 1: ЦБ ждет дальнейшего изменения потребительского пов...
    Парсим новость 2: TCS Group сообщила о падении чистой прибыли и рост...
    Парсим новость 3: Минэкономразвития снизило прогноз добычи нефти в Р...
73 новостей (всего: 2434)
[49/1298] 2022-05-19:     Парсим новость 1: Власти Калининграда через суд изъяли у собственник...
    Парсим новость 2: Пакет законопроектов об объединении ПФР и ФСС внес...
    Парсим новость 3: Думе предложили смягчить наказание бизнесу за нару...
86 новостей (всего: 2520)
[50/1298] 2022-05-20:     Парсим новость 1: Минторг США отозвал экспортные привилегии у авиако...
    Парсим новость 2: "Московская биржа" отказалась от моратория на банк...
    Парсим новость 3: Правительство предписало не выплачивать дивиденды ...
74 новостей (всего: 2594)
[51/1298] 2022-05-21:     Парсим новость 1: Экс-министр транспорта РФ Максим Соколов с 23 мая ...
    Парсим новость 2: "Адмиралтейские верфи" подтвердили поставку субмар...
    Парсим новость 3: "Роскосмос" предложил наладить производство на "ос...
6 новостей (всего: 2600)
[52/1298] 2022-05-22:     Парсим новость 1: Белоруссия и РФ намерены летом подписать соглашени...
    Парсим новость 2: Алекперов заявил о невозможности заменить Россию н...
    Парсим новость 3: Турция разработает новые маршруты для поставки про...
6 новостей (всего: 2606)
[53/1298] 2022-05-23:     Парсим новость 1: Лавров заявил, что экономические связи РФ с КНР ук...
    Парсим новость 2: Qiwi в I квартале увеличила чистую выручку по МСФО...
    Парсим новость 3: Литвиненко передал жене 20,6% акций "ФосАгро", сок...
67 новостей (всего: 2673)
[54/1298] 2022-05-24:     Парсим новость 1: Выдача ипотеки банками РФ в апреле сократилась в 3...
    Парсим новость 2: Средства физлиц в банках РФ в апреле выросли на 3,...
    Парсим новость 3: Нацбанк Грузии впервые за три года купил на валютн...
82 новостей (всего: 2755)
[55/1298] 2022-05-25:     Парсим новость 1: Прожиточный минимум в РФ после индексации составит...
    Парсим новость 2: Постпреды стран ЕС согласовали регламент по хранен...
    Парсим новость 3: ВТБ еще три года будет заниматься эквайринговым об...
85 новостей (всего: 2840)
[56/1298] 2022-05-26:     Парсим новость 1: Продававшие акции "Газпрома" в четверг на слухах м...
    Парсим новость 2: Гостиничный оператор Green Flow планирует облигаци...
    Парсим новость 3: Банки всех размеров, соединяйтесь! Обобщение...
83 новостей (всего: 2923)
[57/1298] 2022-05-27:     Парсим новость 1: Минфин РФ ждет до 1 трлн руб. дополнительных нефте...
    Парсим новость 2: РФ к концу июня подготовит механизм расчетов с инв...
    Парсим новость 3: "Ъ" сообщил об уходе Wella из России...

87 новостей (всего: 3010)
[58/1298] 2022-05-28:     Парсим новость 1: Олег Бударгин может вернуться в совет директоров "...
    Парсим новость 2: Сбербанк снизил ставки по вкладам, потребкредитам ...
    Парсим новость 3: Утверждены параметры льготного кредитования для си...
4 новостей (всего: 3014)
[59/1298] 2022-05-29:     Парсим новость 1: На саммите ЕС обсудят возможность конфискации росс...
    Парсим новость 2: Министр ЕЭК призвал создать биржевое пространство ...
    Парсим новость 3: Евросовет попытается найти компромиссное решение п...
8 новостей (всего: 3022)
[60/1298] 2022-05-30:     Парсим новость 1: "Мегафон" решил не публиковать финансовую отчетнос...
    Парсим новость 2: Топ-менеджеры "Интерроса" и выходцы из группы ВТБ ...
    Парсим новость 3: Выдача ипотеки в России в апреле упала к марту в 3...
77 новостей (всего: 3099)
  -> Сохранено во временный файл
[61/1298] 2022-05-31:     Парсим новость 1: FT узнала о решении Британии и ЕС запретить страхо...
    Парсим новость 2: Санкции закручивают круговорот нефти в природе. Об...
    Парсим новость 3: "ЛУКОЙЛ" хочет сократить состав СД и позволить ему...
73 новостей (всего: 3172)
[62/1298] 2022-06-01:     Парсим новость 1: В администрации Байдена возникли разногласия по по...
    Парсим новость 2: "СПБ биржа" возобновит утренние торги в ближайшие ...
    Парсим новость 3: Пентагон пообещал передать Украине четыре РСЗО HIM...
91 новостей (всего: 3263)
[63/1298] 2022-06-02:     Парсим новость 1: Сбербанк может повысить базовое вознаграждение чле...
    Парсим новость 2: Власти поручили не выплачивать дивиденды по акциям...
    Парсим новость 3: Доля юрлиц-нерезидентов в капитале Сбербанка по ит...
79 новостей (всего: 3342)
[64/1298] 2022-06-03:     Парсим новость 1: REBCO prohibited: ЕС запрещает импорт нефти и нефт...
    Парсим новость 2: РФ может увеличить экспорт зерна в следующем сельх...
    Парсим новость 3: НРД из-за санкций ЕС приостанавливает в банковской...
65 новостей (всего: 3407)
[65/1298] 2022-06-04:     Парсим новость 1: "Промсвязьбанк" начал работу на территории ДНР...
    Парсим новость 2: Закачка в ПХГ ЕС в июне заметно отстает от нормаль...
    Парсим новость 3: FT узнала о планах продать принадлежащий Абрамович...
5 новостей (всего: 3412)
[66/1298] 2022-06-05:     Парсим новость 1: Франция обсуждает возможность поставок нефти из ОА...
1 новостей (всего: 3413)
[67/1298] 2022-06-06:     Парсим новость 1: "Русал" подал в австралийский суд иск к Rio Tinto ...
    Парсим новость 2: OFAC уточнил, что конвертация DR компаний РФ не из...
    Парсим новость 3: Максимальную долю рынка при сделках в ритейле могу...
48 новостей (всего: 3461)
[68/1298] 2022-06-07:     Парсим новость 1: В ЕС согласовали правила, устанавливающие адекватн...
    Парсим новость 2: Чиновники предложили не прерывать взыскание "стары...
    Парсим новость 3: Совет директоров ГК "ПИК" рекомендовал не платить ...
81 новостей (всего: 3542)
[69/1298] 2022-06-08:     Парсим новость 1: Минэкономразвития отметило, что инфляция в РФ скор...
    Парсим новость 2: Сын основателя Walmart купит команду по американск...
    Парсим новость 3: Российская сеть "Л'Этуаль" продала свои активы на ...
88 новостей (всего: 3630)
[70/1298] 2022-06-09:     Парсим новость 1: Литовский суд отклонил апелляцию "Беларуськалия" н...
    Парсим новость 2: Корпорация МСП разместила в депозиты 23,7 млрд руб...
    Парсим новость 3: ВВП Украины в I квартале упал на 15,1%...
70 новостей (всего: 3700)
[71/1298] 2022-06-10:     Парсим новость 1: "Транснефть" может направить на дивиденды за 2021 ...
    Парсим новость 2: Россия расширила возможности экспорта белорусских ...
    Парсим новость 3: Дефицит бюджета США в мае сократился вдвое...
98 новостей (всего: 3798)
[72/1298] 2022-06-11:     Парсим новость 1: "Клуб-Отель" Говора стал владельцем российского би...
    Парсим новость 2: Пленарное заседание ПМЭФ с участием Путина пройдет...
    Парсим новость 3: В МИД РФ заявили, что многие немецкие компании гов...
5 новостей (всего: 3803)
[73/1298] 2022-06-12:     Парсим новость 1: Мезенцев заявил о финишной прямой в реализации сою...
    Парсим новость 2: TotalEnergies будет участвовать в разработке катар...
    Парсим новость 3: Сбербанк снизил ставки по вкладам и потребкредитам...
4 новостей (всего: 3807)
[74/1298] 2022-06-13:     Парсим новость 1: Финляндии разрешили оказать госпомощь пострадавшим...
    Парсим новость 2: Американский брокер IBKR ввел ограничения для клие...
    Парсим новость 3: Заявка Газпрома на прокачку через Украину остается...
4 новостей (всего: 3811)
[75/1298] 2022-06-14:     Парсим новость 1: В ЕС заявили, что любая транзакция, влекущая выпла...
    Парсим новость 2: Более 2 млрд руб. требует с датского производителя...
    Парсим новость 3: Siemens Energy объяснила проблему с оборудованием ...
62 новостей (всего: 3873)
[76/1298] 2022-06-15:     Парсим новость 1: Потери бюджета от "черного рынка" сигарет в РФ пре...
    Парсим новость 2: Глава ФРС Пауэлл не исключил очередного повышения ...
    Парсим новость 3: Эксперты сочли, что рост несостоявшихся закупок го...
62 новостей (всего: 3935)
[77/1298] 2022-06-16:     Парсим новость 1: Перерегистрация цены на инсулины в РФ не скажется ...
    Парсим новость 2: Мантуров заявил, что автопрому РФ по силам создать...
    Парсим новость 3: В перечень технологий для заключения СПИК 2.0 доба...
117 новостей (всего: 4052)
[78/1298] 2022-06-17:     Парсим новость 1: Глава "НОВАТЭКа" заявил об угрозе энергетического ...
    Парсим новость 2: "Гознак" и СПВБ создадут площадку для обращения зо...
    Парсим новость 3: "НОВАТЭК" может рассмотреть покупку российских акт...
108 новостей (всего: 4160)
[79/1298] 2022-06-18:     Парсим новость 1: Баку и Тегеран создадут совместную комиссию для ра...
    Парсим новость 2: Белоруссия и Россия расширят сотрудничество по имп...
    Парсим новость 3: ПМЭФ-22 - по законам времени возможностей. Обобщен...
22 новостей (всего: 4182)
[80/1298] 2022-06-19:     Парсим новость 1: Россия готова вложить в белорусское промышленное и...
    Парсим новость 2: Болгария с 1 июля сможет получать азербайджанский ...
    Парсим новость 3: Байден призвал производителей нефти и газа по всем...
7 новостей (всего: 4189)
[81/1298] 2022-06-20:     Парсим новость 1: Мосбиржа начинает торги узбекским сумом, армянским...
    Парсим новость 2: Рубль вырос к доллару и евро на фоне укрепляющейся...
    Парсим новость 3: Цены евробондов РФ продемонстрировали смешанную ди...
41 новостей (всего: 4230)
[82/1298] 2022-06-21:     Парсим новость 1: Николай Зеленский покинул пост CEO Nordgold...
    Парсим новость 2: Банкам и НФО разрешили отчуждать имевшиеся 22 февр...
    Парсим новость 3: Минцифры и ФАС проверят обоснованность резкого рос...
40 новостей (всего: 4270)
[83/1298] 2022-06-22:     Парсим новость 1: Фондовые индексы Европы завершили торги снижением ...
    Парсим новость 2: Катастрофа, апокалипсис и другие оценки ситуации в...
    Парсим новость 3: Байден призвал производителей и поставщиков бензин...
48 новостей (всего: 4318)
[84/1298] 2022-06-23:     Парсим новость 1: МСЗ сохранил прогноз экспорта пшеницы из РФ в ново...
    Парсим новость 2: ВЭБ готов уступить роль владельца ФК ЦСКА, если по...
    Парсим новость 3: ЦДУ ТЭК закрыло данные по газу, углю, нефтеперераб...
36 новостей (всего: 4354)
[85/1298] 2022-06-24:     Парсим новость 1: ЦБ ввел счет "С" для резидентов под сделки переуст...
    Парсим новость 2: В Думе предложили расширить перечень необлагаемых ...
    Парсим новость 3: Минюст зарегистрировал приказы о повышении с июля ...
34 новостей (всего: 4388)
[86/1298] 2022-06-25:     Парсим новость 1: Белоруссия начала погрузку минеральных удобрений в...
    Парсим новость 2: В Еврокомиссии сообщили, что 12 стран ЕС полностью...
    Парсим новость 3: Заявка "Газпрома" на транзит через Украину в суббо...
3 новостей (всего: 4391)
[87/1298] 2022-06-26:     Парсим новость 1: Матвиенко заявила о постепенном переходе России и ...
    Парсим новость 2: "Севмаш" заложил подводный аппарат по заказу "Газп...
    Парсим новость 3: Франция посчитала нужным согласовать идею "потолка...
7 новостей (всего: 4398)
[88/1298] 2022-06-27:     Парсим новость 1: Минфин утвердил 57 юрисдикций для офшорного владен...

    Парсим новость 2: В Еврокомиссии призвали страны ЕС подготовиться к ...
    Парсим новость 3: Siemens купит разработчика ПО Brightly Software за...
81 новостей (всего: 4479)
[89/1298] 2022-06-28:     Парсим новость 1: Siemens купил долю в американской сети VW станций ...
    Парсим новость 2: Berkshire Hathaway увеличила долю в Occidental Pet...
    Парсим новость 3: Конвертация депозитарных расписок МТС в обыкновенн...
74 новостей (всего: 4553)
[90/1298] 2022-06-29:     Парсим новость 1: Минэкономразвития не поддержало законопроект о при...
    Парсим новость 2: Непротивление казне согласием. Репортаж...
    Парсим новость 3: Саид Гуцериев намерен продать свой пакет в холдинг...
86 новостей (всего: 4639)
  -> Сохранено во временный файл
[91/1298] 2022-06-30:     Парсим новость 1: Крым возобновляет автобусное сообщение с Херсонщин...
    Парсим новость 2: СПГ-проект "Сахалин-2" получит оператора в российс...
    Парсим новость 3: Старт пассажирских поездов между Крымом, Херсонщин...
103 новостей (всего: 4742)
[92/1298] 2022-07-01:     Парсим новость 1: НРД и Мосбиржа обратятся в ЕС за разрешением на ис...
    Парсим новость 2: Эксперты сочли, что рублевые пошлины на экспорт зе...
    Парсим новость 3: Акционеры "ФосАгро" не утвердили дивиденды за 2021...
94 новостей (всего: 4836)
[93/1298] 2022-07-02:     Парсим новость 1: Глава РФПИ отметил, что санкции против РФ бьют по ...
    Парсим новость 2: Пошлина на экспорт подсолнечного масла из РФ в июл...
    Парсим новость 3: Южная Корея и США обсудили введение ограничений на...
3 новостей (всего: 4839)
[94/1298] 2022-07-03:     Парсим новость 1: В Турции заявили о трех вариантах доставки туркмен...
1 новостей (всего: 4840)
[95/1298] 2022-07-04:     Парсим новость 1: Швыдкой предложил рассмотреть возможность параллел...
    Парсим новость 2: Председатель правления Мосбиржи Денисов продал пак...
    Парсим новость 3: Шольц назвал долгосрочными нынешние экономические ...
74 новостей (всего: 4914)
[96/1298] 2022-07-05:     Парсим новость 1: Морской терминал КТК по решению суда приостановит ...
    Парсим новость 2: Эрдоган взял десять дней на переговоры о "зерновых...
    Парсим новость 3: В ответ на санкции в Сыктывкаре наладили выпуск уп...
92 новостей (всего: 5006)
[97/1298] 2022-07-06:     Парсим новость 1: Bloomberg сообщил, что Запад может ввести потолок ...
    Парсим новость 2: Тинькофф банк приостановил SWIFT-переводы, но пока...
    Парсим новость 3: Глава РСПП выступил за максимальную либерализацию ...
59 новостей (всего: 5065)
[98/1298] 2022-07-07:     Парсим новость 1: Золото подорожало после самой длинной череды сниже...
    Парсим новость 2: Рубль на закрытии торгов ускорил рост к доллару и ...
    Парсим новость 3: Минпромторг призвал Wildberries бороться с продажа...
65 новостей (всего: 5130)
[99/1298] 2022-07-08:     Парсим новость 1: Выручка оператора Суэцкого канала достигла рекорда...
    Парсим новость 2: Биржевая цена авиатоплива снова побила исторически...
    Парсим новость 3: Рубль завершил торги пятницы ростом к доллару и ев...
44 новостей (всего: 5174)
[100/1298] 2022-07-09:     Парсим новость 1: В ЕК оценили стоимость газа, поставленного из Азер...
    Парсим новость 2: Citigroup и Citibank отказались быть агентами в от...
    Парсим новость 3: В РФ создадут сервис мониторинга льготных программ...
3 новостей (всего: 5177)
[101/1298] 2022-07-10:     Парсим новость 1: Министр энергетического перехода Франции призвала ...
    Парсим новость 2: Глава Минфина Франции призвал готовиться к полному...
    Парсим новость 3: Канада решила вернуть турбину для "Северного поток...
4 новостей (всего: 5181)
[102/1298] 2022-07-11:     Парсим новость 1: Еврогруппа спланирует налогово-бюджетную политику ...
    Парсим новость 2: Еврокомиссия предложила скорректировать временные ...
    Парсим новость 3: "Система" разрешила себе замораживать выплаты "сан...
62 новостей (всего: 5243)
[103/1298] 2022-07-12:     Парсим новость 1: В АТОР заявили, что пандемия помогла турбизнесу пр...
    Парсим новость 2: Квота на беспошлинный ввоз сахара в РФ может быть ...
    Парсим новость 3: Netflix готовит запуск платформы с рекламой...
77 новостей (всего: 5320)
[104/1298] 2022-07-13:     Парсим новость 1: Зеленский заявил о прогрессе на переговорах в Турц...
    Парсим новость 2: Clearstream возобновит конвертацию депозитарных ра...
    Парсим новость 3: Аналитики отметили, что инвестиционный импорт в РФ...
89 новостей (всего: 5409)
[105/1298] 2022-07-14:     Парсим новость 1: Украина в I полугодии снизила экспорт кокса и полу...
    Парсим новость 2: Бывшая "дочка" Альфа-банка в Казахстане исключена ...
    Парсим новость 3: Минфин США временно разрешил операции с бывшей стр...
69 новостей (всего: 5478)
[106/1298] 2022-07-15:     Парсим новость 1: Алиев поручил искать покупателей электроэнергии из...
    Парсим новость 2: "Мосбиржа" зарегистрировала шесть выпусков облигац...
    Парсим новость 3: "Россети" присоединят к "дочерней" для нее ФСК...
80 новостей (всего: 5558)
[107/1298] 2022-07-16:     Парсим новость 1: В Саудовской Аравии заявили, что не смогут добыват...
    Парсим новость 2: S&P не стал снижать рейтинги Белоруссии, подтверди...
    Парсим новость 3: "Газпром" ждет от Siemens документов по возврату т...
7 новостей (всего: 5565)
[108/1298] 2022-07-17:     Парсим новость 1: Правительство РФ увеличило квоты на экспорт подсол...
    Парсим новость 2: Греф объяснил укрепление рубля усложнением процесс...
    Парсим новость 3: Сбербанк начал рефинансировать ипотеку, полученную...
4 новостей (всего: 5569)
[109/1298] 2022-07-18:     Парсим новость 1: ЦБ предложил поднять втрое потолок начальной капит...
    Парсим новость 2: Монетный двор Хорватии в три смены начал чеканить ...
    Парсим новость 3: Биткойн поднялся выше $22 тыс. впервые за месяц...
61 новостей (всего: 5630)
[110/1298] 2022-07-19:     Парсим новость 1: ГПБ вводит для физлиц комиссию по счетам в доллара...
    Парсим новость 2: Суд назначил на октябрь начало процесса по иску Tw...
    Парсим новость 3: Банк Англии рассмотрит возможность подъема ставки ...
63 новостей (всего: 5693)
[111/1298] 2022-07-20:     Парсим новость 1: Россельхознадзор констатировал, что в РФ продолжаю...
    Парсим новость 2: Аналитики ожидают снижения ЦБ РФ ставки на 50 б.п....
    Парсим новость 3: Прекращение поставок газа из РФ обойдется Германии...
58 новостей (всего: 5751)
[112/1298] 2022-07-21:     Парсим новость 1: Рубль ослабел к доллару и евро по итогам волатильн...
    Парсим новость 2: ЦБ РФ пока не получал ходатайств на покупку россий...
    Парсим новость 3: Рынок акций РФ снизился вслед за миром во главе с ...
64 новостей (всего: 5815)
[113/1298] 2022-07-22:     Парсим новость 1: Автоматическая конвертация DR в российских депозит...
    Парсим новость 2: Канадская McCain продала бизнес в РФ тульскому пре...
    Парсим новость 3: Рубль подешевел к доллару и евро на фоне снижения ...
84 новостей (всего: 5899)
[114/1298] 2022-07-23: 0 новостей
[115/1298] 2022-07-24:     Парсим новость 1: Китай стал вторым по товарообороту с Белоруссией п...
    Парсим новость 2: Лавров отметил, что российские экспортеры зерна пр...
2 новостей (всего: 5901)
[116/1298] 2022-07-25:     Парсим новость 1: Evraz запросил у OFSI лицензию для выплат по евроб...
    Парсим новость 2: Индикатор бизнес-климата ЦБ в июне вернулся в плюс...
    Парсим новость 3: Рубль упал к доллару и евро по итогам понедельника...
66 новостей (всего: 5967)
[117/1298] 2022-07-26:     Парсим новость 1: Глава ЕК приветствовала соглашение о регламенте со...
    Парсим новость 2: Вице-премьер Абрамченко описала ситуацию с произво...
    Парсим новость 3: Michelin списала 202 млн евро в I полугодии из-за ...
69 новостей (всего: 6036)
[118/1298] 2022-07-27:     Парсим новость 1: ФРС выразила готовность повысить ставку на 100 б.п...
    Парсим новость 2: Минэкономразвития сообщило о сокращении ВВП России...
    Парсим новость 3: Минпромторг одобрил заявку "Ауруса" на СПИК с инве...
91 новостей (всего: 6127)
[119/1298] 2022-07-28:     Парсим новость 1: Euroclear подтвердил продление конвертации российс...
    Парсим новость 2: L'Oreal увеличила чистую прибыль и выручку в I пол...
    Парсим новость 3: Закупки зерна в госфонд РФ начнутся 1 августа...

85 новостей (всего: 6212)
[120/1298] 2022-07-29:     Парсим новость 1: Нефтепровод Тенгиз-Новороссийск заработал в штатно...
    Парсим новость 2: Ракета Electron 2 августа стартует на орбиту с раз...
    Парсим новость 3: Европейский рынок акций вырос в июле максимально с...
80 новостей (всего: 6292)
  -> Сохранено во временный файл
[121/1298] 2022-07-30:     Парсим новость 1: В США выразили надежду на скорое исполнение соглаш...
    Парсим новость 2: Глава ЕК сообщила о проблемах с газоснабжением из ...
    Парсим новость 3: "Газпром" прекратил поставки в Латвию в связи с на...
5 новостей (всего: 6297)
[122/1298] 2022-07-31:     Парсим новость 1: В Минсельхозе Белоруссии не намерены экспортироват...
    Парсим новость 2: Тарифная квота на экспорт за пределы ЕАЭС лома и о...
2 новостей (всего: 6299)
[123/1298] 2022-08-01:     Парсим новость 1: "КАМАЗ" и Москва договорились о паритетном участии...
    Парсим новость 2: Саудовская Аравия в июле экспортировала рекордный ...
    Парсим новость 3: Apple снова размещает облигации для выплат акционе...
84 новостей (всего: 6383)
[124/1298] 2022-08-02:     Парсим новость 1: OFAC временно разблокировала бумаги "Северстали" и...
    Парсим новость 2: EBITDA "Норникеля" в I полугодии упала на 16% г/г ...
    Парсим новость 3: Норвежская Jotun продала уральскому девелоперу сво...
61 новостей (всего: 6444)
[125/1298] 2022-08-03:     Парсим новость 1: Цены на бензин в США снизились седьмую неделю подр...
    Парсим новость 2: Цены на Brent снизились до $98,55 за баррель после...
    Парсим новость 3: Искусство маленьких шагов в большой нефтяной дипло...
76 новостей (всего: 6520)
[126/1298] 2022-08-04:     Парсим новость 1: Репортаж с OFSI на шее. Обобщение...
    Парсим новость 2: Турция анонсировала выход из портов Украины еще тр...
    Парсим новость 3: VEON изучает возможность оптимизации своих активов...
78 новостей (всего: 6598)
[127/1298] 2022-08-05:     Парсим новость 1: Мосбиржа перенесла открытие фондового рынка для "д...
    Парсим новость 2: ЕАБР довел долю в Национальном резервном банке до ...
    Парсим новость 3: Рубль завершил торги пятницы небольшим снижением к...
68 новостей (всего: 6666)
[128/1298] 2022-08-06: 0 новостей
[129/1298] 2022-08-07:     Парсим новость 1: Маск заявил, что купит Twitter при условии раскрыт...
1 новостей (всего: 6667)
[130/1298] 2022-08-08:     Парсим новость 1: Указ президента устранил коллизии между отменой ре...
    Парсим новость 2: Юрлицам разрешили открывать счета типа "Д" для исп...
    Парсим новость 3: Данные пользователей Tele2 "утекли" в сеть...
59 новостей (всего: 6726)
[131/1298] 2022-08-09:     Парсим новость 1: Минэнерго США повысило прогноз цены Brent на 2022-...
    Парсим новость 2: НРД присвоил ISIN 5 выпускам гособлигаций Белорусс...
    Парсим новость 3: Рынок акций РФ под конец торгов усилил рост...
63 новостей (всего: 6789)
[132/1298] 2022-08-10:     Парсим новость 1: Дуров пожаловался на Apple из-за задержки "революц...
    Парсим новость 2: Производители картофельных хлопьев РФ просят огран...
    Парсим новость 3: Мосбиржа возобновит в режиме основных торгов сделк...
73 новостей (всего: 6862)
[133/1298] 2022-08-11:     Парсим новость 1: "Полюс" продлил до 25 августа срок голосования дер...
    Парсим новость 2: Европейские биржевые индексы завершили торги в плю...
    Парсим новость 3: Загрузка петербургских отелей выросла в июле на 38...
65 новостей (всего: 6927)
[134/1298] 2022-08-12:     Парсим новость 1: ЦБ РФ увидел признаки затухания дезинфляционных эф...
    Парсим новость 2: "Роснефть" спрогнозировала подорожание топлива в Ф...
    Парсим новость 3: Доля валютных депозитов физлиц в июне обновила мин...
80 новостей (всего: 7007)
[135/1298] 2022-08-13:     Парсим новость 1: Минск запланировал увеличить экспорт в РФ и страны...
    Парсим новость 2: Белоусов заявил, что пик спада в потреблении в РФ ...
    Парсим новость 3: В Минсельхозе заявили, что к 12 августа продовольс...
5 новостей (всего: 7012)
[136/1298] 2022-08-14:     Парсим новость 1: В Белоруссии товары подорожали за год на 10-20%...
    Парсим новость 2: "Росагролизинг" продолжит облигационную программу ...
2 новостей (всего: 7014)
[137/1298] 2022-08-15:     Парсим новость 1: ESG Альянс создаст атлас российской экосистемы уст...
    Парсим новость 2: Минпромторг в четверг начнет отбор компаний для по...
    Парсим новость 3: Подсолнечник и подсолнечное масло дорожают в Росси...
75 новостей (всего: 7089)
[138/1298] 2022-08-16:     Парсим новость 1: МТС подала в JP Morgan уведомление о начале автома...
    Парсим новость 2: АФК "Система" попросила у Минфина разрешения не ко...
    Парсим новость 3: "Роснефть" уведомила депозитарий о необходимости а...
70 новостей (всего: 7159)
[139/1298] 2022-08-17:     Парсим новость 1: Руководство ФРС ожидает дальнейших повышений ключе...
    Парсим новость 2: "Черкизово" уведомило депозитарий об автоматическо...
    Парсим новость 3: Рубль к концу торгов остался в плюсе к доллару и е...
52 новостей (всего: 7211)
[140/1298] 2022-08-18:     Парсим новость 1: Путин раскритиковал главу ОСК за убыточные контрак...
    Парсим новость 2: Путин заявил, что РФ поддержит судоверфь "Звезда" ...
    Парсим новость 3: Инвестиции в компоненты и НИОКР в стратегии автопр...
57 новостей (всего: 7268)
[141/1298] 2022-08-19:     Парсим новость 1: "ФосАгро" направила уведомление об автоматической ...
    Парсим новость 2: "Мосбиржа" зарегистрировала выпуск облигаций "Полю...
    Парсим новость 3: Рубль вырос к доллару и евро по итогам торгов пятн...
73 новостей (всего: 7341)
[142/1298] 2022-08-20: 0 новостей
[143/1298] 2022-08-21: 0 новостей
[144/1298] 2022-08-22:     Парсим новость 1: "Росатом" подал иски на $3 млрд после разрыва конт...
    Парсим новость 2: Саудовский министр допустил, что ОПЕК+ придется со...
    Парсим новость 3: Рубль завершил торги снижением к доллару и повышен...
60 новостей (всего: 7401)
[145/1298] 2022-08-23:     Парсим новость 1: В Минобороны сообщили о выходе из портов Украины 3...
    Парсим новость 2: Новый инвестор одного из старейших банков России п...
    Парсим новость 3: Минсельхоз предложил продлить запрет экспорта рапс...
64 новостей (всего: 7465)
[146/1298] 2022-08-24:     Парсим новость 1: Канада вернет Германии оставшиеся пять турбин для ...
    Парсим новость 2: ЦБ РФ порекомендовал компаниям новые антисанкционн...
    Парсим новость 3: Экспорт нефти и нефтепродуктов из США достиг рекор...
61 новостей (всего: 7526)
[147/1298] 2022-08-25:     Парсим новость 1: "Полюс" продлил срок голосования держателей евробо...
    Парсим новость 2: Испанский парламент утвердил план по экономии газа...
    Парсим новость 3: WSJ ждет скорой договоренности США и КНР о китайск...
61 новостей (всего: 7587)
[148/1298] 2022-08-26:     Парсим новость 1: Трейдер "Калита" подал заявление о ликвидации юрид...
    Парсим новость 2: "Новая концессионная компания" 31 августа начнет р...
    Парсим новость 3: Porsche заручилась поддержкой инвесторов на провед...
95 новостей (всего: 7682)
[149/1298] 2022-08-27:     Парсим новость 1: ЦБ РФ расширил возможности банков по продаже насел...
1 новостей (всего: 7683)
[150/1298] 2022-08-28:     Парсим новость 1: Франция обсудит с Алжиром возможное увеличение зак...
    Парсим новость 2: Премьер Японии пообещал в течение трех лет выделит...
2 новостей (всего: 7685)
  -> Сохранено во временный файл
[151/1298] 2022-08-29:     Парсим новость 1: ОАК в I полугодии нарастила чистый убыток по МСФО ...
    Парсим новость 2: В Союзе экспортеров зерна заявили о трудностях при...
    Парсим новость 3: "ЮТэйр" в I полугодии увеличила чистую прибыль по ...
62 новостей (всего: 7747)
[152/1298] 2022-08-30:     Парсим новость 1: Из украинского порта Южный вышло второе зафрахтова...
    Парсим новость 2: Азербайджан и Болгария обсудили поставки газа Софи...
    Парсим новость 3: "Газпром" приостановил поставки во Францию...
69 новостей (всего: 7816)
[153/1298] 2022-08-31:     Парсим новость 1: На "Мосбирже" прошли первые торги производными на ...
    Парсим новость 2: Правительство Бельгии предложило меры по смягчению...
    Парсим новость 3: ВВП Латвии в I полугодии вырос на 4,7%...
77 новостей (всего: 7893)

[154/1298] 2022-09-01:     Парсим новость 1: ЦБ попросил продлить право регулировать раскрытие ...
    Парсим новость 2: Рубль завершил первые торги месяца снижением к дол...
    Парсим новость 3: Индекс МосБиржи к вечеру обновил максимум с середи...
63 новостей (всего: 7956)
[155/1298] 2022-09-02:     Парсим новость 1: Европейские фондовые рынки завершили торги в пятни...
    Парсим новость 2: США ждут публикации предварительного плана касател...
    Парсим новость 3: Глава Shell может уйти в отставку в 2023 году...
72 новостей (всего: 8028)
[156/1298] 2022-09-03:     Парсим новость 1: Баку поддержит строительство Транскаспийского газо...
    Парсим новость 2: Один человек погиб при пожаре в оружейном магазине...
    Парсим новость 3: В Siemens выразили готовность устранить проблемы н...
4 новостей (всего: 8032)
[157/1298] 2022-09-04:     Парсим новость 1: Новак заявил о нарушении условий контракта по ремо...
    Парсим новость 2: Песков заявил, что вина за остановку "Северного по...
2 новостей (всего: 8034)
[158/1298] 2022-09-05:     Парсим новость 1: Германия продлит до апреля срок эксплуатации двух ...
    Парсим новость 2: "Газпром" заявил о системном дефекте турбин Siemen...
    Парсим новость 3: "Почта России" и Skolkovo Ventures создали компани...
34 новостей (всего: 8068)
[159/1298] 2022-09-06:     Парсим новость 1: Путин попросил Минфин не повышать льготные ставки ...
    Парсим новость 2: Минфин РФ выступил против снижения налогов для тур...
    Парсим новость 3: Рубль вечером немного ослаб к доллару и евро...
55 новостей (всего: 8123)
[160/1298] 2022-09-07:     Парсим новость 1: США продолжат помогать Европе в подготовке к зиме ...
    Парсим новость 2: Apple представила iPhone 14 со спутниковым SOS-опо...
    Парсим новость 3: Меморандумы и соглашения на общую сумму 3,2 трлн р...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/861031 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176BEC2690>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
48 новостей (всего: 8171)
[161/1298] 2022-09-08:     Парсим новость 1: Кредиторы и должники в РФ получат площадку-фонд дл...
    Парсим новость 2: Валюту с открытых после 9 сентября счетов выдадут ...
    Парсим новость 3: Санкционные банки смогут возвращать юрлицам-резиде...
47 новостей (всего: 8218)
[162/1298] 2022-09-09:     Парсим новость 1: УГМК закрыла сделку по покупке активов Petropavlov...
    Парсим новость 2: Мария Гордон покинет совет директоров "Детского ми...
    Парсим новость 3: Цены на сахар в РФ в августе повысились на 2,4%, с...
40 новостей (всего: 8258)
[163/1298] 2022-09-10:     Парсим новость 1: Полина Юмашева купила сеть клиник "Чайка" у Алекса...
1 новостей (всего: 8259)
[164/1298] 2022-09-11:     Парсим новость 1: Глава Минэнерго РФ заявил, что потолок цен на нефт...
    Парсим новость 2: В Софии заявили о договоренности с Азербайджаном о...
    Парсим новость 3: Землетрясение магнитудой 7,6 произошло в Папуа-Нов...
4 новостей (всего: 8263)
[165/1298] 2022-09-12:     Парсим новость 1: Белоруссия и Россия ожидают исторический максимум ...
    Парсим новость 2: Цены на литий в Китае вернулись к мартовским рекор...
    Парсим новость 3: Рубль умеренно укрепился к доллару и евро в понеде...
62 новостей (всего: 8325)
[166/1298] 2022-09-13:     Парсим новость 1: Минский моторный завод нарастил экспорт в Россию н...
    Парсим новость 2: В Латвии расследуют, почему трейдер Latvijas gaze ...
    Парсим новость 3: "Яндекс" увеличил долю выкупа конвертируемых облиг...
69 новостей (всего: 8394)
[167/1298] 2022-09-14:     Парсим новость 1: Украина запланировала покрывать дефицит госбюджета...
    Парсим новость 2: Аналитики назвали решающий период для технологичес...
    Парсим новость 3: Soft Bank рассматривает возможность запуска третье...
75 новостей (всего: 8469)
[168/1298] 2022-09-15:     Парсим новость 1: Акционеры ФСК одобрили присоединение к компании "Р...
    Парсим новость 2: Ставки по ипотеке в США превысили 6% впервые с 200...
    Парсим новость 3: Рубль растерял часть дневного роста, но все равно ...
80 новостей (всего: 8549)
[169/1298] 2022-09-16:     Парсим новость 1: "Роснефть" готовит ответ в связи с передачей ее не...
    Парсим новость 2: Минтруд предложил в 2023 году сохранить размер пос...
    Парсим новость 3: Evraz не сможет в срок выплатить купоны по двум вы...
82 новостей (всего: 8631)
[170/1298] 2022-09-17:     Парсим новость 1: Эрдоган выразил надежду на то, что АЭС "Аккую" зар...
    Парсим новость 2: "Норникель" готовится к переориентации на восток, ...
    Парсим новость 3: "Норникель" в 2023 году запустит 10-летнюю програм...
4 новостей (всего: 8635)
[171/1298] 2022-09-18:     Парсим новость 1: Новак посчитал, что кризис в энергетике Европы тол...
    Парсим новость 2: ЕК предложила приостановить выделение Венгрии 7,5 ...
2 новостей (всего: 8637)
[172/1298] 2022-09-19:     Парсим новость 1: "Совкомфлот" планирует заместить два выпуска долла...
    Парсим новость 2: Изменения рубля к доллару и евро в понедельник ока...
    Парсим новость 3: "Газпром" выпустит еще одни замещающие облигации...
80 новостей (всего: 8717)
[173/1298] 2022-09-20:     Парсим новость 1: ЦБ Армении заявил, что банки страны сами выбирают ...
    Парсим новость 2: ЦБ не поддержал идею защиты клиентов от санкций пр...
    Парсим новость 3: В РФ в 3,6 раза снизили размер субсидий на кредито...
75 новостей (всего: 8792)
[174/1298] 2022-09-21:     Парсим новость 1: ФРС ожидаемо подняла ставку на 75 базисных пунктов...
    Парсим новость 2: Meta планирует урезать расходы на 10%, в том числе...
    Парсим новость 3: Капитализация рынка акций РФ в среду снизилась на ...
64 новостей (всего: 8856)
[175/1298] 2022-09-22:     Парсим новость 1: ЕС потратил 450 млрд евро на противодействие после...
    Парсим новость 2: НАУФОР хочет вернуть ЦБ к дискуссии о расширении д...
    Парсим новость 3: "Полюс" перечислил trustee купон для иностранных д...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/863405 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176AB6AA20>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
97 новостей (всего: 8953)
[176/1298] 2022-09-23:     Парсим новость 1: Соцфонд РФ направит в 2023 году свыше 11 трлн рубл...
    Парсим новость 2: Субсидирование кредитов системообразующим компания...
    Парсим новость 3: Минфин оценил поступления в бюджет 2023-25 гг. от ...
76 новостей (всего: 9029)
[177/1298] 2022-09-24:     Парсим новость 1: В Белоруссии на полгода вводится запрет на экспорт...
    Парсим новость 2: Свыше 4,5 млн тонн продукции АПК экспортировали из...
    Парсим новость 3: "Автотор" вложит 5,7 млрд рублей в развитие мощнос...
3 новостей (всего: 9032)
[178/1298] 2022-09-25:     Парсим новость 1: СМИ сообщили о планах Mazda свернуть производство ...
    Парсим новость 2: ФРГ и ОАЭ подписали контракт о поставках СПГ в Гер...
2 новостей (всего: 9034)
[179/1298] 2022-09-26:     Парсим новость 1: Приложение "ВКонтакте" и другие сервисы экосистемы...
    Парсим новость 2: Давление газа упало на обеих нитках газопровода "С...
    Парсим новость 3: Банки и другие финорганизации хотят обязать отвеча...
54 новостей (всего: 9088)
[180/1298] 2022-09-27:     Парсим новость 1: НЛМК получил согласие держателей евробондов-26 на ...
    Парсим новость 2: Капитализация рынка акций РФ во вторник снизилась ...
    Парсим новость 3: VK продает игровое подразделение My.Games за $642 ...
61 новостей (всего: 9149)
  -> Сохранено во временный файл
[181/1298] 2022-09-28:     Парсим новость 1: Эстония возобновила создание стратегического запас...
    Парсим новость 2: Минтруда пообещало индексировать пенсии по старост...
    Парсим новость 3: В Литве электроэнергия для населения может подорож...
99 новостей (всего: 9248)
[182/1298] 2022-09-29:     Парсим новость 1: Правительство разрешило "Энел Россия" вывезти част...
    Парсим новость 2: Нидерланды отозвали экспортную лицензию у "Турецко...
    Парсим новость 3: Подписано межправсоглашение о транзите белорусских...

71 новостей (всего: 9319)
[183/1298] 2022-09-30: Ошибка при парсинге https://www.interfax.ru/business/news/2022/09/30: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/news/2022/09/30 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176AC9B170>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
0 новостей
[184/1298] 2022-10-01:     Парсим новость 1: Правительство утвердило новый порядок госаккредита...
    Парсим новость 2: СМИ сообщили о работе Eni над возобновлением поста...
    Парсим новость 3: "Газпром" связал снижение поставок газа в Молдавию...
8 новостей (всего: 9327)
[185/1298] 2022-10-02:     Парсим новость 1: Макрон заявил о готовности работать вместе со стра...
    Парсим новость 2: Совкомбанк намерен подать иск о банкротстве сети "...
    Парсим новость 3: Баку оставил на усмотрение ЕС распределение допобъ...
6 новостей (всего: 9333)
[186/1298] 2022-10-03:     Парсим новость 1: Кабмин утвердил правила предоставления в 2022 г. с...
    Парсим новость 2: Субсидирование льготных кредитов для системообразу...
    Парсим новость 3: Глава итальянской Eni заявил о важности возобновле...
89 новостей (всего: 9422)
[187/1298] 2022-10-04:     Парсим новость 1: Постпреды стран ЕС предварительно согласовали вось...
    Парсим новость 2: МВФ утвердил финансирование 93 странам на $258 млр...
    Парсим новость 3: Маск предложил закрыть сделку по покупке Twitter н...
60 новостей (всего: 9482)
[188/1298] 2022-10-05:     Парсим новость 1: Экономика vs. политика - ОПЕК+ решила снизить квот...
    Парсим новость 2: Глава "Росатома" сообщил, что строительные инвести...
    Парсим новость 3: План Байдена списывать кредиты студентов обойдется...
88 новостей (всего: 9570)
[189/1298] 2022-10-06:     Парсим новость 1: Промипотеку предложили распространить на стройку и...
    Парсим новость 2: Французам предложили план экономии электричества...
    Парсим новость 3: LME запросила мнения участников рынка о возможност...
73 новостей (всего: 9643)
[190/1298] 2022-10-07:     Парсим новость 1: Указ президента РФ о применении спецмер в отношени...
    Парсим новость 2: Байден заявил, что из-за решения ОПЕК+ в США начал...
    Парсим новость 3: "Сахалин-1" переведут в юрисдикцию РФ по аналогии ...
74 новостей (всего: 9717)
[191/1298] 2022-10-08:     Парсим новость 1: Сбербанк повысил ставки по ипотеке из-за изменения...
1 новостей (всего: 9718)
[192/1298] 2022-10-09:     Парсим новость 1: ВТБ вслед за Сбербанком повышает ставки по ипотеке...
    Парсим новость 2: Глава Минфина США назвала бесполезным решение ОПЕК...
    Парсим новость 3: Песков отметил, что решения в рамках ОПЕК+ позволя...
3 новостей (всего: 9721)
[193/1298] 2022-10-10:     Парсим новость 1: Власти Франции потратят 100 млрд евро на борьбу с ...
    Парсим новость 2: Правительство РФ разрешило авансировать ряд "униве...
    Парсим новость 3: "Газпром" разместит локальные облигации для замены...
64 новостей (всего: 9785)
[194/1298] 2022-10-11:     Парсим новость 1: Более 7 млн тонн продовольствия экспортировали из ...
    Парсим новость 2: Льготы по ИИС не будут предоставляться на покупку ...
    Парсим новость 3: Минфин счел, что инвесторы из недружественных стра...
62 новостей (всего: 9847)
[195/1298] 2022-10-12:     Парсим новость 1: Минэнерго США понизило прогноз цены Brent на 2022 ...
    Парсим новость 2: СПБ биржа до 14 ноября свернет операции с акциями ...
    Парсим новость 3: Лагард призвала мировые центробанки активнее сотру...
86 новостей (всего: 9933)
[196/1298] 2022-10-13:     Парсим новость 1: В странах ЕС заморожено более 17 млрд евро фондов ...
    Парсим новость 2: Приложение "ВКонтакте" снова доступно в App Store...
    Парсим новость 3: ЦБ РФ сообщил о постепенном исчерпании весеннего у...
89 новостей (всего: 10022)
[197/1298] 2022-10-14:     Парсим новость 1: Три сухогруза доставят продовольствие из Украины в...
    Парсим новость 2: Новый оператор проекта "Сахалин-1" зарегистрирован...
    Парсим новость 3: Рубль в пятницу заметно вырос к доллару и евро...
86 новостей (всего: 10108)
[198/1298] 2022-10-15:     Парсим новость 1: В Польше заявили, что устранили утечку на нефтепро...
    Парсим новость 2: Путин ввёл дополнительный контроль за сделками в ф...
    Парсим новость 3: ЦБ РФ получил право выдавать разрешения на вывоз и...
4 новостей (всего: 10112)
[199/1298] 2022-10-16:     Парсим новость 1: Салливан заявил, что Байден намерен "методично" ме...
    Парсим новость 2: Миллер заявил о потенциале значительного расширени...
    Парсим новость 3: Миллер заявил, что ограничение цен на газ РФ в Евр...
3 новостей (всего: 10115)
[200/1298] 2022-10-17:     Парсим новость 1: Замглавы МИД РФ обсудил с замгенсека ООН и генсеко...
    Парсим новость 2: Подача газа из РФ в Армению будет приостановлена 1...
    Парсим новость 3: Рубль вырос к доллару и снизился к евро вслед за и...
72 новостей (всего: 10187)
[201/1298] 2022-10-18:     Парсим новость 1: "Интеррос" передал благотворительному фонду своего...
    Парсим новость 2: СД "Газпрома" утвердил увеличение инвестпрограммы ...
    Парсим новость 3: Рубль завершил торги вторника небольшим повышением...
84 новостей (всего: 10271)
[202/1298] 2022-10-19:     Парсим новость 1: Правительство Белоруссии подписало постановление о...
    Парсим новость 2: Рубль развернулся вниз к доллару и сократил темпы ...
    Парсим новость 3: Часть закупок новых субъектов РФ временно может по...
72 новостей (всего: 10343)
[203/1298] 2022-10-20:     Парсим новость 1: Глава Европарламента указала лидерам стран ЕС на п...
    Парсим новость 2: Рубль вырос к доллару и снизился к евро по итогам ...
    Парсим новость 3: АФК "Система" готова консолидировать 100% ритейлер...
86 новостей (всего: 10429)
[204/1298] 2022-10-21:     Парсим новость 1: Владельцы облигаций "ФСК - Россетей" смогут требов...
    Парсим новость 2: Deutsche Bank обещал сократить "финансируемые выбр...
    Парсим новость 3: FATF запретила России участвовать в своих текущих ...
67 новостей (всего: 10496)
[205/1298] 2022-10-22:     Парсим новость 1: РФ в ближайшее время предоставит Белоруссии кредит...
1 новостей (всего: 10497)
[206/1298] 2022-10-23: 0 новостей
[207/1298] 2022-10-24:     Парсим новость 1: Йеллен предупредила о рисках для финансовой стабил...
    Парсим новость 2: Berkshire Hathaway может обойти Tesla по рыночной ...
    Парсим новость 3: Рубль подрос к доллару и подешевел к евро вслед за...
73 новостей (всего: 10570)
[208/1298] 2022-10-25:     Парсим новость 1: Все инвестрешения в "Роснано" будут проходить чере...
    Парсим новость 2: Xerox получила убыток в III квартале на фоне обесц...
    Парсим новость 3: Рубль завершил торги вторника ослаблением к доллар...
78 новостей (всего: 10648)
[209/1298] 2022-10-26:     Парсим новость 1: Сальдированная прибыль розничной торговли РФ в авг...
    Парсим новость 2: "Соллерс" до конца года запустит производство ново...
    Парсим новость 3: Министр энергетики США заявила о планах самостояте...
84 новостей (всего: 10732)
[210/1298] 2022-10-27:     Парсим новость 1: Saipem за девять месяцев снизила чистый убыток в в...
    Парсим новость 2: США ждут поддержки союзниками ограничений на поста...
    Парсим новость 3: "Газпром" вводит новые мощности добычи и транспорт...
103 новостей (всего: 10835)
  -> Сохранено во временный файл
[211/1298] 2022-10-28:     Парсим новость 1: В Крыму сделали первые шаги к изъятию активов инос...
    Парсим новость 2: Ставка вышла на плато, окруженное туманом. Заявлен...
    Парсим новость 3: Великобритания с января откажется от импорта росси...
113 новостей (всего: 10948)
[212/1298] 2022-10-29: 0 новостей
[213/1298] 2022-10-30:     Парсим новость 1: Блинкен призвал все заинтересованные стороны верну...
    Парсим новость 2: СКЦ сообщил об отсутствии договоренности о движени...
    Парсим новость 3: "Победа" с воскресенья переведет большую часть рей...
3 новостей (всего: 10951)
[214/1298] 2022-10-31:     Парсим новость 1: "Газпром" допущен к обследованию места взрыва на "...
    Парсим новость 2: Рынок акций РФ и ОФЗ заметно выросли в октябре в р...
    Парсим новость 3: Vitol продолжает выполнять существующие контракты ...

68 новостей (всего: 11019)
[215/1298] 2022-11-01:     Парсим новость 1: В Анкаре заявили, что суда под флагом Турции продо...
    Парсим новость 2: Еврокомиссар по энергетике обсудила в Киеве поддер...
    Парсим новость 3: Рубль завершил торги вторника умеренным повышением...
84 новостей (всего: 11103)
[216/1298] 2022-11-02:     Парсим новость 1: Evraz могут понадобиться новые лицензии OFSI для п...
    Парсим новость 2: Минпромторг включил алкоголь в перечень товаров дл...
    Парсим новость 3: ФРС ожидаемо подняла ставку до 3,75-4%...
86 новостей (всего: 11189)
[217/1298] 2022-11-03:     Парсим новость 1: Юристы ЕС изучают возможность направить активы Бан...
    Парсим новость 2: "Черкизово" претендует на агроактивы банка "Траст"...
    Парсим новость 3: Британия запретит транспортировку российской нефти...
106 новостей (всего: 11295)
[218/1298] 2022-11-04:     Парсим новость 1: Один сухогруз в пятницу покинул украинский порт в ...
    Парсим новость 2: СПБ банк перевел на неторговые разделы субсчетов д...
    Парсим новость 3: Молдавия использовала первый транш кредита ЕБРР на...
7 новостей (всего: 11302)
[219/1298] 2022-11-05:     Парсим новость 1: Крупнейшие страны ЕС начали тратить запасы газа из...
    Парсим новость 2: ЕК выделит 66 млн евро на программу сотрудничества...
2 новостей (всего: 11304)
[220/1298] 2022-11-06:     Парсим новость 1: В Белоруссии прогнозируют рост доходов от экспорта...
1 новостей (всего: 11305)
[221/1298] 2022-11-07:     Парсим новость 1: Почти 80 сухогрузов ждут разрешения на заход в пор...
    Парсим новость 2: Глобальные юридические фирмы сокращают наём сотруд...
    Парсим новость 3: Минсельхоз планирует сохранить запрет на экспорт р...
73 новостей (всего: 11378)
[222/1298] 2022-11-08:     Парсим новость 1: Запасы газа в ПХГ США перед зимой оказались на 4% ...
    Парсим новость 2: Золото активно дорожает на фоне ослабления доллара...
    Парсим новость 3: Минэнерго США повысило прогноз потребления нефти в...
76 новостей (всего: 11454)
[223/1298] 2022-11-09:     Парсим новость 1: Госкомпании получили возможность формировать прогр...
    Парсим новость 2: Правительство РФ установило доптребования к участн...
    Парсим новость 3: Накопления иностранных акционеров зачислят на счет...
72 новостей (всего: 11526)
[224/1298] 2022-11-10:     Парсим новость 1: Министерство торговли США признало экономику Росси...
    Парсим новость 2: Греф отметил восстановление спроса на ипотеку посл...
    Парсим новость 3: Европейские акции резко выросли на данных о замедл...
94 новостей (всего: 11620)
[225/1298] 2022-11-11:     Парсим новость 1: Правительство утвердило на 2023 год индексацию гру...
    Парсим новость 2: Рубль не изменился к доллару и упал к евро перед в...
    Парсим новость 3: Schneider Electric повысила предложение о покупке ...
83 новостей (всего: 11703)
[226/1298] 2022-11-12:     Парсим новость 1: Новак провел совещание по поддержке нефтяной отрас...
    Парсим новость 2: КТК успешно заменил танк плавучести на причальном ...
2 новостей (всего: 11705)
[227/1298] 2022-11-13:     Парсим новость 1: Восемь судов с продовольствием вышли из портов Укр...
    Парсим новость 2: Axios сообщил о расторжениях контрактов Twitter с ...
2 новостей (всего: 11707)
[228/1298] 2022-11-14:     Парсим новость 1: Европарламент принял новую директиву по ESG-отчетн...
    Парсим новость 2: Дания вслед за Швецией разрешила Nord Stream обсле...
    Парсим новость 3: Amazon может начать увольнения сотрудников на этой...
79 новостей (всего: 11786)
[229/1298] 2022-11-15:     Парсим новость 1: Рынок акций РФ упал на вечерних торгах из-за эскал...
    Парсим новость 2: США ввели санкции за предполагаемые поставки иранс...
    Парсим новость 3: "Детский мир" привлечет новый долг для выкупа акци...
72 новостей (всего: 11858)
[230/1298] 2022-11-16:     Парсим новость 1: Утренний удар по нефтебазе в Орловской области пов...
    Парсим новость 2: Суд признал банкротом IT-компанию "Техносерв Конса...
    Парсим новость 3: Freeport LNG увеличила штат на 30% после июньского...
80 новостей (всего: 11938)
[231/1298] 2022-11-17:     Парсим новость 1: ЕС окажет Украине помощь в модернизации управления...
    Парсим новость 2: Турция пообещала посредничество в устранении препя...
    Парсим новость 3: Опрос показал рост доверия российских предпринимат...
72 новостей (всего: 12010)
[232/1298] 2022-11-18:     Парсим новость 1: Доля валютных депозитов физлиц в сентябре упала до...
    Парсим новость 2: Минпромторг предложил продлить квоты на экспорт уд...
    Парсим новость 3: Держатели евробондов GeoProMining согласились на а...
69 новостей (всего: 12079)
[233/1298] 2022-11-19:     Парсим новость 1: Общий объем поставленного Азербайджаном газа по TA...
    Парсим новость 2: Белоусов заявил, что предстоящие годы - период иде...
2 новостей (всего: 12081)
[234/1298] 2022-11-20: 0 новостей
[235/1298] 2022-11-21:     Парсим новость 1: ОАЭ отрицают участие в переговорах с членами ОПЕК+...
    Парсим новость 2: Китай за 10 месяцев увеличил импорт алюминия из РФ...
    Парсим новость 3: Банки РФ в октябре замедлили темпы роста ипотеки д...
75 новостей (всего: 12156)
[236/1298] 2022-11-22:     Парсим новость 1: ЕС предложил ввести 45-дневный переходный период п...
    Парсим новость 2: "Газпром" выплатил купон по евробондам-2024 в евро...
    Парсим новость 3: Власти Приднестровья пожаловались на Кишинев в ООН...
74 новостей (всего: 12230)
[237/1298] 2022-11-23:     Парсим новость 1: РФ в октябре снизила выпуск стального проката на 1...
    Парсим новость 2: Цены промпроизводителей в РФ в октябре снизились н...
    Парсим новость 3: ЕЭК рассмотрит поэтапное снижение порога для беспо...
80 новостей (всего: 12310)
[238/1298] 2022-11-24:     Парсим новость 1: Совет ЕС договорился о коллективных закупках газа ...
    Парсим новость 2: Эксперимент по ввозу товаров e-commerce в РФ через...
    Парсим новость 3: Минфин склоняется к тому, чтобы взимать НДФЛ с "уд...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/874050 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176AB69520>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
73 новостей (всего: 12383)
[239/1298] 2022-11-25:     Парсим новость 1: Минфин РФ предложил продлить действие норм, разреш...
    Парсим новость 2: Маркетплейсы выступили за расширение эксперимента ...
    Парсим новость 3: Stoxx 600 завершил ростом 6-ю неделю подряд, брита...
67 новостей (всего: 12450)
[240/1298] 2022-11-26:     Парсим новость 1: В Сербии заявили, что рассчитывают с января начать...
    Парсим новость 2: "Соллерс" начал выпуск легких коммерческих авто по...
    Парсим новость 3: Два сухогруза перевезут соевые бобы из Украины в И...
4 новостей (всего: 12454)
  -> Сохранено во временный файл
[241/1298] 2022-11-27: 0 новостей
[242/1298] 2022-11-28:     Парсим новость 1: Сухогрузы с продовольствием в понедельник не смогл...
    Парсим новость 2: Segezha получила право на льготный ввоз оборудован...
    Парсим новость 3: Белоруссия нарастит экспорт в Россию на 6,5% в сле...
39 новостей (всего: 12493)
[243/1298] 2022-11-29:     Парсим новость 1: Встречи министров ОПЕК и ОПЕК+ 3 и 4 декабря пройд...
    Парсим новость 2: Министр нефти Венесуэлы сообщил о скором подписани...
    Парсим новость 3: Рубль во вторник укрепился к доллару и евро благод...
54 новостей (всего: 12547)
[244/1298] 2022-11-30:     Парсим новость 1: ЦБ РФ начнет в 2023 г. сворачивать меры поддержки ...
    Парсим новость 2: Маркировка жидкости для вейпов станет обязательной...
    Парсим новость 3: "АвтоВАЗ" в ноябре продал на 12,5% больше автомоби...
55 новостей (всего: 12602)
[245/1298] 2022-12-01:     Парсим новость 1: Глава "АЛРОСА" Сергей Иванов покинет компанию...
    Парсим новость 2: Правительство утвердило директиву о назначении Вол...
    Парсим новость 3: Минюст зарегистрировал приказы об увеличении цен "...
51 новостей (всего: 12653)
[246/1298] 2022-12-02:     Парсим новость 1: Мировые цены на продовольствие в ноябре практическ...
    Парсим новость 2: ОПЕК+ упирается в нефтяной потолок. Обзор...
    Парсим новость 3: В ЕС на уровне постпредов согласовали потолок цен ...

43 новостей (всего: 12696)
[247/1298] 2022-12-03:     Парсим новость 1: Совет ЕС принял решение по "потолку" цен на россий...
    Парсим новость 2: Россия с 1 января вводит экспортные пошлины на удо...
    Парсим новость 3: ОПЕК на министерской встрече обсудила только админ...
3 новостей (всего: 12699)
[248/1298] 2022-12-04:     Парсим новость 1: ОПЕК+ затаился в ожидании ответа России на введени...
    Парсим новость 2: Более 13 млн тонн продовольствия было экспортирова...
    Парсим новость 3: Новак отметил, что нефтяной рынок сейчас в лучшем ...
14 новостей (всего: 12713)
[249/1298] 2022-12-05:     Парсим новость 1: "Яндекс" получил президентское разрешение на докап...
    Парсим новость 2: Более 70 судов может быть построено в РФ в рамках ...
    Парсим новость 3: Рубль подешевел к доллару и евро на фоне действия ...
71 новостей (всего: 12784)
[250/1298] 2022-12-06:     Парсим новость 1: ЦБ рассматривает возможность поэтапного введения р...
    Парсим новость 2: США повысили прогноз добычи нефти в стране в 2022 ...
    Парсим новость 3: Airbus не сможет выполнить свой прогноз поставок в...
61 новостей (всего: 12845)
[251/1298] 2022-12-07:     Парсим новость 1: США и Турция обсудили потолок цен на российскую не...
    Парсим новость 2: Франция начала подсчет ущерба от погромов футбольн...
    Парсим новость 3: Собянин заявил, что экономика Москвы в 2023 году д...
73 новостей (всего: 12918)
[252/1298] 2022-12-08:     Парсим новость 1: Совет ЕС принял директиву по снижению уязвимости к...
    Парсим новость 2: ЦБ отложит до марта запрет неквалам покупать бумаг...
    Парсим новость 3: В Московском регионе платежеспособный спрос снизил...
68 новостей (всего: 12986)
[253/1298] 2022-12-09:     Парсим новость 1: Турция лидирует по закупкам российской пшеницы в и...
    Парсим новость 2: Рубль укрепился к доллару и евро по итогам пятницы...
    Парсим новость 3: Рынок акций РФ завершил пятницу и неделю снижением...
73 новостей (всего: 13059)
[254/1298] 2022-12-10:     Парсим новость 1: "Газпром" в пятницу обновил рекорд поставок газа в...
    Парсим новость 2: Министр энергетики Австралии поддержал введение в ...
    Парсим новость 3: Миллер назвал развитие темы газового хаба в Турции...
3 новостей (всего: 13062)
[255/1298] 2022-12-11:     Парсим новость 1: Песков заявил, что Европа в желании не зависеть от...
    Парсим новость 2: Южная Корея установила новый годовой рекорд экспор...
    Парсим новость 3: Четыре сухогруза доставят украинское продовольстви...
3 новостей (всего: 13065)
[256/1298] 2022-12-12:     Парсим новость 1: В Думу внесены поправки о механизмах обособления з...
    Парсим новость 2: Белоруссия создала компанию, которая может стать "...
    Парсим новость 3: Финляндия закупит у Израиля и Швеции ракеты на 147...
68 новостей (всего: 13133)
[257/1298] 2022-12-13:     Парсим новость 1: ЕС продолжит обсуждать потолок цен на газ на следу...
    Парсим новость 2: ЦБ обяжет страховщиков жизни выплачивать инвестдох...
    Парсим новость 3: ЦБ планирует продлить меры поддержки страховых ком...
63 новостей (всего: 13196)
[258/1298] 2022-12-14:     Парсим новость 1: Объем buyback компаний из S&P 500 в III кв. сократ...
    Парсим новость 2: Рост ВВП РФ, очищенный от сезонности, в III кварта...
    Парсим новость 3: Рубль сильно упал к доллару и евро в среду в ожида...
72 новостей (всего: 13268)
[259/1298] 2022-12-15:     Парсим новость 1: СТГТ нужны технологические партнеры для производст...
    Парсим новость 2: Фондовые рынки Европы упали на итогах заседаний ЕЦ...
    Парсим новость 3: Ericsson ускорит сокращение расходов на фоне нулев...
75 новостей (всего: 13343)
[260/1298] 2022-12-16:     Парсим новость 1: Байден одобрил продление финансирования правительс...
    Парсим новость 2: Болгария, Венгрия и Словакия смогут экспортировать...
    Парсим новость 3: Минтруд РФ установил размер прожиточного минимума ...
89 новостей (всего: 13432)
[261/1298] 2022-12-17:     Парсим новость 1: Первый плавучий СПГ-терминал заработал в ФРГ...
    Парсим новость 2: "ЛУКОЙЛ" запланировал расширить присутствие в Егип...
    Парсим новость 3: Более 14 млн тонн продовольствия экспортировали из...
3 новостей (всего: 13435)
[262/1298] 2022-12-18: 0 новостей
[263/1298] 2022-12-19:     Парсим новость 1: Лукашенко сообщил, что Белоруссия согласовала с РФ...
    Парсим новость 2: РФ и Белоруссия согласовали все основные параметры...
    Парсим новость 3: АСВ продлило действие нулевых ставок дополнительны...
58 новостей (всего: 13493)
[264/1298] 2022-12-20:     Парсим новость 1: НРД подтвердил получение генлицензии Минфина Люксе...
    Парсим новость 2: Средства юрлиц в российских банках в ноябре выросл...
    Парсим новость 3: Банк России отметил ускорение ипотеки в ноябре поч...
67 новостей (всего: 13560)
[265/1298] 2022-12-21:     Парсим новость 1: В США уточнили, что купленные до price cap нефтепр...
    Парсим новость 2: Минпромторг намерен смягчить условия доступа проду...
    Парсим новость 3: Рубль завершил торги среды на минимумах с апреля к...
72 новостей (всего: 13632)
[266/1298] 2022-12-22:     Парсим новость 1: Акционеры "Яндекса" переизбрали трех независимых д...
    Парсим новость 2: Сенат США одобрил проект бюджета в $1,7 трлн на 20...
    Парсим новость 3: НРД получил лицензию Минфина Бельгии на разблокиро...
76 новостей (всего: 13708)
[267/1298] 2022-12-23:     Парсим новость 1: Российские регионы довели до аграриев 96,3% федера...
    Парсим новость 2: Рубль по итогам пятницы не сохранил рост и упал к ...
    Парсим новость 3: Eni начинает строительство второй плавучей СПГ уст...
64 новостей (всего: 13772)
[268/1298] 2022-12-24:     Парсим новость 1: "Татнефть" запустила вторую очередь комплекса аром...
    Парсим новость 2: Премьер Белоруссии ждет экспорта в РФ на уровне $2...
    Парсим новость 3: НРД определил порядок работы по разблокировке акти...
3 новостей (всего: 13775)
[269/1298] 2022-12-25:     Парсим новость 1: В Турции заявили о вывозе из Украины более 15 млн ...
    Парсим новость 2: В США на фоне зимнего шторма зафиксирован рекордны...
2 новостей (всего: 13777)
[270/1298] 2022-12-26:     Парсим новость 1: Депозитарий НРД будет принимать документы для разб...
    Парсим новость 2: В ЦБ в феврале изучат фактор повышения оценки дефи...
    Парсим новость 3: ЦБ в феврале может сузить прогноз по динамике ВВП ...
52 новостей (всего: 13829)
  -> Сохранено во временный файл
[271/1298] 2022-12-27:     Парсим новость 1: "Газпром нефть" без аукциона получила Салетинский ...
    Парсим новость 2: В РФ с 1 января 2023 года повысят минимальные цены...
    Парсим новость 3: Новым партнером Троценко по "Воркутауглю" стала ко...
80 новостей (всего: 13909)
[272/1298] 2022-12-28:     Парсим новость 1: Главы МИД РФ и Саудовской Аравии обсудили взаимоде...
    Парсим новость 2: ЦБ выявил недобросовестные практики в страховании ...
    Парсим новость 3: Рубль заметно упал к доллару и евро по итогам сред...
70 новостей (всего: 13979)
[273/1298] 2022-12-29:     Парсим новость 1: "Ведомости" сообщили о предложении повысить предел...
    Парсим новость 2: ЦБ до апреля не будет применять меры к банкам, не ...
    Парсим новость 3: Топ-менеджеры "Системы" по программе мотивации пол...
60 новостей (всего: 14039)
[274/1298] 2022-12-30:     Парсим новость 1: Правительство РФ утвердило изменения взаимных пост...
    Парсим новость 2: Иностранные покупатели "Газпрома", отказавшиеся от...
    Парсим новость 3: Автопрому РФ нужны 300 млрд руб. на локализацию кр...
47 новостей (всего: 14086)
[275/1298] 2022-12-31:     Парсим новость 1: Азербайджан за два года поставил в Европу почти 20...
    Парсим новость 2: На вывоз из РФ отходов и лома черных металлов за п...
    Парсим новость 3: В план дорожного строительства до 2027 года включи...
5 новостей (всего: 14091)
[276/1298] 2023-01-01:     Парсим новость 1: Банки РФ с 2023 года начнут выходить из регулятивн...
    Парсим новость 2: Запрет на раскрытие информации для банков в РФ сме...
    Парсим новость 3: Расширен перечень налоговых льгот для резидентов С...
9 новостей (всего: 14100)
[277/1298] 2023-01-02:     Парсим новость 1: "РусХимАльянс" инициирует арбитраж в отношении Lin...
    Парсим новость 2: Экспорт газа РФ в Китай вышел на новый уровень сог...

2 новостей (всего: 14102)
[278/1298] 2023-01-03:     Парсим новость 1: Рубль упал к доллару и евро по итогам первых торго...
    Парсим новость 2: Рынок акций РФ начал торговый год с роста выше 217...
    Парсим новость 3: Рынки акций Европы растут во вторник...
20 новостей (всего: 14122)
[279/1298] 2023-01-04:     Парсим новость 1: Рубль подешевел к доллару, евро и юаню на фоне пад...
    Парсим новость 2: Снижение рынка акций РФ вслед за нефтью сдерживало...
    Парсим новость 3: Объем торгов драгметаллами на Мосбирже в декабре 2...
18 новостей (всего: 14140)
[280/1298] 2023-01-05:     Парсим новость 1: Рубль к концу торгов четверга перешел к снижению...
    Парсим новость 2: Рынок акций РФ в четверг скорректировался вниз всл...
    Парсим новость 3: Американские фондовые индексы снижаются...
17 новостей (всего: 14157)
[281/1298] 2023-01-06:     Парсим новость 1: Рубль слегка укрепился к доллару и евро на фоне по...
    Парсим новость 2: Рынок акций РФ в пятницу консолидировался при смеш...
    Парсим новость 3: Европейские акции растут на данных о замедлении ин...
18 новостей (всего: 14175)
[282/1298] 2023-01-07:     Парсим новость 1: ВТБ обратился за лицензией на разблокировку активо...
    Парсим новость 2: Джек Ма лишится контроля над Ant Group...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/879806 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176E0FAA20>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
2 новостей (всего: 14177)
[283/1298] 2023-01-08:     Парсим новость 1: Босфор временно закрыли для судоходства из-за тума...
    Парсим новость 2: Более 12 тысяч тонн подсолнечного масла из Украины...
2 новостей (всего: 14179)
[284/1298] 2023-01-09:     Парсим новость 1: Золото подорожало до максимума с мая на фоне паден...
    Парсим новость 2: Финляндия не намерена запрещать работу российского...
    Парсим новость 3: Цена газа в Европе впервые в новом году превысила ...
50 новостей (всего: 14229)
[285/1298] 2023-01-10:     Парсим новость 1: Минэнерго США резко понизило прогноз цены Brent на...
    Парсим новость 2: Boeing в 2022 году увеличил поставки коммерческих ...
    Парсим новость 3: Рубль слабо изменился к бивалютной корзине на фоне...
62 новостей (всего: 14291)
[286/1298] 2023-01-11:     Парсим новость 1: "Газпром" сообщил CNPC, что работа по поставкам с ...
    Парсим новость 2: Дочернее предприятие "Аэрофлота" "А-Техникс" в 202...
    Парсим новость 3: Рубль укрепился к основным валютам по итогам среды...
60 новостей (всего: 14351)
[287/1298] 2023-01-12:     Парсим новость 1: Минсельхоз США сохранил прогноз экспорта пшеницы и...
    Парсим новость 2: ТВК "Авиапарк" намерен инициировать банкротство со...
    Парсим новость 3: Рубль в четверг укрепился к основным мировым валют...
60 новостей (всего: 14411)
[288/1298] 2023-01-13:     Парсим новость 1: "Мегафон" приобрел разработчика билинговых систем ...
    Парсим новость 2: Замглавы МИД РФ обсудил с генсеком ЮНКТАД изъятие ...
    Парсим новость 3: Дорожающее золото может завершить сессию выше $190...
76 новостей (всего: 14487)
[289/1298] 2023-01-14:     Парсим новость 1: Министр энергетики Катара предположил, что газ РФ ...
    Парсим новость 2: "Победа" уточнит правила провоза ручной клади посл...
    Парсим новость 3: 12 судов доставят украинское продовольствие в Кита...
4 новостей (всего: 14491)
[290/1298] 2023-01-15:     Парсим новость 1: Белоруссия планирует получить от РФ около $650 млн...
    Парсим новость 2: Белорусский минфин намерен договориться с РФ о реф...
    Парсим новость 3: Путин заявил, что инфляция в РФ по итогам I кварта...
4 новостей (всего: 14495)
[291/1298] 2023-01-16:     Парсим новость 1: Медиа-права на трансляцию Олимпийских игр в Европе...
    Парсим новость 2: Комитет Думы одобрил поправки для соглашений о сер...
    Парсим новость 3: AliExpres разрешит европейским клиентам платить за...
60 новостей (всего: 14555)
[292/1298] 2023-01-17:     Парсим новость 1: Wintershall Dea заявила о намерении уйти из РФ пос...
    Парсим новость 2: Цены на дома в Великобритании могут упасть на 10% ...
    Парсим новость 3: "1С" подтвердила утечку данных пользователей своег...
64 новостей (всего: 14619)
[293/1298] 2023-01-18:     Парсим новость 1: Принадлежащие "Росгеологии" 38% акций "Самаранефте...
    Парсим новость 2: Рубль в среду подрос к доллару и евро на фоне акти...
    Парсим новость 3: Инфляция в РФ с 10 по 16 января составила 0,15%...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /world/881151 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A3C6F90>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
72 новостей (всего: 14691)
[294/1298] 2023-01-19:     Парсим новость 1: "КАМАЗ" поставил в Туркменистан два электробуса со...
    Парсим новость 2: Баку запланировал к 2027 году увеличить экспорт га...
    Парсим новость 3: "Автодор" хочет построить трассу-дублер Джубга-Соч...
77 новостей (всего: 14768)
[295/1298] 2023-01-20:     Парсим новость 1: Рубль развернулся вниз к доллару и евро к закрытию...
    Парсим новость 2: Цены на нефть замедлили рост до минимума, но завер...
    Парсим новость 3: Рынок акций РФ в пятницу консолидировался на смеша...
63 новостей (всего: 14831)
[296/1298] 2023-01-21:     Парсим новость 1: Менеджмент "Норникеля" предложил направить на диви...
    Парсим новость 2: Голикова заявила, что уровень регистрируемой безра...
    Парсим новость 3: Сбербанк установил банкоматы в Ялте, Севастополе и...
3 новостей (всего: 14834)
[297/1298] 2023-01-22:     Парсим новость 1: Посол Алжира заявил, что Италия может стать хабом ...
1 новостей (всего: 14835)
[298/1298] 2023-01-23:     Парсим новость 1: Microsoft вложит несколько миллиардов долларов в р...
    Парсим новость 2: Цена Brent превысила $89 за баррель впервые с 1 де...
    Парсим новость 3: SEC оштрафовала Bloomberg на $5 млн за нарушения в...
57 новостей (всего: 14892)
[299/1298] 2023-01-24:     Парсим новость 1: РФ продлила право "Газпрома" на газ "Сахалина-2" к...
    Парсим новость 2: Телеком-оператор Truphone, доля в котором принадле...
    Парсим новость 3: Рубль снизился к доллару и евро по итогам вторника...
56 новостей (всего: 14948)
[300/1298] 2023-01-25:     Парсим новость 1: Министр экономики ФРГ спрогнозировал рост ВВП Герм...
    Парсим новость 2: РФ предложила сформировать общий добровольный рыно...
    Парсим новость 3: Рубль упал к доллару и евро по итогам торгов среды...
63 новостей (всего: 15011)
  -> Сохранено во временный файл
[301/1298] 2023-01-26:     Парсим новость 1: Дочь Назарбаева с мужем могут продать миноритарную...
    Парсим новость 2: Финтех-стартап Stripe может выйти на открытый рыно...
    Парсим новость 3: Кредит Европа банк получил разрешение на покупку д...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/883432 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A255DF0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
68 новостей (всего: 15079)
[302/1298] 2023-01-27:     Парсим новость 1: Золото стабилизировалось, взяв паузу после 17%-ног...
    Парсим новость 2: Рубль немного подешевел к доллару и евро перед вых...
    Парсим новость 3: Toyota отзовет в РФ 8,3 тысяч Lexus в рамках второ...
78 новостей (всего: 15157)
[303/1298] 2023-01-28:     Парсим новость 1: Eni подписала соглашение об участии в разработке л...
    Парсим новость 2: В G7 сочли приемлемым потолок цен на дизтопливо из...
    Парсим новость 3: "Газпромбанк Инвестиции" отрицает утечку данных св...
3 новостей (всего: 15160)
[304/1298] 2023-01-29: 0 новостей
[305/1298] 2023-01-30:     Парсим новость 1: РФ и Китай подготовили соглашение о поставках газа...
    Парсим новость 2: Мишустин подписал постановление во исполнение указ...
    Парсим новость 3: ICE запустит параллельный газовый хаб в Лондоне дл...
62 новостей (всего: 15222)
[306/1298] 2023-01-31:     Парсим новость 1: Суд удовлетворил иск банка "Санкт-Петербург" к Eur...

    Парсим новость 2: Глобальный рынок сервисных услуг для энергетическо...
    Парсим новость 3: Рубль дорожает к доллару и евро на фоне перешедшей...
91 новостей (всего: 15313)
[307/1298] 2023-02-01:     Парсим новость 1: Инфляция в США остается выше долгосрочного целевог...
    Парсим новость 2: ФРС ожидаемо подняла ставку на 25 б.п., ждет дальн...
    Парсим новость 3: Поймай меня, если сможешь – наладить контроль за п...
84 новостей (всего: 15397)
[308/1298] 2023-02-02:     Парсим новость 1: Внешнеторговый оборот Белоруссии и России по итога...
    Парсим новость 2: "Газпром" в ближайшие дни начнет строительство зав...
    Парсим новость 3: De Beers в 2022 г. увеличила добычу на 7% и в 2023...
75 новостей (всего: 15472)
[309/1298] 2023-02-03:     Парсим новость 1: Avito через суд потребовала от топ-менеджеров порт...
    Парсим новость 2: "АвтоВАЗ" предложил активнее субсидировать легковы...
    Парсим новость 3: CEO Volkswagen назвал Китай самым важным рынком дл...
72 новостей (всего: 15544)
[310/1298] 2023-02-04:     Парсим новость 1: Минфин РФ объяснил провал по исполнению доходов в ...
    Парсим новость 2: Хорватия и Болгария смогут импортировать нефтепрод...
    Парсим новость 3: Совет ЕС утвердил потолок цен на нефтепродукты из ...
7 новостей (всего: 15551)
[311/1298] 2023-02-05: 0 новостей
[312/1298] 2023-02-06:     Парсим новость 1: Bank of America улучшил прогноз роста мировой экон...
    Парсим новость 2: Россия планирует продлить запрет на экспорт рапса ...
    Парсим новость 3: Китайские ритейлеры снизили цены на последние моде...
84 новостей (всего: 15635)
[313/1298] 2023-02-07:     Парсим новость 1: "Газпром" и "Газпром трансгаз Беларусь" продлили к...
    Парсим новость 2: Глава ФРС заявил, что замедление инфляции в США за...
    Парсим новость 3: Минэнерго США повысило прогноз добычи нефти в РФ н...
68 новостей (всего: 15703)
[314/1298] 2023-02-08:     Парсим новость 1: Бюджетное финансирование нацпроектов в январе отст...
    Парсим новость 2: Бизнесу со сверхдоходами предложили сделать разовы...
    Парсим новость 3: "Газпром трансгаз НН" возглавил менеджер головной ...
99 новостей (всего: 15802)
[315/1298] 2023-02-09:     Парсим новость 1: Toshiba подтвердила получение предложения о покупк...
    Парсим новость 2: Производитель кукол Барби в IV квартале снизил чис...
    Парсим новость 3: Exxon Mobil продолжит сокращать расходы, планирует...
74 новостей (всего: 15876)
[316/1298] 2023-02-10:     Парсим новость 1: Мосбиржа ограничила максимальное отклонение цен за...
    Парсим новость 2: Авдолян и Исаев разделили долю Адоньева в компании...
    Парсим новость 3: Заявление Банка России: ЦБ заглянул в будущее ужес...
104 новостей (всего: 15980)
[317/1298] 2023-02-11:     Парсим новость 1: Взлет малоликвидных акций не должен вводить в иску...
1 новостей (всего: 15981)
[318/1298] 2023-02-12:     Парсим новость 1: Топ-менеджеры нефтяных компаний России согласовали...
    Парсим новость 2: Ущерб экономике Турции от землетрясений может прев...
    Парсим новость 3: Кабмин РФ разработал законопроект, меняющий расчет...
4 новостей (всего: 15985)
[319/1298] 2023-02-13:     Парсим новость 1: Правительство выдвинуло сотрудника РАНХиГС в совет...
    Парсим новость 2: Британский фондовый индекс FTSE 100 обновил рекорд...
    Парсим новость 3: Крупнейшие аэропорты Германии в 2022 году удвоили ...
61 новостей (всего: 16046)
[320/1298] 2023-02-14:     Парсим новость 1: Денежная база РФ в широком определении в январе ум...
    Парсим новость 2: Рубль слегка подрос к доллару и немного ослаб к ев...
    Парсим новость 3: Минэкономразвития может улучшить в апреле ряд пока...
75 новостей (всего: 16121)
[321/1298] 2023-02-15:     Парсим новость 1: Президент Всемирного банка сообщил о намерении пок...
    Парсим новость 2: Фондовые индексы Европы завершили торги ростом, бр...
    Парсим новость 3: Участники рынка спрогнозировали снижение цен на ог...
93 новостей (всего: 16214)
[322/1298] 2023-02-16:     Парсим новость 1: "Лузалес" возобновит 100% производства на заводах ...
    Парсим новость 2: В Саудовской Аравии заявили, что панические оценки...
    Парсим новость 3: В Думу внесен проект об оборотных штрафах IT-компа...
84 новостей (всего: 16298)
[323/1298] 2023-02-17:     Парсим новость 1: Президент РФ разрешил "Газпром нефти" приобрести д...
    Парсим новость 2: Путин дал разрешение на реорганизацию дочерних бан...
    Парсим новость 3: Путин разрешил "Компании ВК" приобрести 100% долей...
73 новостей (всего: 16371)
[324/1298] 2023-02-18: 0 новостей
[325/1298] 2023-02-19:     Парсим новость 1: США планируют новые санкции против РФ в сферах обо...
    Парсим новость 2: "Газпром" в ближайшее время начнет строительство н...
2 новостей (всего: 16373)
[326/1298] 2023-02-20:     Парсим новость 1: Структуры "Росатома", "Роснано" и ГПБ учредили сою...
    Парсим новость 2: Ценовые ожидания предприятий РФ в феврале снижалис...
    Парсим новость 3: Банки РФ в январе увеличили чистую прибыль в 1,5 р...
62 новостей (всего: 16435)
[327/1298] 2023-02-21:     Парсим новость 1: Freeport LNG получила разрешение на запуск двух СП...
    Парсим новость 2: "Норникель" отправил много проектов на перепроекти...
    Парсим новость 3: Рубль во вторник подешевел к доллару и евро в ожид...
67 новостей (всего: 16502)
[328/1298] 2023-02-22:     Парсим новость 1: Перевалка нефти на морском терминале КТК возобновл...
    Парсим новость 2: Банк России не разрешил белорусскому брокеру запус...
    Парсим новость 3: Совет директоров "Россетей" утвердил правительстве...
78 новостей (всего: 16580)
[329/1298] 2023-02-23:     Парсим новость 1: Байден выдвинул бизнесмена Аджая Бангу на пост пре...
    Парсим новость 2: Казахстан начал транспортировку нефти для экспорта...
    Парсим новость 3: Минэнерго Белоруссии создало оператора по обращени...
3 новостей (всего: 16583)
[330/1298] 2023-02-24:     Парсим новость 1: Канада ввела новые санкции против России...
    Парсим новость 2: "Мегафон" не исключил, что оспорит включение в спи...
    Парсим новость 3: Постпреды ЕС снова не смогли согласовать новый пак...
22 новостей (всего: 16605)
  -> Сохранено во временный файл
[331/1298] 2023-02-25:     Парсим новость 1: ЕС включил в санкционный список ФНБ, Альфа-банк, Р...
    Парсим новость 2: Суд удовлетворил иск Сбербанка о взыскании с "дочк...
    Парсим новость 3: Банк "Приморье" предупредил о возможной блокировке...
7 новостей (всего: 16612)
[332/1298] 2023-02-26:     Парсим новость 1: "Тинькофф инвестиции" приостанавливает торговлю ин...
    Парсим новость 2: Минфин РФ заявил, что санкции против ФНБ не отразя...
2 новостей (всего: 16614)
[333/1298] 2023-02-27:     Парсим новость 1: Лукашенко предложил объединить промышленную полити...
    Парсим новость 2: Портфель займов МФО в 2022 году вырос на 11% - до ...
    Парсим новость 3: Что произошло за день: понедельник, 27 февраля...
65 новостей (всего: 16679)
[334/1298] 2023-02-28:     Парсим новость 1: Названы победители XVII Национальной премии "Дирек...
    Парсим новость 2: Мосбиржа с 6 марта обновит правила листинга...
    Парсим новость 3: Цены на зерно в РФ ускорили снижение...
87 новостей (всего: 16766)
[335/1298] 2023-03-01:     Парсим новость 1: Цены экспорта нефти в рамках price cap будут монит...
    Парсим новость 2: В ОЗК заявили о необходимости некоторой корректиро...
    Парсим новость 3: Минсельхоз назвал стабильной ценовую ситуацию на р...
68 новостей (всего: 16834)
[336/1298] 2023-03-02:     Парсим новость 1: МИД РФ заявил, что "зерновая сделка" не работает и...
    Парсим новость 2: Силуанов заявил, что концепция windfall tax "детал...
    Парсим новость 3: В бюджет РФ в январе-феврале поступило налогов бол...
86 новостей (всего: 16920)
[337/1298] 2023-03-03:     Парсим новость 1: В Евросоюзе сообщили о значительном сокращении тор...
    Парсим новость 2: Чистая прибыль "Синара-ТМ" по РСБУ снизилась в 202...
    Парсим новость 3: "Газпром нефть" закрыла сделку по выкупу доли Shel...
62 новостей (всего: 16982)
[338/1298] 2023-03-04:     Парсим новость 1: Годовой план производства белорусско-китайских Gee...
    Парсим новость 2: Росфинмониторинг хочет установить лимит в 100 тыс....
2 новостей (всего: 16984)

[339/1298] 2023-03-05:     Парсим новость 1: АФК "Система" не будет покупать 47,7% ритейлера Me...
    Парсим новость 2: В МИД Турции сообщили о работе Анкары над продлени...
2 новостей (всего: 16986)
[340/1298] 2023-03-06:     Парсим новость 1: Российское юрлицо VK выкупило 100% "Деньги.Мэйл.Ру...
    Парсим новость 2: Экспорт угля из РФ по сети РЖД вырос в феврале на ...
    Парсим новость 3: Вознаграждение ключевых управленцев ГК "Русагро" в...
70 новостей (всего: 17056)
[341/1298] 2023-03-07:     Парсим новость 1: США повысили оценку добычи нефти в РФ в 2023 г. на...
    Парсим новость 2: Минэнерго США понизило прогноз цены Brent на 2023 ...
    Парсим новость 3: Рубль во вторник ускорил снижение к доллару и умер...
62 новостей (всего: 17118)
[342/1298] 2023-03-08:     Парсим новость 1: Генсек ООН пообещал содействовать беспрепятственно...
    Парсим новость 2: Минсельхоз США сохранил прогноз экспорта пшеницы и...
    Парсим новость 3: ВТБ из-за санкций может продать дочерний банк в Ан...
3 новостей (всего: 17121)
[343/1298] 2023-03-09:     Парсим новость 1: Тинькофф банк отменил выплату купона по еще одному...
    Парсим новость 2: США внесли в "черный список" 39 предприятий сети и...
    Парсим новость 3: Рубль немного укрепился к доллару и евро по итогам...
78 новостей (всего: 17199)
[344/1298] 2023-03-10:     Парсим новость 1: Meta задумала создать соцсеть, похожую на Twitter...
    Парсим новость 2: Канада запретит импорт из России алюминия и продук...
    Парсим новость 3: Молдавия в феврале сократила потребление газа на т...
68 новостей (всего: 17267)
[345/1298] 2023-03-11:     Парсим новость 1: "Газпрому" в ближайшие 6 лет потребуется 4,5 тыс. ...
    Парсим новость 2: Сбор зерна в РФ в 2022 году вырос на 29,9% по срав...
    Парсим новость 3: Болгария готова транспортировать дополнительные об...
4 новостей (всего: 17271)
[346/1298] 2023-03-12: 0 новостей
[347/1298] 2023-03-13:     Парсим новость 1: Доходность госбумаг по всему миру продолжает падат...
    Парсим новость 2: Фондовые индексы Европы упали до уровней января вс...
    Парсим новость 3: ЕЦБ аннулировал лицензию Baltic International Bank...
63 новостей (всего: 17334)
[348/1298] 2023-03-14:     Парсим новость 1: МИД РФ раскритиковал высказывания чиновников США и...
    Парсим новость 2: Новак оценил потребность Сибири в новых энергомощн...
    Парсим новость 3: Европарламент одобрил обновленный регламент ЕС по ...
62 новостей (всего: 17396)
[349/1298] 2023-03-15:     Парсим новость 1: Минпромторг РФ предложил упростить при госзакупках...
    Парсим новость 2: TCS Group продлевает паузу в выплате дивидендов...
    Парсим новость 3: Рубль завершил торги среды без изменений к бивалют...
77 новостей (всего: 17473)
[350/1298] 2023-03-16:     Парсим новость 1: Законопроект о продаже пива на АЗС отозван автором...
    Парсим новость 2: Glencore не хочет продлевать истекающий в 2024 год...
    Парсим новость 3: "Совкомфлот" в 2022 году увеличил чистую прибыль п...
85 новостей (всего: 17558)
[351/1298] 2023-03-17:     Парсим новость 1: Россвифт сменит название и расширит деятельность...
    Парсим новость 2: Заявление Банка России: На денежно-кредитном фронт...
    Парсим новость 3: Проект терминала по перевалке аммиака в Тамани под...
107 новостей (всего: 17665)
[352/1298] 2023-03-18: 0 новостей
[353/1298] 2023-03-19:     Парсим новость 1: Путин уверен, что торговый оборот РФ и КНР превыси...
    Парсим новость 2: Костин заявил, что ВТБ ждет рекордной прибыли в I ...
2 новостей (всего: 17667)
[354/1298] 2023-03-20:     Парсим новость 1: Нацбанк Молдавии снизил базовую ставку с 17% до 14...
    Парсим новость 2: Руководство Евросоюза обсудит увеличение Европейск...
    Парсим новость 3: ЦБ определил для депозитариев порядок возврата рос...
78 новостей (всего: 17745)
[355/1298] 2023-03-21:     Парсим новость 1: Банки РФ в феврале получили прибыль в размере 293 ...
    Парсим новость 2: Рост средств юрлиц в банках РФ в феврале замедлилс...
    Парсим новость 3: Корпоративные кредиты в РФ в феврале выросли на 1,...
69 новостей (всего: 17814)
[356/1298] 2023-03-22:     Парсим новость 1: Глава ФРС заявил, что  реагировать изменением став...
    Парсим новость 2: ФРС ухудшила прогноз роста ВВП США и повысила оцен...
    Парсим новость 3: ФРС ожидаемо подняла ставку на 25 б.п., отметив ус...
66 новостей (всего: 17880)
[357/1298] 2023-03-23:     Парсим новость 1: ВТБ запланировал выплаты по евробондам, учитываемы...
    Парсим новость 2: Чистая прибыль банка "Санкт-Петербург" по МСФО в 2...
    Парсим новость 3: ЦБ продлил ограничения на переводы за рубеж средст...
63 новостей (всего: 17943)
[358/1298] 2023-03-24:     Парсим новость 1: Восточный экономический форум во Владивостоке пере...
    Парсим новость 2: "Совкомфлот" в апреле досрочно погасит "замещающие...
    Парсим новость 3: IKEA продала свою последнюю мебельную фабрику в РФ...
67 новостей (всего: 18010)
[359/1298] 2023-03-25:     Парсим новость 1: Путин назвал ошибочным решение США избирательно ог...
1 новостей (всего: 18011)
[360/1298] 2023-03-26:     Парсим новость 1: Белоруссия намерена добиваться равных с РФ условий...
    Парсим новость 2: Шинный завод Nokian Tyres в Ленобласти перешел в с...
2 новостей (всего: 18013)
  -> Сохранено во временный файл
[361/1298] 2023-03-27:     Парсим новость 1: Экспортные цены на российскую пшеницу снизились до...
    Парсим новость 2: Американской International Paper разрешили продать...
    Парсим новость 3: Еврокомиссия потребовала взыскать с Alitalia незак...
75 новостей (всего: 18088)
[362/1298] 2023-03-28:     Парсим новость 1: Министры энергетики стран ЕС согласовали позицию п...
    Парсим новость 2: OFSI разрешило реструктуризацию бондов с санкционн...
    Парсим новость 3: Операционная "дочка" "Глории Джинс" в 2022 году по...
68 новостей (всего: 18156)
[363/1298] 2023-03-29:     Парсим новость 1: Производство 90% закупаемых за рубежом лекарств на...
    Парсим новость 2: Собянин заявил, что экономика Москвы оказалась уст...
    Парсим новость 3: Спад ВВП России в феврале замедлился с 3,2% до 3,1...
74 новостей (всего: 18230)
[364/1298] 2023-03-30:     Парсим новость 1: Винодельческий проект семьи Ткачева в Геленджике в...
    Парсим новость 2: Крупнейшие банки Китая увеличили чистую прибыль в ...
    Парсим новость 3: Сводный фондовый индекс Европы обновил максимум за...
70 новостей (всего: 18300)
[365/1298] 2023-03-31:     Парсим новость 1: ЕК расширит ценовой "потолок" на газ на все хабы Е...
    Парсим новость 2: МВФ утвердил новую программу для Украины на $15,6 ...
    Парсим новость 3: Пять стран ЕС призвали Еврокомиссию купить скопивш...
57 новостей (всего: 18357)
[366/1298] 2023-04-01:     Парсим новость 1: Fitch ожидает рост ВВП Азербайджана в 2023-2024 гг...
    Парсим новость 2: Fitch подтвердило рейтинг Азербайджана на уровне "...
    Парсим новость 3: Обязательная маркировка пива и слабоалкогольных на...
4 новостей (всего: 18361)
[367/1298] 2023-04-02:     Парсим новость 1: Ряд стран ОПЕК+ с мая по конец 2023 г. добровольно...
    Парсим новость 2: РФ продлит решение о снижении нефтедобычи на 500 т...
    Парсим новость 3: Эр-Рияд и еще несколько участников ОПЕК+ дополните...
4 новостей (всего: 18365)
[368/1298] 2023-04-03:     Парсим новость 1: Цена сахара в США выросла до максимума за шесть ле...
    Парсим новость 2: Brent может подорожать к лету до $100 на фоне сокр...
    Парсим новость 3: General Motors в I квартале увеличил продажи автом...
72 новостей (всего: 18437)
[369/1298] 2023-04-04:     Парсим новость 1: Золото обновило годовые максимумы на слабых статда...
    Парсим новость 2: Рубль упал к основным валютам по итогам вторника...
    Парсим новость 3: В JPMorgan считают, что фондовый рынок США вступил...
60 новостей (всего: 18497)
[370/1298] 2023-04-05:     Парсим новость 1: Трейдер Gunvor увеличил годовую чистую прибыль бол...
    Парсим новость 2: Резидентам САР пообещали больше инструментов инвес...
    Парсим новость 3: Белый дом покинул экономический советник, разрабат...
82 новостей (всего: 18579)
[371/1298] 2023-04-06:     Парсим новость 1: "СИБУР" продлил до конца апреля предложение о выку...
    Парсим новость 2: Рубль в четверг обновил валютные минимумы почти за...

    Парсим новость 3: ВБ улучшил прогноз для экономики РФ на 2023 год и ...
76 новостей (всего: 18655)
[372/1298] 2023-04-07:     Парсим новость 1: В Минске сообщили, что годовой российско-белорусск...
    Парсим новость 2: МосБиржа намерена увеличить период расчета валютны...
    Парсим новость 3: Рубль завершил торги пятницы небольшим повышением ...
74 новостей (всего: 18729)
[373/1298] 2023-04-08:     Парсим новость 1: Сотрудники Tesla годами пересылали друг другу виде...
    Парсим новость 2: В марте число нефтегазовых буровых в мире снизилос...
2 новостей (всего: 18731)
[374/1298] 2023-04-09:     Парсим новость 1: Посол Белоруссии заявил, что страна начнет получат...
    Парсим новость 2: Чистая прибыль ЮТэйр по РСБУ выросла в 2022г на 6%...
2 новостей (всего: 18733)
[375/1298] 2023-04-10:     Парсим новость 1: АФК "Система" готовится продать люксембургский Eas...
    Парсим новость 2: МТС-банк подал лицензию на перевод в юрисдикцию РФ...
    Парсим новость 3: Дружественные нерезиденты в марте сократили продаж...
57 новостей (всего: 18790)
[376/1298] 2023-04-11:     Парсим новость 1: Доля внутреннего производства автоэлектроники в РФ...
    Парсим новость 2: Минэнерго США сохранило прогноз потребления нефти ...
    Парсим новость 3: Минэнерго США повысило оценку нефтедобычи в России...
70 новостей (всего: 18860)
[377/1298] 2023-04-12:     Парсим новость 1: Выручка LVMH в I квартале выросла на 17%, сильнее ...
    Парсим новость 2: Рубль развернулся вверх к доллару и снизился к евр...
    Парсим новость 3: Страны G7 готовятся ввести санкции в отношении час...
63 новостей (всего: 18923)
[378/1298] 2023-04-13:     Парсим новость 1: "Система" 14 мая уйдет с LSE в связи с истечением ...
    Парсим новость 2: Рубль завершил торги четверга разнонаправленной ди...
    Парсим новость 3: Рынок акций РФ в четверг провел торги в консолидац...
77 новостей (всего: 19000)
[379/1298] 2023-04-14:     Парсим новость 1: Совет директоров МТС рассмотрит вопрос о снижении ...
    Парсим новость 2: Минэкономразвития улучшило оценки снижения ВВП РФ ...
    Парсим новость 3: Свинина из РФ в I квартале поставлялась в 11 стран...
89 новостей (всего: 19089)
[380/1298] 2023-04-15:     Парсим новость 1: Эксперимент по маркировке икры пройдет в РФ с 15 а...
    Парсим новость 2: Силуанов освобожден от исполнения обязанностей пол...
2 новостей (всего: 19091)
[381/1298] 2023-04-16:     Парсим новость 1: В Думу внесен законопроект, которым дисконт Urals ...
    Парсим новость 2: Иран и Венесуэла договорились усилить сотрудничест...
    Парсим новость 3: Министры G7 на переговорах в Японии не смогли дого...
3 новостей (всего: 19094)
[382/1298] 2023-04-17:     Парсим новость 1: Польша ждет гарантий, что украинская агропродукция...
    Парсим новость 2: Петербург объявил повторный конкурс на поставку 22...
    Парсим новость 3: Финансовая компания Charles Schwab увеличила кварт...
57 новостей (всего: 19151)
[383/1298] 2023-04-18:     Парсим новость 1: Аналитики ЦБ РФ увидели дилемму для денежно-кредит...
    Парсим новость 2: Олово подорожало до максимума за 8 недель из-за за...
    Парсим новость 3: Аналитики ЦБ отметили, что ВВП РФ сохраняет динами...
71 новостей (всего: 19222)
[384/1298] 2023-04-19:     Парсим новость 1: Выручка российской "дочки" UnionPay по РСБУ в 2022...
    Парсим новость 2: Санкт-Петербургская биржа по внебиржевым данным ви...
    Парсим новость 3: ЦБ прогнозирует сбор 130-145 млн т зерна в России ...
76 новостей (всего: 19298)
[385/1298] 2023-04-20:     Парсим новость 1: Запас рублевой ликвидности банков РФ в марте снизи...
    Парсим новость 2: Банки РФ в марте заработали 330 млрд рублей чистой...
    Парсим новость 3: Темпы роста ипотеки в марте ускорились до 2,1% и п...
92 новостей (всего: 19390)
[386/1298] 2023-04-21:     Парсим новость 1: Минфин и ЦБ задумались о снижении долгосрочных про...
    Парсим новость 2: Lyft планирует значительное сокращение рабочих мес...
    Парсим новость 3: Росбанк может направить на дивиденды свыше 50% от ...
99 новостей (всего: 19489)
[387/1298] 2023-04-22:     Парсим новость 1: Казахстан начал отгрузку своей нефти из Джейхана в...
    Парсим новость 2: Первая партия подпавших под санкции минеральных уд...
    Парсим новость 3: Кабмин дополнительно выделит более 60,5 млрд руб. ...
3 новостей (всего: 19492)
[388/1298] 2023-04-23:     Парсим новость 1: Власти ФРГ увеличат оплату труда более 2,5 млн гос...
1 новостей (всего: 19493)
[389/1298] 2023-04-24:     Парсим новость 1: Петербургские заводы Hyundai, Toyota и Nissan отра...
    Парсим новость 2: Рубль умеренно укрепился к основным валютам в поне...
    Парсим новость 3: НЛМК сдвинул на 2024 год сроки ввода электростанци...
72 новостей (всего: 19565)
[390/1298] 2023-04-25:     Парсим новость 1: Росимущество получило во временное управление доли...
    Парсим новость 2: Ozon заплатил 38,6 млрд рублей за выкуп 94% выпуск...
    Парсим новость 3: В ЕК приблизились к решению проблемы скопившейся в...
75 новостей (всего: 19640)
  -> Сохранено во временный файл
[391/1298] 2023-04-26:     Парсим новость 1: Минцифры РФ перезапустит механизм "сквозных проект...
    Парсим новость 2: Выпуск золота в России в марте вырос на 26,5%...
    Парсим новость 3: Universal Music в I квартале увеличила выручку на ...
72 новостей (всего: 19712)
[392/1298] 2023-04-27:     Парсим новость 1: Собянин назвал МНПЗ после модернизации одним из лу...
    Парсим новость 2: В "Руднево" локализуют производство банкоматов на ...
    Парсим новость 3: Выдвинуты кандидаты в набсовет и ревизионную комис...
84 новостей (всего: 19796)
[393/1298] 2023-04-28:     Парсим новость 1: Заявление Банка России: Калибровка жесткости...
    Парсим новость 2: Выдача ипотечных кредитов в РФ в январе-марте сниз...
    Парсим новость 3: ГК "Монополия" выкупила 75,07% акций Globaltruck з...
117 новостей (всего: 19913)
[394/1298] 2023-04-29: 0 новостей
[395/1298] 2023-04-30: 0 новостей
[396/1298] 2023-05-01:     Парсим новость 1: В Армению приостановлена подача газа из РФ из-за п...
    Парсим новость 2: Казахстанская "КазТрансОйл" повысила тарифы на тра...
    Парсим новость 3: Пошлина на экспорт подсолнечного масла из РФ в мае...
4 новостей (всего: 19917)
[397/1298] 2023-05-02:     Парсим новость 1: ЕК запретила импорт зерна с Украины в Польшу, Венг...
    Парсим новость 2: Минсельхоз РФ уже распределил первые 10 млрд руб. ...
    Парсим новость 3: КТК ввел в работу второе выносное причальное устро...
91 новостей (всего: 20008)
[398/1298] 2023-05-03:     Парсим новость 1: ФРС США будет принимать решения по ДКП в зависимос...
    Парсим новость 2: ФРС США подняла ставку на 25 базисных пунктов...
    Парсим новость 3: Airbus зафиксировала 2%-е снижение выручки в I ква...
83 новостей (всего: 20091)
[399/1298] 2023-05-04:     Парсим новость 1: EBITDA "Мечела" в 2022 году выросла на 5% до $1,8 ...
    Парсим новость 2: Bosch выделит бизнес автокомпонентов в самостоятел...
    Парсим новость 3: Рубль в четверг уверенно укрепился к доллару и евр...
88 новостей (всего: 20179)
[400/1298] 2023-05-05:     Парсим новость 1: Авиакомпании с долей внутренних перевозок менее 70...
    Парсим новость 2: Глава ЮНКТАД Гринспен обсудила в Москве тему экспо...
    Парсим новость 3: L'Oreal четвертый год возглавляет рейтинг самых до...
69 новостей (всего: 20248)
[401/1298] 2023-05-06:     Парсим новость 1: "ГАЗ" подал к Volkswagen новый иск, сумма требован...
    Парсим новость 2: Сбербанк откроет отделение в Севастополе через нес...
    Парсим новость 3: Первое отделение Сбербанка открылось в Крыму...
3 новостей (всего: 20251)
[402/1298] 2023-05-07:     Парсим новость 1: "Ростех" вышел из капитала "АвтоВАЗа", 100% долей ...
1 новостей (всего: 20252)
[403/1298] 2023-05-08:     Парсим новость 1: Рубль в понедельник снизился к основным валютам...
    Парсим новость 2: Рынок акций РФ начал неделю со снижения в преддвер...
    Парсим новость 3: Нефть продолжает активно дорожать, Brent у $76,85 ...
18 новостей (всего: 20270)
[404/1298] 2023-05-09:     Парсим новость 1: Минэнерго США слегка повысило прогнозы добычи нефт...
    Парсим новость 2: США слегка понизили прогноз добычи нефти в стране ...
    Парсим новость 3: Минэнерго США резко понизило прогноз цены Brent на...

6 новостей (всего: 20276)
[405/1298] 2023-05-10:     Парсим новость 1: Дефицит бюджета РФ в январе-апреле составил 3,4 тр...
    Парсим новость 2: Рубль в среду взлетел в основных валютных парах, о...
    Парсим новость 3: Рынок акций РФ в среду поднялся к 2550п по индексу...
83 новостей (всего: 20359)
[406/1298] 2023-05-11:     Парсим новость 1: Акционеры HeadHunter одобрили решение о buyback...
    Парсим новость 2: ЦБ РФ отметил, что доля физлиц в обороте биржевого...
    Парсим новость 3: "Дружественные" нерезиденты в апреле продолжили со...
91 новостей (всего: 20450)
[407/1298] 2023-05-12:     Парсим новость 1: Стратегию ЕАЭС - 2030+ обсудят в рамках II Евразий...
    Парсим новость 2: РМК редомицилировала в РФ компании, владеющие росс...
    Парсим новость 3: ЦБ связал снижение объема продаж экспортной выручк...
72 новостей (всего: 20522)
[408/1298] 2023-05-13:     Парсим новость 1: Авиакомпании РФ попросили освободить их от windfal...
1 новостей (всего: 20523)
[409/1298] 2023-05-14:     Парсим новость 1: Алиев обсудил с Шефчовичем сотрудничество Азербайд...
1 новостей (всего: 20524)
[410/1298] 2023-05-15:     Парсим новость 1: Заявление на взаимозачет активов Сбера с его брита...
    Парсим новость 2: Суд взыскал с OR Group еще 104 млн рублей по иску ...
    Парсим новость 3: "Делимобиль" за 2-3 года планирует повысить рентаб...
58 новостей (всего: 20582)
[411/1298] 2023-05-16:     Парсим новость 1: Курс рубля во вторник обновил минимумы к доллару и...
    Парсим новость 2: Компании техсектора уволили свыше 194 тыс. человек...
    Парсим новость 3: Рынок акций РФ во вторник превысил 2630п по индекс...
63 новостей (всего: 20645)
[412/1298] 2023-05-17:     Парсим новость 1: ЦБ ждет, что ослабление рубля отразится в ценах мн...
    Парсим новость 2: Банк "Зенит" в I квартале получил 1,3 млрд рублей ...
    Парсим новость 3: Газпромбанк в I квартале получил 51,7 млрд рублей ...
76 новостей (всего: 20721)
[413/1298] 2023-05-18:     Парсим новость 1: Скорректированная EBITDA "ФосАгро" в I квартале уп...
    Парсим новость 2: Совет директоров МТС рекомендовал дивиденды по ито...
    Парсим новость 3: Рубль по итогам торгов четверга подешевел к бивалю...
86 новостей (всего: 20807)
[414/1298] 2023-05-19:     Парсим новость 1: Квартальная выручка "МаксимаТелекома" по РСБУ упал...
    Парсим новость 2: В Думу внесены поправки о сохранении льгот на элек...
    Парсим новость 3: "Дочки" РусГидро проведут допэмиссии в пользу мате...
73 новостей (всего: 20880)
[415/1298] 2023-05-20:     Парсим новость 1: В РСТ назвали запуск регулярного авиасообщения с К...
1 новостей (всего: 20881)
[416/1298] 2023-05-21:     Парсим новость 1: Байден исключил объявление дефолта в США...
1 новостей (всего: 20882)
[417/1298] 2023-05-22:     Парсим новость 1: Путин поручил правительству проработать вопрос сни...
    Парсим новость 2: Лимит на покупку валюты для сделок с уходящими из ...
    Парсим новость 3: ЦБ РФ ужесточил ограничения на кредитование заемщи...
61 новостей (всего: 20943)
[418/1298] 2023-05-23:     Парсим новость 1: "Макомнет" консолидировал 100% "МаксимаТелекома"...
    Парсим новость 2: Мосбиржа с 25 мая переведет акции "Магнита" из пер...
    Парсим новость 3: Рубль во вторник не изменился к доллару и евро в о...
65 новостей (всего: 21008)
[419/1298] 2023-05-24:     Парсим новость 1: Рост ипотеки в апреле сохранился около докризисных...
    Парсим новость 2: В ЦБ отметили, что рост экономики РФ продолжается,...
    Парсим новость 3: Рубль завершил среду небольшим повышением к бивалю...
83 новостей (всего: 21091)
[420/1298] 2023-05-25:     Парсим новость 1: Байден сообщил о прогрессе на переговорах по пробл...
    Парсим новость 2: Новак сообщил, что Россия будет придерживаться пре...
    Парсим новость 3: МИД РФ заявил о поиске альтернатив "зерновой сделк...
81 новостей (всего: 21172)
  -> Сохранено во временный файл
[421/1298] 2023-05-26:     Парсим новость 1: "Инарктика" стала совладельцем проектной компании...
    Парсим новость 2: "Деловые линии" купят интеллектуальные продукты у ...
    Парсим новость 3: Правительство включило котировку Brent в мониторин...
74 новостей (всего: 21246)
[422/1298] 2023-05-27:     Парсим новость 1: РФ в 2022 году увеличила поставки аграрной продукц...
1 новостей (всего: 21247)
[423/1298] 2023-05-28: 0 новостей
[424/1298] 2023-05-29:     Парсим новость 1: Правительство РФ разрешило экспорт рапса через Заб...
    Парсим новость 2: Акционеры "Ленты" 29 июня рассмотрят вопрос о диви...
    Парсим новость 3: Портфель займов МФО в России в I квартале вырос на...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/903655 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002177033C650>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
58 новостей (всего: 21305)
[425/1298] 2023-05-30:     Парсим новость 1: Evraz в 2022 году сократил производство стали на 5...
    Парсим новость 2: Эксперты отметили усиление колебания цен на зерно ...
    Парсим новость 3: Новак поручил компаниям равномерно продавать топли...
62 новостей (всего: 21367)
[426/1298] 2023-05-31:     Парсим новость 1: LyondellBasell отложила планы по выходу из нефтепе...
    Парсим новость 2: Евросоюз выделит на усиление нацбезопасности Молда...
    Парсим новость 3: Создание базовых станций Yadro в рамках форвардных...
101 новостей (всего: 21468)
[427/1298] 2023-06-01:     Парсим новость 1: ГК "Титан" начала строить завод силикагелей за 8 м...
    Парсим новость 2: Goldman Sachs предупредил о снижении доходов от тр...
    Парсим новость 3: Опрошенные ЦБ аналитики ожидают рост ВВП РФ в 2023...
74 новостей (всего: 21542)
[428/1298] 2023-06-02:     Парсим новость 1: Азербайджан и Венгрия подписали контракт на постав...
    Парсим новость 2: Банк России отметил рост числа квалифицированных и...
    Парсим новость 3: В Думу внесли законопроект о создании системы гара...
68 новостей (всего: 21610)
[429/1298] 2023-06-03:     Парсим новость 1: Байден подписал закон о повышении лимита госдолга ...
    Парсим новость 2: Moody's понизило кредитный рейтинг Белоруссии с "С...
    Парсим новость 3: Министр Саудовской Аравии заявил, что страны ОПЕК ...
6 новостей (всего: 21616)
[430/1298] 2023-06-04:     Парсим новость 1: Саудовская Аравия в июле на месяц дополнительно со...
    Парсим новость 2: Общая добыча нефти стран ОПЕК+ в 2024 году будет с...
    Парсим новость 3: Источники сообщили о планах ОПЕК+ продлить соглаше...
7 новостей (всего: 21623)
[431/1298] 2023-06-05:     Парсим новость 1: Плательщиков единого сельхозналога могут вывести и...
    Парсим новость 2: SEC обвинила криптовалютную биржу Binance и ее осн...
    Парсим новость 3: Страховые компании мира собрали рекордные 5,6 трлн...
66 новостей (всего: 21689)
[432/1298] 2023-06-06:     Парсим новость 1: Акционеры "Норникеля" обновили совет директоров...
    Парсим новость 2: ЦБ усмотрел в индексе золота Мосбиржи потенциальну...
    Парсим новость 3: США прогнозируют рост добычи жидких углеводородов ...
52 новостей (всего: 21741)
[433/1298] 2023-06-07:     Парсим новость 1: Путин и наследный принц Саудовской Аравии дали выс...
    Парсим новость 2: Чистая прибыль российских страховщиков увеличилась...
    Парсим новость 3: Структура АФК "Система" учредила управляющую компа...
77 новостей (всего: 21818)
[434/1298] 2023-06-08:     Парсим новость 1: Льготы по НДФЛ в рамках ИИС-3 могут распространить...
    Парсим новость 2: Рубль обновил апрельские минимумы к доллару, евро ...
    Парсим новость 3: Рынок акций превысил 2700п по индексу МосБиржи во ...
57 новостей (всего: 21875)
[435/1298] 2023-06-09:     Парсим новость 1: Заявление Банка России: Ставка собирается в путь...
    Парсим новость 2: ВТБ в 2024 году планирует возобновить выплату купо...
    Парсим новость 3: "ТАИФ" частично законсервирует нефтебазу "Татнефте...
89 новостей (всего: 21964)
[436/1298] 2023-06-10:     Парсим новость 1: Владелец брендов Zewa и Libresse передал предприят...
    Парсим новость 2: S&P подтвердило кредитные рейтинги Азербайджана в ...
2 новостей (всего: 21966)
[437/1298] 2023-06-11:     Парсим новость 1: Источник допустил принятие поправок об отмене НДС ...

    Парсим новость 2: Туркменистан закупит шесть новых пассажирских само...
2 новостей (всего: 21968)
[438/1298] 2023-06-12:     Парсим новость 1: Промышленность ФРГ может пострадать, если РФ и Укр...
    Парсим новость 2: В ЕС изучают возможности хранить газ в ПХГ на Укра...
    Парсим новость 3: Завершилось плановое обслуживание газопровода "Тур...
4 новостей (всего: 21972)
[439/1298] 2023-06-13:     Парсим новость 1: Всемирная продовольственная программа ООН сократит...
    Парсим новость 2: Референтная база отсчета уровня добычи РФ на 2024г...
    Парсим новость 3: ЦБ РФ улучшил прогноз по прибыли банков на 2023 го...
70 новостей (всего: 22042)
[440/1298] 2023-06-14:     Парсим новость 1: Инфляционное давление в США продолжает оставаться ...
    Парсим новость 2: ФРС повысила прогноз роста экономики США на 2023 г...
    Парсим новость 3: ФРС ожидаемо сохранила ставку в диапазоне 5-5,25%...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/906212 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A6518B0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
71 новостей (всего: 22113)
[441/1298] 2023-06-15:     Парсим новость 1: "ВЭБ" может получить возможность входить в капитал...
    Парсим новость 2: Минфин включил в "черный список" офшоров недружест...
    Парсим новость 3: Союз золотопромышленников назвал условия для повыш...
126 новостей (всего: 22239)
[442/1298] 2023-06-16:     Парсим новость 1: "Газпром" обсудил развитие сотрудничества с CNPC...
    Парсим новость 2: Сечин обсудил с замом премьера Узбекистана возможн...
    Парсим новость 3: "Роснефть" и CNPC перешли на оплату сырья в национ...
127 новостей (всего: 22366)
[443/1298] 2023-06-17:     Парсим новость 1: Путин заявил, что из портов Украины в страны Африк...
    Парсим новость 2: "СИБУР" перенаправил поставки полимеров из Европы,...
    Парсим новость 3: ПМЭФ-2023 принес Петербургу более 660 млрд рублей ...
16 новостей (всего: 22382)
[444/1298] 2023-06-18: 0 новостей
[445/1298] 2023-06-19:     Парсим новость 1: В ЕС заявили о продолжении реализации программы по...
    Парсим новость 2: Рубль в понедельник немного подешевел в основных п...
    Парсим новость 3: ЦБ разработал проект указания о минимальном регион...
28 новостей (всего: 22410)
[446/1298] 2023-06-20:     Парсим новость 1: Cisco решила ликвидировать одно из российских юрли...
    Парсим новость 2: Российская Softline не будет выплачивать дивиденды...
    Парсим новость 3: Льготная ипотека в России "обогнала" бюджетный про...
35 новостей (всего: 22445)
[447/1298] 2023-06-21:     Парсим новость 1: Сеть диагностических центров "Хеликс" планирует вы...
    Парсим новость 2: "Автотор" начал строительство металлургического ко...
    Парсим новость 3: "Роснефть" восполнит Монголии недопоставленные из-...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /world/908396 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002177046C200>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
41 новостей (всего: 22486)
[448/1298] 2023-06-22:     Парсим новость 1: "Газпром" готов помочь развитию производства и исп...
    Парсим новость 2: Fitch пересмотрело прогноз цен на цветные металлы,...
    Парсим новость 3: Чистая прибыль банков РФ в мае составила 273 млрд ...
43 новостей (всего: 22529)
[449/1298] 2023-06-23:     Парсим новость 1: Турецкая лира обновила рекордный минимум после реш...
    Парсим новость 2: Рубль в пятницу упал к доллару и евро перед выходн...
    Парсим новость 3: ЦБ РФ упразднит департамент противодействия недобр...
38 новостей (всего: 22567)
[450/1298] 2023-06-24:     Парсим новость 1: Крупнейшие банки снизили обменные курсы с утренних...
1 новостей (всего: 22568)
  -> Сохранено во временный файл
[451/1298] 2023-06-25:     Парсим новость 1: Петербургская товарно-сырьевая биржа будет проводи...
    Парсим новость 2: "СПБ биржа" будет проводить торги в понедельник в ...
    Парсим новость 3: Торги на Московской бирже 26 июня будут проводитьс...
3 новостей (всего: 22571)
[452/1298] 2023-06-26:     Парсим новость 1: Аграрии РФ к 26 июня собрали 1,5 млн т зерна, в 1,...
    Парсим новость 2: Рубль на закрытии торгов вернулся к умеренному сни...
    Парсим новость 3: Рынок акций РФ начал неделю со снижения, выросли "...
36 новостей (всего: 22607)
[453/1298] 2023-06-27:     Парсим новость 1: Рубль завершил торги вторника разнонаправленной ди...
    Парсим новость 2: Российская Softline планирует направлять на дивиде...
    Парсим новость 3: Рынок акций РФ вырос во главе с "Яндексом" и метал...
45 новостей (всего: 22652)
[454/1298] 2023-06-28:     Парсим новость 1: Власти Ставропольского края выступили за взимание ...
    Парсим новость 2: Путин поддержал продление на 3 года повышенного ко...
    Парсим новость 3: Путин призвал ускорить разработку концепции автомо...
47 новостей (всего: 22699)
[455/1298] 2023-06-29:     Парсим новость 1: Резиденты смогут продавать полученную по внешнетор...
    Парсим новость 2: Whoosh изучает возможность выхода на рынки трех ст...
    Парсим новость 3: "Ростелеком" объявил об отмене ГОСА, назначенного ...
39 новостей (всего: 22738)
[456/1298] 2023-06-30:     Парсим новость 1: "Траст" продал "Тимано-Печорскую газовую компанию"...
    Парсим новость 2: "Россети" разместят допэмиссию на 120,5 млрд рубле...
    Парсим новость 3: Акционеры X5 переизбрали трех членов правления...
57 новостей (всего: 22795)
[457/1298] 2023-07-01:     Парсим новость 1: Глобальные зернотрейдеры с 1 июля прекратили экспо...
    Парсим новость 2: РФ с 1 июля 2023 г. вводит контроль импорта пестиц...
    Парсим новость 3: Пошлина на экспорт подсолнечного масла из РФ в июл...
3 новостей (всего: 22798)
[458/1298] 2023-07-02:     Парсим новость 1: В Белоруссии предложили запретить сделки с криптов...
1 новостей (всего: 22799)
[459/1298] 2023-07-03:     Парсим новость 1: Mondi закрыла сделку по продаже упаковочного бизне...
    Парсим новость 2: Часть "санкционных" правил раскрытия информации пр...
    Парсим новость 3: Рубль с началом нового месяца и квартала вырос к д...
90 новостей (всего: 22889)
[460/1298] 2023-07-04:     Парсим новость 1: Рубль по итогам вторника отыграл часть дневных пот...
    Парсим новость 2: Рынок акций РФ во вторник превысил 2800п по индекс...
    Парсим новость 3: Повторное годовое собрание акционеров FESCO пройде...
52 новостей (всего: 22941)
[461/1298] 2023-07-05:     Парсим новость 1: Кувейт к концу 2024 года увеличит мощности по добы...
    Парсим новость 2: Генсек ОПЕК уверен в правильности недавнего решени...
    Парсим новость 3: Генсек ОПЕК заявил, что организация открыта для но...
69 новостей (всего: 23010)
[462/1298] 2023-07-06:     Парсим новость 1: Финансовый конгресс ЦБ: надежда на раскрытие...
    Парсим новость 2: Рубль в четверг сумел отыграть значительную часть ...
    Парсим новость 3: Запасы сахара в РФ к концу июня совпали с уровнем ...
88 новостей (всего: 23098)
[463/1298] 2023-07-07:     Парсим новость 1: В Думу внесены поправки об инвестиционном вычете д...
    Парсим новость 2: Представители ООН готовы провести переговоры по зе...
    Парсим новость 3: Россия заняла пятое место по импорту томатов из Ту...
81 новостей (всего: 23179)
[464/1298] 2023-07-08:     Парсим новость 1: Йеллен заявила, что сотрудничество США и КНР спосо...
    Парсим новость 2: Wison начала изготовление верхних строений установ...
    Парсим новость 3: Эрдоган выразил надежду на продление "зерновой сде...
3 новостей (всего: 23182)
[465/1298] 2023-07-09:     Парсим новость 1: На Мангистауском атомном энергетическом комбинате ...
1 новостей (всего: 23183)
[466/1298] 2023-07-10:     Парсим новость 1: Ветеран "АЛРОСА" Игорь Соболев покинул пост первог...
    Парсим новость 2: Путин подписал закон об удаленной идентификации не...
    Парсим новость 3: Рубль вечером немного ускорил темпы роста к доллар...
66 новостей (всего: 23249)
[467/1298] 2023-07-11:     Парсим новость 1: Группа ОАТ не смогла найти в РФ производителя штам...
    Парсим новость 2: Суд США отказался блокировать сделку Microsoft и A...

    Парсим новость 3: Рубль сократил темпы роста к доллару и евро по ито...
66 новостей (всего: 23315)
[468/1298] 2023-07-12:     Парсим новость 1: ФАС завершает анализ стратегии поведения участнико...
    Парсим новость 2: Рубль в среду заметно упал в основных парах на фон...
    Парсим новость 3: В ЦБ РФ заявили о росте ВВП во II квартале на 0,7%...
71 новостей (всего: 23386)
[469/1298] 2023-07-13:     Парсим новость 1: Глава ЕК заявила, что Россия несет ответственность...
    Парсим новость 2: SberCIB ожидает повышения ключевой ставки ЦБ на 10...
    Парсим новость 3: Siemens инвестирует миллиард евро в проекты на тер...
58 новостей (всего: 23444)
[470/1298] 2023-07-14:     Парсим новость 1: Комитет Думы отказался продлевать мораторий на упл...
    Парсим новость 2: Нобелиат Писсаридес не увидел необходимости в ново...
    Парсим новость 3: На "Мосбирже" доллар подешевел на 5,25 копейки, ев...
55 новостей (всего: 23499)
[471/1298] 2023-07-15:     Парсим новость 1: ADNOC подтвердила начало переговоров с OMV об объе...
1 новостей (всего: 23500)
[472/1298] 2023-07-16:     Парсим новость 1: Carlsberg заявил, что указ о временном управлении ...
    Парсим новость 2: РФ забрала под управление "Балтику" и "дочку" Dano...
2 новостей (всего: 23502)
[473/1298] 2023-07-17:     Парсим новость 1: Мировые продажи чипов в мае сократились на 21% в г...
    Парсим новость 2: ЦБ рекомендовал финорганизациям раскрывать информа...
    Парсим новость 3: Комитет Госдумы одобрил ко II чтению законопроект ...
58 новостей (всего: 23560)
[474/1298] 2023-07-18:     Парсим новость 1: Экс-руководитель "Балтики" Боллоев стал президенто...
    Парсим новость 2: Рубль во вторник умеренно подорожал к доллару и ев...
    Парсим новость 3: Заказы на постройку судов в Китае в I полугодии вы...
71 новостей (всего: 23631)
[475/1298] 2023-07-19:     Парсим новость 1: Сбербанк рассматривает возможность открытия филиал...
    Парсим новость 2: ЦБ намерен масштабировать "пилот" с цифровыми рубл...
    Парсим новость 3: Депутаты внесли в Госдуму поправки, расширяющие по...
75 новостей (всего: 23706)
[476/1298] 2023-07-20:     Парсим новость 1: Суд не признал недействительным решение ФАС о необ...
    Парсим новость 2: Банк "Солидарность" посоветовал находящимся за руб...
    Парсим новость 3: Банк-оператор платежной системы "Юнистрим" сможет ...
96 новостей (всего: 23802)
[477/1298] 2023-07-21:     Парсим новость 1: Росбанк не смог добиться ареста активов Citibank в...
    Парсим новость 2: Заявление Банка России: Экономика оправдывает инфл...
    Парсим новость 3: Equinor купит компанию-владельца возобновляемых ис...
78 новостей (всего: 23880)
[478/1298] 2023-07-22:     Парсим новость 1: Частные инвесторы подали коллективный иск к Eurocl...
1 новостей (всего: 23881)
[479/1298] 2023-07-23:     Парсим новость 1: Южная Корея разрешит бизнесменам посещать Украину ...
1 новостей (всего: 23882)
[480/1298] 2023-07-24:     Парсим новость 1: ФАС предложила увеличить нормы биржевых продаж бен...
    Парсим новость 2: Новак поддержал предложения Минэнерго по ограничен...
    Парсим новость 3: UBS выплатит $387 млн штрафов из-за трейдинговых н...
60 новостей (всего: 23942)
  -> Сохранено во временный файл
[481/1298] 2023-07-25:     Парсим новость 1: Рубль во вторник вырос к доллару и евро на фоне по...
    Парсим новость 2: Новым главой китайского ЦБ назначен Пань Гуншэн...
    Парсим новость 3: Рынок акций РФ обновил максимум индекса МосБиржи с...
83 новостей (всего: 24025)
[482/1298] 2023-07-26:     Парсим новость 1: Пауэлл заявил, что Федрезерв будет принимать решен...
    Парсим новость 2: ФРС ожидаемо повысила ставку на 25 базисных пункто...
    Парсим новость 3: США вместе с ЕС и Украиной ищут варианты экспорта ...
96 новостей (всего: 24121)
[483/1298] 2023-07-27:     Парсим новость 1: Выдача разрешений на импорт запрещенной рыбной про...
    Парсим новость 2: Эксперимент по исключению техвозможности продажи п...
    Парсим новость 3: Kering купит 30% бренда Valentino за 1,7 млрд евро...
87 новостей (всего: 24208)
[484/1298] 2023-07-28:     Парсим новость 1: Капитализация рынка акций РФ в пятницу выросла на ...
    Парсим новость 2: Pirelli в I полугодии увеличил чистую прибыль на 4...
    Парсим новость 3: Crocs во II квартале увеличил выручку на 11,2% год...
82 новостей (всего: 24290)
[485/1298] 2023-07-29:     Парсим новость 1: Президент Гвинеи-Бисау выступил за более активное ...
    Парсим новость 2: Россия продлила запрет на экспорт риса до конца 20...
2 новостей (всего: 24292)
[486/1298] 2023-07-30:     Парсим новость 1: Иран увеличил поставки нефти в Китай в три раза за...
    Парсим новость 2: Россия не планирует забирать в управление новые ин...
2 новостей (всего: 24294)
[487/1298] 2023-07-31:     Парсим новость 1: ЦБ РФ ожидает годовую инфляцию в 5% к октябрю и в ...
    Парсим новость 2: ЦБ оценил рост ВВП РФ во II квартале в 4,8%, ждет ...
    Парсим новость 3: Рубль в понедельник слегка подрос к доллару и евро...
63 новостей (всего: 24357)
[488/1298] 2023-08-01:     Парсим новость 1: Мосбиржа выявила несоответствие акций "Детского ми...
    Парсим новость 2: Мировой спрос на золото во II квартале снизился на...
    Парсим новость 3: Минтруд  предложил не учитывать ряд доходов при на...
64 новостей (всего: 24421)
[489/1298] 2023-08-02:     Парсим новость 1: "Норникель" пока не планирует повторить опыт "Магн...
    Парсим новость 2: "Ведомости" пишут, что падение рубля может вынудит...
    Парсим новость 3: "Сервис-Телеком" создал IT-компанию для управления...
83 новостей (всего: 24504)
[490/1298] 2023-08-03:     Парсим новость 1: Eni, BP, Sonatrach сняли форс-мажор на работу на н...
    Парсим новость 2: Mondi рассчитывает продать "Монди Сыктывкарский ЛП...
    Парсим новость 3: Эксперты МАГАТЭ в четверг впервые осмотрели крыши ...
89 новостей (всего: 24593)
[491/1298] 2023-08-04:     Парсим новость 1: Совет директоров Positive Technologies покинул еще...
    Парсим новость 2: Аграрии РФ рассчитывают на дожди для пополнения за...
    Парсим новость 3: Рубль в пятницу в основных парах обновил минимумы ...
62 новостей (всего: 24655)
[492/1298] 2023-08-05: 0 новостей
[493/1298] 2023-08-06:     Парсим новость 1: Польский оператор PERN подтвердил повреждение одно...
    Парсим новость 2: В Казахстане заявили о планах поставить в Германию...
2 новостей (всего: 24657)
[494/1298] 2023-08-07:     Парсим новость 1: Yadro получит в 2023 году 3,4 млрд рублей субсидий...
    Парсим новость 2: Денежная масса в РФ в июле увеличилась на 1%, годо...
    Парсим новость 3: Рубль умеренно подорожал в рамках коррекции после ...
71 новостей (всего: 24728)
[495/1298] 2023-08-08:     Парсим новость 1: В Союзе экспортеров зерна заявили, что РФ создает ...
    Парсим новость 2: Региональные сети будут ограничивать наценки на со...
    Парсим новость 3: Рубль упал по итогам торгов вторника на фоне после...
68 новостей (всего: 24796)
[496/1298] 2023-08-09:     Парсим новость 1: ФАС намерена усилить контроль за региональными про...
    Парсим новость 2: Рубль отыграл почти все дневные потери к доллару и...
    Парсим новость 3: Продукты питания в РФ в июле подорожали на 0,55%, ...
58 новостей (всего: 24854)
[497/1298] 2023-08-10:     Парсим новость 1: Структура Marathon Group вышла из состава владельц...
    Парсим новость 2: "Магнит" выкупил акции у нерезидентов, владевших 1...
    Парсим новость 3: Рубль в четверг возобновил снижение к доллару и ев...
57 новостей (всего: 24911)
[498/1298] 2023-08-11:     Парсим новость 1: Телеком-операторов обяжут обосновывать повышение т...
    Парсим новость 2: Россельхознадзор отменил ограничения на ввоз проду...
    Парсим новость 3: Банк "Ак Барс" в I полугодии получил 625 млн рубле...
69 новостей (всего: 24980)
[499/1298] 2023-08-12:     Парсим новость 1: Первая линия завода "Арктик СПГ 2" доставлена к ме...
1 новостей (всего: 24981)
[500/1298] 2023-08-13:     Парсим новость 1: В Минсельхозе заявили о падении цен производителей...
1 новостей (всего: 24982)
[501/1298] 2023-08-14:     Парсим новость 1: Подготовлены правила субсидирования производителей...
    Парсим новость 2: ЦБ заявил, что эффект переноса ослабления рубля на...
    Парсим новость 3: Аналитики допускают повышение Банком России ставки...

60 новостей (всего: 25042)
[502/1298] 2023-08-15:     Парсим новость 1: Red Wings починила оба Boeing 777 и вернется к обы...
    Парсим новость 2: Власти обсуждают с экспортерами меры по стабилизац...
    Парсим новость 3: ЦБ РФ повысил ставку до 12%, допускает возможность...
56 новостей (всего: 25098)
[503/1298] 2023-08-16:     Парсим новость 1: Qiwi оценивает выплаты по windfall tax в 0,5 млрд ...
    Парсим новость 2: Qiwi пока не видит возможности для выплаты дивиден...
    Парсим новость 3: Qiwi ведет диалог с ЦБ РФ по поводу предписания Ки...
63 новостей (всего: 25161)
[504/1298] 2023-08-17:     Парсим новость 1: Рубль подрос к доллару и евро на планах властей со...
    Парсим новость 2: Fitch может пересмотреть рейтинг КНР "A+" в случае...
    Парсим новость 3: Индекс МосБиржи вырос в четверг впервые с начала н...
52 новостей (всего: 25213)
[505/1298] 2023-08-18:     Парсим новость 1: Россия призвала страны БРИКС расширять расчеты в н...
    Парсим новость 2: В Венгрии первый бетон на АЭС "Пакш-2" зальют до к...
    Парсим новость 3: Дочь основателя "Нэфис косметикс" требует 11 млрд ...
50 новостей (всего: 25263)
[506/1298] 2023-08-19:     Парсим новость 1: ФАС проверит обоснованность оптово-отпускных цен п...
1 новостей (всего: 25264)
[507/1298] 2023-08-20:     Парсим новость 1: Будапешт и Ашхабад заключили политическое соглашен...
    Парсим новость 2: Глава МИД Венгрии заявил о готовности Сербии поста...
    Парсим новость 3: Первый иск российских инвесторов к Clearstream пос...
3 новостей (всего: 25267)
[508/1298] 2023-08-21:     Парсим новость 1: Банки РФ в июле продолжили наращивать корпоративно...
    Парсим новость 2: Средства физлиц в российских банках в июле выросли...
    Парсим новость 3: Запас валютной ликвидности в банках РФ в июле сокр...
64 новостей (всего: 25331)
[509/1298] 2023-08-22:     Парсим новость 1: Принято решение о либерализации выплат дивидендов ...
    Парсим новость 2: Минфин рассчитывает на участие 2 млн человек в про...
    Парсим новость 3: IBM продает активы Weather Co. инвесткомпании Fran...
66 новостей (всего: 25397)
[510/1298] 2023-08-23:     Парсим новость 1: Россия за 7 месяцев увеличила производство БАДов п...
    Парсим новость 2: Что произошло за день: среда, 23 августа...
    Парсим новость 3: HSBC рекомендует не возобновлять инвестиции в акци...
63 новостей (всего: 25460)
  -> Сохранено во временный файл
[511/1298] 2023-08-24:     Парсим новость 1: РФ предоставила Кубе отсрочки по кредиту на строит...
    Парсим новость 2: Первые пробы подсолнечника нового урожая в РФ пока...
    Парсим новость 3: Рубль в четверг подешевел к доллару и евро на фоне...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/917619 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176F2F9F40>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
50 новостей (всего: 25510)
[512/1298] 2023-08-25:     Парсим новость 1: Petra Diamonds увеличила продажи в августе на 88% ...
    Парсим новость 2: ХКФ банк погасит казначейские 49,5% и уменьшит уст...
    Парсим новость 3: "Алор" повторил прежнее предложение российским дер...
76 новостей (всего: 25586)
[513/1298] 2023-08-26:     Парсим новость 1: Процесс передачи ОСК в доверительное управление ВТ...
    Парсим новость 2: Вопрос финподдержки ОСК государством решится в теч...
    Парсим новость 3: Силуанов допустил, что инфляция в РФ в 2023 году с...
4 новостей (всего: 25590)
[514/1298] 2023-08-27: 0 новостей
[515/1298] 2023-08-28:     Парсим новость 1: "Медси" в I полугодии нарастила выручку на 16%...
    Парсим новость 2: Выручка "МаксимаТелекома" в I полугодии по МСФО сн...
    Парсим новость 3: Рубль завершил торги понедельника слабыми изменени...
70 новостей (всего: 25660)
[516/1298] 2023-08-29:     Парсим новость 1: Чистая прибыль "Роснефти" по МСФО в I полугодии со...
    Парсим новость 2: "ЮТэйр" в I полугодии получила 1,9 млрд руб. чисто...
    Парсим новость 3: EBITDA "Металлоинвеста" в I полугодии упала до 100...
96 новостей (всего: 25756)
[517/1298] 2023-08-30:     Парсим новость 1: Девелопер Legenda в I полугодии увеличил портфель ...
    Парсим новость 2: СД "ФосАгро" рекомендовал промежуточные дивиденды ...
    Парсим новость 3: Deere увеличила квартальные дивиденды на 8% до $1,...
82 новостей (всего: 25838)
[518/1298] 2023-08-31:     Парсим новость 1: Рубль вечером укрепился к доллару и евро по итогам...
    Парсим новость 2: Бери от биржи все: цены на топливо завершают авгус...
    Парсим новость 3: Рынок акций РФ завершил август на годовом максимум...
57 новостей (всего: 25895)
[519/1298] 2023-09-01:     Парсим новость 1: Банк России разделит биометрию на группы по уровня...
    Парсим новость 2: Ирак в августе сохранил экспорт нефти на уровне 3,...
    Парсим новость 3: В США приостановили разрешение перевозить газ по ж...
79 новостей (всего: 25974)
[520/1298] 2023-09-02:     Парсим новость 1: Белоруссия повысила экспортные пошлины на нефть и ...
1 новостей (всего: 25975)
[521/1298] 2023-09-03: 0 новостей
[522/1298] 2023-09-04:     Парсим новость 1: Путин заявил о необходимости баланса интересов эне...
    Парсим новость 2: Роль учетно-контрольных спецмарок для табака будут...
    Парсим новость 3: Путин заявил, что рассматривается возможность уско...
40 новостей (всего: 26015)
[523/1298] 2023-09-05:     Парсим новость 1: "Аэрофлот" урегулировал отношения с ирландским лиз...
    Парсим новость 2: Тему "окрашивания" цифровых рублей рассмотрят на б...
    Парсим новость 3: Китайская ракета "Церера-1" вывела на орбиту четыр...
47 новостей (всего: 26062)
[524/1298] 2023-09-06:     Парсим новость 1: Вопрос о покупке акций на СД "Газпрома" не относит...
    Парсим новость 2: ЦБ РФ повысил прогноз по росту средств населения в...
    Парсим новость 3: ЦБ ждет прироста потребкредитов в 2023 г. ближе к ...
55 новостей (всего: 26117)
[525/1298] 2023-09-07:     Парсим новость 1: Сбер поддерживает оборотные штрафы за утечку персо...
    Парсим новость 2: "Газпром" будет партнером в проекте создания морск...
    Парсим новость 3: Число банкротств компаний в ЕС во II квартале дост...
43 новостей (всего: 26160)
[526/1298] 2023-09-08:     Парсим новость 1: Доля нефтегазового сектора в ВВП РФ во II квартале...
    Парсим новость 2: ГК "Полипласт" приобрела 100% "Русского хрома 1915...
    Парсим новость 3: Девелопер "Самолет" пока потратил на buyback 3,1 м...
34 новостей (всего: 26194)
[527/1298] 2023-09-09:     Парсим новость 1: Держатели евробондов РФ с правами в иностранных де...
1 новостей (всего: 26195)
[528/1298] 2023-09-10:     Парсим новость 1: В ЦБ пояснили, что новый порядок выплат по евробон...
    Парсим новость 2: Лавров назвал неприемлемой идею возобновить зернов...
    Парсим новость 3: В Якутии добыли самый крупный за последние 10 лет ...
3 новостей (всего: 26198)
[529/1298] 2023-09-11:     Парсим новость 1: Корпоративной репатриации готовят ручной режим. Ре...
    Парсим новость 2: Рубль заметно укрепился в понедельник на заявления...
    Парсим новость 3: Рынок акций РФ начал неделю с отката индекса МосБи...
89 новостей (всего: 26287)
[530/1298] 2023-09-12:     Парсим новость 1: Qiwi попросила Nasdaq продлить срок реструктуризац...
    Парсим новость 2: Минэкономразвития РФ ожидает сальдо счета текущих ...
    Парсим новость 3: Минэкономразвития прогнозирует уровень безработицы...
100 новостей (всего: 26387)
[531/1298] 2023-09-13:     Парсим новость 1: Узбекская "дочка" Qiwi приостановила международные...
    Парсим новость 2: Рубль подешевел на фоне снижения ожиданий в отноше...
    Парсим новость 3: Мнения аналитиков в отношении ставки ЦБ РФ разошли...
69 новостей (всего: 26456)
[532/1298] 2023-09-14:     Парсим новость 1: "РТК-Солар" разделил бизнес на коммерческий и госу...
    Парсим новость 2: "СИБУР" продлил предложение о выкупе евробондов тр...
    Парсим новость 3: Бумаги Arm прибавили более 17% в ходе дебютных тор...
64 новостей (всего: 26520)
[533/1298] 2023-09-15:     Парсим новость 1: Резиденты ЕС могут до 25 сентября подавать заявки ...
    Парсим новость 2: Капитализация российского рынка акций в пятницу сн...
    Парсим новость 3: Астраханский ГПЗ возобновил выпуск бензина после п...

82 новостей (всего: 26602)
[534/1298] 2023-09-16:     Парсим новость 1: Премьер Болгарии не стал говорить с фермерами на ф...
    Парсим новость 2: Словакия продлила действие эмбарго на поставку зер...
    Парсим новость 3: Польша на неопределенный срок запретила ввоз ряда ...
3 новостей (всего: 26605)
[535/1298] 2023-09-17: 0 новостей
[536/1298] 2023-09-18:     Парсим новость 1: Комитет Думы одобрил проект о реформе инвестиционн...
    Парсим новость 2: В Думе заявили, что ФНС и ЦБ не готовы пойти на уп...
    Парсим новость 3: Рубль слегка укрепился к доллару и юаню из-за раст...
72 новостей (всего: 26677)
[537/1298] 2023-09-19:     Парсим новость 1: Intel в декабре выведет на рынок новые ИИ-чипы и л...
    Парсим новость 2: Рубль к концу торгов вторника сдал позиции к основ...
    Парсим новость 3: Производитель мебели Mr.Doors вложил 100 млн рубле...
64 новостей (всего: 26741)
[538/1298] 2023-09-20:     Парсим новость 1: Глава ФРС пообещал продолжать повышение ставок по ...
    Парсим новость 2: ФРС повысила прогнозы по росту ВВП США и по инфляц...
    Парсим новость 3: Власти РФ хотят снять с экспортеров "курсовую рент...
91 новостей (всего: 26832)
[539/1298] 2023-09-21:     Парсим новость 1: Внутренний рынок топлива РФ решительно защитили. О...
    Парсим новость 2: Прирост средств компаний в российских банках в авг...
    Парсим новость 3: Темпы роста ипотеки в РФ в августе ускорились до р...
78 новостей (всего: 26910)
[540/1298] 2023-09-22:     Парсим новость 1: Канада ввела санкции против 63 физлиц и структур, ...
    Парсим новость 2: Минфин прогнозирует ликвидную часть ФНБ к концу 20...
    Парсим новость 3: Эксперты допустили, что "курсовая" пошлина более в...
113 новостей (всего: 27023)
  -> Сохранено во временный файл
[541/1298] 2023-09-23:     Парсим новость 1: Премьер Азербайджана сообщил, что валютные резервы...
    Парсим новость 2: В Думе заявили, что оперативные решения по регулир...
    Парсим новость 3: Байден заявил, что присоединится к пикету работник...
3 новостей (всего: 27026)
[542/1298] 2023-09-24:     Парсим новость 1: Бюджетом запланирован рост расходов на льготную и ...
    Парсим новость 2: Поступление НДПИ от нефти в 2024 г. прогнозируется...
    Парсим новость 3: В 2023-34 гг. от "курсовых" экспортных пошлин план...
8 новостей (всего: 27034)
[543/1298] 2023-09-25:     Парсим новость 1: Рубль в понедельник укрепился к основным валютам п...
    Парсим новость 2: Домохозяйства США увеличили вложения в госбумаги д...
    Парсим новость 3: "Трансмашхолдинг" в I полугодии получил по МСФО 4,...
96 новостей (всего: 27130)
[544/1298] 2023-09-26:     Парсим новость 1: ВТБ не ведет переговоры об обмене своей доли в For...
    Парсим новость 2: Минфин предложил в 2024 г. сохранить расходы на по...
    Парсим новость 3: Финансирование АПК РФ в 2024 году может увеличитьс...
61 новостей (всего: 27191)
[545/1298] 2023-09-27:     Парсим новость 1: Европа с 2020 года получила по TAP свыше 27 млрд к...
    Парсим новость 2: Росстат отметил рост производства в стране за 8 ме...
    Парсим новость 3: Морской линии в Калининград пообещали еще три желе...
103 новостей (всего: 27294)
[546/1298] 2023-09-28:     Парсим новость 1: Отборы мощности и проектов модернизации в электроэ...
    Парсим новость 2: "ПроЗерно" прогнозирует трудности с экспортом зерн...
    Парсим новость 3: Ставки по ипотеке в США достигли максимума почти з...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/923156 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000217703279E0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
97 новостей (всего: 27391)
[547/1298] 2023-09-29:     Парсим новость 1: Honeywell повысила годовые дивиденды на 5%...
    Парсим новость 2: Йеллен отметила снижение эффективности ценового по...
    Парсим новость 3: Крупнейший круизный оператор мира получил кварталь...
108 новостей (всего: 27499)
[548/1298] 2023-09-30:     Парсим новость 1: Новак заявил, что снижение биржевых цен на топливо...
    Парсим новость 2: Байден запланировал обсудить меры на случай "шатда...
2 новостей (всего: 27501)
[549/1298] 2023-10-01:     Парсим новость 1: Будущий запрет на экспорт топлива из РФ будет каса...
    Парсим новость 2: Власти РФ проследят за снижением цен на заправках...
    Парсим новость 3: Выработка российских АЭС в сентябре сократилась на...
3 новостей (всего: 27504)
[550/1298] 2023-10-02:     Парсим новость 1: "Аэрофлот" урегулировал отношения с лизингодателем...
    Парсим новость 2: РФ оставила на год на том же уровне цены и тарифы ...
    Парсим новость 3: Подъем российского рынка акций захлебнулся из-за у...
69 новостей (всего: 27573)
[551/1298] 2023-10-03:     Парсим новость 1: Федеральное казначейство сможет проводить операции...
    Парсим новость 2: ЕК проводит очередной тендер совместных закупок пр...
    Парсим новость 3: Evraz не смог опубликовать финрезультаты за I полу...
79 новостей (всего: 27652)
[552/1298] 2023-10-04:     Парсим новость 1: Ведомства и НК поддержали введение заградительных ...
    Парсим новость 2: Сбербанк хочет сохранить тренд роста размера дивид...
    Парсим новость 3: Рубль в среду чуть подрос к доллару и более заметн...
80 новостей (всего: 27732)
[553/1298] 2023-10-05:     Парсим новость 1: Орешкин отметил, что меры по укреплению рубля помо...
    Парсим новость 2: Сбербанк к началу ноября планирует запустить серви...
    Парсим новость 3: Планируемые в октябре поставки "Газпрома" в Узбеки...
78 новостей (всего: 27810)
[554/1298] 2023-10-06:     Парсим новость 1: Доля Гордеева в ПИКе опустилась ниже контрольной...
    Парсим новость 2: Минэнерго пока не планирует вводить единого экспор...
    Парсим новость 3: Квота на экспорт удобрений из России на период до ...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/924546 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176AB68260>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
78 новостей (всего: 27888)
[555/1298] 2023-10-07:     Парсим новость 1: Президент РФ обсудит проекты в энергетике с лидера...
    Парсим новость 2: Путин, Токаев и Мирзиёев дали старт началу поставо...
    Парсим новость 3: Президенты Узбекистана и Казахстана прибыли в подм...
5 новостей (всего: 27893)
[556/1298] 2023-10-08:     Парсим новость 1: В Белоруссии заявили об экспорте товаров страны че...
1 новостей (всего: 27894)
[557/1298] 2023-10-09:     Парсим новость 1: На долю резидентов РФ пришлось около 83% выплат пр...
    Парсим новость 2: Американцы стали меньше использовать кредитные кар...
    Парсим новость 3: Рубль в понедельник развернулся вверх на фоне рост...
70 новостей (всего: 27964)
[558/1298] 2023-10-10:     Парсим новость 1: Минфин предложил обсуждать финансирование "Почты Р...
    Парсим новость 2: Globaltrans не имеет "выраженного" интереса к ПГК,...
    Парсим новость 3: Минкультуры ищет способ пресечь показ в кино фильм...
65 новостей (всего: 28029)
[559/1298] 2023-10-11:     Парсим новость 1: Путин ввел обязательную продажу валютной выручки д...
    Парсим новость 2: В Белом доме заявили, что США почти исчерпали сред...
    Парсим новость 3: Минэнерго США понизило прогноз цены Brent на 2023 ...
71 новостей (всего: 28100)
[560/1298] 2023-10-12:     Парсим новость 1: Рубль в четверг уверенно вырос к основным валютам...
    Парсим новость 2: Barrick в III квартале увеличил выпуск золота на 5...
    Парсим новость 3: Снижение рынка акций по индексу МосБиржи на укрепл...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/925451 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A42DE80>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
100 новостей (всего: 28200)
[561/1298] 2023-10-13:     Парсим новость 1: Золото подскочило в цене до максимума за три недел...
    Парсим новость 2: "Татнефть" вложит 91 млрд руб. в строительство зав...
    Парсим новость 3: Юрфирмы Allen&Overy и Shearman проведут слияние в ...

74 новостей (всего: 28274)
[562/1298] 2023-10-14:     Парсим новость 1: Болгария вводит сбор свыше $100/тыс. куб. м на тра...
    Парсим новость 2: Товарооборот между Россией и Турцией вырос до $60 ...
    Парсим новость 3: Российско-индийский товарооборот вырос за 1,5 года...
3 новостей (всего: 28277)
[563/1298] 2023-10-15: 0 новостей
[564/1298] 2023-10-16:     Парсим новость 1: Баланс расчетов в инвалюте по ВЭД РФ в августе ста...
    Парсим новость 2: Рубль в понедельник подешевел к доллару и евро на ...
    Парсим новость 3: Рынок акций РФ обновил максимум индекса МосБиржи с...
66 новостей (всего: 28343)
[565/1298] 2023-10-17:     Парсим новость 1: Рубль развернулся вниз к доллару и усилил падение ...
    Парсим новость 2: Решетников назвал рабочим прогноз по среднегодовом...
    Парсим новость 3: Рынок акций РФ поднялся к 3250 пунктам по индексу ...
72 новостей (всего: 28415)
[566/1298] 2023-10-18:     Парсим новость 1: Правительство РФ одобрило продление поставок нефти...
    Парсим новость 2: В НСПК рассказали о создании банками "квазиплатежн...
    Парсим новость 3: Член совета управляющих ФРС Уоллер предложил не сп...
78 новостей (всего: 28493)
[567/1298] 2023-10-19:     Парсим новость 1: Правительство утвердило допэмиссию РЖД на 85,7 млр...
    Парсим новость 2: L'Oreal в III квартале увеличила продажи на 4,4% д...
    Парсим новость 3: "Газпрому" и "Транснефти" могут дать право добычи ...
79 новостей (всего: 28572)
[568/1298] 2023-10-20:     Парсим новость 1: Фондовые индексы Европы упали до минимумов за неск...
    Парсим новость 2: Новым владельцем активов Bonava в РФ станет презид...
    Парсим новость 3: Рубль в пятницу уверенно вырос к основным валютам...
73 новостей (всего: 28645)
[569/1298] 2023-10-21:     Парсим новость 1: Белоусов предложил создать в РФ систему поддержки ...
    Парсим новость 2: Ирак предупредил, что расширение конфликта на Ближ...
    Парсим новость 3: Россельхознадзор снял запрет на поставки курятины ...
5 новостей (всего: 28650)
[570/1298] 2023-10-22:     Парсим новость 1: "Газпром" обсуждает поставки по "Силе Сибири" выше...
    Парсим новость 2: "Газпром" начнет поставки в КНР по дальневосточном...
    Парсим новость 3: Миллер допустил, что в 2023 году в КНР дополнитель...
5 новостей (всего: 28655)
  -> Сохранено во временный файл
[571/1298] 2023-10-23:     Парсим новость 1: Эксперты спрогнозировали рекордные поставки пшениц...
    Парсим новость 2: Глава Qatar Airways в ноябре покинет свой пост пос...
    Парсим новость 3: Структура корпорации "Экополис" получила статус аф...
68 новостей (всего: 28723)
[572/1298] 2023-10-24:     Парсим новость 1: Золото слабо дешевеет, остается вблизи максимумов ...
    Парсим новость 2: Рубль во вторник сильно укрепился к основным валют...
    Парсим новость 3: Профильный комитет Думы счел неактуальными ряд мер...
58 новостей (всего: 28781)
[573/1298] 2023-10-25:     Парсим новость 1: Акционеры Совкомбанка одобрили обращение на биржу ...
    Парсим новость 2: Россия в этом году может увеличить производство мя...
    Парсим новость 3: ЕС увеличил выпуск макаронных изделий на 20% за пя...
92 новостей (всего: 28873)
[574/1298] 2023-10-26:     Парсим новость 1: Universal Music увеличила квартальную выручку на 3...
    Парсим новость 2: Ставки ипотечных кредитов в США достигли максимума...
    Парсим новость 3: Великобритания в сентябре увеличила выпуск автомоб...
84 новостей (всего: 28957)
[575/1298] 2023-10-27:     Парсим новость 1: Аэропорт в Абхазии реконструирует московская компа...
    Парсим новость 2: Набсовет Совкомбанка одобрил замещение евробондов,...
    Парсим новость 3: Правительство РФ заявило о стабилизации цен на топ...
97 новостей (всего: 29054)
[576/1298] 2023-10-28:     Парсим новость 1: Новый собственник "АрселорМиттал Темиртау" должен ...
1 новостей (всего: 29055)
[577/1298] 2023-10-29:     Парсим новость 1: Правительство РФ расширило границы территории опер...
1 новостей (всего: 29056)
[578/1298] 2023-10-30:     Парсим новость 1: Оператор карт "Мир" опроверг возможность утечки да...
    Парсим новость 2: Финструктуры РФ за 9 месяцев выдали участникам гос...
    Парсим новость 3: Объем госзакупок в РФ за девять месяцев 2023 года ...
65 новостей (всего: 29121)
[579/1298] 2023-10-31:     Парсим новость 1: Правительство ввело на полгода запрет на вывоз отх...
    Парсим новость 2: Uniper вернулся к чистой прибыли за 9 месяцев при ...
    Парсим новость 3: Квота на импорт агрохимикатов в Россию предложена ...
76 новостей (всего: 29197)
[580/1298] 2023-11-01:     Парсим новость 1: Пауэлл заявил, что ФРС в дальнейшем будет действов...
    Парсим новость 2: Минэкономразвития оценило рост ВВП РФ в III кварта...
    Парсим новость 3: Оборот розничной торговли РФ в сентябре вырос на 1...
86 новостей (всего: 29283)
[581/1298] 2023-11-02:     Парсим новость 1: Правительство определило правила сохранения на ино...
    Парсим новость 2: Источники сообщили о предложении Минфина увеличить...
    Парсим новость 3: "МосБиржа" проводит дискретный аукцион для акций "...
87 новостей (всего: 29370)
[582/1298] 2023-11-03:     Парсим новость 1: СПБ биржа 6 ноября будет проводить торги российски...
    Парсим новость 2: ЦБ озаботился недостатками комплаенса сделок УК по...
    Парсим новость 3: Число физлиц с брокерскими счетами на Мосбирже в о...
76 новостей (всего: 29446)
[583/1298] 2023-11-04:     Парсим новость 1: Мощности нефтепроводов к порту Приморск будут расш...
    Парсим новость 2: Продавать на АЗС премиальное ДТ разрешат только пр...
    Парсим новость 3: Глава Минэнерго РФ заявил, что не планируется ввод...
7 новостей (всего: 29453)
[584/1298] 2023-11-05:     Парсим новость 1: РФ продолжит сокращение поставок нефти и нефтепрод...
    Парсим новость 2: Саудовская Аравия в ноябре не поменяет параметры д...
2 новостей (всего: 29455)
[585/1298] 2023-11-06:     Парсим новость 1: Курс рубля практически не изменился в понедельник...
    Парсим новость 2: Рынок акций РФ начал неделю с роста выше 3235 п по...
    Парсим новость 3: В Думу внесен законопроект о продаже алкоголя в зо...
16 новостей (всего: 29471)
[586/1298] 2023-11-07:     Парсим новость 1: Минэнерго США повысило прогноз добычи нефти и ЖУВ ...
    Парсим новость 2: Минфин предложил ужесточить контроль за трансфертн...
    Парсим новость 3: Минэнерго США понизило прогноз цены Brent на 2023 ...
79 новостей (всего: 29550)
[587/1298] 2023-11-08:     Парсим новость 1: Лоретта Местер покинет пост президента ФРБ Кливлен...
    Парсим новость 2: Матыцин внес предложения по получению налогового в...
    Парсим новость 3: ЦБ предложил сделать обязательным для банков станд...
87 новостей (всего: 29637)
[588/1298] 2023-11-09:     Парсим новость 1: ЦБ отметил дальнейшее снижение объема трансграничн...
    Парсим новость 2: В России начали составлять списки турфирм для безв...
    Парсим новость 3: ЦБ до конца года определится с ужесточением услови...
89 новостей (всего: 29726)
[589/1298] 2023-11-10:     Парсим новость 1: Субсидии на выпуск автокомпонентов распространят н...
    Парсим новость 2: Mountain Province Diamonds договорилась с De Beers...
    Парсим новость 3: Минсельхоз и Минпромторг будут добиваться долгосро...
87 новостей (всего: 29813)
[590/1298] 2023-11-11:     Парсим новость 1: Миллер заявил о поступлении газа из России даже в ...
1 новостей (всего: 29814)
[591/1298] 2023-11-12: 0 новостей
[592/1298] 2023-11-13:     Парсим новость 1: Тинькофф банк за девять месяцев получил 33,6 млрд ...
    Парсим новость 2: Рубль завершил торги понедельника укреплением к ос...
    Парсим новость 3: Чистая прибыль "Газпром нефти" по РСБУ за девять м...
67 новостей (всего: 29881)
[593/1298] 2023-11-14:     Парсим новость 1: Совет директоров Yandex N.V в ноябре может рассмот...
    Парсим новость 2: Рубль заметно ускорил рост к доллару и развернулся...
    Парсим новость 3: "ЮТэйр" приостановила эксплуатацию трети парка Ми-...
72 новостей (всего: 29953)
[594/1298] 2023-11-15:     Парсим новость 1: Иран снизил темпы накопления высокообогащенного ур...
    Парсим новость 2: Запасы мяса птицы в сельхозорганизациях РФ к концу...
    Парсим новость 3: Рубль по итогам среды уверенно вырос к основным ва...
90 новостей (всего: 30043)

[595/1298] 2023-11-16:     Парсим новость 1: Виртуальная реальность во взыскании с банкротов кр...
    Парсим новость 2: Импорт алмазов в Индию в октябре вырос на 9% г/г п...
    Парсим новость 3: Перевозчик Lux Express с 18 ноября приостановит ав...
66 новостей (всего: 30109)
[596/1298] 2023-11-17:     Парсим новость 1: Глава Минэкономразвития считает, что спрос на внут...
    Парсим новость 2: Объем льготного кредитования в туризме по нацпроек...
    Парсим новость 3: Законопроект о расчетах в ЦФА во внешней торговле ...
70 новостей (всего: 30179)
[597/1298] 2023-11-18:     Парсим новость 1: "Газпром" приступил к отбору газа из своих подземн...
1 новостей (всего: 30180)
[598/1298] 2023-11-19: 0 новостей
[599/1298] 2023-11-20:     Парсим новость 1: Рубль в понедельник уверенно вырос к основным валю...
    Парсим новость 2: Citi уведомил сотрудников о мерах по реорганизации...
    Парсим новость 3: Рынок акций РФ начал неделю со стагнации вблизи 32...
61 новостей (всего: 30241)
[600/1298] 2023-11-21:     Парсим новость 1: Орешкин заявил, что рубль может укрепиться, но сил...
    Парсим новость 2: Цена золота превысила $2000 за унцию впервые с окт...
    Парсим новость 3: Рубль во вторник заметно укрепился к основным валю...
58 новостей (всего: 30299)
  -> Сохранено во временный файл
[601/1298] 2023-11-22:     Парсим новость 1: Прирост средств физлиц в банках России в октябре у...
    Парсим новость 2: Корпоративное кредитование в РФ в октябре ускорило...
    Парсим новость 3: Темпы роста ипотеки в октябре замедлились до 2,9% ...
68 новостей (всего: 30367)
[602/1298] 2023-11-23:     Парсим новость 1: BASF изучает продажу Wintershall Dea...
    Парсим новость 2: Конкурсный управляющий "Открытие холдинга" потребо...
    Парсим новость 3: "Группа Позитив" запланировала начать в 2024 году ...
71 новостей (всего: 30438)
[603/1298] 2023-11-24:     Парсим новость 1: Минэкономразвития сообщило о подготовке с Турцией ...
    Парсим новость 2: "Промышленные инвестиции" закрыли сделку по покупк...
    Парсим новость 3: Трюдо удивлен голосованием консерваторов против со...
68 новостей (всего: 30506)
[604/1298] 2023-11-25:     Парсим новость 1: "Нижнекамскнефтехим" за 9 месяцев снизил чистую пр...
    Парсим новость 2: РФ и Турция намерены увеличить номенклатуру и объе...
    Парсим новость 3: Новак заявил, что РФ готова расширить сотрудничест...
6 новостей (всего: 30512)
[605/1298] 2023-11-26:     Парсим новость 1: "Газпром" сообщил о новых суточных максимумах пост...
1 новостей (всего: 30513)
[606/1298] 2023-11-27:     Парсим новость 1: МТС-банк пытается в суде взыскать 10,1 млрд рублей...
    Парсим новость 2: Рубль в понедельник умеренно опустился к основным ...
    Парсим новость 3: Президент РФ подписал закон о федеральном бюджете ...
59 новостей (всего: 30572)
[607/1298] 2023-11-28:     Парсим новость 1: Белоруссия получила около $500 млн за счет ввозных...
    Парсим новость 2: Онлайн-продажи в США в киберпонедельник достигли р...
    Парсим новость 3: Главой экс-завода Volvo в Калуге назначен Роман Пе...
63 новостей (всего: 30635)
[608/1298] 2023-11-29:     Парсим новость 1: Путин отметил снижение уровня угрозы от введения в...
    Парсим новость 2: Нефть Африки имеет значение. Обзор...
    Парсим новость 3: Акции связанной с "Северной верфью" компании истре...
100 новостей (всего: 30735)
[609/1298] 2023-11-30:     Парсим новость 1: Ирак добровольно сократит добычу нефти в I квартал...
    Парсим новость 2: Новак заявил, что сокращение добычи странами ОПЕК+...
    Парсим новость 3: ОАЭ добровольно сократят добычу нефти в I квартале...
114 новостей (всего: 30849)
[610/1298] 2023-12-01:     Парсим новость 1: "ЛУКОЙЛ" получил разрешение на покупку доли UROC L...
    Парсим новость 2: Дума 7 декабря рассмотрит законопроект об отмене б...
    Парсим новость 3: В союзе свиноводов прогнозируют годовой экспорт св...
69 новостей (всего: 30918)
[611/1298] 2023-12-02:     Парсим новость 1: Хуснуллин не исключил увеличения первоначального в...
1 новостей (всего: 30919)
[612/1298] 2023-12-03: 0 новостей
[613/1298] 2023-12-04:     Парсим новость 1: Комитет Думы одобрил проект о минимизации налогов ...
    Парсим новость 2: Компаниям в РФ могут усложнить переезд из столиц в...
    Парсим новость 3: Число квалифицированных инвесторов-физлиц в РФ за ...
74 новостей (всего: 30993)
[614/1298] 2023-12-05:     Парсим новость 1: На Кубе карты "Мир" начали принимать магазины в Га...
    Парсим новость 2: "Норникель" заместит снижающийся спрос на палладий...
    Парсим новость 3: Германский индекс DAX завершил торги во вторник на...
82 новостей (всего: 31075)
[615/1298] 2023-12-06:     Парсим новость 1: Volkswagen планирует сократить расходы на рабочую ...
    Парсим новость 2: НРД отменил комиссии за перевод иностранных бумаг ...
    Парсим новость 3: Сбербанк в 2024 году планирует заработать больше, ...
92 новостей (всего: 31167)
[616/1298] 2023-12-07:     Парсим новость 1: Кондитеры РФ планируют в 2023 г. увеличить экспорт...
    Парсим новость 2: Что произошло за день: четверг, 7 декабря...
    Парсим новость 3: В "Аэрофлоте" заявили, что говорить о дивидендах п...
102 новостей (всего: 31269)
[617/1298] 2023-12-08:     Парсим новость 1: Минсельхоз США сохранил прогноз экспорта пшеницы и...
    Парсим новость 2: Несколько ритейлеров согласились ограничить наценк...
    Парсим новость 3: Рубль в пятницу растерял рост к основным валютам...
83 новостей (всего: 31352)
[618/1298] 2023-12-09:     Парсим новость 1: Bloomberg сообщил об уходе из Apple ответственного...
1 новостей (всего: 31353)
[619/1298] 2023-12-10:     Парсим новость 1: "Росатом" допустил использование технологии "сухой...
    Парсим новость 2: В Сбербанке оценили ежегодный ущерб РФ от изменени...
    Парсим новость 3: Азербайджан в 2023 году поставит в Болгарию около ...
5 новостей (всего: 31358)
[620/1298] 2023-12-11:     Парсим новость 1: ВС РФ изучит неустойку за "уход из России" на прим...
    Парсим новость 2: Новак рекомендовал компаниям увеличить предложение...
    Парсим новость 3: ЦБ определил порядок взаимодействия участников фин...
60 новостей (всего: 31418)
[621/1298] 2023-12-12:     Парсим новость 1: "Цифра брокер" планирует принудительно конвертиров...
    Парсим новость 2: Минэнерго США понизило прогноз потребления нефти в...
    Парсим новость 3: Прогноз добычи нефти в США в 2023 г. повышен на 30...
73 новостей (всего: 31491)
[622/1298] 2023-12-13:     Парсим новость 1: ЕК инвестирует 680 млн евро в транспортные и энерг...
    Парсим новость 2: Кремль рассчитывает на участие Аргентины в БРИКС...
    Парсим новость 3: ФРС намерена вернуть инфляцию в США к целевому уро...
70 новостей (всего: 31561)
[623/1298] 2023-12-14:     Парсим новость 1: Британский регулятор временно разрешил платежи чер...
    Парсим новость 2: С судозавода "Пелла" взыскали 533 млн руб. из-за н...
    Парсим новость 3: Литовский завод холодильников Snaige до 12 января ...
76 новостей (всего: 31637)
[624/1298] 2023-12-15:     Парсим новость 1: Доля "токсичных" валют при оплате экспорта РФ в ст...
    Парсим новость 2: Рубль в пятницу почти не изменился к бивалютной ко...
    Парсим новость 3: Запасы пшеницы в сельхозорганизациях на конец нояб...
82 новостей (всего: 31719)
[625/1298] 2023-12-16: 0 новостей
[626/1298] 2023-12-17:     Парсим новость 1: Силуанов заявил, что РФ не собирается национализир...
    Парсим новость 2: Глава Минсельхоза надеется, что цены на яйца начну...
    Парсим новость 3: Новак заявил о продолжении проработки сделки по вх...
8 новостей (всего: 31727)
[627/1298] 2023-12-18:     Парсим новость 1: ЦБ в I полугодии 2024 года определится с публикаци...
    Парсим новость 2: ЕС объяснил отсутствие санкций против российского ...
    Парсим новость 3: Импорт алмазов в Индию в ноябре рухнул на 76% в го...
89 новостей (всего: 31816)
[628/1298] 2023-12-19:     Парсим новость 1: Сенаторы США не согласуют в декабре сделку о финпо...
    Парсим новость 2: Калужский ликероводочный завод "Кристалл" перенес ...
    Парсим новость 3: Райффайзенбанк купит долю "Распериа" в концерне St...
67 новостей (всего: 31883)
[629/1298] 2023-12-20:     Парсим новость 1: OMV изучает указ о "русификации" владения СП с "Га...

    Парсим новость 2: Фонд развития промышленности докапитализируют в 20...
    Парсим новость 3: ФАС возбудила 26 антимонопольных дел на топливном ...
100 новостей (всего: 31983)
[630/1298] 2023-12-21:     Парсим новость 1: Минфин надеется обменом замороженных активов верну...
    Парсим новость 2: СУГ повернут вспять. Обзор...
    Парсим новость 3: Банки РФ в ноябре заработали 268 млрд рублей, с на...
67 новостей (всего: 32050)
  -> Сохранено во временный файл
[631/1298] 2023-12-22:     Парсим новость 1: Китайская компания BYD построит свой первый завод ...
    Парсим новость 2: "Почта России" получит около 1 млрд руб. от продаж...
    Парсим новость 3: IDC ожидает снижения продаж "умных" телевизоров в ...
64 новостей (всего: 32114)
[632/1298] 2023-12-23:     Парсим новость 1: Азербайджан поставил в Россию вторую партию яиц...
    Парсим новость 2: Кабмин РФ продлил квоту на экспорт лома черных мет...
    Парсим новость 3: Суд отменил арест 2,7 млрд рублей на счетах типа "...
4 новостей (всего: 32118)
[633/1298] 2023-12-24:     Парсим новость 1: "Газпром" заявил о новых суточных максимумах поста...
    Парсим новость 2: Росбанк выкупит у Societe Generale пакеты акций в ...
2 новостей (всего: 32120)
[634/1298] 2023-12-25:     Парсим новость 1: "БКС МИ" начал выплаты по бумагам, заблокированным...
    Парсим новость 2: Пошлина на экспорт подсолнечного масла из РФ в янв...
    Парсим новость 3: "Роснано" погасило облигации на 10 млрд рублей без...
58 новостей (всего: 32178)
[635/1298] 2023-12-26:     Парсим новость 1: Белгородская "Лесная сказка" создаст кондитерское ...
    Парсим новость 2: Правительство утвердило квоту на экспорт зерна в 2...
    Парсим новость 3: Сбербанк изменит условия льготной ипотеки...
58 новостей (всего: 32236)
[636/1298] 2023-12-27:     Парсим новость 1: Акционеры "Роснефти" утвердили промежуточные дивид...
    Парсим новость 2: Госпакеты трех принадлежащих ОЗК компаний будут пр...
    Парсим новость 3: "Полюс" будет платить иностранным держателям евроб...
86 новостей (всего: 32322)
[637/1298] 2023-12-28:     Парсим новость 1: Четыре страны осудили Тегеран за ускорение произво...
    Парсим новость 2: Кабмин утвердил правила ликвидации накопленного вр...
    Парсим новость 3: "Герофарму" и "Промомеду" разрешили выпускать анал...
78 новостей (всего: 32400)
[638/1298] 2023-12-29:     Парсим новость 1: JD.com выиграла антимонопольное дело против конкур...
    Парсим новость 2: ЦБ РФ оценит трансграничные переводы физлиц, связа...
    Парсим новость 3: Сводные индексы акций, валют и облигаций emerging ...
62 новостей (всего: 32462)
[639/1298] 2023-12-30:     Парсим новость 1: Что произошло за день: суббота, 30 декабря...
    Парсим новость 2: Россия продлила запрет на экспорт риса на первое п...
    Парсим новость 3: Минэкономразвития оценило рост ВВП РФ в 2023 году ...
3 новостей (всего: 32465)
[640/1298] 2023-12-31:     Парсим новость 1: Поставки азербайджанского газа в Европу в 2023 год...
1 новостей (всего: 32466)
[641/1298] 2024-01-01:     Парсим новость 1: Президент отметил устойчивость российской экономик...
    Парсим новость 2: "Транснефть" повысила тарифы на прокачку нефти и н...
    Парсим новость 3: Российский АПК переходит на единую субсидию...
12 новостей (всего: 32478)
[642/1298] 2024-01-02: 0 новостей
[643/1298] 2024-01-03:     Парсим новость 1: Оценка ущерба Shell "Сахалину-2" будет учитывать о...
    Парсим новость 2: Путин запретил обременения и аресты в отношении ак...
    Парсим новость 3: Рубль заметно упал по итогам первых торгов года...
29 новостей (всего: 32507)
[644/1298] 2024-01-04:     Парсим новость 1: Рубль умеренно укрепился в четверг, частично отыгр...
    Парсим новость 2: Цены на нефть снижаются после публикации данных о ...
    Парсим новость 3: Рынок акций РФ вырос по индексам вторые торги подр...
15 новостей (всего: 32522)
[645/1298] 2024-01-05:     Парсим новость 1: Финляндия планирует отказаться в 2025 году от импо...
    Парсим новость 2: Рубль в пятницу укрепился к основным валютам...
    Парсим новость 3: Рынок акций РФ завершил пятницу и неделю ростом ин...
19 новостей (всего: 32541)
[646/1298] 2024-01-06:     Парсим новость 1: "Росатом" почти готов к заливке первого бетона на ...
1 новостей (всего: 32542)
[647/1298] 2024-01-07:     Парсим новость 1: Баку и Ашхабад ведут переговоры о продолжении своп...
    Парсим новость 2: Китай ввел санкции против пяти компаний США из-за ...
2 новостей (всего: 32544)
[648/1298] 2024-01-08:     Парсим новость 1: Собрание акционеров TCS Group по вопросу редомицил...
    Парсим новость 2: Рынок акций РФ начал постновогоднюю неделю с роста...
    Парсим новость 3: Boston Scientific покупает конкурирующую Axonics п...
17 новостей (всего: 32561)
[649/1298] 2024-01-09:     Парсим новость 1: Минэнерго США повысило прогноз потребления нефти в...
    Парсим новость 2: Минэнерго США понизило прогноз цены Brent на 2024 ...
    Парсим новость 3: Структура АФК "Система" стала владельцем несостояв...
69 новостей (всего: 32630)
[650/1298] 2024-01-10:     Парсим новость 1: Рубль в среду умеренно укрепился к основным валюта...
    Парсим новость 2: Депозитарий СПБ биржи направил OFAC стратегию разб...
    Парсим новость 3: Турция стала самым крупным покупателем пшеницы из ...
65 новостей (всего: 32695)
[651/1298] 2024-01-11:     Парсим новость 1: ЦБ еще год не будет наказывать банки за работу с к...
    Парсим новость 2: Lucid увеличила производство электромобилей в 2023...
    Парсим новость 3: Золото дешевеет на данных об ускорении инфляции в ...
66 новостей (всего: 32761)
[652/1298] 2024-01-12:     Парсим новость 1: Минсельхоз США повысил прогноз экспорта пшеницы из...
    Парсим новость 2: Рост цен на бензин в РФ с 1 по 9 января составил 0...
    Парсим новость 3: Цены на огурцы в РФ в декабре выросли на 40,4%, на...
83 новостей (всего: 32844)
[653/1298] 2024-01-13:     Парсим новость 1: "Газпром" снова обновил максимумы экспорта газа в ...
1 новостей (всего: 32845)
[654/1298] 2024-01-14: 0 новостей
[655/1298] 2024-01-15:     Парсим новость 1: TCS Group перерегистрируется в САР на острове Русс...
    Парсим новость 2: Генпрокуратура попросила суд взыскать активы "Роль...
    Парсим новость 3: Заявки на поставки в Россию курятины по беспошлинн...
76 новостей (всего: 32921)
[656/1298] 2024-01-16:     Парсим новость 1: Рубль по итогам волатильных торгов вторника не изм...
    Парсим новость 2: В Думу внесен законопроект о праве ЦБ РФ ограничив...
    Парсим новость 3: Barrick в 2023 году снизил выпуск золота на 2% до ...
62 новостей (всего: 32983)
[657/1298] 2024-01-17:     Парсим новость 1: Доля рублевых платежей при оплате экспорта РФ в но...
    Парсим новость 2: Россия в 2023 году увеличила производство сахара д...
    Парсим новость 3: Миллер обсудил с вице-премьером Казахстана поставк...
84 новостей (всего: 33067)
[658/1298] 2024-01-18:     Парсим новость 1: "ФосАгро" ожидает стабильных цен на фосфорные удоб...
    Парсим новость 2: Долю риска инициаторов неипотечной секьюритизации ...
    Парсим новость 3: Шахтинский полиэфирный завод планируется восстанов...
70 новостей (всего: 33137)
[659/1298] 2024-01-19:     Парсим новость 1: Qiwi после продажи российских активов проведет buy...
    Парсим новость 2: Qiwi продаст активы в РФ менеджменту во главе с Пр...
    Парсим новость 3: Рубль в пятницу вырос к доллару и евро на фоне при...
70 новостей (всего: 33207)
[660/1298] 2024-01-20:     Парсим новость 1: Около 7 млн ипотечных кредитов выдали в РФ с 2020 ...
1 новостей (всего: 33208)
  -> Сохранено во временный файл
[661/1298] 2024-01-21:     Парсим новость 1: Технологический процесс "НОВАТЭК - Усть-Луги" оста...
    Парсим новость 2: Льготное финансирование посевной-2024 стартовало в...
    Парсим новость 3: Банки РФ начинают рассчитывать полную стоимость кр...
3 новостей (всего: 33211)
[662/1298] 2024-01-22:     Парсим новость 1: IDC ждет роста глобального рынка подержанных смарт...
    Парсим новость 2: Поставки натурального графита из КНР в декабре упа...
    Парсим новость 3: ЦБ сообщил, что эффект переноса курса в цены остае...
58 новостей (всего: 33269)
[663/1298] 2024-01-23:     Парсим новость 1: Qiwi проведет собрание акционеров по обратному вык...

    Парсим новость 2: Рубль во вторник упал к доллару и евро после двух ...
    Парсим новость 3: ЕК начала углубленную проверку сделки Lufthansa по...
60 новостей (всего: 33329)
[664/1298] 2024-01-24:     Парсим новость 1: "Ростелеком" стал едпоставщиком услуг доступа в ин...
    Парсим новость 2: Ценовые ожидания предприятий в январе вновь выросл...
    Парсим новость 3: ФАС запросит у нефтяников динамику цен на бензин в...
80 новостей (всего: 33409)
[665/1298] 2024-01-25:     Парсим новость 1: Московская компания может стать владельцем двух бы...
    Парсим новость 2: Экспорт рыбных консервов из Калининграда избавят о...
    Парсим новость 3: "СИБУР" предоставит "Петерпайпу" спецусловия на по...
87 новостей (всего: 33496)
[666/1298] 2024-01-26:     Парсим новость 1: Хуснуллин оценил сроки строительства первого этапа...
    Парсим новость 2: Космолет Virgin Galactic успешно сел после суборби...
    Парсим новость 3: Решетников перечислил ориентиры для планирования и...
84 новостей (всего: 33580)
[667/1298] 2024-01-27:     Парсим новость 1: РФ экспортировала в 2023г в АТР 193 млн тонн нефти...
    Парсим новость 2: Группа ОЗК ввезла в РФ почти 900 тыс. яиц из Турци...
    Парсим новость 3: В Минэнерго РФ сообщили о замысле объединения ряда...
15 новостей (всего: 33595)
[668/1298] 2024-01-28:     Парсим новость 1: Белоруссия за последние годы почти вдвое увеличила...
    Парсим новость 2: Путин оценил в $42,5 млрд товарооборот между РФ и ...
2 новостей (всего: 33597)
[669/1298] 2024-01-29:     Парсим новость 1: "Цифра брокер" с 30 января прекращает операции на ...
    Парсим новость 2: Совет директоров "Диасофта" обратится на "Мосбиржу...
    Парсим новость 3: Под Воронежем импортозаместят производство светоот...
75 новостей (всего: 33672)
[670/1298] 2024-01-30:     Парсим новость 1: Qiwi закрыла сделку по продаже российских активов ...
    Парсим новость 2: Минсельхоз подготовил проект распределения квоты н...
    Парсим новость 3: Аналитики спрогнозировали сохранение базовой ставк...
90 новостей (всего: 33762)
[671/1298] 2024-01-31:     Парсим новость 1: ФРС сохранила базовую ставку в диапазоне 5,25-5,5%...
    Парсим новость 2: Выпускаемые в РФ машины с 1 февраля должны быть не...
    Парсим новость 3: Ввоз золота в Гонконг из России в 2023 году вырос ...
97 новостей (всего: 33859)
[672/1298] 2024-02-01:     Парсим новость 1: Рубль в четверг снизился к основным валютам...
    Парсим новость 2: "Мосбиржа" оставила расписки TCS Group в списке до...
    Парсим новость 3: На СПбМТСБ в январе продажи дизтоплива выросли на ...
85 новостей (всего: 33944)
[673/1298] 2024-02-02:     Парсим новость 1: Разрешение на сделки с акциями "Русснефти" позволи...
    Парсим новость 2: МКБ отложил анонсированное замещение евробондов-20...
    Парсим новость 3: Турецкий строительный подрядчик Ronesans объявил о...
86 новостей (всего: 34030)
[674/1298] 2024-02-03:     Парсим новость 1: Etalon запланировал делистинг с LSE на февраль...
1 новостей (всего: 34031)
[675/1298] 2024-02-04:     Парсим новость 1: Минск нарастит перевалку грузов через порты Петерб...
    Парсим новость 2: Поставки "Газпрома" в Китай в субботу обновили рек...
2 новостей (всего: 34033)
[676/1298] 2024-02-05:     Парсим новость 1: Производители смарт-карт ждут введения балльной оц...
    Парсим новость 2: Новый пакет санкций ЕС против России затронет комп...
    Парсим новость 3: Глава Shell раскритиковал заморозку выдачи лицензи...
95 новостей (всего: 34128)
[677/1298] 2024-02-06:     Парсим новость 1: Мосбиржа допустила акции "Диасофта" к торгам с 15 ...
    Парсим новость 2: Минэнерго США понизило оценку добычи газа в стране...
    Парсим новость 3: Минэнерго США слегка понизило прогноз цены Brent в...
78 новостей (всего: 34206)
[678/1298] 2024-02-07:     Парсим новость 1: Оборот телеком-операторов РФ в 2023 году вырос на ...
    Парсим новость 2: Производство компьютеров в РФ в 2023 году выросло ...
    Парсим новость 3: Автопроизводители в РФ корректируют объемы выпуска...
87 новостей (всего: 34293)
[679/1298] 2024-02-08:     Парсим новость 1: Кабмин одобрил поправки к проекту о вычете по НДФЛ...
    Парсим новость 2: В США сохранили прогноз экспорта пшеницы из РФ в э...
    Парсим новость 3: В ООН осудили разрушение Израилем зданий в секторе...
81 новостей (всего: 34374)
[680/1298] 2024-02-09:     Парсим новость 1: Девелопер "Самолет" подал иск к своему бывшему топ...
    Парсим новость 2: Экспорт газа из Азербайджана в 2023 году увеличилс...
    Парсим новость 3: В Европе фермеры на тракторах вновь блокировали ав...
83 новостей (всего: 34457)
[681/1298] 2024-02-10: 0 новостей
[682/1298] 2024-02-11: 0 новостей
[683/1298] 2024-02-12:     Парсим новость 1: РФ в 2023 году увеличила экспорт рыбы на 12%, до 2...
    Парсим новость 2: Минэкономразвития обещает "очень аккуратно" подход...
    Парсим новость 3: Рубль вечером в понедельник слегка усилил снижение...
67 новостей (всего: 34524)
[684/1298] 2024-02-13:     Парсим новость 1: Производство сельхозпродукции в ЕАЭС снизилось на ...
    Парсим новость 2: Минсельхоз РФ предложил продлить запрет на экспорт...
    Парсим новость 3: Ориентир темпов роста сельхозпроизводства РФ предл...
65 новостей (всего: 34589)
[685/1298] 2024-02-14:     Парсим новость 1: ОАК увеличила годовой чистый убыток по РСБУ на 18%...
    Парсим новость 2: "Белавиа" будет летать из Гомеля во "Внуково" и "Ш...
    Парсим новость 3: ВВП Нидерландов в октябре-декабре вырос впервые за...
96 новостей (всего: 34685)
[686/1298] 2024-02-15:     Парсим новость 1: Финмодель ВСМ Москва-СПб включает 580 млрд рублей ...
    Парсим новость 2: Equinor остановила НПЗ Mongstad из-за возгорания...
    Парсим новость 3: Банки топ-10 с середины января снижают ставки по в...
88 новостей (всего: 34773)
[687/1298] 2024-02-16:     Парсим новость 1: Акционеры Совкомбанка обсудят увеличение уставного...
    Парсим новость 2: Совкомбанк ожидает одобрения регуляторами сделки п...
    Парсим новость 3: Совкомбанк после покупки ХКФ банка считает маловер...
78 новостей (всего: 34851)
[688/1298] 2024-02-17:     Парсим новость 1: Главы МИД G7 пообещали удерживать замороженными ак...
1 новостей (всего: 34852)
[689/1298] 2024-02-18:     Парсим новость 1: Президент России подверг критике экономическую пол...
    Парсим новость 2: Путин заявил, что Украина продолжает получать день...
2 новостей (всего: 34854)
[690/1298] 2024-02-19:     Парсим новость 1: EKF намерена стать провайдером облачной платформы ...
    Парсим новость 2: "ПИК" довел долю замещенных еврооблигаций-2026 до ...
    Парсим новость 3: Дальневосточную надбавку в энергетике могут "части...
83 новостей (всего: 34937)
  -> Сохранено во временный файл
[691/1298] 2024-02-20:     Парсим новость 1: РФ завершила поставку 200 тыс. тонн пшеницы в шест...
    Парсим новость 2: Путин разрешил сделки с акциями АО "Полиметалл"...
    Парсим новость 3: ОСК подала иск к финской Arctech Helsinki Shipyard...
80 новостей (всего: 35017)
[692/1298] 2024-02-21:     Парсим новость 1: Розничный портфель кредитов банков РФ в январе зам...
    Парсим новость 2: Закупки зерна в госфонд РФ в среду снизились до 12...
    Парсим новость 3: Долги по зарплате в РФ в январе выросли на 1,3% до...
86 новостей (всего: 35103)
[693/1298] 2024-02-22:     Парсим новость 1: "Балтика" намерена выращивать хмель в Чувашии...
    Парсим новость 2: Правительство РФ распространит меры поддержки на п...
    Парсим новость 3: Индекс крупнейших европейских компаний Stoxx 600 о...
94 новостей (всего: 35197)
[694/1298] 2024-02-23:     Парсим новость 1: СПБ банк изучит изменения в стратегию разблокировк...
    Парсим новость 2: "Трансконтейнер" и терминал Global Ports в Приморь...
    Парсим новость 3: США ввели санкции против IT-компании Газпромбанка ...
14 новостей (всего: 35211)
[695/1298] 2024-02-24:     Парсим новость 1: В ЕК пообещали Киеву первые 4,5 млрд евро макрофин...
    Парсим новость 2: Марио Драги уверен, что ЕС нужны срочные инвестици...
    Парсим новость 3: Костин назвал беспочвенными выдвинутые в его адрес...
3 новостей (всего: 35214)
[696/1298] 2024-02-25: 0 новостей
[697/1298] 2024-02-26:     Парсим новость 1: Qiwi предупредила о возможных рисках для buyback н...
    Парсим новость 2: Девелопер "Самолет" закрыл сделку по покупке собст...

    Парсим новость 3: Citigroup назначил главой банковского направления ...
73 новостей (всего: 35287)
[698/1298] 2024-02-27:     Парсим новость 1: Конго вошло в лигу стран-экспортеров СПГ, произвед...
    Парсим новость 2: Центробанк усматривает проинфляционный эффект в бо...
    Парсим новость 3: Некоторые участники дискуссии по ставке в РФ допус...
78 новостей (всего: 35365)
[699/1298] 2024-02-28:     Парсим новость 1: Россия и Иран расширят сотрудничество в ТЭК, автом...
    Парсим новость 2: "Транснефть" и Иран планируют сотрудничать в сфере...
    Парсим новость 3: Новак назвал преждевременным обсуждение планов доб...
105 новостей (всего: 35470)
[700/1298] 2024-02-29:     Парсим новость 1: Объем выдачи ипотеки в РФ в январе снизился на 3,5...
    Парсим новость 2: Россия в ближайшие 2-3 года может возобновить пром...
    Парсим новость 3: Рубль подрос к бивалютной корзине с учетом вероятн...
93 новостей (всего: 35563)
[701/1298] 2024-03-01:     Парсим новость 1: Сенаторы предложили отменить нулевой НДС при прода...
    Парсим новость 2: Участие офшоров в СПИК могут уточнить, предусмотре...
    Парсим новость 3: Рубль подешевел к основным валютам в первый день м...
81 новостей (всего: 35644)
[702/1298] 2024-03-02:     Парсим новость 1: ФСЭГ будет поддерживать привязку цен на газ к нефт...
    Парсим новость 2: РФ выступила за международное сотрудничество в защ...
    Парсим новость 3: Белоруссия повысила минимальные экспортные цены на...
3 новостей (всего: 35647)
[703/1298] 2024-03-03:     Парсим новость 1: Казахстан продлит добровольное сокращение добычи н...
    Парсим новость 2: ОАЭ продолжит дополнительно сокращать добычу нефти...
    Парсим новость 3: Алжир продлил дополнительное добровольное сокращен...
7 новостей (всего: 35654)
[704/1298] 2024-03-04:     Парсим новость 1: Индекс МосБиржи на вечерних торгах превысил 3300п ...
    Парсим новость 2: Рубль в понедельник слабо изменился к бивалютной к...
    Парсим новость 3: Отельерам могут снизить размер штрафов за нарушени...
63 новостей (всего: 35717)
[705/1298] 2024-03-05:     Парсим новость 1: Цена акций "Мосбиржи" обновила максимум с начала ф...
    Парсим новость 2: "Газпрому" разрешили самому определять перечень ра...
    Парсим новость 3: РЖД отметили рост экспорта алюминия "Русалом" на 1...
68 новостей (всего: 35785)
[706/1298] 2024-03-06:     Парсим новость 1: МТС в 2023 г. дополнительно приобрела 38% оператор...
    Парсим новость 2: Предварительная сумма сделки МТС по продаже бизнес...
    Парсим новость 3: Денежная масса в РФ в феврале увеличилась на 1,5%...
75 новостей (всего: 35860)
[707/1298] 2024-03-07:     Парсим новость 1: Правкомиссия по иностранным инвестициям одобрила п...
    Парсим новость 2: Акционеры Yandex N.V. одобрили продажу российского...
    Парсим новость 3: Запрет публикации статистики по добыче нефти и газ...
57 новостей (всего: 35917)
[708/1298] 2024-03-08:     Парсим новость 1: Минсельхоз США сохранил прогноз экспорта пшеницы и...
1 новостей (всего: 35918)
[709/1298] 2024-03-09:     Парсим новость 1: Сэм Альтман вернулся в совет директоров OpenAI пос...
    Парсим новость 2: Сенат США одобрил пакет законопроектов о расходах ...
2 новостей (всего: 35920)
[710/1298] 2024-03-10:     Парсим новость 1: Скончался президент Ассоциации банков России Лунто...
1 новостей (всего: 35921)
[711/1298] 2024-03-11:     Парсим новость 1: Гендиректором крупнейшей добычной "дочки" "Газпром...
    Парсим новость 2: Германия сократила дефицит бюджета почти на 10% в ...
    Парсим новость 3: Глава департамента информполитики "Газпрома" Купри...
68 новостей (всего: 35989)
[712/1298] 2024-03-12:     Парсим новость 1: "Северсталь" заявила о тенденции к повышению стоим...
    Парсим новость 2: Минэнерго США повысило оценку добычи нефти в стран...
    Парсим новость 3: "Северсталь" не исключила возможности направить на...
64 новостей (всего: 36053)
[713/1298] 2024-03-13:     Парсим новость 1: Суд запретил "Равису" выбирать СД из-за спора с но...
    Парсим новость 2: ЕП одобрил продление беспошлинной торговли для Укр...
    Парсим новость 3: ЦБ спрогнозировал замедление темпов роста средств ...
86 новостей (всего: 36139)
[714/1298] 2024-03-14:     Парсим новость 1: Реальный эффективный курс рубля в феврале снизился...
    Парсим новость 2: Чистая прибыль "Росгосстраха" по МСФО за 2023 год ...
    Парсим новость 3: Рубль в четверг почти не изменился к бивалютной ко...
65 новостей (всего: 36204)
[715/1298] 2024-03-15:     Парсим новость 1: Грузовой железнодорожный оператор "РэйлСпецТранс" ...
    Парсим новость 2: Курс рубля обновил минимумы за несколько недель на...
    Парсим новость 3: Думе предложили расширить антиотмывочные меры на о...
65 новостей (всего: 36269)
[716/1298] 2024-03-16: 0 новостей
[717/1298] 2024-03-17:     Парсим новость 1: ЦБ РФ подал иск к Киви банку...
1 новостей (всего: 36270)
[718/1298] 2024-03-18:     Парсим новость 1: Крупные банки с октября обяжут давать возможность ...
    Парсим новость 2: Microsoft обсуждает перенос срока приостановки дос...
    Парсим новость 3: Капитализация производителей электромобилей упала ...
48 новостей (всего: 36318)
[719/1298] 2024-03-19:     Парсим новость 1: Путин предложил ЕЭК проработать взаимодействие стр...
    Парсим новость 2: Wikimedia и Рinterest оштрафовали на 3 млн и 1 млн...
    Парсим новость 3: Рубль заметно подешевел к основным валютам на риск...
60 новостей (всего: 36378)
[720/1298] 2024-03-20:     Парсим новость 1: Пауэлл допустил начало снижения ставки ФРС в 2024 ...
    Парсим новость 2: ФРС повысила прогноз роста ВВП США на 2024 год до ...
    Парсим новость 3: ФРС сохранила базовую ставку в диапазоне 5,25-5,5%...
67 новостей (всего: 36445)
  -> Сохранено во временный файл
[721/1298] 2024-03-21:     Парсим новость 1: Рубль по итогам четверга подрос к основным валютам...
    Парсим новость 2: Рынок акций РФ в четверг превысил 3285п по индексу...
    Парсим новость 3: "Росатом" оценил потребность арктического флота дл...
80 новостей (всего: 36525)
[722/1298] 2024-03-22:     Парсим новость 1: РЖД объявили о начале подготовки к замещению части...
    Парсим новость 2: Девелопер "ПИК" не будет платить дивиденды за 2023...
    Парсим новость 3: Рубль в пятницу упал к мировым валютам после укреп...
91 новостей (всего: 36616)
[723/1298] 2024-03-23:     Парсим новость 1: Банки РФ пообещали списать всю задолженность погиб...
    Парсим новость 2: Французская Danone получила разрешение на продажу ...
    Парсим новость 3: "Газпром" подал в российский суд иск к австрийской...
5 новостей (всего: 36621)
[724/1298] 2024-03-24: 0 новостей
[725/1298] 2024-03-25:     Парсим новость 1: Израиль после принятия СБ ООН резолюции по Газе от...
    Парсим новость 2: Лондон обвинил Пекин в кибератаках на британские и...
    Парсим новость 3: Рубль в понедельник не изменился к бивалютной корз...
43 новостей (всего: 36664)
[726/1298] 2024-03-26:     Парсим новость 1: Член ЕК по сельскому хозяйству предупредил о риска...
    Парсим новость 2: Стоимость возвращенных государству предприятий ВПК...
    Парсим новость 3: Минцифры предложит ограничить круг IT-компаний с н...
56 новостей (всего: 36720)
[727/1298] 2024-03-27:     Парсим новость 1: Росстат отметил рост производства пиломатериалов и...
    Парсим новость 2: "Русская сталь" предупредила о последствиях отвязк...
    Парсим новость 3: "АЛРОСА" и Минфин заключили соглашение о выкупе ал...
89 новостей (всего: 36809)
[728/1298] 2024-03-28:     Парсим новость 1: Генпрокуратура РФ подала иск к "Макфе" и ряду ее к...
    Парсим новость 2: Создание всесезонного морского курорта "Горская" о...
    Парсим новость 3: Whoosh объединяет активы в Латинской Америке в хол...
75 новостей (всего: 36884)
[729/1298] 2024-03-29:     Парсим новость 1: NCOC выплатил $28 млн штрафа за сжигание газа и сб...
    Парсим новость 2: Газпромбанк в 2023 году получил почти 179 млрд руб...
    Парсим новость 3: МосБиржа исключит более 600 иностранных акций из с...
83 новостей (всего: 36967)
[730/1298] 2024-03-30:     Парсим новость 1: "Газпром" подал в суд иск о запрете OMV вести разб...
1 новостей (всего: 36968)
[731/1298] 2024-03-31: 0 новостей
[732/1298] 2024-04-01:     Парсим новость 1: Рынок российских операционных систем вырос в 2023 ...

    Парсим новость 2: Trump Media в 2023 г. зафиксировала чистый убыток ...
    Парсим новость 3: Рубль усилил рост к основным валютам на фоне дорож...
63 новостей (всего: 37031)
[733/1298] 2024-04-02:     Парсим новость 1: Минфин за месяц продал около 23 тонн золота из ФНБ...
    Парсим новость 2: ЦБ предложил включить финансовые сервисы в базовый...
    Парсим новость 3: СД "Трансконтейнера" рекомендовал выплатить 7 млрд...
71 новостей (всего: 37102)
[734/1298] 2024-04-03:     Парсим новость 1: Средняя зарплата в сфере производства в РФ выросла...
    Парсим новость 2: Путина попросили расширить в Забайкалье сеть АЗС с...
    Парсим новость 3: Золотодобытчик "Павлик" сократил годовой чистый уб...
76 новостей (всего: 37178)
[735/1298] 2024-04-04:     Парсим новость 1: "Союзплодоимпорт" в 2023 году увеличил выручку на ...
    Парсим новость 2: "ВУШ Холдинг" ожидает роста выручки в 2024 году вы...
    Парсим новость 3: Глава структурного подразделения "Лукойла" арестов...
73 новостей (всего: 37251)
[736/1298] 2024-04-05:     Парсим новость 1: РСПП предложил снизить федеральную часть налога на...
    Парсим новость 2: HeadHunter столкнулся с трудностями при закрытии р...
    Парсим новость 3: Рубль в пятницу немного подешевел в основных валют...
90 новостей (всего: 37341)
[737/1298] 2024-04-06: 0 новостей
[738/1298] 2024-04-07:     Парсим новость 1: Орский НПЗ приостанавливает работу на фоне подъема...
1 новостей (всего: 37342)
[739/1298] 2024-04-08:     Парсим новость 1: Выручка АФК "Система" по МСФО в 2023 году превысил...
    Парсим новость 2: Путин передал в управление Росимущества активы хол...
    Парсим новость 3: Рубль в понедельник несколько усилил темпы снижени...
78 новостей (всего: 37420)
[740/1298] 2024-04-09:     Парсим новость 1: Елена Михайлова из "Газпрома" возглавила "Холдинго...
    Парсим новость 2: Рубль во вторник немного ускорил снижение в основн...
    Парсим новость 3: США повысили прогноз добычи нефти в стране на 2024...
61 новостей (всего: 37481)
[741/1298] 2024-04-10:     Парсим новость 1: Минфин предложил с лета повысить минимальную цену ...
    Парсим новость 2: Владельцы ХКФ банка могут получить 5,4% в капитале...
    Парсим новость 3: Компания из США в кассации не смогла добиться подк...
74 новостей (всего: 37555)
[742/1298] 2024-04-11:     Парсим новость 1: X5 в 2024 году ожидает двузначного роста выручки...
    Парсим новость 2: "Дочка" Делимобиля открыла представительство в КНР...
    Парсим новость 3: Рубль в четверг развернулся вверх и укрепился к ос...
76 новостей (всего: 37631)
[743/1298] 2024-04-12:     Парсим новость 1: Георгиева останется на второй срок на посту главы ...
    Парсим новость 2: Суд в Петербурге частично удовлетворил иск "РусХим...
    Парсим новость 3: Правительство уточнило участие офшоров в СПИКах...
66 новостей (всего: 37697)
[744/1298] 2024-04-13:     Парсим новость 1: Правительство РФ установило для резидентов САР пра...
    Парсим новость 2: Первая партия российской свинины доставлена в Кита...
    Парсим новость 3: Глава "Газпром нефти" назвал увеличение добычи неф...
6 новостей (всего: 37703)
[745/1298] 2024-04-14:     Парсим новость 1: Казахстан в марте превысил квоту ОПЕК+ на 131 тыся...
    Парсим новость 2: Производителям гибридных авто дали возможность зак...
2 новостей (всего: 37705)
[746/1298] 2024-04-15:     Парсим новость 1: Рубль в понедельник завершил торги умеренным сниже...
    Парсим новость 2: OpenAI открыла первый офис в Азии...
    Парсим новость 3: Новым CFO Segezha назначен исполнительный директор...
63 новостей (всего: 37768)
[747/1298] 2024-04-16:     Парсим новость 1: В Минпромторге не исключили подорожания российских...
    Парсим новость 2: В руководстве ритейлера Х5 дивидендные перспективы...
    Парсим новость 3: Минэкономразвития может повысить прогноз роста ВВП...
87 новостей (всего: 37855)
[748/1298] 2024-04-17:     Парсим новость 1: Агростраховщики ждут сельскохозяйственных убытков ...
    Парсим новость 2: Гендиректор судоверфи "Красное Сормово" может доср...
    Парсим новость 3: СПбМТСБ в I квартале увеличила оборот на 58% - до ...
76 новостей (всего: 37931)
[749/1298] 2024-04-18:     Парсим новость 1: ВТБ и JP Morgan обменялись исками в России и США...
    Парсим новость 2: "Трансмашхолдинг" в 2023 году нарастил EBITDA в 1,...
    Парсим новость 3: Рубль в четверг ускорил рост к основным валютам...
81 новостей (всего: 38012)
[750/1298] 2024-04-19:     Парсим новость 1: СП с Ansaldo по турбинам, доставшееся ГЭХу вместе ...
    Парсим новость 2: Совет директоров Альфа-банка рассмотрит замещение ...
    Парсим новость 3: Власти РФ в 2,5 раза повысили пошлину на импорт пи...
73 новостей (всего: 38085)
  -> Сохранено во временный файл
[751/1298] 2024-04-20:     Парсим новость 1: Путин поручил оказать приоритетную господдержку аг...
1 новостей (всего: 38086)
[752/1298] 2024-04-21: 0 новостей
[753/1298] 2024-04-22:     Парсим новость 1: Минпромторг заявил, что мировое соглашение по делу...
    Парсим новость 2: "Роснано" договорилось с банками о досрочном погаш...
    Парсим новость 3: Минпромторг РФ ждет документы от Knauf о выходе из...
71 новостей (всего: 38157)
[754/1298] 2024-04-23:     Парсим новость 1: В Cheniere заявили, что предложение СПГ со старых ...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/957422 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021774CD52B0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
    Парсим новость 2: ЕЦБ рассмотрит снижение ставки, если прогнозы и ст...
    Парсим новость 3: Совет директоров МТС рекомендовал дивиденды за 202...
94 новостей (всего: 38251)
[755/1298] 2024-04-24:     Парсим новость 1: Экспорт газа из Азербайджана в Европу в 2024 г. мо...
    Парсим новость 2: Michelin в I квартале снизила выручку на 4,6%, хуж...
    Парсим новость 3: РФ в апреле может экспортировать рекордные 4,6 млн...
78 новостей (всего: 38329)
[756/1298] 2024-04-25:     Парсим новость 1: "Газпром" сообщил о рекордном объеме поставок газа...
    Парсим новость 2: Биржевые торги акциями МТС банка начнутся 26 апрел...
    Парсим новость 3: Путин и руководство РСПП обсудили контуры обновлен...
95 новостей (всего: 38424)
[757/1298] 2024-04-26:     Парсим новость 1: В Красном море танкер под флагом Панамы попал под ...
    Парсим новость 2: Выручка "Металлоинвеста" в 2023 году упала на 14%...
    Парсим новость 3: Ставки по ипотеке в США выросли 4-ю неделю подряд...
133 новостей (всего: 38557)
[758/1298] 2024-04-27:     Парсим новость 1: "Нижнекамскшина" снизила годовую чистую прибыль по...
    Парсим новость 2: ЕС призвал Россию пересмотреть решение о судьбе "д...
    Парсим новость 3: МТС выставила оферту для нерезидентов на выкуп до ...
66 новостей (всего: 38623)
[759/1298] 2024-04-28:     Парсим новость 1: Правительство РФ продлило квоты на экспорт удобрен...
    Парсим новость 2: Правительство РФ отменило экспортные пошлины на уг...
    Парсим новость 3: Песков заявил, что присвоение Западом активов РФ н...
3 новостей (всего: 38626)
[760/1298] 2024-04-29:     Парсим новость 1: Рубль умеренно снизился на фоне дешевеющей нефти и...
    Парсим новость 2: Рынок акций РФ начал неделю с роста индекса МосБир...
    Парсим новость 3: Японская Ono Pharmaceutical покупает американскую ...
21 новостей (всего: 38647)
[761/1298] 2024-04-30:     Парсим новость 1: Замороженные российские активы в I квартале принес...
    Парсим новость 2: Coca-Cola увеличила чистую прибыль в I кв. на 2%...
    Парсим новость 3: Рубль умеренно снижается к доллару и евро во вторн...
20 новостей (всего: 38667)
[762/1298] 2024-05-01:     Парсим новость 1: Глава ФРС заявил о  сохраняющемся высоком уровне и...
    Парсим новость 2: ФРС сохранила базовую ставку в диапазоне 5,25-5,5%...
    Парсим новость 3: США ввели санкции в отношении авиакомпании "Победа...
7 новостей (всего: 38674)
[763/1298] 2024-05-02:     Парсим новость 1: Кипр отклонил новый план освоения газового месторо...
    Парсим новость 2: Чистый убыток "Роснано" в 2023 году сократился в 3...
    Парсим новость 3: Суд арестовал акции российской "дочки" Commerzbank...

103 новостей (всего: 38777)
[764/1298] 2024-05-03:     Парсим новость 1: Рубль в пятницу укрепился к доллару и понизился к ...
    Парсим новость 2: SEC закрыла аудитора Trump Media за "масштабные ма...
    Парсим новость 3: АЕБ отметила замедление авторынка РФ на фоне адапт...
60 новостей (всего: 38837)
[765/1298] 2024-05-04:     Парсим новость 1: В Турции готовы экспортировать избыточные объемы г...
    Парсим новость 2: Газодобытчикам с объемом на менее 80 млрд куб. м р...
    Парсим новость 3: Еще одна компания обжаловала взыскание с экс-владе...
3 новостей (всего: 38840)
[766/1298] 2024-05-05: 0 новостей
[767/1298] 2024-05-06:     Парсим новость 1: Рубль в понедельник подрос к основным валютам...
    Парсим новость 2: В России выпуск бензина в последнюю неделю апреля ...
    Парсим новость 3: Росстат сообщил о снижении цен на овощи и фрукты н...
60 новостей (всего: 38900)
[768/1298] 2024-05-07:     Парсим новость 1: Путин разрешил "Лакра Синтез" купить лакокрасочный...
    Парсим новость 2: Новак заявил, что обсуждения увеличения добычи в р...
    Парсим новость 3: Минэнерго США понизило прогноз мирового спроса на ...
63 новостей (всего: 38963)
[769/1298] 2024-05-08:     Парсим новость 1: Shell продаст НПЗ и нефтехимические активы в Синга...
    Парсим новость 2: Токаев призвал устранить в ЕАЭС практику скрытых о...
    Парсим новость 3: Главы стран ЕАЭС одобрили начало переговоров о зон...
81 новостей (всего: 39044)
[770/1298] 2024-05-09:     Парсим новость 1: Турция будет ежегодно закупать у ExxonMobil до 2,5...
    Парсим новость 2: Китай в апреле снизил импорт нефти на 6% к марту...
    Парсим новость 3: "Дочка" Газпрома стала управляющей организацией ро...
3 новостей (всего: 39047)
[771/1298] 2024-05-10:     Парсим новость 1: Минсельхоз США оценил в 52 млн т экспорт пшеницы и...
    Парсим новость 2: Рубль умеренно подешевел на фоне пониженной активн...
    Парсим новость 3: Рынок акций РФ в пятницу подрос по индексу МосБирж...
19 новостей (всего: 39066)
[772/1298] 2024-05-11:     Парсим новость 1: Мишустин предложил переназначить Силуанова министр...
    Парсим новость 2: Новак станет куратором экономического блока в ново...
2 новостей (всего: 39068)
[773/1298] 2024-05-12:     Парсим новость 1: Минфин подготовит поправки к Бюджетному кодексу из...
    Парсим новость 2: Минфин РФ не видит рисков в уровне госдолга и расх...
    Парсим новость 3: Патрушев заявил, что у РФ есть фундамент для увели...
4 новостей (всего: 39072)
[774/1298] 2024-05-13:     Парсим новость 1: Роскомнадзор ждет от TikTok ответа о соблюдении се...
    Парсим новость 2: Рубль заметно укрепился на завершении формирования...
    Парсим новость 3: ЦБ РФ отметил продолжение роста корпоративного и р...
59 новостей (всего: 39131)
[775/1298] 2024-05-14:     Парсим новость 1: "Ростелеком" выпустит ЦФА на 1 млрд рублей...
    Парсим новость 2: Суд закроет рассмотрение иска Генпрокуратуры к свя...
    Парсим новость 3: BHP предлагала Anglo American выделение одного из ...
82 новостей (всего: 39213)
[776/1298] 2024-05-15:     Парсим новость 1: Чистый объем заказов Ubisoft в IV финквартале выро...
    Парсим новость 2: "Магнит" в IV квартале нарастил выручку на 10,5%, ...
    Парсим новость 3: Мантуров возглавил от РФ инвестиционную межправком...
112 новостей (всего: 39325)
[777/1298] 2024-05-16:     Парсим новость 1: Yadro рассчитывает занять 10-15% рынка планшетов в...
    Парсим новость 2: Спрос на детские лагеря на море снизился на 20-40%...
    Парсим новость 3: Калининградская "Варница" запустила производство с...
112 новостей (всего: 39437)
[778/1298] 2024-05-17:     Парсим новость 1: Новак кроме ТЭК будет курировать развитие экономик...
    Парсим новость 2: "Нижнекамскнефтехим" увеличил квартальную чистую п...
    Парсим новость 3: Мишустин утвердил обязанности Хуснуллина...
85 новостей (всего: 39522)
[779/1298] 2024-05-18:     Парсим новость 1: Арестованы активы UniCredit, DB, Commerzbank по ис...
    Парсим новость 2: Власти РФ ухудшили прогноз авиаперевозок в 2024-28...
    Парсим новость 3: В Белоруссии оценили почти в $1 млрд инвестиции ре...
4 новостей (всего: 39526)
[780/1298] 2024-05-19: 0 новостей
  -> Сохранено во временный файл
[781/1298] 2024-05-20:     Парсим новость 1: Китай в апреле сократил импорт российской нефти на...
    Парсим новость 2: Совет директоров "Русолова" рекомендовал не платит...
    Парсим новость 3: Минэнерго допустило продление временного запрета э...
80 новостей (всего: 39606)
[782/1298] 2024-05-21:     Парсим новость 1: Британия ввела запрет на импорт алюминия из Белору...
    Парсим новость 2: Goldman Sachs стал "чуть более оптимистично" оцени...
    Парсим новость 3: "Акрон" в 2023 году увеличил capex на 23% до $531 ...
76 новостей (всего: 39682)
[783/1298] 2024-05-22:     Парсим новость 1: Гендиректор En+ Хардиков покинул компанию спустя п...
    Парсим новость 2: Путин разрешил российскому American Express Bank п...
    Парсим новость 3: Путин разрешил добровольную ликвидацию российского...
81 новостей (всего: 39763)
[784/1298] 2024-05-23:     Парсим новость 1: ЦБ РФ проведет киберучения с нацбанками стран БРИК...
    Парсим новость 2: РФ в 2024 г. увеличит экспорт свинины до 310 тыс. ...
    Парсим новость 3: Дивиденды крупнейших компаний мира в I квартале со...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/961991 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021774ACE480>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
84 новостей (всего: 39847)
[785/1298] 2024-05-24:     Парсим новость 1: BOTAS и "Газпром" работают над созданием в Стамбул...
    Парсим новость 2: Азербайджан повысил цену на нефть в госбюджете-202...
    Парсим новость 3: Альфа-банк подал иск к кипрской ABH Financial Ltd ...
75 новостей (всего: 39922)
[786/1298] 2024-05-25:     Парсим новость 1: G7 заявила о прогрессе в обсуждении схем использов...
    Парсим новость 2: Министры финансов G7 пообещали добиваться соблюден...
    Парсим новость 3: Силуанов подтвердил планы зеркального ответа на ис...
5 новостей (всего: 39927)
[787/1298] 2024-05-26: 0 новостей
[788/1298] 2024-05-27:     Парсим новость 1: Совет директоров "Башнефти" дал рекомендации по ди...
    Парсим новость 2: "Росатом" планирует в этом году приобрести первые ...
    Парсим новость 3: Скорректированная EBITDA "ФосАгро" в I квартале уп...
82 новостей (всего: 40009)
[789/1298] 2024-05-28:     Парсим новость 1: Минфин предлагает ввести акциз на жидкий никотин и...
    Парсим новость 2: Налоговый пакет Минфина даст около 2,6 трлн руб. в...
    Парсим новость 3: Минфин предложил расширить прогрессию в НДФЛ до 22...
63 новостей (всего: 40072)
[790/1298] 2024-05-29:     Парсим новость 1: В Beige Book отмечено продолжение сдержанного рост...
    Парсим новость 2: Опубликована часть решения о взыскании с Deutsche ...
    Парсим новость 3: Эксперты считают предложенный для IT налог на приб...
106 новостей (всего: 40178)
[791/1298] 2024-05-30:     Парсим новость 1: Чистая прибыль "Роснефти" в I кв. по МСФО составил...
    Парсим новость 2: Турция в марте резко нарастила импорт как нефти, т...
    Парсим новость 3: Дефицит бюджета РФ в январе-апреле вырос почти до ...
67 новостей (всего: 40245)
[792/1298] 2024-05-31:     Парсим новость 1: Экспортерам разрешат не продавать валюту, если кон...
    Парсим новость 2: Курс рубля скорректировался вниз в последний день ...
    Парсим новость 3: Совет директоров "Магнита" рекомендовал дивиденды-...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/964277 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A93AA20>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
84 новостей (всего: 40329)
[793/1298] 2024-06-01:     Парсим новость 1: Страны "семерки" изучают варианты санкций против б...
    Парсим новость 2: Пошлина на экспорт подсолнечного масла из РФ в июн...
    Парсим новость 3: РФ в июне должна снизить добычу нефти до 9 млн б/с...
3 новостей (всего: 40332)
[794/1298] 2024-06-02:     Парсим новость 1: ОПЕК+ обещает сократить добычу нефти сверх ожидани...

    Парсим новость 2: РФ работает со вторичными источниками для обновлен...
    Парсим новость 3: "Добровольцы" ОПЕК+ продлят ограничения в 1,7 млн ...
8 новостей (всего: 40340)
[795/1298] 2024-06-03:     Парсим новость 1: IDC ожидает слабых изменений мировых поставок ПК и...
    Парсим новость 2: Акцизы на никотиновое сырье и бестабачные смеси в ...
    Парсим новость 3: Рубль в понедельник уверенно вырос к основным валю...
69 новостей (всего: 40409)
[796/1298] 2024-06-04:     Парсим новость 1: Рубль во вторник умеренно подрос к основным валюта...
    Парсим новость 2: Occidental Petroleum и "дочка" подразделения Berks...
    Парсим новость 3: Брокер "Финам" ограничит вывод долларов в сторонни...
65 новостей (всего: 40474)
[797/1298] 2024-06-05:     Парсим новость 1: Объем каршеринговых услуг в РФ в апреле вырос на 1...
    Парсим новость 2: Оборот телеком-компаний в РФ в апреле вырос на 7,7...
    Парсим новость 3: Минцифры РФ обсуждает создание единой платформы по...
109 новостей (всего: 40583)
[798/1298] 2024-06-06:     Парсим новость 1: Рубль в четверг немного скорректировался вниз к ос...
    Парсим новость 2: РФ продлит механизм параллельного импорта на 2025 ...
    Парсим новость 3: Ozon получил разрешение правкомиссии РФ на редомиц...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /spief2024/965353 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A93B8C0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
137 новостей (всего: 40720)
[799/1298] 2024-06-07:     Парсим новость 1: Промсвязьбанк запустит виртуального сотового опера...
    Парсим новость 2: Замглавы "Ростеха" Игорь Завьялов выдвинут в совет...
    Парсим новость 3: Набиуллина объяснила повышение ставок по депозитов...
145 новостей (всего: 40865)
[800/1298] 2024-06-08:     Парсим новость 1: ВЭБ видит флоатеры основным долговым инструментом ...
    Парсим новость 2: "Циан" может провести обмен бумаг для миноритариев...
    Парсим новость 3: НРД планирует осенью запуск сервиса быстрого перев...
17 новостей (всего: 40882)
[801/1298] 2024-06-09: 0 новостей
[802/1298] 2024-06-10:     Парсим новость 1: Гендиректор ЕМС Яновский передал свою долю в компа...
    Парсим новость 2: ВТБ с 11 июня повысит первоначальный взнос по ряду...
    Парсим новость 3: "Интер РАО" рассчитывает в 2024 году подписать кон...
80 новостей (всего: 40962)
[803/1298] 2024-06-11:     Парсим новость 1: Минсельхоз РФ сохраняет прогноз сбора черешни на у...
    Парсим новость 2: Рубль во вторник скорректировался вниз к основным ...
    Парсим новость 3: США повысило прогноз добычи нефти в стране на 2024...
68 новостей (всего: 41030)
[804/1298] 2024-06-12:     Парсим новость 1: Пауэлл заявил, что ФРС нужно больше уверенности в ...
    Парсим новость 2: Дефицит бюджета США в мае вырос на 44% до $347 млр...
    Парсим новость 3: ФРС ожидает снижения ставки в 2024 г., повысила пр...
17 новостей (всего: 41047)
[805/1298] 2024-06-13:     Парсим новость 1: ЦБ РФ временно отменяет утренние торги на МосБирже...
    Парсим новость 2: Российский ИТ-рынок проходит через санкционную обл...
    Парсим новость 3: Глава "Росатома" оценил стоимость строительства АЭ...
79 новостей (всего: 41126)
[806/1298] 2024-06-14:     Парсим новость 1: ВТБ временно приостановит выдачу IT-ипотеки из-за ...
    Парсим новость 2: ВТБ с 17 июня повысит на 0,5 п.п. базовую ставку п...
    Парсим новость 3: Оборот внебиржевого рынка с расчетами "завтра" в п...
69 новостей (всего: 41195)
[807/1298] 2024-06-15:     Парсим новость 1: В "Газпроме" назвали дополнительные источники газа...
    Парсим новость 2: "Полка" добычи газа на проекте "Сахалин-2" продлен...
    Парсим новость 3: В "Газпроме" заявили, что "Сахалин-2" все более ув...
5 новостей (всего: 41200)
[808/1298] 2024-06-16: 0 новостей
[809/1298] 2024-06-17:     Парсим новость 1: Акционеры "М.Видео" утвердили решение не выплачива...
    Парсим новость 2: МИД РФ заявил, что подобные швейцарской встречи по...
    Парсим новость 3: Доля внешнеторговых платежей РФ в токсичных валюта...
35 новостей (всего: 41235)
[810/1298] 2024-06-18:     Парсим новость 1: Wildberries и группа Russ создадут совместную цифр...
    Парсим новость 2: Кабмин выпустил постановление о "русификации" влад...
    Парсим новость 3: Рубль во вторник заметно вырос в паре с юанем...
38 новостей (всего: 41273)
  -> Сохранено во временный файл
[811/1298] 2024-06-19:     Парсим новость 1: Совкомбанк планирует присоединить ХКФ банк зимой...
    Парсим новость 2: Доля расчетов между РФ и Вьетнамом в рублях и донг...
    Парсим новость 3: Минсельхоз ожидает сохранения стабильной ценовой с...
53 новостей (всего: 41326)
[812/1298] 2024-06-20:     Парсим новость 1: Пенсии работающих пенсионеров с 2025 года будут ин...
    Парсим новость 2: РФ в мае снизила экспорт нефти в КНР к апрелю почт...
    Парсим новость 3: Зампредом правкомиссии по иностранным инвестициям ...
43 новостей (всего: 41369)
[813/1298] 2024-06-21:     Парсим новость 1: Сбербанк рассчитывает на увеличение прибыли в 2024...
    Парсим новость 2: KKR купила организатора ведущих музыкальных фестив...
    Парсим новость 3: "Карвиль" планирует к 2027 году увеличить производ...
40 новостей (всего: 41409)
[814/1298] 2024-06-22:     Парсим новость 1: Объем заблокированной из-за санкций в отношении Мо...
    Парсим новость 2: "Интерлизинг" планирует IPO на Мосбирже...
    Парсим новость 3: Совкомбанк откроет свой НПФ...
5 новостей (всего: 41414)
[815/1298] 2024-06-23: 0 новостей
[816/1298] 2024-06-24:     Парсим новость 1: Совладелец инвестгруппы "Русские фонды" Васильев о...
    Парсим новость 2: ЧКПЗ не ожидает влияния санкций ЕС на производство...
    Парсим новость 3: Национальный клиринговый центр сконвертирует гонко...
37 новостей (всего: 41451)
[817/1298] 2024-06-25:     Парсим новость 1: ВС РФ отменил решения судов о взыскании в пользу Р...
    Парсим новость 2: Куратор формирования бюджета Окладникова стала пер...
    Парсим новость 3: Qatar Airways стала лидером рейтинга авиакомпаний ...
35 новостей (всего: 41486)
[818/1298] 2024-06-26:     Парсим новость 1: Мосбиржа допустила акции онлайн-ритейлера "Всеинст...
    Парсим новость 2: Производство стабильного газового конденсата в РФ ...
    Парсим новость 3: Новым CEO Segezha станет первый вице-президент ком...
50 новостей (всего: 41536)
[819/1298] 2024-06-27:     Парсим новость 1: "Тольяттиазот" планирует увеличить производство ам...
    Парсим новость 2: Кабмин предписал РСХБ выплатить дивиденды за 2023 ...
    Парсим новость 3: Рубль в четверг вырос в паре с юанем перед налогов...
33 новостей (всего: 41569)
[820/1298] 2024-06-28:     Парсим новость 1: "Почта России" увеличит уставный капитал на 65 млр...
    Парсим новость 2: Акционеры "Роснефти" утвердили финальные дивиденды...
    Парсим новость 3: Пошлина на экспорт пшеницы из РФ с 3 июля снизится...
52 новостей (всего: 41621)
[821/1298] 2024-06-29:     Парсим новость 1: Правительство России разрешило экспорт бензина на ...
1 новостей (всего: 41622)
[822/1298] 2024-06-30: 0 новостей
[823/1298] 2024-07-01:     Парсим новость 1: Рубль в понедельник подешевел в паре с юанем...
    Парсим новость 2: Рынок акций РФ начал неделю с роста выше 3185 пунк...
    Парсим новость 3: Акционеры "РусГидро" не приняли решение по дивиден...
86 новостей (всего: 41708)
[824/1298] 2024-07-02:     Парсим новость 1: Бенефициары смогут раздробить свое право на вступл...
    Парсим новость 2: ЦБ зарегистрировал допэмиссию "М.Видео" на 17% от ...
    Парсим новость 3: ЭЗО будут обязаны уведомлять Минэкономразвития и Ц...
65 новостей (всего: 41773)
[825/1298] 2024-07-03:     Парсим новость 1: Богатые клиенты британских УК продают активы в ожи...
    Парсим новость 2: АСВ хочет вступить в дело о банкротстве экс-владел...
    Парсим новость 3: Акционеры IVA Technologies решили не выплачивать д...
89 новостей (всего: 41862)
[826/1298] 2024-07-04: 0 новостей
[827/1298] 2024-07-05: 0 новостей
[828/1298] 2024-07-06: 0 новостей
[829/1298] 2024-07-07: 0 новостей
[830/1298] 2024-07-08: 0 новостей
[831/1298] 2024-07-09: 0 новостей
[832/1298] 2024-07-10: 0 новостей

[833/1298] 2024-07-11: 0 новостей
[834/1298] 2024-07-12: 0 новостей
[835/1298] 2024-07-13: 0 новостей
[836/1298] 2024-07-14:     Парсим новость 1: Европейским компаниям с собственниками из Белорусс...
1 новостей (всего: 41863)
[837/1298] 2024-07-15:     Парсим новость 1: Поэтапная индексация утильсбора в автопроме может ...
    Парсим новость 2: Утильсбор на автотехнику в РФ планируют повысить н...
    Парсим новость 3: ЦБ РФ закрыл статистику внебиржевого валютного рын...
73 новостей (всего: 41936)
[838/1298] 2024-07-16:     Парсим новость 1: Золото подорожало до рекорда...
    Парсим новость 2: Рубль во вторник немного укрепился в паре с юанем ...
    Парсим новость 3: Рынок акций РФ во вторник подрос к 2945 п. по инде...
54 новостей (всего: 41990)
[839/1298] 2024-07-17:     Парсим новость 1: ЦБ обяжет банки запретить клиентам передавать элек...
    Парсим новость 2: ФАС запросит у нефтяников экономическое обосновани...
    Парсим новость 3: Смоленская АЭС отключила на ремонт энергоблок №3...
61 новостей (всего: 42051)
[840/1298] 2024-07-18:     Парсим новость 1: Алиев обсудил поставки газа в Чехию с премьером эт...
    Парсим новость 2: Зарубежнефть учредила структуру под геотермальный ...
    Парсим новость 3: "Ростелеком" консолидировал 100% интегратора инфор...
59 новостей (всего: 42110)
  -> Сохранено во временный файл
[841/1298] 2024-07-19:     Парсим новость 1: Падение Stoxx Europe 600 пять дней подряд стало са...
    Парсим новость 2: Котировки золота падают более чем на 2%...
    Парсим новость 3: Рубль в пятницу подорожал к юаню...
55 новостей (всего: 42165)
[842/1298] 2024-07-20:     Парсим новость 1: Группа Т-Банка выкупила контрольные доли в фактори...
    Парсим новость 2: В Минтрансе РФ стоит вопрос о повышении аэронавига...
    Парсим новость 3: Старовойт заявил, что выделение допсредств ФНБ на ...
5 новостей (всего: 42170)
[843/1298] 2024-07-21:     Парсим новость 1: Алиев заявил, что добыча газа в Азербайджане в 202...
    Парсим новость 2: Алиев назвал ложью утверждения, что Азербайджан за...
2 новостей (всего: 42172)
[844/1298] 2024-07-22:     Парсим новость 1: КНР в июне слегка снизила импорт российской нефти ...
    Парсим новость 2: Рубль к вечеру растерял рост, по итогам торгов не ...
    Парсим новость 3: Американская Clearwater Paper продала бизнес по вы...
66 новостей (всего: 42238)
[845/1298] 2024-07-23:     Парсим новость 1: LVMH в I полугодии сократила чистую прибыль на 14%...
    Парсим новость 2: Рынок акций РФ консолидировался у 3030 пунктов по ...
    Парсим новость 3: Нефть ускорила снижение, Brent упала до $81,1 за б...
64 новостей (всего: 42302)
[846/1298] 2024-07-24:     Парсим новость 1: "Финам" планирует в августе предоставить доступ к ...
    Парсим новость 2: Основным акционером "М.Видео" стал гендиректор ком...
    Парсим новость 3: Россельхознадзор запретил транзит продукции птицев...
76 новостей (всего: 42378)
[847/1298] 2024-07-25:     Парсим новость 1: Индия выразила заинтересованность в увеличении пос...
    Парсим новость 2: Суд в РФ отметил, что иск держателя евробондов к "...
    Парсим новость 3: Американский владелец складов Lineage провел IPO о...
83 новостей (всего: 42461)
[848/1298] 2024-07-26:     Парсим новость 1: Миноритарии ЭЗО с владением через недружественные ...
    Парсим новость 2: Рубль вечером перешел к снижению перед выходными д...
    Парсим новость 3: Депутаты согласились на экспериментальные биржевые...
78 новостей (всего: 42539)
[849/1298] 2024-07-27: 0 новостей
[850/1298] 2024-07-28: 0 новостей
[851/1298] 2024-07-29:     Парсим новость 1: Банк России определил порядок выплат по евробондам...
    Парсим новость 2: TotalEnergies и Qatar Energy уйдут из газоконденса...
    Парсим новость 3: ВТБ доразместит замещающие облигации под "вечные" ...
53 новостей (всего: 42592)
[852/1298] 2024-07-30:     Парсим новость 1: Рубль во вторник подешевел в паре с юанем в рамках...
    Парсим новость 2: Рынок акций РФ во вторник поднялся к 2945п по инде...
    Парсим новость 3: РСХБ сообщил о продолжении работы карт Union Pay з...
72 новостей (всего: 42664)
[853/1298] 2024-07-31:     Парсим новость 1: ФРС ожидаемо сохранила базовую ставку в диапазоне ...
    Парсим новость 2: Минэкономразвития сообщило о росте экономики Росси...
    Парсим новость 3: В июне в России выпуск по базовым видам деятельнос...
82 новостей (всего: 42746)
[854/1298] 2024-08-01:     Парсим новость 1: Менеджмент МДМГ предлагает направлять на дивиденды...
    Парсим новость 2: Pirelli сократил полугодовую чистую прибыль на 4,7...
    Парсим новость 3: Минсельхоз сообщил об экспорте из России в прошлом...
85 новостей (всего: 42831)
[855/1298] 2024-08-02:     Парсим новость 1: "Дочка" "Софтлайна" получила взаймы 3% акций матер...
    Парсим новость 2: "Промомед" докапитализирует на 1,1 млрд рублей R&D...
    Парсим новость 3: Revolut позволит сотрудникам продать акции на сумм...
65 новостей (всего: 42896)
[856/1298] 2024-08-03:     Парсим новость 1: Промсвязьбанк получил в залог 100% ООО "Балтийский...
1 новостей (всего: 42897)
[857/1298] 2024-08-04: 0 новостей
[858/1298] 2024-08-05:     Парсим новость 1: Сбербанк с 6 августа повысит ставки по ипотеке...
    Парсим новость 2: "Судоремонт" обжалует изъятие у него участка в Мах...
    Парсим новость 3: Европейские рынки акций завершили торги резким сни...
69 новостей (всего: 42966)
[859/1298] 2024-08-06:     Парсим новость 1: Временные правила очередности грузоперевозок по се...
    Парсим новость 2: США чуть понизили прогноз цены газа на Henry Hub в...
    Парсим новость 3: Мосбиржа введет маркировку "зеленых" облигаций до ...
68 новостей (всего: 43034)
[860/1298] 2024-08-07:     Парсим новость 1: Скорректированная EBITDA "ФосАгро" во II квартале ...
    Парсим новость 2: Минэнерго заявило, что спрос на топливо в РФ обесп...
    Парсим новость 3: МТС запустила вторую оферту для нерезидентов на вы...
77 новостей (всего: 43111)
[861/1298] 2024-08-08:     Парсим новость 1: Рубль в четверг опустился в паре с юанем, несмотря...
    Парсим новость 2: Рынок акций РФ в четверг просел к 2850п по индексу...
    Парсим новость 3: Владимирский производитель колбас "Стародворье" и ...
67 новостей (всего: 43178)
[862/1298] 2024-08-09:     Парсим новость 1: Минцифры и разработчики ПО готовят предложение по ...
    Парсим новость 2: Возможное введение платы за использование западног...
    Парсим новость 3: ТБанк во II квартале увеличил кредитный портфель п...
74 новостей (всего: 43252)
[863/1298] 2024-08-10:     Парсим новость 1: Транзит газа через Украину растет, заявка "Газпром...
1 новостей (всего: 43253)
[864/1298] 2024-08-11:     Парсим новость 1: Транзит через Украину остаётся на прежнем уровне, ...
1 новостей (всего: 43254)
[865/1298] 2024-08-12:     Парсим новость 1: Рубль в понедельник развернулся вниз и немного опу...
    Парсим новость 2: Индекс МосБиржи снизился в понедельник на 0,1%, от...
    Парсим новость 3: ПАО "ИКС 5" начало распределение акций после приос...
53 новостей (всего: 43307)
[866/1298] 2024-08-13:     Парсим новость 1: Kismet Capital продаст медиаактивы группе инвестор...
    Парсим новость 2: "СОГАЗ" упростил урегулирование убытков жителям Ку...
    Парсим новость 3: Рубль во вторник упал в паре с юанем, обновив мини...
58 новостей (всего: 43365)
[867/1298] 2024-08-14:     Парсим новость 1: В совет директоров АФК "Система" может войти Фелик...
    Парсим новость 2: Минстрой России сообщил о вводе 62,2 млн кв. м жил...
    Парсим новость 3: Рубль на "Мосбирже" подорожал к юаню в рамках корр...
69 новостей (всего: 43434)
[868/1298] 2024-08-15:     Парсим новость 1: Новый CEO Starbucks Никкол обойдется компании боле...
    Парсим новость 2: Подкомиссия одобрила продление до осени 2026 г. по...
    Парсим новость 3: Рубль опустился в паре с юанем после сильного рост...
64 новостей (всего: 43498)
[869/1298] 2024-08-16:     Парсим новость 1: Маркировку автомобильных жидкостей в РФ планируетс...
    Парсим новость 2: Иностранные граждане будут проходить собеседование...
    Парсим новость 3: Сбор зерна в РФ к 14 августа на 8,2 млн т меньше п...
59 новостей (всего: 43557)
[870/1298] 2024-08-17:     Парсим новость 1: Посол Ирана заявил, что страна заинтересована в тр...
    Парсим новость 2: Российский газ подается для транзита через Украину...

2 новостей (всего: 43559)
  -> Сохранено во временный файл
[871/1298] 2024-08-18:     Парсим новость 1: Российский газ подается для транзита через Украину...
1 новостей (всего: 43560)
[872/1298] 2024-08-19:     Парсим новость 1: Совет директоров "ТКС Холдинга" утвердил дивидендн...
    Парсим новость 2: Глобальные инвестфонды провели 13 сделок объемом с...
    Парсим новость 3: В Евросоюзе во II квартале увеличилось число банкр...
52 новостей (всего: 43612)
[873/1298] 2024-08-20:     Парсим новость 1: Нефтегазовые компании создали "Консорциум технолог...
    Парсим новость 2: Экспорт электроэнергии из РФ до 2042 г. оцениваетс...
    Парсим новость 3: Boeing приостанавливает испытания лайнеров 777X из...
63 новостей (всего: 43675)
[874/1298] 2024-08-21:     Парсим новость 1: Руководители ФРС готовы начать снижение ставки в с...
    Парсим новость 2: Банкам введут срок для уведомления об изменении "п...
    Парсим новость 3: Челябинский суд оставил без рассмотрения иск ММК к...
69 новостей (всего: 43744)
[875/1298] 2024-08-22:     Парсим новость 1: Энергоблок №8 мощностью 1,2 ГВт планируют построит...
    Парсим новость 2: Глава ФРБ Филадельфии заявил, что Федрезерву следу...
    Парсим новость 3: Сбербанк запустил публичные программы багбаунти дл...
68 новостей (всего: 43812)
[876/1298] 2024-08-23:     Парсим новость 1: Аграрная отрасль РФ в 2023 году потеряла 200 тыс. ...
    Парсим новость 2: Чистая прибыль "Трансконтейнера" по РСБУ снизилась...
    Парсим новость 3: В санкционный список США внесли ООО "Сжиженный при...
67 новостей (всего: 43879)
[877/1298] 2024-08-24:     Парсим новость 1: Потребление газа в РФ обновило августовский максим...
    Парсим новость 2: Производители малотоннажного СПГ смогут беспошлинн...
2 новостей (всего: 43881)
[878/1298] 2024-08-25:     Парсим новость 1: ГК "Абрау-Дюрсо" начала производство игристых напи...
    Парсим новость 2: Потребление газа в России обновило абсолютный летн...
2 новостей (всего: 43883)
[879/1298] 2024-08-26:     Парсим новость 1: "Роснано" увеличило полугодовую выручку по РСБУ в ...
    Парсим новость 2: Быстринский ГОК "Норникеля" не будет выплачивать д...
    Парсим новость 3: Участвовать в расконвертации ADR "Норникеля" смогу...
55 новостей (всего: 43938)
[880/1298] 2024-08-27:     Парсим новость 1: Акционеры Qiwi утвердили смену названия компании н...
    Парсим новость 2: Рубль во вторник понизился в паре с юанем после ро...
    Парсим новость 3: Рынок акций РФ во вторник возобновил снижение всле...
61 новостей (всего: 43999)
[881/1298] 2024-08-28:     Парсим новость 1: Выпуск по базовым видам деятельности в РФ в июле в...
    Парсим новость 2: Росстат сообщил о росте реальных зарплат в июне на...
    Парсим новость 3: Выпуск золота в РФ в июле вырос на 10,1%...
90 новостей (всего: 44089)
[882/1298] 2024-08-29:     Парсим новость 1: Чистая прибыль FESCO по МСФО в I полугодии сократи...
    Парсим новость 2: Девелопер "ПИК" в I полугодии снизил скорректирова...
    Парсим новость 3: АФК "Система" во II квартале нарастила выручку на ...
103 новостей (всего: 44192)
[883/1298] 2024-08-30:     Парсим новость 1: Правительство утвердило переходные положения по ма...
    Парсим новость 2: Оборот e-commerce "Магнита" в I полугодии вырос в ...
    Парсим новость 3: ФАС будет контролировать сделки крупных финансовых...
84 новостей (всего: 44276)
[884/1298] 2024-08-31: 0 новостей
[885/1298] 2024-09-01:     Парсим новость 1: Энергопотребление в ЕЭС России в 2024 году может в...
    Парсим новость 2: Три беспилотника сбито над Тульской областью...
    Парсим новость 3: Россия с 1 сентября сняла запрет на экспорт рапса,...
4 новостей (всего: 44280)
[886/1298] 2024-09-02:     Парсим новость 1: Гонконгская Cathay Pacific отменила 24 рейса из-за...
    Парсим новость 2: X5 Retail Group N.V. намерена провести делистинг с...
    Парсим новость 3: Рубль в понедельник растерял дневной рост и лишь с...
35 новостей (всего: 44315)
[887/1298] 2024-09-03:     Парсим новость 1: "Металлоинвест" направит на дивиденды по итогам I ...
    Парсим новость 2: Продажи дизтоплива на Петербургской бирже в август...
    Парсим новость 3: ФНС исключит из перечня для автообмена страновыми ...
45 новостей (всего: 44360)
[888/1298] 2024-09-04:     Парсим новость 1: Акционеры АФК "Система" избрали совет директоров и...
    Парсим новость 2: Правительство Германии предложило налоговые льготы...
    Парсим новость 3: ГТЛК объявила конкурс на строительство двух паромо...
74 новостей (всего: 44434)
[889/1298] 2024-09-05:     Парсим новость 1: Суд наложил арест на акции Райффайзенбанка из-за с...
    Парсим новость 2: Рубль в четверг уверенно вырос в паре с юанем...
    Парсим новость 3: Восемь стран ОПЕК+ отложили на два месяца увеличен...
71 новостей (всего: 44505)
[890/1298] 2024-09-06:     Парсим новость 1: Суд отклонил кассационную жалобу Linde на взыскани...
    Парсим новость 2: Минэкономразвития ожидает ослабления рубля к концу...
    Парсим новость 3: Прогноз Минэкономразвития по экспортной цене нефти...
46 новостей (всего: 44551)
[891/1298] 2024-09-07: 0 новостей
[892/1298] 2024-09-08:     Парсим новость 1: Аналитики подсчитали, что Маск может стать триллио...
1 новостей (всего: 44552)
[893/1298] 2024-09-09:     Парсим новость 1: MOL Group нашла решение для поставок нефти в Венгр...
    Парсим новость 2: Шерегешский рудник "Евраз ЗСМК" приостановил работ...
    Парсим новость 3: Маркировку стройматериалов в РФ предлагается ввест...
58 новостей (всего: 44610)
[894/1298] 2024-09-10:     Парсим новость 1: Минэнерго США понизило прогноз цены Brent в 2024 г...
    Парсим новость 2: Рубль подешевел в паре с юанем на фоне сильного па...
    Парсим новость 3: Индекс МосБиржи снизился до 2670 пунктов из-за упа...
55 новостей (всего: 44665)
[895/1298] 2024-09-11:     Парсим новость 1: Депутат Аксаков допустил, что ЦБ РФ в пятницу сохр...
    Парсим новость 2: Аналитики ждут сохранения ставки ЦБ в пятницу на у...
    Парсим новость 3: Spirit Airlines договорилась о продлении срока рес...
62 новостей (всего: 44727)
[896/1298] 2024-09-12:     Парсим новость 1: "Элемент" ожидает роста выручки по итогам 2024 год...
    Парсим новость 2: Готовы 55 из 800 км газопровода Белогорск - Хабаро...
    Парсим новость 3: Дефицит бюджета США в августе был максимальным за ...
60 новостей (всего: 44787)
[897/1298] 2024-09-13:     Парсим новость 1: Дмитрий Патрушев поручил изучить повышение приорит...
    Парсим новость 2: Акционеры Росбанка 1 ноября рассмотрят вопрос о ег...
    Парсим новость 3: "Софтлайн" 16 сентября начнет размещение акций доп...
82 новостей (всего: 44869)
[898/1298] 2024-09-14: 0 новостей
[899/1298] 2024-09-15:     Парсим новость 1: СМИ сообщили о давлении Турции и Египта на Ливию д...
1 новостей (всего: 44870)
[900/1298] 2024-09-16:     Парсим новость 1: Правительство разрешило экспорт аммиачной селитры ...
    Парсим новость 2: Весь внешнеторговый профицит РФ в июле сформировал...
    Парсим новость 3: Утвержден текст межправсоглашения по строительству...
55 новостей (всего: 44925)
  -> Сохранено во временный файл
[901/1298] 2024-09-17:     Парсим новость 1: Лукашенко заявил, что США ожидают эскалации конфли...
    Парсим новость 2: Нефть Brent подорожала до $73,36 за баррель...
    Парсим новость 3: Рубль вырос по итогам торгов во вторник на фоне ув...
52 новостей (всего: 44977)
[902/1298] 2024-09-18:     Парсим новость 1: ФРС ожидает роста ВВП США на 2% в 2024-2027 годах...
    Парсим новость 2: ФРС снизила базовую ставку на 50 базисных пунктов ...
    Парсим новость 3: Что произошло за день: среда, 18 сентября...
80 новостей (всего: 45057)
[903/1298] 2024-09-19:     Парсим новость 1: Евросоюз экстренно выделит 10 млрд евро пострадавш...
    Парсим новость 2: Комитет Госдумы предложил ввести уведомления для з...
    Парсим новость 3: Минцифры утвердило приказ о скидках по оплате част...
67 новостей (всего: 45124)
[904/1298] 2024-09-20:     Парсим новость 1: Китай в августе на четверть увеличил закупки росси...
    Парсим новость 2: Канада запустит комплекс переработки редкоземельны...
    Парсим новость 3: Правительство ФРГ решило пока больше не продавать ...
63 новостей (всего: 45187)

[905/1298] 2024-09-21:     Парсим новость 1: Boeing объявил об уходе главы Boeing Defense, Spac...
1 новостей (всего: 45188)
[906/1298] 2024-09-22: 0 новостей
[907/1298] 2024-09-23:     Парсим новость 1: Сбербанк 30 сентября начнет размещение выпуска обл...
    Парсим новость 2: Что произошло за день: понедельник, 23 сентября...
    Парсим новость 3: Экс-замминистра МВД и юстиции Сергей Герасимов вош...
67 новостей (всего: 45255)
[908/1298] 2024-09-24:     Парсим новость 1: ВТБ с 25 сентября на 1,5 п.п. повышает базовую ста...
    Парсим новость 2: Что произошло за день: вторник, 24 сентября...
    Парсим новость 3: Headhunter после редомициляции планирует выплатить...
74 новостей (всего: 45329)
[909/1298] 2024-09-25:     Парсим новость 1: WSJ узнала, что Google заплатил $2,7 млрд стартапу...
    Парсим новость 2: Совкомбанк наметил выпуск ЦФА для квалифицированны...
    Парсим новость 3: IT-сбой обрушил цену газа в системе балансировки T...
85 новостей (всего: 45414)
[910/1298] 2024-09-26:     Парсим новость 1: "Яндекс" выведет электровелосипеды своей разработк...
    Парсим новость 2: Новак заявил, что добыча газа в РФ в 2024 г. ожида...
    Парсим новость 3: Рубль в четверг опустился в паре с юанем на фоне а...
90 новостей (всего: 45504)
[911/1298] 2024-09-27:     Парсим новость 1: Что произошло за день: пятница, 27 сентября...
    Парсим новость 2: Фондовые индексы Европы закрылись в плюсе, Stoxx 6...
    Парсим новость 3: Toyota, Mazda и Fiat Chrysler отзывают 136 тыс. ма...
69 новостей (всего: 45573)
[912/1298] 2024-09-28: 0 новостей
[913/1298] 2024-09-29: 0 новостей
[914/1298] 2024-09-30:     Парсим новость 1: Проект трехлетнего бюджета внесен в Госдуму. Обобщ...
    Парсим новость 2: Минфин заложил рост НДПИ для отрасли удобрений на ...
    Парсим новость 3: ВЭБ за трехлетку получит от РФ взносы на 225 млрд ...
106 новостей (всего: 45679)
[915/1298] 2024-10-01:     Парсим новость 1: Новый премьер Франции пообещал сократить бюджетный...
    Парсим новость 2: Сбербанк приостановил прием заявок на IT-ипотеку и...
    Парсим новость 3: Рубль к вечеру растерял дневной рост и немного под...
78 новостей (всего: 45757)
[916/1298] 2024-10-02:     Парсим новость 1: В ОПЕК опровергли публикацию WSJ о словах саудовск...
    Парсим новость 2: ЕС снизил импорт энергоносителей во II квартале в ...
    Парсим новость 3: Аудитор оценил сделку по покупке "Интерросом" 35% ...
87 новостей (всего: 45844)
[917/1298] 2024-10-03:     Парсим новость 1: Цены на дома в еврозоне во II квартале выросли впе...
    Парсим новость 2: OpenAI привлекла кредитную линию на $4 млрд...
    Парсим новость 3: Мосбиржа предложила смягчить для крупных IPO требо...
75 новостей (всего: 45919)
[918/1298] 2024-10-04:     Парсим новость 1: Число нефтегазовых буровых в мире в сентябре дости...
    Парсим новость 2: Avito создала отдельное юрлицо под развитие финанс...
    Парсим новость 3: Рубль в пятницу слегка подрос в паре с юанем на фо...
58 новостей (всего: 45977)
[919/1298] 2024-10-05:     Парсим новость 1: Посол Индии отметил, что страна заинтересована в з...
1 новостей (всего: 45978)
[920/1298] 2024-10-06: 0 новостей
[921/1298] 2024-10-07:     Парсим новость 1: Производитель лекарств от ожирения Rivus планирует...
    Парсим новость 2: GDR Fix Price рискуют лишиться первого уровня лист...
    Парсим новость 3: Рубль упал в паре с юанем, в очередной раз обновив...
69 новостей (всего: 46047)
[922/1298] 2024-10-08:     Парсим новость 1: Минэнерго США понизило прогноз цены Brent в 2024 г...
    Парсим новость 2: Рубль во вторник упал в паре с юанем на фоне сильн...
    Парсим новость 3: "Коблик Групп" начала выпуск с/х техники на бывшем...
78 новостей (всего: 46125)
[923/1298] 2024-10-09:     Парсим новость 1: ЦБ РФ сообщил о снижении реального эффективного ку...
    Парсим новость 2: Рубль в среду подешевел в паре с юанем на фоне сни...
    Парсим новость 3: Снижение цен на фрукты и овощи в РФ за неделю уско...
74 новостей (всего: 46199)
[924/1298] 2024-10-10:     Парсим новость 1: Переработка нефти на Омском НПЗ за 9 месяцев вырос...
    Парсим новость 2: Белоруссия ввела лицензирование вывоза белокочанно...
    Парсим новость 3: Запуск первой очереди объектов инфраструктуры куро...
85 новостей (всего: 46284)
[925/1298] 2024-10-11:     Парсим новость 1: Под санкции США попадают все граждане, задействова...
    Парсим новость 2: Более 10% процедур личного банкротства россиян про...
    Парсим новость 3: Электрометаллурги призвали продлить ограничения на...
78 новостей (всего: 46362)
[926/1298] 2024-10-12:     Парсим новость 1: Лукашенко заявил о договоренности с "Роснефтью" на...
1 новостей (всего: 46363)
[927/1298] 2024-10-13:     Парсим новость 1: Нерезиденты выкупили бумаги российских инвесторов ...
1 новостей (всего: 46364)
[928/1298] 2024-10-14:     Парсим новость 1: Золотодобытчик Auriant собрался в январе провести ...
    Парсим новость 2: Боррель пообещал найти решение для разблокирования...
    Парсим новость 3: Жилищное строительство в РФ в сентябре выросло на ...
73 новостей (всего: 46437)
[929/1298] 2024-10-15:     Парсим новость 1: В ЦБ считают, что средний уровень ставки должен бы...
    Парсим новость 2: Дефицит при расчетах в токсичных валютах по внешне...
    Парсим новость 3: ASML в III квартале увеличила чистую прибыль на 32...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/986778 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021775EAA8D0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
74 новостей (всего: 46511)
[930/1298] 2024-10-16:     Парсим новость 1: Банки накопили на балансах иммобилизованные активы...
    Парсим новость 2: МВД выявило хищение 1,3 млрд рублей у кредиторов п...
    Парсим новость 3: Курс биткойна обновил максимум с июля...
86 новостей (всего: 46597)
  -> Сохранено во временный файл
[931/1298] 2024-10-17:     Парсим новость 1: Цена золота обновила рекорд, превысив отметку в $2...
    Парсим новость 2: Рубль вечером возобновил снижение, слегка опустивш...
    Парсим новость 3: Рынок акций РФ в четверг просел ниже 2765 пунктов ...
95 новостей (всего: 46692)
[932/1298] 2024-10-18:     Парсим новость 1: ЦБ РФ займется устранением регуляторного арбитража...
    Парсим новость 2: В Минфине считают, что эффективность повышения нал...
    Парсим новость 3: Аналитики BofA допустили рост котировок Nvidia еще...
73 новостей (всего: 46765)
[933/1298] 2024-10-19:     Парсим новость 1: Минпромторг РФ предложит пересмотреть условия субс...
    Парсим новость 2: Минфин может не целиком использовать право на допр...
2 новостей (всего: 46767)
[934/1298] 2024-10-20:     Парсим новость 1: Россия в августе поставила в Китай рекордный объем...
    Парсим новость 2: Китай в сентябре с падением цен на нефть активизир...
    Парсим новость 3: Мантуров сообщил о финальной стадии переговоров о ...
6 новостей (всего: 46773)
[935/1298] 2024-10-21:     Парсим новость 1: Сбербанк повысит ставки по ипотеке сразу на 3 п.п....
    Парсим новость 2: Более 100 млрд руб. направят до 2030 г. на проект ...
    Парсим новость 3: Air France решила пока не возобновлять рейсы в Тел...
57 новостей (всего: 46830)
[936/1298] 2024-10-22:     Парсим новость 1: РФ за 9 месяцев увеличила производство растительно...
    Парсим новость 2: Рубль немного подешевел в паре с юанем, несмотря н...
    Парсим новость 3: США скоро определят объем участия в предоставлении...
93 новостей (всего: 46923)
[937/1298] 2024-10-23:     Парсим новость 1: "ТКС Холдинг" подтвердил планы по возвращению к ре...
    Парсим новость 2: Компания Бакальчука подала иск из-за одностороннег...
    Парсим новость 3: Решетников назвал пессимистичным прогноз МВФ по ро...
85 новостей (всего: 47008)
[938/1298] 2024-10-24:     Парсим новость 1: На выплату страховых пенсий в 2024 году потребуетс...
    Парсим новость 2: Индия в сентябре увеличила импорт алмазов на 11%...
    Парсим новость 3: Ставки по ипотеке в США росли четвертую неделю под...
69 новостей (всего: 47077)
[939/1298] 2024-10-25:     Парсим новость 1: Заявление Банка России: ревущие двадцатые...
    Парсим новость 2: Курсовая экспортная пошлина в ноябре вырастет до м...

    Парсим новость 3: Совет директоров "Мегафона" рекомендовал дивиденды...
82 новостей (всего: 47159)
[940/1298] 2024-10-26:     Парсим новость 1: Совкомбанк пересмотрит прогноз по прибыли на 2024 ...
    Парсим новость 2: Мосбиржа ожидает завершения дискуссии по торгам в ...
    Парсим новость 3: Мосбиржа допустила обновление рекорда по объему то...
3 новостей (всего: 47162)
[941/1298] 2024-10-27: 0 новостей
[942/1298] 2024-10-28:     Парсим новость 1: Совет директоров "Хэдхантера" рекомендовал дивиден...
    Парсим новость 2: Выплаты правлению ВТБ в I полугодии составили 3,2 ...
    Парсим новость 3: Рубль в понедельник заметно подешевел в паре с юан...
58 новостей (всего: 47220)
[943/1298] 2024-10-29:     Парсим новость 1: ЕС ввел высокие ввозные пошлины на китайские элект...
    Парсим новость 2: Трамп пообещал ввести новые пошлины на импортные т...
    Парсим новость 3: Ростовский метзавод структуры, близкой к "Уральско...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/989170 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000217760D6840>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
70 новостей (всего: 47290)
[944/1298] 2024-10-30:     Парсим новость 1: Газпром нашел покупателя на 22-этажную "малахитову...
    Парсим новость 2: В России за девять месяцев расходы на нефтесервис ...
    Парсим новость 3: Великобритания отменит особый налоговый режим для ...
100 новостей (всего: 47390)
[945/1298] 2024-10-31:     Парсим новость 1: ПСБ за 9 месяцев получил 118,7 млрд руб. прибыли п...
    Парсим новость 2: Estee Lauder завершила I финквартал с чистым убытк...
    Парсим новость 3: Минпромторг не планирует ужесточать условия допуск...
97 новостей (всего: 47487)
[946/1298] 2024-11-01:     Парсим новость 1: МосБиржа вводит механизм стабилизации на валютном ...
    Парсим новость 2: Рубль в пятницу подешевел в паре с юанем, несмотря...
    Парсим новость 3: Рынок акций РФ в пятницу подрос в рамках коррекции...
60 новостей (всего: 47547)
[947/1298] 2024-11-02:     Парсим новость 1: Правительство РФ освободило от курсовых экспортных...
    Парсим новость 2: Выручка "МаксимаТелекома" за девять месяцев по РСБ...
    Парсим новость 3: "СИБУР" выкупил 1,3% своих акций у акционеров, не ...
45 новостей (всего: 47592)
[948/1298] 2024-11-03:     Парсим новость 1: ОПЕК+ продлевает до конца декабря добровольные сок...
    Парсим новость 2: "Татнефть" требует взыскать с "Туполева" 5,6 млрд ...
    Парсим новость 3: Власти РФ не считают нужным вводить предельные роз...
5 новостей (всего: 47597)
[949/1298] 2024-11-04:     Парсим новость 1: Министр промышленности ОАЭ сообщил о росте спроса ...
    Парсим новость 2: Inpex завершила продажу половины своей доли в прое...
    Парсим новость 3: TotalEnergies договорилась о поставках 2 млн т/г С...
4 новостей (всего: 47601)
[950/1298] 2024-11-05:     Парсим новость 1: Минтруд РФ намерен продлить до 2025 г. право менят...
    Парсим новость 2: FT сообщила о планах "ЛУКОЙЛа" продать НПЗ в Болга...
    Парсим новость 3: Денежная масса в РФ в октябре выросла на 1,5%...
65 новостей (всего: 47666)
[951/1298] 2024-11-06:     Парсим новость 1: "Префы" "Ростелекома" допустили к торгам на СПБ Би...
    Парсим новость 2: Акции "ВУШ Холдинга" допущены к торгам на СПБ Бирж...
    Парсим новость 3: Банк России увидел перелом тренда бурного роста ко...
66 новостей (всего: 47732)
[952/1298] 2024-11-07:     Парсим новость 1: Стандарты работы платежных агентов на финрынке буд...
    Парсим новость 2: ЦБ с 1 апреля может получить право ограничивать ба...
    Парсим новость 3: Рубль в четверг подешевел в паре с китайским юанем...
69 новостей (всего: 47801)
[953/1298] 2024-11-08:     Парсим новость 1: Эксперимент по маркировке запчастей начнется в РФ ...
    Парсим новость 2: Совет директоров "Роснефти" рекомендовал промежуто...
    Парсим новость 3: Лидеры стран ЕС наметили курс на прорыв в конкурен...
79 новостей (всего: 47880)
[954/1298] 2024-11-09:     Парсим новость 1: "Агроэкспорт" назвал страны Африки для наращивания...
    Парсим новость 2: Товарооборот продукции АПК между РФ и странами Афр...
    Парсим новость 3: Россия предлагает Африке сырьевые альянсы в недроп...
3 новостей (всего: 47883)
[955/1298] 2024-11-10:     Парсим новость 1: США запретили Тайваню поставлять в КНР чипы для ра...
1 новостей (всего: 47884)
[956/1298] 2024-11-11:     Парсим новость 1: Дагестан в 2024 году увеличил урожай винограда на ...
    Парсим новость 2: Платежную систему "Мир" подключили к иранской Shet...
    Парсим новость 3: "Газпром" готовится увеличить поставки в Китай...
65 новостей (всего: 47949)
[957/1298] 2024-11-12:     Парсим новость 1: Падение индекса Stoxx Europe 600 на 2% стало макси...
    Парсим новость 2: Капитализация рынка акций РФ во вторник выросла на...
    Парсим новость 3: Рубль немного укрепился в паре с китайским юанем н...
64 новостей (всего: 48013)
[958/1298] 2024-11-13:     Парсим новость 1: США повысили прогноз добычи нефти в стране в 2024 ...
    Парсим новость 2: Минфин предложил увеличить лимит на сумму покупок ...
    Парсим новость 3: Минэнерго США сохранило прогноз цены Brent в 2024 ...
83 новостей (всего: 48096)
[959/1298] 2024-11-14:     Парсим новость 1: В правительстве России пообещали содействовать раз...
    Парсим новость 2: Новые системы "Газпрома" по контролю за качеством ...
    Парсим новость 3: Банк "Ак Барс" в январе-сентябре увеличил активы н...
79 новостей (всего: 48175)
[960/1298] 2024-11-15:     Парсим новость 1: "Русский стандарт водка", "Уральские локомотивы" и...
    Парсим новость 2: В Минэкономразвития рассказали о продвижении позиц...
    Парсим новость 3: Правительство одобрило поправки в закон о налогооб...
80 новостей (всего: 48255)
  -> Сохранено во временный файл
[961/1298] 2024-11-16:     Парсим новость 1: Заявка на транзит российского газа через Украину в...
1 новостей (всего: 48256)
[962/1298] 2024-11-17: 0 новостей
[963/1298] 2024-11-18:     Парсим новость 1: Минфин предложил обнулить НДПИ для газа и конденса...
    Парсим новость 2: Рубль в понедельник опустился в паре с юанем на фо...
    Парсим новость 3: Рынок акций РФ начал неделю со снижения из-за эска...
54 новостей (всего: 48310)
[964/1298] 2024-11-19:     Парсим новость 1: В Москве в 2025 году изменятся тарифы на электриче...
    Парсим новость 2: "ФосАгро" отказалась от идеи полномасштабной карбо...
    Парсим новость 3: Аналитики ждут спад спроса на стальные трубы в Рос...
89 новостей (всего: 48399)
[965/1298] 2024-11-20:     Парсим новость 1: Глава ОСК заявил, что возможное вхождение "Звезды"...
    Парсим новость 2: Бельгийский конкурент SAP – Odoo – оценен в 5 млрд...
    Парсим новость 3: Владельцы всех выпусков облигаций Росбанка получил...
79 новостей (всего: 48478)
[966/1298] 2024-11-21:     Парсим новость 1: В Будапеште изучают эффект от новых санкций США пр...
    Парсим новость 2: Подпавшие под санкции США банки РФ работают штатно...
    Парсим новость 3: Банк "Синара" заявил, что санкции США не повлияют ...
73 новостей (всего: 48551)
[967/1298] 2024-11-22:     Парсим новость 1: Правительство РФ утвердило размер индексации тариф...
    Парсим новость 2: Рубль упал в паре с юанем, обновил минимальные зна...
    Парсим новость 3: Кабмин по согласованию с ЦБ сможет устанавливать л...
73 новостей (всего: 48624)
[968/1298] 2024-11-23:     Парсим новость 1: Правительство РФ продлевает соглашение с Белорусси...
    Парсим новость 2: В РФ введут временный запрет на вывоз отходов и ло...
2 новостей (всего: 48626)
[969/1298] 2024-11-24:     Парсим новость 1: Азербайджан отправил первый контейнерный блок-поез...
1 новостей (всего: 48627)
[970/1298] 2024-11-25:     Парсим новость 1: Индекс Мосбиржи на вечерних торгах обновил минимум...
    Парсим новость 2: Совет директоров АФК "Система" утвердил программу ...
    Парсим новость 3: Минэнерго предложило вернуть понижающие коэффициен...
67 новостей (всего: 48694)
[971/1298] 2024-11-26:     Парсим новость 1: Мощность потенциальных проектов "Интер РАО" на Куб...
    Парсим новость 2: ФАС заявила, что изменение подходов к установке та...

    Парсим новость 3: Банки будут выполнять "антиотмывочные" меры на пла...
73 новостей (всего: 48767)
[972/1298] 2024-11-27:     Парсим новость 1: Регионам с газификацией ниже 5% повысили диапазоны...
    Парсим новость 2: В Сабетте построят терминал для СУГ и конденсата н...
    Парсим новость 3: Правительство утвердило параметры терминала по пер...
97 новостей (всего: 48864)
[973/1298] 2024-11-28:     Парсим новость 1: Поставщик автозапчастей Valeo уволит более тысячи ...
    Парсим новость 2: АФК "Система" в III квартале нарастила выручку поч...
    Парсим новость 3: ЕК оштрафовала Pierre Cardin за нарушение антимоно...
83 новостей (всего: 48947)
[974/1298] 2024-11-29:     Парсим новость 1: Минюст зарегистрировал приказ ФНС о порядке трансф...
    Парсим новость 2: Продажа валюты/золота из ФНБ будет согласовываться...
    Парсим новость 3: "Росморпорт" планирует вступить в дело о банкротст...
100 новостей (всего: 49047)
[975/1298] 2024-11-30:     Парсим новость 1: Росавиация объявила отбор претендующих на субсидии...
    Парсим новость 2: "Аэрофлот" поставит арендуемые у iFly A330 на рейс...
    Парсим новость 3: "Роснефть" может перенести сроки модернизации НПЗ ...
6 новостей (всего: 49053)
[976/1298] 2024-12-01:     Парсим новость 1: Путин подписал закон о федеральном бюджете на 2025...
1 новостей (всего: 49054)
[977/1298] 2024-12-02:     Парсим новость 1: Аналитики Wedbush допустили рост акций Apple еще н...
    Парсим новость 2: Число квалифицированных инвесторов за III квартал ...
    Парсим новость 3: Сбор зерна в РФ к 26 ноября составил 132 млн т...
78 новостей (всего: 49132)
[978/1298] 2024-12-03:     Парсим новость 1: "Суал" добивается в суде созыва собрания акционеро...
    Парсим новость 2: Adobe Analytics оценили онлайн-траты американцев в...
    Парсим новость 3: Минфин России сообщил об эмиссии замещающих сувере...
62 новостей (всего: 49194)
[979/1298] 2024-12-04:     Парсим новость 1: Костин заявил, что вопрос о покупке "Звезды" ОСК п...
    Парсим новость 2: Казмунайгаз не рассматривает вариант выкупа доли "...
    Парсим новость 3: Бизнес объяснил рост цен на картофель в этом году ...
91 новостей (всего: 49285)
[980/1298] 2024-12-05:     Парсим новость 1: Экспортированный из РФ газ продолжает оплачиваться...
    Парсим новость 2: США выделили Польше кредит в $4 млрд на трансформа...
    Парсим новость 3: American Airlines улучшила прогноз скорректированн...
111 новостей (всего: 49396)
[981/1298] 2024-12-06:     Парсим новость 1: В Сбербанке полагают, что "легкий разворот" ДКП ве...
    Парсим новость 2: Bloomberg сообщил о попытках ЕС убедить США смягчи...
    Парсим новость 3: Число и объем IPO в мире в январе-сентябре снизили...
88 новостей (всего: 49484)
[982/1298] 2024-12-07:     Парсим новость 1: Fitch изменило прогноз по рейтингу Грузии на "нега...
1 новостей (всего: 49485)
[983/1298] 2024-12-08:     Парсим новость 1: Суточные поставки "Газпрома" в КНР по "Силе Сибири...
1 новостей (всего: 49486)
[984/1298] 2024-12-09:     Парсим новость 1: Порог уголовной ответственности за манипулирование...
    Парсим новость 2: Американские биткойн-ETF привлекли почти $10 млрд ...
    Парсим новость 3: Рубль в понедельник сильно упал в паре с юанем в р...
79 новостей (всего: 49565)
[985/1298] 2024-12-10:     Парсим новость 1: В ЦБ отметили, что ослабление рубля во второй поло...
    Парсим новость 2: США выделят Киеву кредит на $20 млрд с погашением ...
    Парсим новость 3: Сбер в ноябре зафиксировал небольшой рост просроче...
83 новостей (всего: 49648)
[986/1298] 2024-12-11:     Парсим новость 1: Большинство российских предприятий планирует увели...
    Парсим новость 2: OMV расторгла контракт с "Газпромом" после прекращ...
    Парсим новость 3: ЦБ уличил администратора Telegram-канала в манипул...
79 новостей (всего: 49727)
[987/1298] 2024-12-12:     Парсим новость 1: "Финам" хочет в 2025 г. провести IPO одной из свои...
    Парсим новость 2: Правительство РФ утвердило индексацию оптовых цен ...
    Парсим новость 3: Рубль в четверг подрос в паре с юанем...
74 новостей (всего: 49801)
[988/1298] 2024-12-13:     Парсим новость 1: Депутаты уточнили подход к расчету экспортной пошл...
    Парсим новость 2: Повышенные пошлины на ввоз ряда товаров из недруже...
    Парсим новость 3: Глава ЕК предложила восстанавливать Сирию через ме...
76 новостей (всего: 49877)
[989/1298] 2024-12-14:     Парсим новость 1: Мантуров подчеркнул, что ограничения экспорта долж...
    Парсим новость 2: Решетников отметил, что компании сокращают инвестп...
    Парсим новость 3: Минэкономразвития к апрелю уточнит прогноз по инфл...
7 новостей (всего: 49884)
[990/1298] 2024-12-15:     Парсим новость 1: Новак сообщил, что добыча угля в 2024 году снизитс...
1 новостей (всего: 49885)
  -> Сохранено во временный файл
[991/1298] 2024-12-16:     Парсим новость 1: Доля рублевых платежей при оплате импорта РФ в окт...
    Парсим новость 2: Рубль перешел к росту и завершил торги в небольшом...
    Парсим новость 3: СД "СИБУРа" принял решение обратиться с заявлением...
73 новостей (всего: 49958)
[992/1298] 2024-12-17:     Парсим новость 1: Экспортерам могут разрешать не репатриировать валю...
    Парсим новость 2: Акционеры Совкомбанка 28 января рассмотрят допэмис...
    Парсим новость 3: Первый луноход для Австралии Roo-ver создаст консо...
62 новостей (всего: 50020)
[993/1298] 2024-12-18:     Парсим новость 1: Пауэлл сообщил, что дальнейшее снижение ставок ФРС...
    Парсим новость 2: ФРС повысила прогноз инфляции на 2025 год, ожидает...
    Парсим новость 3: ФРС ожидаемо понизила ключевую ставку на 25 б.п....
95 новостей (всего: 50115)
[994/1298] 2024-12-19:     Парсим новость 1: Минпромторг получит 12 млрд рублей на поддержку ко...
    Парсим новость 2: В морском порту Анапы установили дополнительные бо...
    Парсим новость 3: Авиакомпании запросили субсидии на рейсы в 3,3 раз...
75 новостей (всего: 50190)
[995/1298] 2024-12-20:     Парсим новость 1: Решетников назвал "крайне сбалансированным" решени...
    Парсим новость 2: Минфин РФ по-прежнему ожидает дефицита бюджета в 2...
    Парсим новость 3: Рубль в пятницу немного подрос в паре с юанем на ф...
103 новостей (всего: 50293)
[996/1298] 2024-12-21:     Парсим новость 1: Набсовет Россельхозбанка почти не претерпит измене...
    Парсим новость 2: Орбан сообщил об обсуждении вариантов сохранения т...
    Парсим новость 3: "Газпром" второй раз за месяц обновил рекорд суточ...
3 новостей (всего: 50296)
[997/1298] 2024-12-22:     Парсим новость 1: Глава МИД Венгрии заявил о возобновлении поставок ...
    Парсим новость 2: В Катаре пригрозили прекратить поставки газа в ЕС ...
2 новостей (всего: 50298)
[998/1298] 2024-12-23:     Парсим новость 1: ЦБ сможет менять требования к периоду охлаждения и...
    Парсим новость 2: Законопроект о "периоде охлаждения" в потребительс...
    Парсим новость 3: Сервис Dave стал лидером финтех-сектора в 2024 г. ...
78 новостей (всего: 50376)
[999/1298] 2024-12-24:     Парсим новость 1: Что произошло за день: вторник, 24 декабря...
    Парсим новость 2: Доля дружественных стран в неэнергетическом несырь...
    Парсим новость 3: Банки США подали иск к ФРС, оспаривая процедуру пр...
69 новостей (всего: 50445)
[1000/1298] 2024-12-25:     Парсим новость 1: ЦБ вводит мораторий на применение ограничения ПСК ...
    Парсим новость 2: X5 просит суд продлить приостановку корпоративных ...
    Парсим новость 3: Производство электроэнергии в РФ в январе-ноябре в...
73 новостей (всего: 50518)
[1001/1298] 2024-12-26:     Парсим новость 1: Акционеры "Роснефти" утвердили промежуточные дивид...
    Парсим новость 2: ЕС усилит санкции против российского танкерного фл...
    Парсим новость 3: Минюст зарегистрировал приказ ФАС и Минэнерго о но...
68 новостей (всего: 50586)
[1002/1298] 2024-12-27:     Парсим новость 1: СД "Роснефти" продлил полномочия Сечина в должност...
    Парсим новость 2: Запасы нефти в США снизились на 4,24 млн баррелей ...
    Парсим новость 3: Кредитование сезонных полевых работ в АПК РФ к 24 ...
61 новостей (всего: 50647)
[1003/1298] 2024-12-28:     Парсим новость 1: Оборот разработчиков ПО в ноябре вырос на 28,9% г/...
    Парсим новость 2: В Думу внесли проект о защите подставных лиц в биз...
    Парсим новость 3: "Шереметьево" повысит сборы с авиакомпаний РФ на 1...

36 новостей (всего: 50683)
[1004/1298] 2024-12-29:     Парсим новость 1: Правительство РФ определило порядок беспошлинного ...
1 новостей (всего: 50684)
[1005/1298] 2024-12-30:     Парсим новость 1: Рубль слегка снизился в паре с юанем в понедельник...
    Парсим новость 2: Рынок акций РФ в понедельник продолжил ралли...
    Парсим новость 3: Европейские фондовые индексы снижаются...
22 новостей (всего: 50706)
[1006/1298] 2024-12-31:     Парсим новость 1: "КазРосГаз" и "Карачанак Петролиум Оперейтинг Б.В....
    Парсим новость 2: "Газпром" не заказывал транзит через Украину на 1 ...
    Парсим новость 3: РФ вводит повышенные ввозные пошлины на кофе из не...
3 новостей (всего: 50709)
[1007/1298] 2025-01-01:     Парсим новость 1: В Молдавии вступили в силу меры по экономии электр...
    Парсим новость 2: Т-Банк присоединил Росбанк...
    Парсим новость 3: В Приднестровье прекращена подача газа, тепла и го...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/1001451 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000217783DD730>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
24 новостей (всего: 50733)
[1008/1298] 2025-01-02:     Парсим новость 1: Молдавия покрывает дефицит электроэнергии за счет ...
    Парсим новость 2: Пассажиропоток авиакомпаний РФ в 2024 году вырос п...
2 новостей (всего: 50735)
[1009/1298] 2025-01-03:     Парсим новость 1: Турция в октябре восстановила импорт нефти до 2,2 ...
    Парсим новость 2: Рубль снизился в паре с юанем в пятницу 4-й день п...
    Парсим новость 3: Фондовые индексы Европы продолжают снижаться...
19 новостей (всего: 50754)
[1010/1298] 2025-01-04:     Парсим новость 1: Рынок легковых и легких коммерческих автомобилей в...
    Парсим новость 2: Правительство РФ направило 5 млрд рублей на льготн...
2 новостей (всего: 50756)
[1011/1298] 2025-01-05:     Парсим новость 1: Ремонт на месторождении Тенгиз планируется заверши...
1 новостей (всего: 50757)
[1012/1298] 2025-01-06:     Парсим новость 1: Минфин США разрешил некоторые операции в сфере эне...
    Парсим новость 2: Рубль 6 января подорожал в паре с юанем в рамках к...
    Парсим новость 3: Рынок акций РФ замедлил снижение и удержался выше ...
27 новостей (всего: 50784)
[1013/1298] 2025-01-07: 0 новостей
[1014/1298] 2025-01-08:     Парсим новость 1: Рубль подорожал в паре с юанем 2-й день подряд бла...
    Парсим новость 2: Рынок акций РФ в среду превысил 2840п по индексу М...
    Парсим новость 3: ВТБ оспаривает в суде отзыв лицензии у бывшего VTB...
11 новостей (всего: 50795)
[1015/1298] 2025-01-09:     Парсим новость 1: Шеф Пентагона заявил о готовности военных помочь в...
    Парсим новость 2: Мировые компании с начала 2025 года разместили дол...
    Парсим новость 3: Азербайджан приостановил поставки газа в Болгарию ...
68 новостей (всего: 50863)
[1016/1298] 2025-01-10:     Парсим новость 1: В Бельгии готовят запрет на услуги по перевалке ро...
    Парсим новость 2: США настаивают на полном выходе российского капита...
    Парсим новость 3: Минсельхоз США снизил прогноз экспорта пшеницы из ...
78 новостей (всего: 50941)
[1017/1298] 2025-01-11:     Парсим новость 1: КНР и Великобритания возобновили переговоры в фина...
    Парсим новость 2: США объявили масштабный пакет санкций против росси...
2 новостей (всего: 50943)
[1018/1298] 2025-01-12:     Парсим новость 1: Азербайджанские СМИ сообщили о скором возобновлени...
1 новостей (всего: 50944)
[1019/1298] 2025-01-13:     Парсим новость 1: Рубль в понедельник упал в паре с юанем, несмотря ...
    Парсим новость 2: Акции Moderna подешевели на 21% на публикации прог...
    Парсим новость 3: Индекс МосБиржи начал неделю с роста выше 2865п, л...
69 новостей (всего: 51013)
[1020/1298] 2025-01-14:     Парсим новость 1: Минэнерго США сохранило оценку роста спроса на жид...
    Парсим новость 2: Минэнерго США оценило добычу нефти в стране в 2024...
    Парсим новость 3: Минэнерго США повысило прогноз цены Brent на 2025 ...
67 новостей (всего: 51080)
  -> Сохранено во временный файл
[1021/1298] 2025-01-15:     Парсим новость 1: Франчайзи Rostic's успешно оспорил доначисление в ...
    Парсим новость 2: США обвинили киргизский Керемет банк в обходе санк...
    Парсим новость 3: Цены на бензин в РФ с 1 по 13 января выросли на 0,...
100 новостей (всего: 51180)
[1022/1298] 2025-01-16:     Парсим новость 1: Всемирный банк ждет роста ВВП России в 2025 году н...
    Парсим новость 2: ВБ подтвердил прогнозы роста мирового ВВП в 2025 и...
    Парсим новость 3: Т-Банк разместил допэмиссию акций в рамках присоед...
64 новостей (всего: 51244)
[1023/1298] 2025-01-17:     Парсим новость 1: Рынки акций Европы уверенно выросли, Stoxx Europe ...
    Парсим новость 2: "Фанагория" в 2024 г. увеличила выпуск винодельчес...
    Парсим новость 3: Рубль вечером отыграл дневные потери и немного пов...
77 новостей (всего: 51321)
[1024/1298] 2025-01-18: 0 новостей
[1025/1298] 2025-01-19:     Парсим новость 1: BP возобновила добычу с платформы Shah Deniz Alpha...
1 новостей (всего: 51322)
[1026/1298] 2025-01-20:     Парсим новость 1: Косачев считает, что Трамп еще не решил, как дейст...
    Парсим новость 2: Бюджет РФ в 2024 году исполнен с дефицитом 3,485 т...
    Парсим новость 3: ЦБ РФ повторил сигнал о необходимости поддержания ...
61 новостей (всего: 51383)
[1027/1298] 2025-01-21:     Парсим новость 1: Occidental Petroleum призвала США повременить с ро...
    Парсим новость 2: РФ и Казахстан планируют создать совместный агроби...
    Парсим новость 3: Девелопер Glorax сдвинул на 2028 год планы экспанс...
67 новостей (всего: 51450)
[1028/1298] 2025-01-22:     Парсим новость 1: Совет ЕЭК рассмотрел вопросы улучшения делового кл...
    Парсим новость 2: Алиев обсудил с премьер-министром Хорватии увеличе...
    Парсим новость 3: Глава Commerzbank заявила о стремлении не допустит...
74 новостей (всего: 51524)
[1029/1298] 2025-01-23:     Парсим новость 1: В перечень экономически значимых организаций РФ вк...
    Парсим новость 2: Запасы нефти в США снизились на 1,02 млн баррелей ...
    Парсим новость 3: Цены на нефть резко ушли в минус на заявлениях Тра...
69 новостей (всего: 51593)
[1030/1298] 2025-01-24:     Парсим новость 1: Кабмин разрешил выделить "Ростеху" субсидии на раз...
    Парсим новость 2: Доходы бюджета Китая в 2024 году выросли на 1,3%, ...
    Парсим новость 3: "Северсталь" подтвердила свою оценку падения спрос...
85 новостей (всего: 51678)
[1031/1298] 2025-01-25:     Парсим новость 1: Стала известна суть иска к бывшему топ-менеджеру э...
    Парсим новость 2: Генпрокуратура РФ подала иск к Митюшову по поводу ...
2 новостей (всего: 51680)
[1032/1298] 2025-01-26: 0 новостей
[1033/1298] 2025-01-27:     Парсим новость 1: Промсвязьбанк сменит регистрацию на ярославскую...
    Парсим новость 2: Китай увеличил резервы золота до рекорда в 2024 го...
    Парсим новость 3: Капитализация Nvidia рухнула на рекордные $465 млр...
62 новостей (всего: 51742)
[1034/1298] 2025-01-28:     Парсим новость 1: ЕС введет пошлины на ряд сельхозтоваров и удобрени...
    Парсим новость 2: "Циан" раскрыл актуальную структуру акционеров пер...
    Парсим новость 3: Аналитики спрогнозировали сохранение ФРС базовой с...
84 новостей (всего: 51826)
[1035/1298] 2025-01-29:     Парсим новость 1: Глава ФРС не видит необходимости спешить в снижени...
    Парсим новость 2: ФРС ожидаемо сохранила базовую ставку в диапазоне ...
    Парсим новость 3: Банковская группа Lloyds закроет 136 отделений в В...
89 новостей (всего: 51915)
[1036/1298] 2025-01-30:     Парсим новость 1: В Брюсселе хотят ускорить дополнительные инвестици...
    Парсим новость 2: ВС РФ решит, отвечают ли в условиях санкций по дол...
    Парсим новость 3: Nissan сократит производство и сотрудников на заво...
97 новостей (всего: 52012)
[1037/1298] 2025-01-31:     Парсим новость 1: Суд удовлетворил иск о взыскании 100% зернотрейдер...
    Парсим новость 2: Отели Эйлата готовы расширить формат "все включено...
    Парсим новость 3: Royal Jordanian Airlines возобновила полеты в Сири...
72 новостей (всего: 52084)
[1038/1298] 2025-02-01:     Парсим новость 1: "Молдовагаз" начал поставку газа в Приднестровье...

    Парсим новость 2: Подписано постановление о продлении экспорта бензи...
    Парсим новость 3: Молдавия будет поставлять газ в Приднестровье за с...
5 новостей (всего: 52089)
[1039/1298] 2025-02-02:     Парсим новость 1: Кабмин расширил перечень стран, банки которых могу...
1 новостей (всего: 52090)
[1040/1298] 2025-02-03:     Парсим новость 1: Трамп считает, что ЕС заинтересован в соглашении с...
    Парсим новость 2: США и Китай в течение суток обсудят повышение пошл...
    Парсим новость 3: АСВ ищет подрядчика для продажи акций Visa оценочн...
86 новостей (всего: 52176)
[1041/1298] 2025-02-04:     Парсим новость 1: СД "Циана" утвердил решение, необходимое для запус...
    Парсим новость 2: Сбербанк остался в программе льготного кредитовани...
    Парсим новость 3: Союз пивоваров предупредил, что доля импортного пи...
85 новостей (всего: 52261)
[1042/1298] 2025-02-05:     Парсим новость 1: Глава TotalEnergies не верит в Brent по $50-60 за ...
    Парсим новость 2: Для покрытия энергодефицита на Дальнем Востоке пре...
    Парсим новость 3: Яйца в РФ за неделю подешевели на 0,5%, сливочное ...
117 новостей (всего: 52378)
[1043/1298] 2025-02-06:     Парсим новость 1: Правительство предложило нулевой НДС для ВСМ Москв...
    Парсим новость 2: Сводный индекс Stoxx Europe 600 обновил историческ...
    Парсим новость 3: ConocoPhillips сократила квартальную чистую прибыл...
76 новостей (всего: 52454)
[1044/1298] 2025-02-07:     Парсим новость 1: Кондитеры РФ оценили минимум в 62 млрд руб. затрат...
    Парсим новость 2: Рынок акций РФ в пятницу просел в рамках коррекции...
    Парсим новость 3: Рубль в пятницу немного подешевел в паре с юанем п...
74 новостей (всего: 52528)
[1045/1298] 2025-02-08:     Парсим новость 1: Уровень запасов газа в подземных хранилищах Европы...
1 новостей (всего: 52529)
[1046/1298] 2025-02-09: 0 новостей
[1047/1298] 2025-02-10:     Парсим новость 1: Росстат сможет получать от ФНС данные с кассовых а...
    Парсим новость 2: GM, Honda, Nissan, Stellantis сильнее всего постра...
    Парсим новость 3: Рубль ускорил темпы роста в паре с юанем на фоне а...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/1007237 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002177613AE10>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
58 новостей (всего: 52587)
[1048/1298] 2025-02-11:     Парсим новость 1: Минэнерго США повысило прогноз цены газа на Henry ...
    Парсим новость 2: США повысили прогноз добычи нефти в стране в 2025 ...
    Парсим новость 3: Минэнерго США чуть повысило прогноз цены Brent на ...
77 новостей (всего: 52664)
[1049/1298] 2025-02-12:     Парсим новость 1: Руководители ЕС обсудили с премьер-министром Канад...
    Парсим новость 2: Российский рынок акций заметно растет на новостях ...
    Парсим новость 3: ФАС предложила обновить правила недискриминационно...
84 новостей (всего: 52748)
[1050/1298] 2025-02-13:     Парсим новость 1: Скорректированная EBITDA "ФосАгро" в IV квартале в...
    Парсим новость 2: Мосбиржа не будет возобновлять торги на фондовом р...
    Парсим новость 3: Еще пять банков РФ смогут работать со спецсчетами ...
83 новостей (всего: 52831)
  -> Сохранено во временный файл
[1051/1298] 2025-02-14:     Парсим новость 1: Жесткость необходима и, возможно, достаточна. Заяв...
    Парсим новость 2: Пошлина на экспорт пшеницы из РФ с 19 февраля сниз...
    Парсим новость 3: Утверждён порядок расчёта процентов на вознагражде...
102 новостей (всего: 52933)
[1052/1298] 2025-02-15:     Парсим новость 1: Мантуров обсудил вопросы международных платежей с ...
    Парсим новость 2: Мантуров проведет переговоры в рамках оборонной вы...
2 новостей (всего: 52935)
[1053/1298] 2025-02-16: 0 новостей
[1054/1298] 2025-02-17:     Парсим новость 1: Среднетоннажный завод СПГ "Криогаз-Высоцк" получил...
    Парсим новость 2: Доля платежей по внешнеторговым контрактам в токси...
    Парсим новость 3: Прибыль Т-банка в январе по РСБУ без учета разовых...
60 новостей (всего: 52995)
[1055/1298] 2025-02-18:     Парсим новость 1: Набсовет ВТБ 10 марта  рассмотрит избрание Ольги С...
    Парсим новость 2: Минцифры предлагает вдвое увеличить тарифы "Почты ...
    Парсим новость 3: Глава ФРБ Сан-Франциско советует ФРС сохранять огр...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/1009510 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021774E1D340>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
71 новостей (всего: 53066)
[1056/1298] 2025-02-19:     Парсим новость 1: "Манчестер Юнайтед" завершил II финквартал с чисты...
    Парсим новость 2: Рубль умеренно повысился в паре с юанем на улучшен...
    Парсим новость 3: Цены производителей на бензин в РФ в январе снизил...
85 новостей (всего: 53151)
[1057/1298] 2025-02-20:     Парсим новость 1: Первая жалоба подана в ВС РФ на решение об обращен...
    Парсим новость 2: АГР и китайская Defetoo во II квартале начнут выпу...
    Парсим новость 3: Рубль в четверг вырос благодаря подготовке экспорт...
94 новостей (всего: 53245)
[1058/1298] 2025-02-21:     Парсим новость 1: FATF оставила без изменений статус РФ, включила в ...
    Парсим новость 2: ЦБ установил для крупных банков пороговый показате...
    Парсим новость 3: ЦА ФАС взял на себя рассмотрение жалоб на закупки ...
57 новостей (всего: 53302)
[1059/1298] 2025-02-22:     Парсим новость 1: Решения по возврату иностранных брендов в РФ будут...
1 новостей (всего: 53303)
[1060/1298] 2025-02-23:     Парсим новость 1: РФ намерена реализовать в Мьянме проекты по строит...
    Парсим новость 2: Центральные банки РФ и Мьянмы работают над взаимны...
    Парсим новость 3: Решетников обсудил с премьером Мьянмы инвестиционн...
3 новостей (всего: 53306)
[1061/1298] 2025-02-24:     Парсим новость 1: Путин заявил, что РФ и США могли бы подумать над э...
    Парсим новость 2: Путин подтвердил, что ряд компаний России и США об...
    Парсим новость 3: Президент РФ выразил готовность работать с америка...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/1010463 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002177853DFD0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
88 новостей (всего: 53394)
[1062/1298] 2025-02-25:     Парсим новость 1: Краудлендинг-платформа JetLend анонсировала IPO на...
    Парсим новость 2: В России потребление лома черных металлов в 2025 г...
    Парсим новость 3: ЦБ отметил активизацию открытия инвесторами ИИС-3 ...
70 новостей (всего: 53464)
[1063/1298] 2025-02-26:     Парсим новость 1: Выпуск золота в России снизился на 2,5% в январе...
    Парсим новость 2: Добыча угля в РФ в январе выросла на 6,2% год к го...
    Парсим новость 3: Производство компьютеров и электроники в январе вы...
81 новостей (всего: 53545)
[1064/1298] 2025-02-27:     Парсим новость 1: Эстония намерена довести оборонные расходы до почт...
    Парсим новость 2: В Татарстане при участии "Роснано" создадут центр ...
    Парсим новость 3: Индекс незавершенных сделок на рынке жилья США в я...
105 новостей (всего: 53650)
[1065/1298] 2025-02-28:     Парсим новость 1: Кабмин установил квоту на экспорт пшеницы из Крыма...
    Парсим новость 2: Сменился глава подконтрольной агрохолдингу "Степь"...
    Парсим новость 3: Ставки по ипотеке в США опустились до минимума за ...
86 новостей (всего: 53736)
[1066/1298] 2025-03-01:     Парсим новость 1: ЦБ РФ на заседании в марте может рассмотреть и пов...
    Парсим новость 2: ЦБ сможет учитывать движения на рынках на фоне гео...
    Парсим новость 3: Банк России по-прежнему жестко настроен на возвращ...
7 новостей (всего: 53743)
[1067/1298] 2025-03-02:     Парсим новость 1: FT сообщила об участии Маттиаса Варнига в обсужден...
1 новостей (всего: 53744)
[1068/1298] 2025-03-03:     Парсим новость 1: ОПЕК+ подтвердила планы по постепенному увеличению...
    Парсим новость 2: Индекс Stoxx Europe 600 обновил рекорд...
    Парсим новость 3: Инвесторы Марк Уолтер и Томас Тулл объединят актив...

73 новостей (всего: 53817)
[1069/1298] 2025-03-04:     Парсим новость 1: Продуктовая инфляция в Великобритании в феврале ус...
    Парсим новость 2: CK Hutchison продает портовые активы консорциуму с...
    Парсим новость 3: Рубль во вторник опустился в паре с юанем на фоне ...
74 новостей (всего: 53891)
[1070/1298] 2025-03-05:     Парсим новость 1: Минэнерго США на 3 года продлило лицензию Golden P...
    Парсим новость 2: В странах Евросоюза в 2024 году число ночевок тури...
    Парсим новость 3: В Белоруссии определили площадки для поиска редкоз...
92 новостей (всего: 53983)
[1071/1298] 2025-03-06:     Парсим новость 1: Thyssenkrupp сократит штат автоподразделения на 1,...
    Парсим новость 2: Глава ФРБ Филадельфии считает, что растущее инфляц...
    Парсим новость 3: ЕЦБ ожидает среднюю цену Brent в $74,7 за баррель ...
78 новостей (всего: 54061)
[1072/1298] 2025-03-07:     Парсим новость 1: Пошлина на экспорт пшеницы из РФ с 12 марта повыси...
    Парсим новость 2: Китай в январе-феврале импортировал в среднем 10,3...
    Парсим новость 3: "Металлоинвест" направит 10 млрд рублей на дивиден...
99 новостей (всего: 54160)
[1073/1298] 2025-03-08: 0 новостей
[1074/1298] 2025-03-09:     Парсим новость 1: США блокируют создание G7 структуры, отслеживающей...
1 новостей (всего: 54161)
[1075/1298] 2025-03-10:     Парсим новость 1: Минпромторг объявил конкурс на доработку самолета ...
    Парсим новость 2: Рынки акций Европы начали неделю резким снижением...
    Парсим новость 3: "Центральный телеграф" сократил годовую выручку до...
63 новостей (всего: 54224)
[1076/1298] 2025-03-11:     Парсим новость 1: Минэнерго США понизило оценку роста мирового спрос...
    Парсим новость 2: Минэнерго США повысило прогноз цены газа на Henry ...
    Парсим новость 3: На Московском НПЗ сообщили о штатной работе...
66 новостей (всего: 54290)
[1077/1298] 2025-03-12:     Парсим новость 1: Для инвесторов предложили обеспечить налоговую ней...
    Парсим новость 2: В РФ прорабатывают формулу автоматической корректи...
    Парсим новость 3: Spotify выплатила роялти на сумму $10 млрд в 2024 ...
76 новостей (всего: 54366)
[1078/1298] 2025-03-13:     Парсим новость 1: Виноделы Европы в шоке от угрозы Трампа ввести пош...
    Парсим новость 2: Вице-президент Segezha, глава Сегежского ЦБК Батал...
    Парсим новость 3: ЦБ предложил имущественные цензы для признания инв...
88 новостей (всего: 54454)
[1079/1298] 2025-03-14:     Парсим новость 1: Подписано постановление, позволяющее размещать ден...
    Парсим новость 2: Рубль укрепился к юаню благодаря надеждам на урегу...
    Парсим новость 3: Рынок акций РФ поднялся в пятницу к 3200п по индек...
73 новостей (всего: 54527)
[1080/1298] 2025-03-15:     Парсим новость 1: Российская "дочка" "Белоруснефти" завершила строит...
1 новостей (всего: 54528)
  -> Сохранено во временный файл
[1081/1298] 2025-03-16:     Парсим новость 1: РФ придает большое значение сотрудничеству с Катар...
    Парсим новость 2: РФ в 2024 году экспортировала в Катар продукции АП...
    Парсим новость 3: Мантуров заявил о готовности РФ создать агропромыш...
4 новостей (всего: 54532)
[1082/1298] 2025-03-17:     Парсим новость 1: Хорватии интересна покупка российской доли в сербс...
    Парсим новость 2: "Бумажная" переоценка акций ГПН стоила "Газпрому" ...
    Парсим новость 3: Чистая прибыль "Трансконтейнера" по МСФО в 2024 го...
76 новостей (всего: 54608)
[1083/1298] 2025-03-18:     Парсим новость 1: Председатель совета директоров Walgreens удвоит до...
    Парсим новость 2: Капзатраты ГК "Русагро" в 2024 году выросли до 30 ...
    Парсим новость 3: Siemens уволит более 6 тысяч сотрудников...
87 новостей (всего: 54695)
[1084/1298] 2025-03-19:     Парсим новость 1: Глава ФРС заявил о возросшей неопределенности в эк...
    Парсим новость 2: ФРС повысила прогнозы инфляции в США на 2025 и 202...
    Парсим новость 3: ФРС ожидаемо оставила базовую ставку в диапазоне 4...
85 новостей (всего: 54780)
[1085/1298] 2025-03-20:     Парсим новость 1: "Россети Ленэнерго" в 2024 году увеличили чистую п...
    Парсим новость 2: Китай в январе существенно снизил импорт нефти у о...
    Парсим новость 3: Экспорт российских удобрений в Китай в январе-февр...
93 новостей (всего: 54873)
[1086/1298] 2025-03-21:     Парсим новость 1: Производитель грузовиков Iveco хочет продать оборо...
    Парсим новость 2: Пошлина на экспорт пшеницы из РФ с 26 марта снизит...
    Парсим новость 3: Рубль немного подрос в паре с юанем перед выходным...
87 новостей (всего: 54960)
[1087/1298] 2025-03-22: 0 новостей
[1088/1298] 2025-03-23:     Парсим новость 1: В Китае заявили о готовности защитить экономику от...
1 новостей (всего: 54961)
[1089/1298] 2025-03-24:     Парсим новость 1: Белый дом продлил до 27 мая лицензию Chevron на до...
    Парсим новость 2: Надежность продавцов на маркетплейсах можно будет ...
    Парсим новость 3: Власти Турции принимают меры для стабилизации курс...
63 новостей (всего: 55024)
[1090/1298] 2025-03-25:     Парсим новость 1: Банки КНР остались лидерами рейтинга стоимости бан...
    Парсим новость 2: Shell готова развивать химию в США и пересматривае...
    Парсим новость 3: Energean отказалась от продажи Carlyle нефтегазовы...
84 новостей (всего: 55108)
[1091/1298] 2025-03-26:     Парсим новость 1: Квота на экспорт удобрений из РФ в июне-ноябре выр...
    Парсим новость 2: Цены на плодоовощную продукцию в РФ снова пошли вв...
    Парсим новость 3: РФ в феврале сократила выпуск стального проката на...
92 новостей (всего: 55200)
[1092/1298] 2025-03-27:     Парсим новость 1: FT сообщила об идее возможной покупки российской д...
    Парсим новость 2: TotalEnergies, Equinor и Shell решили расширить хр...
    Парсим новость 3: Путин поручил донастроить налоговые льготы и админ...
94 новостей (всего: 55294)
[1093/1298] 2025-03-28:     Парсим новость 1: ЦБ РФ в 2024 году увеличил капвложения в работу св...
    Парсим новость 2: "Татнефть" планирует организовать производство био...
    Парсим новость 3: Пошлина на экспорт пшеницы из РФ со 2 апреля повыс...
81 новостей (всего: 55375)
[1094/1298] 2025-03-29:     Парсим новость 1: "КазМунайГаз" и "Узбекнефтегаз" подписали соглашен...
1 новостей (всего: 55376)
[1095/1298] 2025-03-30: 0 новостей
[1096/1298] 2025-03-31:     Парсим новость 1: Минфин РФ доволен ритмичностью расходов федерально...
    Парсим новость 2: "Дочка" Alphabet в сфере разработки лекарств с пом...
    Парсим новость 3: Бюджет РФ в 2025 год получил 120 млрд руб. "платы ...
84 новостей (всего: 55460)
[1097/1298] 2025-04-01:     Парсим новость 1: Группа "Илим" в 2024 г. увеличила выручку по РСБУ ...
    Парсим новость 2: Дюков заявил, что нефтяная отрасль заинтересована ...
    Парсим новость 3: Апелляция поддержала взыскание с Euroclear в польз...
92 новостей (всего: 55552)
[1098/1298] 2025-04-02:     Парсим новость 1: Президент США объявил о решении ввести зеркальные ...
    Парсим новость 2: Правительство разрешило ОСК передачу "Северной вер...
    Парсим новость 3: Грузооборот транспорта в РФ снизился в январе-февр...
97 новостей (всего: 55649)
[1099/1298] 2025-04-03:     Парсим новость 1: Спрос на бонды ВЭБа с привязкой к RUONIA почти дос...
    Парсим новость 2: В Мехико приветствуют отказ США от введения дополн...
    Парсим новость 3: Зампредседателя ФРС Джефферсон не считает нужным с...
92 новостей (всего: 55741)
[1100/1298] 2025-04-04:     Парсим новость 1: Пошлина на экспорт пшеницы из РФ с 9 апреля повыси...
    Парсим новость 2: Рынки акций Европы рухнули в пятницу на внешнеторг...
    Парсим новость 3: Число нефтегазовых буровых в мире снизилось в март...
65 новостей (всего: 55806)
[1101/1298] 2025-04-05:     Парсим новость 1: Казахстан вместе с семью странами ОПЕК+ скорректир...
    Парсим новость 2: Не исполняющие соглашение страны ОПЕК+ представят ...
    Парсим новость 3: Иран планирует возобновить разведку нефти и газа в...
4 новостей (всего: 55810)
[1102/1298] 2025-04-06:     Парсим новость 1: Bloomberg сообщил, что Индия будет добиваться ново...
    Парсим новость 2: Индонезия не будет отвечать зеркально на пошлины С...
2 новостей (всего: 55812)
[1103/1298] 2025-04-07:     Парсим новость 1: США продлили разрешение своим гражданам и юрлицам ...

    Парсим новость 2: Президент США заверил, что введенные им пошлины пр...
    Парсим новость 3: Трамп не ввел пошлины против России, так как США с...
77 новостей (всего: 55889)
[1104/1298] 2025-04-08:     Парсим новость 1: Цены на нефть возобновили снижение, Brent опускала...
    Парсим новость 2: Рынки акций Европы завершили торги ростом на 2,4-2...
    Парсим новость 3: Рубль во вторник незначительно изменился к юаню на...
92 новостей (всего: 55981)
[1105/1298] 2025-04-09:     Парсим новость 1: Отсрочка повышения пошлин на 90 дней нужна для пер...
    Парсим новость 2: Российский индекс IMOEX2 взлетел к 2780 пунктам на...
    Парсим новость 3: ВТО предварительно прогнозирует спад торговли США ...
100 новостей (всего: 56081)
[1106/1298] 2025-04-10:     Парсим новость 1: Трамп надеется заключить взаимовыгодное соглашение...
    Парсим новость 2: "Газпром" предложил держателям ЗО в евро "перейти"...
    Парсим новость 3: Минэнерго США повысило прогноз по ценам на газ на ...
82 новостей (всего: 56163)
[1107/1298] 2025-04-11:     Парсим новость 1: Девелопер "Самолет" разместил ЦФА на 3 млрд рублей...
    Парсим новость 2: Пошлина на экспорт пшеницы из РФ с 16 апреля повыс...
    Парсим новость 3: "Хлебный дом" сменит регистрацию с Петербурга на М...
74 новостей (всего: 56237)
[1108/1298] 2025-04-12:     Парсим новость 1: США исключили десятки видов электроники из ответны...
1 новостей (всего: 56238)
[1109/1298] 2025-04-13: 0 новостей
[1110/1298] 2025-04-14:     Парсим новость 1: В РФ разработали правила для самозапрета на оформл...
    Парсим новость 2: LVMH в I квартале снизила выручку на 2%...
    Парсим новость 3: Европейские рынки акций уверенно выросли в понедел...
73 новостей (всего: 56311)
  -> Сохранено во временный файл
[1111/1298] 2025-04-15:     Парсим новость 1: "Диасофт" отказался от проведения допэмиссии...
    Парсим новость 2: ЦБ предложил запретить банкам взимать комиссии по ...
    Парсим новость 3: "Газпром" готовит перезапуск производства бытовой ...
104 новостей (всего: 56415)
[1112/1298] 2025-04-16:     Парсим новость 1: Российской космической программе необходимы стабил...
    Парсим новость 2: Основатель "Делимобиля" Трани может вернуться в со...
    Парсим новость 3: Fitch ухудшило прогноз роста мирового ВВП в 2025 г...
79 новостей (всего: 56494)
[1113/1298] 2025-04-17:     Парсим новость 1: Розничные продажи в США в 2025 году могут достичь ...
    Парсим новость 2: АФК "Система" в IV квартале нарастила выручку на 1...
    Парсим новость 3: Рубль в четверг заметно подрос в паре с юанем на ф...
83 новостей (всего: 56577)
[1114/1298] 2025-04-18:     Парсим новость 1: Пошлина на экспорт пшеницы из РФ с 23 апреля снизи...
    Парсим новость 2: Рубль немного повысился в паре с юанем по итогам в...
    Парсим новость 3: Рынок акций РФ завершил неделю ростом на новостях ...
57 новостей (всего: 56634)
[1115/1298] 2025-04-19:     Парсим новость 1: СМИ узнали о заинтересованности Сирии в участии SO...
1 новостей (всего: 56635)
[1116/1298] 2025-04-20:     Парсим новость 1: Сбербанк и ВТБ отменят комиссии при выдаче льготно...
1 новостей (всего: 56636)
[1117/1298] 2025-04-21:     Парсим новость 1: Курс биткойна поднялся на 4%, вернувшись к уровню ...
    Парсим новость 2: Аналитик допустил, что акции Apple могут подешевет...
    Парсим новость 3: Рубль в понедельник заметно опустился в паре с юан...
56 новостей (всего: 56692)
[1118/1298] 2025-04-22:     Парсим новость 1: Глава Минфина США считает, что торговое противосто...
    Парсим новость 2: Индекс IMOEX2 на вечерней сессии превысил 3000п в ...
    Парсим новость 3: "Группа Аренадата" планирует в этом году увеличить...
74 новостей (всего: 56766)
[1119/1298] 2025-04-23:     Парсим новость 1: Россия в марте увеличила выпуск стального проката ...
    Парсим новость 2: ФАС учла часть замечаний бизнеса при корректировке...
    Парсим новость 3: Производство компьютеров и электроники в РФ в март...
86 новостей (всего: 56852)
[1120/1298] 2025-04-24:     Парсим новость 1: Обновлен состав подкомиссии по устойчивости финсек...
    Парсим новость 2: Операторы связи назвали невыгодными частоты 5G, ко...
    Парсим новость 3: Российские цветоводы ждут роста своей доли на внут...
98 новостей (всего: 56950)
[1121/1298] 2025-04-25:     Парсим новость 1: Жесткость мягкостью не испортишь. Заявление Банка ...
    Парсим новость 2: Пошлина на экспорт подсолнечного масла из РФ в мае...
    Парсим новость 3: ГК СМК вложила в модернизацию своего нижегородског...
97 новостей (всего: 57047)
[1122/1298] 2025-04-26:     Парсим новость 1: США отсрочили на два месяца санкции против сербско...
    Парсим новость 2: Трамп назвал маловероятным продление моратория на ...
2 новостей (всего: 57049)
[1123/1298] 2025-04-27: 0 новостей
[1124/1298] 2025-04-28:     Парсим новость 1: В правящей партии Японии заявили, что пошлины США ...
    Парсим новость 2: Мосбиржа возобновила торги на срочном рынке после ...
    Парсим новость 3: Старт вечерней сессии на срочном рынке Мосбиржи за...
73 новостей (всего: 57122)
[1125/1298] 2025-04-29:     Парсим новость 1: Schaeffler Aerospace подала кассационную жалобу по...
    Парсим новость 2: В ЕК пообещали извлечь уроки из энергоаварии в Исп...
    Парсим новость 3: В "Роскосмосе" сообщили о переговорах об участии в...
91 новостей (всего: 57213)
[1126/1298] 2025-04-30:     Парсим новость 1: Песков заявил, что механизм обязательной продажи в...
    Парсим новость 2: Переоценка инфляции учтена в индексации цен "Газпр...
    Парсим новость 3: Тариф на передачу электроэнергии в РФ в 2026 году ...
130 новостей (всего: 57343)
[1127/1298] 2025-05-01:     Парсим новость 1: Загрузка европейской ветки "Турецкого потока" в ап...
    Парсим новость 2: Сбербанк в 2025 году планирует открыть дополнитель...
2 новостей (всего: 57345)
[1128/1298] 2025-05-02:     Парсим новость 1: Баку поставит Турции около 10 млрд куб. м газа в 2...
    Парсим новость 2: Капитализация рынка акций РФ в пятницу снизилась н...
    Парсим новость 3: Рубль упал на фоне возросшей геополитической неопр...
28 новостей (всего: 57373)
[1129/1298] 2025-05-03:     Парсим новость 1: Новак отметил, что торговые войны будут влиять и н...
    Парсим новость 2: Фактический рост добычи нефти ОПЕК+ в июне с учето...
    Парсим новость 3: Восемь стран ОПЕК+ в июне увеличат добычу нефти на...
5 новостей (всего: 57378)
[1130/1298] 2025-05-04:     Парсим новость 1: Путин отметил, что были риски в связи с уходом из ...
1 новостей (всего: 57379)
[1131/1298] 2025-05-05:     Парсим новость 1: Темп роста цен на московских АЗС к концу апреля за...
    Парсим новость 2: Комитет Госдумы предложил реформу выпуска и обраще...
    Парсим новость 3: Число жалоб на российские банки в I квартале вырос...
72 новостей (всего: 57451)
[1132/1298] 2025-05-06:     Парсим новость 1: Рассмотрение по существу иска о выводе 150 млрд ру...
    Парсим новость 2: ВЭБ обсуждает с ЦБ механизмы расширения круга банк...
    Парсим новость 3: Продажи Tesla в Европе в апреле продолжили падение...
73 новостей (всего: 57524)
[1133/1298] 2025-05-07:     Парсим новость 1: Компании РФ и КНР ведут активные переговоры по кон...
    Парсим новость 2: Пауэлл планирует дождаться большей ясности с влиян...
    Парсим новость 3: ФРС ожидаемо сохранила базовую ставку в диапазоне ...
66 новостей (всего: 57590)
[1134/1298] 2025-05-08:     Парсим новость 1: Зарубежнефть передаст PetroVietnam 35% в Харьягинс...
    Парсим новость 2: РФ и Китай хотят увеличить возможный объем поставо...
    Парсим новость 3: Рубль к вечеру отыграл часть дневных потерь, но вс...
24 новостей (всего: 57614)
[1135/1298] 2025-05-09:     Парсим новость 1: Bloomberg сообщил, что Венгрия настроена против ид...
    Парсим новость 2: Среднесуточный объем импорта нефти Китаем в апреле...
    Парсим новость 3: Ушаков заявил об обсуждении с американцами поставо...
6 новостей (всего: 57620)
[1136/1298] 2025-05-10:     Парсим новость 1: Россия и Вьетнам договорились обеспечить строитель...
    Парсим новость 2: РФ и Вьетнам будут продвигать новые нефтегазовые п...
    Парсим новость 3: РФ и Вьетнам подписали "дорожную карту" по мирному...
7 новостей (всего: 57627)
[1137/1298] 2025-05-11:     Парсим новость 1: Землетрясение произошло на западе Казахстана вблиз...

1 новостей (всего: 57628)
[1138/1298] 2025-05-12:     Парсим новость 1: Правительство доработало внесенные в апреле поправ...
    Парсим новость 2: Акцизные отчисления в бюджет РФ от сладких напитко...
    Парсим новость 3: "М.Видео" меняет формат допэмиссии с открытого на ...
93 новостей (всего: 57721)
[1139/1298] 2025-05-13:     Парсим новость 1: ВТБ запускает процесс рублификации 8 выпусков валю...
    Парсим новость 2: Доля просроченных кредитов в США в I квартале дост...
    Парсим новость 3: Программа льготного автокредитования расширена на ...
70 новостей (всего: 57791)
[1140/1298] 2025-05-14:     Парсим новость 1: Экспорт белорусского продовольствия в Россию в I к...
    Парсим новость 2: РФ в 2024 г. увеличила экспорт рыбы в Малайзию на ...
    Парсим новость 3: Saudi Aramco подписала предварительные соглашения ...
118 новостей (всего: 57909)
  -> Сохранено во временный файл
[1141/1298] 2025-05-15:     Парсим новость 1: Доля поставок нефти в Индию из РФ в феврале сократ...
    Парсим новость 2: Кабмин одобрил проект о налоговых стимулах для раб...
    Парсим новость 3: Минфин подготовил поправки о налоговом вычете на с...
82 новостей (всего: 57991)
[1142/1298] 2025-05-16:     Парсим новость 1: Пошлина на экспорт пшеницы с 21 мая снизится на 11...
    Парсим новость 2: Потери бюджета от нелегального табака в 2024 году ...
    Парсим новость 3: ЦБ обсуждает дифференциацию требований к free floa...
92 новостей (всего: 58083)
[1143/1298] 2025-05-17:     Парсим новость 1: Путин поручил обеспечить до 2030 г. ввод в эксплуа...
1 новостей (всего: 58084)
[1144/1298] 2025-05-18:     Парсим новость 1: Объем использования нацвалют в расчетах между РФ и...
1 новостей (всего: 58085)
[1145/1298] 2025-05-19:     Парсим новость 1: Президент США заявил о готовности к торговым проек...
    Парсим новость 2: Netflix получил права на показ "Улицы Сезам"...
    Парсим новость 3: Intel представила новые графические процессоры для...
75 новостей (всего: 58160)
[1146/1298] 2025-05-20:     Парсим новость 1: В ЦБ отметили, что укрепление рубля еще не полност...
    Парсим новость 2: Каллас верит в эффективность обсуждаемого снижения...
    Парсим новость 3: Росрыболовство сообщило об экспорте российской рыб...
114 новостей (всего: 58274)
[1147/1298] 2025-05-21:     Парсим новость 1: Акционеры VTB Africa приняли решение о ликвидации ...
    Парсим новость 2: Решетников допустил, что кризис международной торг...
    Парсим новость 3: Совет директоров En+ рекомендовал не выплачивать д...
92 новостей (всего: 58366)
[1148/1298] 2025-05-22:     Парсим новость 1: Госдепартамент США не намерен продлевать лицензию ...
    Парсим новость 2: Гендиректор "Юнипро" Никонов вышел из числа владел...
    Парсим новость 3: Режим обязательной продажи части валютной выручки ...
86 новостей (всего: 58452)
[1149/1298] 2025-05-23:     Парсим новость 1: Трамп заявил, что ему не нужно торговое соглашение...
    Парсим новость 2: Пошлина на экспорт подсолнечного масла в июне повы...
    Парсим новость 3: Пошлина на экспорт пшеницы с 28 мая снизится на 12...
79 новостей (всего: 58531)
[1150/1298] 2025-05-24:     Парсим новость 1: Более 631 млн акций двух крупных компаний РФ перед...
1 новостей (всего: 58532)
[1151/1298] 2025-05-25: 0 новостей
[1152/1298] 2025-05-26:     Парсим новость 1: Более 50 соглашений почти на 180 млрд рублей подпи...
    Парсим новость 2: Новак заявил, что партнеры ОПЕК+ еще не обсуждали ...
    Парсим новость 3: FT сообщила о намерении Trump Media привлечь $3 мл...
75 новостей (всего: 58607)
[1153/1298] 2025-05-27:     Парсим новость 1: ЕК разъяснила порядок участия третьих стран в фини...
    Парсим новость 2: Ракета Falcon 9 вывела на орбиту еще 24 интернет-с...
    Парсим новость 3: Польша потратит на оборону в 2025 году 4,7% ВВП, о...
99 новостей (всего: 58706)
[1154/1298] 2025-05-28:     Парсим новость 1: "Газпром СПГ технологии" требует банкротства Зелен...
    Парсим новость 2: ЕС и ОАЭ приступили к переговорам по соглашению о ...
    Парсим новость 3: Бизнес РФ в этом году не ждет серьезных изменений ...
101 новостей (всего: 58807)
[1155/1298] 2025-05-29:     Парсим новость 1: Индекс доверия CEO компаний к экономике США показа...
    Парсим новость 2: Председатель ФРС Пауэлл встретился с Трампом в чет...
    Парсим новость 3: Сбербанк не видит ухудшения качества кредитов у кр...
76 новостей (всего: 58883)
[1156/1298] 2025-05-30:     Парсим новость 1: Добыча углеводородов "Роснефти" в I кв. составила ...
    Парсим новость 2: Чистая прибыль "Роснефти" по МСФО в I квартале сос...
    Парсим новость 3: "Почта России" в I квартале нарастила чистый убыто...
90 новостей (всего: 58973)
[1157/1298] 2025-05-31:     Парсим новость 1: Фактический рост добычи нефти ОПЕК+ в июле с учето...
    Парсим новость 2: Страны ОПЕК+ увеличат добычу нефти в июле ввиду зд...
    Парсим новость 3: Белоруссия с 1 июня обнуляет экспортные пошлины на...
5 новостей (всего: 58978)
[1158/1298] 2025-06-01: 0 новостей
[1159/1298] 2025-06-02:     Парсим новость 1: Инвестиции Yadro в производство базовых станций со...
    Парсим новость 2: Продажи Tesla во Франции в мае упали в три раза...
    Парсим новость 3: Рубль развернулся вверх в паре с юанем после росси...
63 новостей (всего: 59041)
[1160/1298] 2025-06-03:     Парсим новость 1: "Т-Технологии" не исключили коммерческого партнерс...
    Парсим новость 2: ВТБ пробил кворум по рублификации бондов СУБ-Т1-2 ...
    Парсим новость 3: Рубль во вторник немного опустился в паре с юанем...
58 новостей (всего: 59099)
[1161/1298] 2025-06-04:     Парсим новость 1: Маск призвал полностью переделать предложенный Тра...
    Парсим новость 2: "Мосбиржа" допустила акции "Фикс прайс" к торгам с...
    Парсим новость 3: Трамп выступил за отказ от лимита госдолга США...
96 новостей (всего: 59195)
[1162/1298] 2025-06-05:     Парсим новость 1: МЭА прогнозирует падение инвестиций в мировую добы...
    Парсим новость 2: Резидентам ОЭЗ в Калининграде сохранят старые усло...
    Парсим новость 3: ГК "Руст" в 2024 году увеличила продажи ключевых в...
88 новостей (всего: 59283)
[1163/1298] 2025-06-06:     Парсим новость 1: ВЭБ готов стать "более прозрачным" для ЦБ, чтобы п...
    Парсим новость 2: Россия ввела пошлину на экспорт чистопородных овец...
    Парсим новость 3: Пошлина на экспорт пшеницы из РФ с 11 июня снизитс...
103 новостей (всего: 59386)
[1164/1298] 2025-06-07:     Парсим новость 1: Акционеры "РусГидро" выберут между отсутствием див...
    Парсим новость 2: Итальянская Eni ликвидировала представительство в ...
    Парсим новость 3: Путин подписал закон о ратификации соглашения о ст...
3 новостей (всего: 59389)
[1165/1298] 2025-06-08: 0 новостей
[1166/1298] 2025-06-09:     Парсим новость 1: ЦБ РФ отметил снижение доходности биткойна в мае н...
    Парсим новость 2: Розничные инвесторы в мае оставались крупнейшими н...
    Парсим новость 3: Крупнейшие экспортеры в мае сократили продажу валю...
55 новостей (всего: 59444)
[1167/1298] 2025-06-10:     Парсим новость 1: Правительство поддержало законопроект о введении а...
    Парсим новость 2: "Яндекс" увеличил уставный капитал дочернего банка...
    Парсим новость 3: УК сети клиник "Мать и дитя" ожидает в 2025 году р...
88 новостей (всего: 59532)
[1168/1298] 2025-06-11:     Парсим новость 1: Латник назвал ЕС одним из самых трудных для США уч...
    Парсим новость 2: Дефицит бюджета США в мае снизился на 9%...
    Парсим новость 3: ЕС планирует санкции против двух китайских банков ...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/1030887 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176A18F6E0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
81 новостей (всего: 59613)
[1169/1298] 2025-06-12:     Парсим новость 1: Минсельхоз США сохранил прогноз экспорта пшеницы и...
    Парсим новость 2: Венгрия и Словакия выступят против отказа от энерг...
    Парсим новость 3: СМИ отметили ужесточение позиций Индии и США на пе...
7 новостей (всего: 59620)
[1170/1298] 2025-06-13:     Парсим новость 1: Рубль вырос в паре с юанем в пятницу на фоне скачк...
    Парсим новость 2: Рынок акций РФ в пятницу превысил 2750п по индексу...

    Парсим новость 3: ЕК выделила Украине 1 млрд евро в счет кредитной и...
20 новостей (всего: 59640)
  -> Сохранено во временный файл
[1171/1298] 2025-06-14:     Парсим новость 1: В Казахстане заявили, что у КНР наиболее высокий у...
    Парсим новость 2: Китайская СNNC возглавит консорциум по строительст...
    Парсим новость 3: АЭС в Казахстане будет построена на основе российс...
4 новостей (всего: 59644)
[1172/1298] 2025-06-15: 0 новостей
[1173/1298] 2025-06-16:     Парсим новость 1: Реальный эффективный курс рубля в мае вырос на 2,7...
    Парсим новость 2: Рубль по итогам волатильных торгов понедельника сл...
    Парсим новость 3: Рынок акций РФ начал неделю с отката ниже 2740 пун...
38 новостей (всего: 59682)
[1174/1298] 2025-06-17:     Парсим новость 1: Yum! Brands в октябре возглавит нынешний финдирект...
    Парсим новость 2: Владельцы биржевых бондов "Домодедово" не поддержа...
    Парсим новость 3: Канада вводит санкции против более 40 юрлиц из РФ ...
57 новостей (всего: 59739)
[1175/1298] 2025-06-18:     Парсим новость 1: Пауэлл заявил, что ФРС находится в хорошем положен...
    Парсим новость 2: Новак обсудил с генсеком ОПЕК ситуацию на мировых ...
    Парсим новость 3: ФРС повысила прогнозы инфляции в США на 2025-2027 ...
65 новостей (всего: 59804)
[1176/1298] 2025-06-19:     Парсим новость 1: Новак заявил, что Россия в 2025 году продолжила на...
    Парсим новость 2: Новак заявил, что крепкий рубль отражает жесткую д...
    Парсим новость 3: Глава РСПП не ждет волны банкротств из-за переохла...
83 новостей (всего: 59887)
[1177/1298] 2025-06-20:     Парсим новость 1: Путин отметил деполитизированный характер деятельн...
    Парсим новость 2: АЕБ снизила прогноз российского авторынка на 2025 ...
    Парсим новость 3: Пошлина на экспорт пшеницы из РФ с 25 июня снизитс...
102 новостей (всего: 59989)
[1178/1298] 2025-06-21:     Парсим новость 1: ПМЭФ-2025: Лето великого перелома...
    Парсим новость 2: В Евросоюзе посчитали чрезмерными требования США н...
    Парсим новость 3: Минцифры обещает IT-отрасли эффективную регуляторн...
22 новостей (всего: 60011)
[1179/1298] 2025-06-22:     Парсим новость 1: ЦБ сейчас больше уверен в устойчивости снижения ин...
    Парсим новость 2: УК "Домодедово" возглавил бывший первый замглавы М...
2 новостей (всего: 60013)
[1180/1298] 2025-06-23:     Парсим новость 1: Минцифры предлагает не брать плату с бизнеса за за...
    Парсим новость 2: Темпы роста кредитования экономики РФ в мае замедл...
    Парсим новость 3: Рубль немного укрепился к юаню на подготовке экспо...
26 новостей (всего: 60039)
[1181/1298] 2025-06-24:     Парсим новость 1: Nordgold планирует перерабатывать на проекте "Рома...
    Парсим новость 2: Эксперты отметили рост рынка микроэлектроники РФ в...
    Парсим новость 3: Ритейлер автозапчастей Autodoc отложил IPO во Фран...
29 новостей (всего: 60068)
[1182/1298] 2025-06-25:     Парсим новость 1: Иностранные покупатели газа получили отсрочку до о...
    Парсим новость 2: ВТБ в долгосрочной перспективе будет думать над уп...
    Парсим новость 3: АСВ переведет принадлежащие ему привилегированные ...
41 новостей (всего: 60109)
[1183/1298] 2025-06-26:     Парсим новость 1: ЦБ РФ продолжит снижать ставку, убедившись в устой...
    Парсим новость 2: Путин ожидает ускорения регионализации платежных с...
    Парсим новость 3: Средства юрлиц в банках РФ в мае выросли на 0,4%, ...
29 новостей (всего: 60138)
[1184/1298] 2025-06-27:     Парсим новость 1: OFAC продлило лицензию для санкционных банков РФ н...
    Парсим новость 2: Великобритания с 18 июля повысит пошлины на ввоз а...
    Парсим новость 3: Президент США объявил о прекращении торговых перег...
66 новостей (всего: 60204)
[1185/1298] 2025-06-28:     Парсим новость 1: Мосбиржа обсуждает установление индивидуального це...
    Парсим новость 2: Около 50 компаний готовятся к pre-IPO на Мосбирже...
    Парсим новость 3: Новак сообщил, что первый блок АЭС "Аккую" в Турци...
4 новостей (всего: 60208)
[1186/1298] 2025-06-29: 0 новостей
[1187/1298] 2025-06-30:     Парсим новость 1: Акционеры "Уралкалия" утвердили решение не выплачи...
    Парсим новость 2: РФ с 1 июля вводит квоту на экспорт 50 тыс. т рисо...
    Парсим новость 3: Рубль в понедельник не изменился к юаню после заве...
70 новостей (всего: 60278)
[1188/1298] 2025-07-01:     Парсим новость 1: Fix Price продлила до 18 июля сбор заявок для внеб...
    Парсим новость 2: "Ростелеком" может продать актив в Армении компани...
    Парсим новость 3: Продажи General Motors и Ford в США во II квартале...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/1033938 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021778405FD0>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
83 новостей (всего: 60361)
[1189/1298] 2025-07-02:     Парсим новость 1: Разрешение Главгосэкспертизы на строительство ВСМ ...
    Парсим новость 2: Набиуллина назвала рост "экономики впечатлений" до...
    Парсим новость 3: МТС внесла доли в кикшеринге и финтехе в юрлицо эк...
101 новостей (всего: 60462)
[1190/1298] 2025-07-03:     Парсим новость 1: Заседание "восьмерки" ОПЕК+ перенесено на 5 июля...
    Парсим новость 2: Рубль в четверг умеренно опустился в паре с юанем ...
    Парсим новость 3: Petrobras инвестирует $6,1 млрд в свои проекты в ш...
100 новостей (всего: 60562)
[1191/1298] 2025-07-04:     Парсим новость 1: В России в перечень сельскохозяйственной продукции...
    Парсим новость 2: КС проверит переложение на покупателей иностранног...
    Парсим новость 3: Господдержка фермеров в 2026 году может остаться н...
74 новостей (всего: 60636)
[1192/1298] 2025-07-05:     Парсим новость 1: Эрдоган сообщил, что Азербайджан поможет Сирии при...
    Парсим новость 2: Суд ЕС отклонил апелляцию белорусского химзавода "...
    Парсим новость 3: Фактический рост добычи нефти ОПЕК+ в августе с уч...
7 новостей (всего: 60643)
[1193/1298] 2025-07-06:     Парсим новость 1: Лавров заявил, что БРИКС прорабатывает проекты тра...
    Парсим новость 2: Лидеры БРИКС предостерегают против подрывающих меж...
    Парсим новость 3: Путин отметил прогресс в работе над инициативой Зе...
4 новостей (всего: 60647)
[1194/1298] 2025-07-07:     Парсим новость 1: Оператор интерконнектора Греция-Болгария оценит сп...
    Парсим новость 2: Норвегия вслед за ЕС введет санкции против двух ры...
    Парсим новость 3: Трамп скоро объявит новые торговые пошлины для 12 ...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/1034870 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002176AB6BB30>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
66 новостей (всего: 60713)
[1195/1298] 2025-07-08:     Парсим новость 1: Торги акциями Fix Price после конвертации расписок...
    Парсим новость 2: Intel сократит более 500 сотрудников в штате Орего...
    Парсим новость 3: Airbus в июне поставила 63 самолета, в I полугодии...
73 новостей (всего: 60786)
[1196/1298] 2025-07-09:     Парсим новость 1: Конго предлагает "ЛУКОЙЛу" участие в газовом проек...
    Парсим новость 2: Рубль в среду немного повысился в паре с юанем на ...
    Парсим новость 3: Бензин на АЗС с 1 по 7 июля подорожал на 0,27% пос...
79 новостей (всего: 60865)
[1197/1298] 2025-07-10:     Парсим новость 1: Президент Бразилии задумался о введении для США от...
    Парсим новость 2: В июне число доступных для "неквалов" выпусков ЦФА...
    Парсим новость 3: Альберта надеется удвоить добычу нефти, нарастить ...
80 новостей (всего: 60945)
[1198/1298] 2025-07-11:     Парсим новость 1: Минпромторг предложил ограничить госзакупки импорт...
    Парсим новость 2: РФ будет доплачивать преподавателям русского языка...
    Парсим новость 3: "Дочка" Сбербанка оспаривает в КС РФ модель финанс...
83 новостей (всего: 61028)
[1199/1298] 2025-07-12:     Парсим новость 1: США вводят с 1 августа 30-процентные пошлины на то...
    Парсим новость 2: Поставки азербайджанского газа в Сирию через Турци...
    Парсим новость 3: Сирия подписала меморандум о взаимопонимании с Гос...

5 новостей (всего: 61033)
[1200/1298] 2025-07-13: 0 новостей
  -> Сохранено во временный файл
[1201/1298] 2025-07-14:     Парсим новость 1: Рубль вырос в паре с юанем на фоне отсутствия серь...
    Парсим новость 2: Объем грузоперевозок по сети РЖД снизился в I полу...
    Парсим новость 3: На новых заявлениях Трампа Brent подешевела до $69...
49 новостей (всего: 61082)
[1202/1298] 2025-07-15:     Парсим новость 1: В кабмин внесен проект поправок о налоговом вычете...
    Парсим новость 2: В Банке России оценили инфляцию в июне как близкую...
    Парсим новость 3: Рубль во вторник умеренно вырос к юаню на фоне вне...
58 новостей (всего: 61140)
[1203/1298] 2025-07-16:     Парсим новость 1: Опрос ЦБ показал, что охлаждение внутреннего спрос...
    Парсим новость 2: Цены производителей на бензин в РФ в июне выросли ...
    Парсим новость 3: Bloomberg сообщает, что Трамп может вскоре уволить...
58 новостей (всего: 61198)
[1204/1298] 2025-07-17:     Парсим новость 1: Принадлежащая менеджменту VK компания сократила до...
    Парсим новость 2: Сбер предложил регулировать токены в рамках ЭПР ка...
    Парсим новость 3: Повышенная ставка ЦБ нашла отражение в финансовой ...
62 новостей (всего: 61260)
[1205/1298] 2025-07-18:     Парсим новость 1: Порядок расчета утильсбора на спецтехнику и шасси ...
    Парсим новость 2: Глава ФРБ Чикаго допустил, что ФРС сможет существе...
    Парсим новость 3: Пошлина на экспорт пшеницы из РФ с 23 июля останет...
82 новостей (всего: 61342)
[1206/1298] 2025-07-19:     Парсим новость 1: ЕС ввел полный запрет на финансовые транзакции ряд...
    Парсим новость 2: ЕС опубликовал список из 22 банков, попавших в нов...
    Парсим новость 3: "Селигдар" открыл золотоизвлекательную фабрику на ...
11 новостей (всего: 61353)
[1207/1298] 2025-07-20:     Парсим новость 1: "Роснефть" считает необоснованным и незаконным реш...
    Парсим новость 2: США не собираются давать ЕС дополнительные отсрочк...
    Парсим новость 3: Алиев отметил, что экспорт азербайджанского газа к...
3 новостей (всего: 61356)
[1208/1298] 2025-07-21:     Парсим новость 1: Аналитики отмечают, что дисконт Urals под давление...
    Парсим новость 2: Технологии производства редкоземельных металлов вк...
    Парсим новость 3: Рубль укрепился в паре с юанем в ожидании новостей...
51 новостей (всего: 61407)
[1209/1298] 2025-07-22:     Парсим новость 1: Трамп заключил с президентом Филиппин торговое сог...
    Парсим новость 2: Southwest Airlines отменит свободную рассадку пасс...
    Парсим новость 3: Денежная масса в России в июне увеличилась на 0,7%...
53 новостей (всего: 61460)
[1210/1298] 2025-07-23:     Парсим новость 1: Минэнерго РФ объяснило рост цен на бензин сезонной...
    Парсим новость 2: Росстат сообщил, что производство СПГ в РФ в июне ...
    Парсим новость 3: Цены на бензин в РФ с 15 по 21 июля выросли на 0,3...
48 новостей (всего: 61508)
[1211/1298] 2025-07-24:     Парсим новость 1: Китайская NewNew Shipping Line может инвестировать...
    Парсим новость 2: Wildberries изменила проект логоцентра в Карелии...
    Парсим новость 3: Anglo American во II квартале снизила выпуск меди ...
55 новостей (всего: 61563)
[1212/1298] 2025-07-25:     Парсим новость 1: Пошлина на экспорт пшеницы из РФ с 30 июля вновь б...
    Парсим новость 2: Рубль в пятницу слегка снизился в паре с юанем...
    Парсим новость 3: Рынок акций РФ упал к 2770п по индексу МосБиржи и ...
76 новостей (всего: 61639)
[1213/1298] 2025-07-26:     Парсим новость 1: Правительство РФ утвердило решение об отсрочках по...
1 новостей (всего: 61640)
[1214/1298] 2025-07-27:     Парсим новость 1: Трамп и фон дер Ляйен согласовали торговое соглаше...
1 новостей (всего: 61641)
[1215/1298] 2025-07-28:     Парсим новость 1: Правительство выделило почти 1,2 млрд руб. на разв...
    Парсим новость 2: Рубль усилил падение на фоне слов Трампа о более к...
    Парсим новость 3: Индекс МосБиржи опустился к 2730 пунктам на опасен...
42 новостей (всего: 61683)
[1216/1298] 2025-07-29:     Парсим новость 1: Бессент предупредил Китай о рисках вторичных пошли...
    Парсим новость 2: Трамп не ждет негатива для нефтяного сектора от бу...
    Парсим новость 3: Армения увеличила поставки фруктов и овощей в Росс...
70 новостей (всего: 61753)
[1217/1298] 2025-07-30:     Парсим новость 1: Трамп ввел пошлины в 50% на импорт изделий из меди...
    Парсим новость 2: ФРС не делает прогнозов для сентябрьского заседани...
    Парсим новость 3: ФРС оставила базовую ставку в диапазоне 4,25-4,5%,...
89 новостей (всего: 61842)
[1218/1298] 2025-07-31:     Парсим новость 1: Правительство РФ включило ряд алкогольных предприя...
    Парсим новость 2: В ВТБ заявили, что заинтересованы в повторении див...
    Парсим новость 3: Инвестфонд Atlas закрыл сделку по покупке североам...
94 новостей (всего: 61936)
[1219/1298] 2025-08-01:     Парсим новость 1: Поставки ПК в мире во II квартале выросли на 6,5%...
    Парсим новость 2: Гонконгская фондовая биржа смягчит некоторые прави...
    Парсим новость 3: Чистая прибыль АЛРОСА в I полугодии выросла на 12%...
65 новостей (всего: 62001)
[1220/1298] 2025-08-02:     Парсим новость 1: "Восьмерка" ОПЕК+ достигла принципиального согласи...
    Парсим новость 2: Турция начала поставки газа из Азербайджана в Сири...
2 новостей (всего: 62003)
[1221/1298] 2025-08-03:     Парсим новость 1: Bloomberg сообщил, что власти Индии не запрещали с...
    Парсим новость 2: "Восьмерка" ОПЕК+ в сентябре свернет ограничения д...
    Парсим новость 3: Фактический рост добычи нефти ОПЕК+ в сентябре с у...
5 новостей (всего: 62008)
[1222/1298] 2025-08-04:     Парсим новость 1: "Росатом" ведет работу по выпуску облигаций в юаня...
    Парсим новость 2: Нидерланды, Норвегия, Португалия и ФРГ провели вое...
    Парсим новость 3: Бензин на АЗС Москвы подорожал за июль и первые дн...
55 новостей (всего: 62063)
[1223/1298] 2025-08-05:     Парсим новость 1: США изучают возможность санкций против связанных с...
    Парсим новость 2: ВР планирует сократить не менее 15% офисных сотруд...
    Парсим новость 3: Мировые центробанки в июне закупили 22 т золота...
65 новостей (всего: 62128)
[1224/1298] 2025-08-06:     Парсим новость 1: Индекс IMOEX2 подскочил выше 2800п после позитивно...
    Парсим новость 2: Саудовская Аравия в сентябре повысит цены на нефть...
    Парсим новость 3: Рубль почти не изменился в среду, проигнорировав в...
70 новостей (всего: 62198)
[1225/1298] 2025-08-07:     Парсим новость 1: ЕС увеличил выпуск пива на 0,6% в 2024 году...
    Парсим новость 2: "ФосАгро" во II квартале увеличила скорректированн...
    Парсим новость 3: В ЕК считают, что угроза Трампа обложить пошлиной ...
80 новостей (всего: 62278)
[1226/1298] 2025-08-08:     Парсим новость 1: Ставки пошлин на экспорт пшеницы, ячменя и кукуруз...
    Парсим новость 2: Tesla получила лицензию на службу роботакси в Теха...
    Парсим новость 3: Полугодовая чистая прибыль "Газпром нефти" по РСБУ...
69 новостей (всего: 62347)
[1227/1298] 2025-08-09:     Парсим новость 1: S&P подтвердило рейтинг Грузии "ВВ/B" со "стабильн...
    Парсим новость 2: Эстония запланировала взять кредит до 3,6 млрд евр...
2 новостей (всего: 62349)
[1228/1298] 2025-08-10: 0 новостей
[1229/1298] 2025-08-11:     Парсим новость 1: Рубль укрепился в паре с юанем в ожидании встречи ...
    Парсим новость 2: В Минфине отметили сохранение устойчивого спроса н...
    Парсим новость 3: Трамп хотел бы быстро добиться перемирия на Украин...
52 новостей (всего: 62401)
[1230/1298] 2025-08-12:     Парсим новость 1: Минэнерго США повысило прогноз по добыче нефти в с...
    Парсим новость 2: Проверка доходов заемщика на основе данных ФНС и С...
    Парсим новость 3: Минэнерго США понизило прогноз средней цены Brent ...
76 новостей (всего: 62477)
  -> Сохранено во временный файл
[1231/1298] 2025-08-13:     Парсим новость 1: Минэкономразвития отметило ускорение роста ВВП РФ ...
    Парсим новость 2: Минэнерго работает над дополнительными поставками ...
    Парсим новость 3: Рубль в среду почти не изменился к юаню в ожидании...
64 новостей (всего: 62541)
[1232/1298] 2025-08-14:     Парсим новость 1: США ввели санкции против платежного агента А7 и кр...
    Парсим новость 2: ЕК ждет скорого завершения согласования декларации...

    Парсим новость 3: Инвестиции в нефтегазовый сектор Норвегии достигну...
68 новостей (всего: 62609)
[1233/1298] 2025-08-15:     Парсим новость 1: Путин поручил зафиксировать сроки давности для осп...
    Парсим новость 2: Суд завершил конкурсное производство на "Евродоне"...
    Парсим новость 3: Правительство подготовит предложения по созданию "...
74 новостей (всего: 62683)
[1234/1298] 2025-08-16:     Парсим новость 1: Ставки пошлин на экспорт пшеницы, ячменя и кукуруз...
1 новостей (всего: 62684)
[1235/1298] 2025-08-17:     Парсим новость 1: Ростовская область снизила сбор зерновых на 24%, д...
1 новостей (всего: 62685)
[1236/1298] 2025-08-18:     Парсим новость 1: Bloomberg сообщил о намерении властей США получить...
    Парсим новость 2: Доходность 30-летних британских облигаций с защито...
    Парсим новость 3: Рубль в понедельник опустился к юаню в ожидании вн...
49 новостей (всего: 62734)
[1237/1298] 2025-08-19:     Парсим новость 1: Латвия вложит 14 млн евро в капитал airBaltic пере...
    Парсим новость 2: В Омской области введут режим ЧС из-за переувлажне...
    Парсим новость 3: Страны ЕС обсудят 19-й пакет санкций против России...
51 новостей (всего: 62785)
[1238/1298] 2025-08-20:     Парсим новость 1: Росавиация запретила "Ангаре" самостоятельно обуча...
    Парсим новость 2: В Иркутской области ввели режим ЧС из-за засухи, п...
    Парсим новость 3: Минэнерго ждет стабилизации цен на бензин за счет ...
82 новостей (всего: 62867)
[1239/1298] 2025-08-21:     Парсим новость 1: Lufthansa и Латвия внесли 28 млн евро в капитал ai...
    Парсим новость 2: Рубль немного подешевел в паре с юанем, несмотря н...
    Парсим новость 3: Рынок акций РФ упал к 2880п по индексу МосБиржи, у...
63 новостей (всего: 62930)
[1240/1298] 2025-08-22:     Парсим новость 1: Канада отменит часть пошлин на американскую продук...
    Парсим новость 2: Nvidia обсуждает с властями США возможность постав...
    Парсим новость 3: Новак на 25 августа созвал совещание по ситуации н...
66 новостей (всего: 62996)
[1241/1298] 2025-08-23:     Парсим новость 1: Первый вице-премьер РФ поручил проработать господд...
    Парсим новость 2: Мантуров поручил проработать введение ввозных пошл...
2 новостей (всего: 62998)
[1242/1298] 2025-08-24: 0 новостей
[1243/1298] 2025-08-25:     Парсим новость 1: Минэнерго поручено следить за балансом цен на АЗС...
    Парсим новость 2: НК рекомендовано увеличить предложение топлива, в ...
    Парсим новость 3: Intel видит риски для акционеров и зарубежных прод...
65 новостей (всего: 63063)
[1244/1298] 2025-08-26:     Парсим новость 1: "ВСМПО-Ависма" выразила готовность вернуться к сот...
    Парсим новость 2: Подготовлен проект о введении с марта 2026 г. "рос...
    Парсим новость 3: Минфин предложил поднять порог авансирования госза...
67 новостей (всего: 63130)
[1245/1298] 2025-08-27:     Парсим новость 1: "Русснефть" в январе выкупила у Glencore часть пак...
    Парсим новость 2: Близость осени обновляет рекорды потребления газа ...
    Парсим новость 3: Цены производителей на компьютеры и электронику в ...
91 новостей (всего: 63221)
[1246/1298] 2025-08-28:     Парсим новость 1: Ранняя осень обеспечивает "Газпрому" третий день п...
    Парсим новость 2: Автопроизводитель Lotus сократит почти половину шт...
    Парсим новость 3: ВЭБ в I полугодии увеличил чистую прибыль на 42%, ...
79 новостей (всего: 63300)
[1247/1298] 2025-08-29:     Парсим новость 1: Правительство ввело правила определения минимально...
    Парсим новость 2: Введение маркировки звонков от юрлиц потребует зна...
    Парсим новость 3: Московский кредитный банк снизил полугодовую чисту...
112 новостей (всего: 63412)
[1248/1298] 2025-08-30:     Парсим новость 1: Ликвидация последствий нештатной ситуации в аквато...
    Парсим новость 2: Японский министр отменил визит в США из-за разногл...
    Парсим новость 3: Добыча жидких углеводородов "Роснефти" в январе-ию...
5 новостей (всего: 63417)
[1249/1298] 2025-08-31:     Парсим новость 1: Лукашенко назвал Белоруссию связующим звеном для э...
1 новостей (всего: 63418)
[1250/1298] 2025-09-01:     Парсим новость 1: "Т-Технологии" выходят на рынок кредитных историй...
    Парсим новость 2: Рубль в понедельник развернулся вверх и немного ук...
    Парсим новость 3: Ozon запускает процедуру регистрации юрлица в РФ в...
51 новостей (всего: 63469)
[1251/1298] 2025-09-02:     Парсим новость 1: Рубль во вторник умеренно подешевел в паре с юанем...
    Парсим новость 2: Глава Банка Франции считает, что ЕЦБ взял инфляцию...
    Парсим новость 3: Рынок акций РФ откатился ниже 2850 пунктов по инде...
56 новостей (всего: 63525)
[1252/1298] 2025-09-03:     Парсим новость 1: HSBC улучшил прогноз для S&P 500 второй раз менее ...
    Парсим новость 2: Ставки по ипотеке в США упали до минимума с апреля...
    Парсим новость 3: Рубль подешевел по отношению к юаню в среду, опуст...
48 новостей (всего: 63573)
[1253/1298] 2025-09-04:     Парсим новость 1: Греф ожидает к концу года ослабление курса рубля д...
    Парсим новость 2: Глава ФРБ Нью-Йорка считает, что ФРС со временем н...
    Парсим новость 3: Новак заявил, что уровень исполнения сделки ОПЕК+ ...
60 новостей (всего: 63633)
[1254/1298] 2025-09-05:     Парсим новость 1: Старт сборки автомобилей Volga в РФ намечен на вес...
    Парсим новость 2: Мантуров считает, что смягчение ДКП может оживить ...
    Парсим новость 3: Первый замгендиректора ИТ-холдинга Т1 Харитонов во...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/1045791 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021779A7CB90>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
66 новостей (всего: 63699)
[1255/1298] 2025-09-06: 0 новостей
[1256/1298] 2025-09-07:     Парсим новость 1: Новак назвал решение ОПЕК+ увеличить добычу нефти ...
    Парсим новость 2: "Восьмерка" ОПЕК+ в октябре увеличит добычу нефти ...
    Парсим новость 3: Новак отметил, что Россия полностью исполняет свои...
7 новостей (всего: 63706)
[1257/1298] 2025-09-08:     Парсим новость 1: Цена золота продолжает бить рекорды, спотовая цена...
    Парсим новость 2: Рубль вечером ускорил темпы снижения, обновил мини...
    Парсим новость 3: Рынок акций РФ начал неделю с роста выше 2920 пунк...
85 новостей (всего: 63791)
[1258/1298] 2025-09-09:     Парсим новость 1: Глава Кубани поручил разработать единую схему разм...
    Парсим новость 2: Алжир пригласил Россию участвовать в нефтегазовых ...
    Парсим новость 3: Walmart откроет первые магазины под своим брендом ...
77 новостей (всего: 63868)
[1259/1298] 2025-09-10:     Парсим новость 1: Суд ЕС отменил решение о продлении санкций против ...
    Парсим новость 2: Great Wall планирует в 2026 году открыть производс...
    Парсим новость 3: Fitch повысило прогноз цен на медь до 2028 года и ...
59 новостей (всего: 63927)
[1260/1298] 2025-09-11:     Парсим новость 1: Правительство предложило 11 кандидатов в совет дир...
    Парсим новость 2: США планируют выделить Армении $145 млн на проект ...
    Парсим новость 3: Из списка для автообмена страновыми отчетами исклю...
71 новостей (всего: 63998)
  -> Сохранено во временный файл
[1261/1298] 2025-09-12:     Парсим новость 1: Тень бюджета легла на ставку. Заявление Банка Росс...
    Парсим новость 2: Новак обсудил с вице-премьером Белоруссии перспект...
    Парсим новость 3: Совет ЕС продлил до 15 марта 2026 года антироссийс...
98 новостей (всего: 64096)
[1262/1298] 2025-09-13:     Парсим новость 1: Мосбиржа возобновит торги на фондовом рынке в 11:4...
    Парсим новость 2: Мосбиржа приостановила торги на фондовом рынке...
2 новостей (всего: 64098)
[1263/1298] 2025-09-14:     Парсим новость 1: Оверчук обсудит с властями Египта создание промзон...
    Парсим новость 2: РФ оценит сроки строительства промзоны в Египте по...
2 новостей (всего: 64100)
[1264/1298] 2025-09-15:     Парсим новость 1: Фирма Левицкого получила контроль над 42%-й долей ...
    Парсим новость 2: Цена золота поднялась выше $3722 за унцию и обнови...
    Парсим новость 3: ЦБ отметил, что динамика финпотоков в августе гово...
64 новостей (всего: 64164)

[1265/1298] 2025-09-16:     Парсим новость 1: Оператор Нежданинского месторождения "Полиметалла"...
    Парсим новость 2: Эстонская Fermi Energia и канадская Aecon будут со...
    Парсим новость 3: Каллас подтвердила планы ЕК ввести ограничения в т...
58 новостей (всего: 64222)
[1266/1298] 2025-09-17:     Парсим новость 1: Пауэлл заявил, что никто не знает, в каком состоян...
    Парсим новость 2: ФРС подтвердила прогноз инфляции на 2025 г., прогн...
    Парсим новость 3: ФРС снизила базовую ставку впервые с декабря - на ...
84 новостей (всего: 64306)
[1267/1298] 2025-09-18:     Парсим новость 1: В ЦБ заявили, что идея субсидий для IPO увязла в с...
    Парсим новость 2: Новые критерии участия в "Сахалине-1" коснутся инд...
    Парсим новость 3: Казначейство планирует в ноябре начать проработку ...
84 новостей (всего: 64390)
[1268/1298] 2025-09-19:     Парсим новость 1: Гендиректором оператора российских космодромов ЦЭН...
    Парсим новость 2: Трамп обсудит с Эрдоганом торговые соглашения и за...
    Парсим новость 3: Введены правила выдачи разрешения на полеты авиате...
66 новостей (всего: 64456)
[1269/1298] 2025-09-20:     Парсим новость 1: РФ в июле обновила рекорд поставок газа в КНР, экс...
    Парсим новость 2: В ЦБ заявили, что ключевая ставка может достичь од...
    Парсим новость 3: ЦБ РФ считает цель по инфляции в 4% пограничным ур...
3 новостей (всего: 64459)
[1270/1298] 2025-09-21:     Парсим новость 1: Экспорт мороженого из РФ в Китай в августе снизилс...
    Парсим новость 2: Китай за восемь месяцев увеличил импорт вина из РФ...
    Парсим новость 3: Экспорт пива из Китая в РФ за 8 месяцев приблизилс...
3 новостей (всего: 64462)
[1271/1298] 2025-09-22:     Парсим новость 1: В Белом доме подтвердили, что Трамп подпишет на эт...
    Парсим новость 2: Nvidia инвестирует до $100 млрд в OpenAI...
    Парсим новость 3: Минпромторг РФ ожидает от электронной отрасли пред...
64 новостей (всего: 64526)
[1272/1298] 2025-09-23:     Парсим новость 1: Индекс IMOEX2 на вечерних торгах упал ниже 2700 п ...
    Парсим новость 2: Женщина ранена при атаке дрона в Белгородской обла...
    Парсим новость 3: Пауэлл заявил, что ФРС находится в сложной ситуаци...
70 новостей (всего: 64596)
[1273/1298] 2025-09-24:     Парсим новость 1: Доходы бюджета от экспортных пошлин на зерно в 202...
    Парсим новость 2: Вучич попросил США вновь отложить санкции против с...
    Парсим новость 3: РФ в 2026 году планирует направить на логистическу...
122 новостей (всего: 64718)
[1274/1298] 2025-09-25:     Парсим новость 1: МИД Венгрии получил обещание Болгарии продолжать т...
    Парсим новость 2: Вучич ждет введения санкций США против NIS 1 октяб...
    Парсим новость 3: Объем российского рынка ERP-систем вырастет к 2030...
89 новостей (всего: 64807)
[1275/1298] 2025-09-26:     Парсим новость 1: Минэнерго прорабатывает механизм стимулирования ин...
    Парсим новость 2: Рубль в пятницу укрепился в паре с юанем...
    Парсим новость 3: Минфин прорабатывает снижение доли РФ в ряде госко...
78 новостей (всего: 64885)
[1276/1298] 2025-09-27:     Парсим новость 1: Кириенко заявил о мировом лидерстве "Росатома" в а...
1 новостей (всего: 64886)
[1277/1298] 2025-09-28:     Парсим новость 1: РФ рассчитывает, что КНР откроет рынок для озимой ...
1 новостей (всего: 64887)
[1278/1298] 2025-09-29:     Парсим новость 1: В Госдуму внесен законопроект об индексации МРОТ с...
    Парсим новость 2: Рубль подрос в паре с юанем, несмотря на сильное п...
    Парсим новость 3: В кабмине влияние повышения НДС на инфляцию оценил...
68 новостей (всего: 64955)
[1279/1298] 2025-09-30:     Парсим новость 1: Регуляторы обсуждают введение налога на продажу им...
    Парсим новость 2: Глава Ford допустил, что рынок электромобилей США ...
    Парсим новость 3: Petronas продаст долю в СПГ-заводе в Канаде компан...
92 новостей (всего: 65047)
[1280/1298] 2025-10-01:     Парсим новость 1: "Долг" Казахстана по компенсации недосокращенной д...
    Парсим новость 2: Во Франции начали расследование против предполагае...
    Парсим новость 3: Вэнс прогнозирует небольшую продолжительность шатд...
97 новостей (всего: 65144)
[1281/1298] 2025-10-02:     Парсим новость 1: Эксперимент по маркировке детского питания может н...
    Парсим новость 2: Путин поручил правительству проработать варианты р...
    Парсим новость 3: Путин ждет от повышения НДС балансирования расходо...
75 новостей (всего: 65219)
[1282/1298] 2025-10-03:     Парсим новость 1: Минцифры рассматривает альтернативные источники эн...
    Парсим новость 2: Аффинажным заводам запретят принимать драгметаллы ...
    Парсим новость 3: Горьковский автозавод в октябре будет работать в р...
68 новостей (всего: 65287)
[1283/1298] 2025-10-04: 0 новостей
[1284/1298] 2025-10-05:     Парсим новость 1: Фактический рост добычи ОПЕК+ в ноябре составит 74...
    Парсим новость 2: Восемь стран ОПЕК+ решили увеличить квоты по добыч...
    Парсим новость 3: "Восьмерка" ОПЕК+ близка к согласованию увеличения...
3 новостей (всего: 65290)
[1285/1298] 2025-10-06:     Парсим новость 1: Денежная масса в РФ в сентябре сократилась на 0,2%...
    Парсим новость 2: Рост оборота биоэкономики в РФ ожидается быстрее з...
    Парсим новость 3: Рубль к вечеру в понедельник отыграл дневные потер...
83 новостей (всего: 65373)
[1286/1298] 2025-10-07:     Парсим новость 1: Минэнерго США на 8% понизило прогноз цен на газ на...
    Парсим новость 2: Возобновляемая энергетика впервые обогнала уголь п...
    Парсим новость 3: Британские банки выплатят 8,2 млрд фунтов компенса...
82 новостей (всего: 65455)
[1287/1298] 2025-10-08:     Парсим новость 1: В Госдуму внесли законопроект о возможности включе...
    Парсим новость 2: У ЦБ пока нет данных о количестве банковских карт ...
    Парсим новость 3: Минфин заметил создание регионами искусственных ис...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /business/1051551 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000217798B3980>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
97 новостей (всего: 65552)
[1288/1298] 2025-10-09:     Парсим новость 1: Новак заявил, что прорабатывается ряд допмер для о...
    Парсим новость 2: Росимущество заявило об отсутствии механизма выста...
    Парсим новость 3: Citigroup отклонил предложение Grupo Mexico о поку...
100 новостей (всего: 65652)
[1289/1298] 2025-10-10:     Парсим новость 1: Renault включена в российский санкционный список...
    Парсим новость 2: Индексы США резко ушли вниз, нефть и медь сильно д...
    Парсим новость 3: Литовская Ignitis grupe получит контроль над проек...
73 новостей (всего: 65725)
[1290/1298] 2025-10-11: 0 новостей
  -> Сохранено во временный файл
[1291/1298] 2025-10-12:     Парсим новость 1: В Минэнерго назвали мораторий на обнуление топливн...
    Парсим новость 2: ЦБ отменил голосование по выбору символов для 500-...
    Парсим новость 3: Путин ввел мораторий на обнуление топливного демпф...
5 новостей (всего: 65730)
[1292/1298] 2025-10-13:     Парсим новость 1: Комитет Думы полагает, что бюджетные инвестиции сл...
    Парсим новость 2: Baker Hughes оценивает в $100 млн негативные после...
    Парсим новость 3: Рубль ускорил рост в паре с юанем, вновь обновив м...
62 новостей (всего: 65792)
[1293/1298] 2025-10-14:     Парсим новость 1: Глава Oxy спрогнозировал цену нефти Brent в 2026 г...
    Парсим новость 2: Жилищное строительство в РФ в сентябре упало на 8,...
    Парсим новость 3: Пауэлл заявил, что перспективы инфляции и занятост...
83 новостей (всего: 65875)
[1294/1298] 2025-10-15:     Парсим новость 1: Международная выставка парфюмерии и косметики Inte...
    Парсим новость 2: Экспортный потенциал РФ по зерну в 2025/26 сельхоз...
    Парсим новость 3: Нулевая импортная пошлина на нефтепродукты будет д...
    Ошибка при парсинге статьи: HTTPSConnectionPool(host='www.interfax.ru', port=443): Max retries exceeded with url: /russia/1052673 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000217797CE300>, 'Connection to www.interfax.ru timed out. (connect timeout=None)'))
107 новостей (всего: 65982)

[1295/1298] 2025-10-16:     Парсим новость 1: На подъем затонувшего в Мурманске плавдока ПД-50 в...
    Парсим новость 2: В Думу повторно внесли законопроект о регулировани...
    Парсим новость 3: Лагард считает, что нынешний уровень ставок поможе...
80 новостей (всего: 66062)
[1296/1298] 2025-10-17:     Парсим новость 1: Рубль в пятницу сильно упал в паре с юанем, растер...
    Парсим новость 2: Индекс Мосбиржи превысил 2720 пунктов на геополити...
    Парсим новость 3: Apple будет транслировать "Формулу-1" в США на экс...
64 новостей (всего: 66126)
[1297/1298] 2025-10-18:     Парсим новость 1: Повышение утильсбора не затронет всех импортеров, ...
    Парсим новость 2: "ВСМПО-Ависма" с 1 декабря планирует перевести адм...
    Парсим новость 3: "Газпром" подал к Linde иск в суд РФ о возмещении ...
3 новостей (всего: 66129)
[1298/1298] 2025-10-19:     Парсим новость 1: Оренбургский ГПЗ после атаки БПЛА временно прекрат...
1 новостей (всего: 66130)

=== РЕЗУЛЬТАТ ===
Итоговый размер датафрейма: 66130 новостей

Первые 3 записи:

1. 2022-04-01 08:36:00
   Заголовок: Фондовые индексы США закрылись снижением, показав максимальное квартальное падение за 2 года
   Текст: Фондовые индексы США закрылись снижением, показав максимальное квартальное падение за 2 года
Москва....
   URL: https://www.interfax.ru/world/832542

2. 2022-04-01 09:07:00
   Заголовок: Цены на нефть продолжили падать после заявления Байдена по нефтяным резервам
   Текст: Цены на нефть продолжили падать после заявления Байдена по нефтяным резервам
Москва. 1 апреля. INTER...
   URL: https://www.interfax.ru/business/832550

3. 2022-04-01 09:13:00
   Заголовок: Европейские покупатели сохраняют высокие заявки на отбор газа "Газпрома"
   Текст: Европейские покупатели сохраняют высокие заявки на отбор газа "Газпрома"
Москва. 1 апреля. INTERFAX....
   URL: https://www.interfax.ru/business/832553

Диапазон дат: 2022-04-01 08:36:00 - 2025-10-19 14:37:00

Сохранено в interfax_complete_2022_2025.csv

In [2]:
df = pd.read_csv('interfax_complete_2022_2025.csv')
df.head()

,datetime,title,full_text,url
0,2022-04-01 08:36:00,"Фондовые индексы США закрылись снижением, пока...","Фондовые индексы США закрылись снижением, пока...",https://www.interfax.ru/world/832542
1,2022-04-01 09:07:00,Цены на нефть продолжили падать после заявлени...,Цены на нефть продолжили падать после заявлени...,https://www.interfax.ru/business/832550
2,2022-04-01 09:13:00,Европейские покупатели сохраняют высокие заявк...,Европейские покупатели сохраняют высокие заявк...,https://www.interfax.ru/business/832553
3,2022-04-01 09:15:00,ЦБ смягчит ограничения на переводы средств за ...,ЦБ смягчит ограничения на переводы средств за ...,https://www.interfax.ru/business/832554
4,2022-04-01 09:16:00,Индекс PMI обрабатывающих отраслей РФ в марте ...,Индекс PMI обрабатывающих отраслей РФ в марте ...,https://www.interfax.ru/business/832557

In [3]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)

In [4]:
df.head()

              datetime                                                                                         title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               full_text                                      url
0  2022-04-01 08:36:00  Фондовые индексы США закрылись снижением, показав максимальное квартальное падение за 2 года                                                                                                                                                                                                Фондовые индексы США закрылись снижением, показав максимальное квартальное падение за 2 года\nМосква. 1 апреля. INTERFAX.RU - Американские фондовые индексы завершили снижением вторые торги подряд в четверг, закрывшись на сессионных минимумах.\nПри этом все три индикатора продемонстрировали самый существенный квартальный спад за два года,\nпишет\nMarketWatch. В то же время по итогам марта индексы выросли.\n"Худший квартал за два года не так плох, поскольку индекс S&P 500 находится примерно в 5% от рекордных максимумов", - отметил старший рыночный аналитик Oanda Эдвард Мойя.\nТрейдеры оценивали новую порцию статистических данных и следили за новостями, касающимися ситуации на Украине.\nКоличество американцев, впервые обратившихся за пособием по безработице, на прошлой неделе увеличилось на 14 тыс. - до 202 тыс. человек, сообщается в отчете министерства труда США.\nСогласно уточненным данным, неделей ранее число обращений составило 188 тыс., а не 187 тыс., как сообщалось ранее.\nОпрошенные Bloomberg аналитики в среднем ожидали повышения числа заявок до 196 тыс. с ранее объявленного уровня. Респонденты Trading Economics прогнозировали 197 тыс.\nТем временем расходы населения США в феврале выросли на 0,2% по сравнению с предыдущим месяцем, свидетельствуют данные министерства торговли страны.\nДоходы американцев увеличились на 0,5%.\nЭксперты, опрошенные агентством Bloomberg, прогнозировали подъем обоих показателей на 0,5%.\nАкции ряда технологических компаний подешевели по итогам торгов в четверг. Так, бумаги Advanced Micro Devices Inc. потеряли 8,3% после того, как аналитики Barclays ухудшили рекомендацию по акциям компании.\nЦена бумаг HP Inc. уменьшилась на 6,54%, Dell Technologies Inc. - на 7,6% на фоне ухудшения рекомендаций аналитиками Morgan Stanley.\nАкции Wendy's Co. подешевели на 2,44%. Третья по величине сеть ресторанов быстрого питания в США откроет первый виртуальный ресторан в метавселенной, разрабатываемой компанией Meta Platforms Inc. (признана в РФ экстремистской организацией и запрещена).\nБумаги Intel Corp. потеряли в цене 3,64%. Компания покупает израильского разработчика и поставщика программного обеспечения для оптимизации Granulate Cloud Solutions Ltd., при этом сумма сделки не раскрывается.     https://www.interfax.ru/world/832542
1  2022-04-01 09:07:00                  Цены на нефть продолжили падать после заявления Байдена по нефтяным резервам                                                                                                                                                                                                                                                                                                                   Цены на нефть продолжили падать после заявления Байдена по нефтяным резервам\nМосква. 1 апреля. INTERFAX.RU - Цены на нефть продолжают снижаться в пятницу после падения накануне на заявлении президента США Джо Байдена о намерении направлять на рынок в среднем по 1 млн баррелей нефти в сутки\nиз стратегического резерва\n(SPR) на протяжении следующих шести месяцев.\nБайден, выступая в Белом доме, призвал американские компании наращивать добычу, чтобы добиться снижения цен на нефть. Это, среди прочего, позволит снизить роль экспорта энергоносителей из РФ, заявил он.\nКроме того, Байден предложил рассмотреть в Конгрессе меры, которые подтолкнули бы компании в США к более активной добыче нефти.\nСтоимость июньских фьючерсов на нефть Brent на лондонской бирже ICE Futures к 8:10 по московскому времени в пятницу составила $104,35 за баррель, что на $0,36 (0,34%) ниже цены на закрытие предыдущей сессии. По итогам торгов в четверг эти контракты подешевели на $6,73 (6%), до $104,71 за баррель.\nЦена фьючерсов на нефть WTI на май на электронных торгах Нью-йоркской товарной биржи (NYMEX) составили к этому времени $99,66 за баррель, что на $0,62 (0,62%) ниже итогового значения предыдущей сессии. В четверг стоимость этих контрактов упала на $7,54 (7%), до $100,28 за баррель.\nВ марте Brent подорожала на 6,9%, WTI - на 4,8%, за первый квартал цены выросли соответственно на 39% и 33%.\n"В принципе, это временная мера, призванная минимизировать весенний подъем цен на нефть, - заявил аналитик S&P Global Commodity Insights Маршалл Стивз, комментируя решение Байдена о высвобождении нефти из SPR. - Она позволит немного увеличить поставки на рынок и соответствующим образом ограничит цены".\n"Однако война на Украине оказывает решающее влияние на рынок, и основным фактором остается возможная потеря российской нефти", - приводит слова эксперта Market Watch.\nАналитики Goldman Sachs понизили прогноз стоимости Brent на второе полугодие 2022 года на $10 за баррель, до $125 за баррель вслед за появлением информации о планах Байдена. По мнению экспертов, действия США не решат проблему "структурного дефицита на нефтяном рынке".  https://www.interfax.ru/business/832550
2  2022-04-01 09:13:00                      Европейские покупатели сохраняют высокие заявки на отбор газа "Газпрома"                                                                                                                                                                                                                                                                                                                                 Европейские покупатели сохраняют высокие заявки на отбор газа "Газпрома"\nМосква. 1 апреля. INTERFAX.RU - Цена поставок газа по экспортным контрактам\n"Газпрома"\nс начала апреля должна заметно вырасти.\nБольшинство контрактов используют биржевой индекс "на месяц вперед": в марте его значение было около $930 за тысячу кубометров, в апреле он увеличился до примерно $1400 (это, кстати, почти совпадает со значением спотового контракта "на день вперед" на хабе TTF на пятницу).\nТакже с 1 апреля действует введенный президентским указом новый порядок оплаты поставок российского газа - с обязательной конвертацией валюты контрактов в рубли. Несмотря на растерянные или враждебные комментарии европейских политиков на это нововведение, а также на рост цены, - европейские покупатели сохраняют практически прежние заявки на отбор российского газа.\nЗагрузка украинского газотранспортного коридора в пятницу сохраняется на прежнем, максимальном уровне долгосрочного контракта (40 млрд куб. м в год, или 109 млн куб. м в сутки). Как свидетельствуют данные "Оператора ГТС Украины", номинация на 1 апреля составляет 107,6 млн куб. м, заявка на 31 марта была 109,5 млн куб. м.\nФизический поток газа по газопроводу "Ямал-Европа", который транспортирует газ через Белоруссию и Польшу в Германию, на входе в ГТС ФРГ половину дня среды и весть четверг качал газ в прямом направлении. Сумма заявок на 1 апреля (в прямом и обратном направлении) складывается в пользу реверсного направления (из Германии в Польшу).\nНа этой неделе в Европу пришло сильное похолодание. Средняя температура воздуха на 7 градусов ниже, чем на неделе с 14 по 20 марта; со значительными минусовыми температурами по ночам, что оказывает новую поддержку ценам на газ. На будущей неделе также предсказываются новые вторжения холодных воздушных масс.\nВ Европе улучшилась ситуация с выработкой электроэнергии за счет ветровой электрогенерации. Если за первые три дня текущей недели (с 28 по 30 марта) ветроэлектростанции обеспечили лишь 10% выработки электроэнергии по ЕС, то четверг их доля подскочила до 20,5%, свидетельствуют данные ассоциации WindEurope.  https://www.interfax.ru/business/832553
3  2022-04-01 09:15:00                                ЦБ смягчит ограничения на переводы средств за рубеж для физлиц                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ЦБ смягчит ограничения на переводы средств за рубеж для физлиц\nМосква. 1 апреля. INTERFAX.RU - Банк России решил смягчить ограничения на переводы денег за рубеж для физлиц.\nНа ближайшие шесть месяцев установлены новые ограничения по суммам, которые граждане могут перевести со своего счета,\nследует из пресс-релиза\nрегулятора.\nВ течение календарного месяца физические лица имеют право перевести за пределы Российской Федерации со своего счета в российском банке на свой счет или другому физическому лицу за рубежом не более $10 тысяч или эквивалент этой суммы по другой валюте. Через компании, оказывающие услуги по переводу денежных средств без открытия счета, можно перевести в месяц не более $5 тысяч (или в эквиваленте в другой валюте).\nЭти нормы касаются резидентов России и нерезидентов - из стран, не поддерживающих санкции. Такую же возможность получили нерезиденты из всех других государств, работающих в России по трудовым или гражданско-правовым договорам.\nГражданам стран, поддерживающих санкции, которые не работают в России, а также юрлицам из этих государств переводы делать запрещено в течение шести месяцев.\nНа этот же срок приостановлены переводы за рубеж средств физических и юридических лиц — нерезидентов из стран, поддерживающих санкции, со счетов российских брокеров.\nСуммы переводов рассчитываются по официальному курсу иностранных валют к рублю, установленному Банком России на дату поручения на осуществление перевода.\nРанее ЦБ ограничил переводы средств физлиц за рубеж суммой в $5 тысяч в месяц, приостановил трансграничные переводы для нерезидентов (физлиц и юрлиц) из стран, поддерживающих санкции. При этом физлица не могли перевести деньги на свои счета за границей, но могли перевести другому человеку в месяц не более $5 тысяч (или эквивалент этой суммы в любой другой валюте). При этом граждане могли оплачивать учебу, медицинские услуги и проводить коммунальные платежи за рубежом.  https://www.interfax.ru/business/832554
4  2022-04-01 09:16:00                           Индекс PMI обрабатывающих отраслей РФ в марте рухнул до 44,1 пункта  Индекс PMI обрабатывающих отраслей РФ в марте рухнул до 44,1 пункта\nМосква. 1 апреля. INTERFAX.RU - Индекс PMI обрабатывающих отраслей РФ в марте 2022 года составил 44,1 пункта, резко снизившись с февральского значения 48,6 пункта, согласно исследованию IHS Markit.\nЗначение показателя выше 50 пунктов указывает на рост деловой активности, а ниже этого уровня - на ее снижение.\n"Последние данные указали на самое резкое ухудшение операционных условий по всему сектору за последние два года", - отмечается в пресс-релизе.\nВ ходе исследования было отмечено второе подряд месячное падение объемов производства, темпы которого заметно ускорились и оказались самыми стремительными с мая 2020 года. Компании связывали снижение выпуска со слабым клиентским спросом и уменьшением числа новых заказов.\nЧисло новых продаж заметно снизилось в марте на фоне ухудшения спроса. Некоторые участники опроса заявляли, что покупательная способность клиентов оказалась под ударом резкого роста цен. Снижение новых заказов было самым быстрым за почти два года.\nСпрос со стороны иностранных клиентов также снизился в конце первого квартала. Темпы падения экспортных заказов стали одними из самых резких за историю наблюдений.\nИнфляционное давление заметно усилилось в марте. Стоимость сырья росла самыми быстрыми темпами за историю наблюдений в свете повышения цен у поставщиков и неблагоприятного обменного курса. Компании перекладывали свои издержки на покупателей, рост отпускных цен стал самым заметным с января 2003 года (момента запуска исследований).\nЗначительно ухудшились и показатели поставщиков - увеличились сроки поставок, так как острая нехватка материалов мешала их своевременной доставке.\nСнижение притока новых заказов и существенные задержек со стороны поставщиков привело к самому быстрому падению закупок сырья с мая 2020 года. Снижение закупок усугубило проблемы пополнения складских запасов на фоне их серьезного истощения (наиболее резкого по скорости при сравнении с январем 2009 года и августом 1999 года).\nУменьшение нагрузки на мощности повлекло за собой самое быстрое сокращение невыполненных работ в 2022 году. На этом фоне компании сокращали наем и численность работников темпами, скорейшими почти за два года.\nОжидания участников опроса относительно перспектив производства на грядущий год оставались оптимистичными в марте. Тем не менее, уровень оптимизма упал до самого низкого значения в текущей 22-месячной серии.  https://www.interfax.ru/business/832557

In [9]:
df.shape

(66130, 4)